### ISSUE TITLE
Markdown cell with contents '# header' appear as empty

### ISSUE THREAD

**Issue by shadanan** [jupyter/nbconvert#100]
If you create a markdown cell with the following contents:

    # header

The resulting rendered cell is blank. 
http://stackoverflow.com/questions/32556675/writing-a-header-in-ipython-notebook-causes-the-header-to-be-invisible

**Comment by colin1alexander** [comment]
The expected output should be equivalent to <h1> header </h1>

**Comment by Carreau** [comment]
I guess this is meant to be for jupyter/notebook. fix in progress.
