### ISSUE TITLE
Kernel dying mysteriously when using ExecutePreprocessor/Exporter in docker container

### ISSUE THREAD

**Issue by marangamax** [jupyter/nbconvert#1035]
I am running ExecutePreprocessor and Exporter as part of a notebook training application, component looks something like this:

`preprocessor = ExecutePreprocessor(timeout=-1, kernel_name=self.kernel)`
`exec = Exporter()`
`exec.register_preprocessor(preprocessor, True)`
`exec.from_file(self.notebook_file)`

This runs no problem locally but when running this code in a docker image, the kernel seems to die mysteriously with a rather vague error message:

> Kernel died while waiting for execute reply.

Time-out occurs after 1 - 2 minutes so execution time is definitely not extreme.

Could be related to one of these two:
https://github.com/jupyter/nbconvert/issues/277
https://github.com/jupyter/jupyter_client/issues/142

nbconvert==5.5.0

**Comment by MSeal** [comment]
I see this happening only in the Travis CI tests -- we run many many thousands of papermill (wrapped nbconvert) processes in docker containers in prod and it never happens in our environment. Are you by chance printing a lot of messages or have particularly low resource constraints for disk or memory? What's the entrypoint like when you see this (e.g. any wrapping processes that might affect execution)?

Hoping we can find what's similar between Travis and a real setup where this occurs to track down what causes it for others.

**Comment by marangamax** [comment]
Hey thanks for response, we narrowed down the problem to most likely be due to multiprocessing.Pool (which is wrapping our data loading) not being handled well by Docker (even with up to 8GB shared memory). Currently trying to find ways to minimize the memory peaks, in this process, but most likely this is not actually not a nbconvert issue.
