### ISSUE TITLE
Document "remove_input_tag" traitlet

### ISSUE THREAD

**Issue by choldgraf** [jupyter/nbconvert#1043]
I just noticed that while "remove_input_tag" exists in the TagRemovePreprocessor:

https://github.com/jupyter/nbconvert/blob/474fe3c080211b5eefdd6c3e7c313a1ddba2fa9d/nbconvert/preprocessors/tagremove.py#L38

it isn't documented in the docstring:

https://github.com/jupyter/nbconvert/blob/474fe3c080211b5eefdd6c3e7c313a1ddba2fa9d/nbconvert/preprocessors/tagremove.py#L23

We should document that!

**Comment by MSeal** [comment]
Agreed

**Comment by tv-watts-tatari** [comment]
i'm happy to help with this if it's still needed.

**Comment by tv-watts-tatari** [comment]
https://github.com/jupyter/nbconvert/pull/1087

pls review? 🐼

**Comment by MSeal** [comment]
I also noticed that the class isn't in the readthedocs links at all, which we should add to the generation list.

**Comment by choldgraf** [comment]
closed by #1089
