### ISSUE TITLE
NBConvert 5.6 Release

### ISSUE THREAD

**Issue by MSeal** [jupyter/nbconvert#1052]
We have a lot of really nice features merged into nbconvert that don't need to wait for the 6.0 release. We're waiting for jupyter_client to release https://github.com/jupyter/jupyter_client/pull/438 (should be any day now) to enable parallel processing. There's still a rare race condition for ipython kernels, but https://github.com/ipython/ipykernel/pull/412 once passing should resolve the issues there. I don't want to block the release on this change.

Are there any open PRs we want merged before such a release? I will note I do not have time to finish the requested changes on https://github.com/jupyter/nbconvert/pull/986 for this release. I will endeavour to fix that before 6.0 if I can though.

**Comment by t-makaro** [comment]
#1028 I'll make a change to it now, and I'll push a version of #947 so that at least we can get better errors from latex.

**Comment by MSeal** [comment]
You can steal the code I added to #986 for nbconvert/exporters/pdf.py to handle errors better. That part was solid.

**Comment by MSeal** [comment]
@t-makaro @willingc Do we want to get the minimal version of #947 in for this release of just bump it to a later release? Are there any other open issues / bugs that we should tackle first? I do want to get 5.6 out soon.

**Comment by MSeal** [comment]
Also an FYI https://github.com/ipython/ipykernel/pull/412 got merged but there's some issue with the fixes for the tests, so master is in a broken state. We'll need to note the status or need to upgrade ipykernel to allow for parallel python execution.

**Comment by willingc** [comment]
> Do we want to get the minimal version of #947 in for this release of just bump it to a later release? Are there any other open issues / bugs that we should tackle first? I do want to get 5.6 out soon.

I would bump these to 5.7 (or 6.0).

**Comment by willingc** [comment]
Needed for release:
- [ ] Changelog updates
- [ ] Any doc updates
- [ ] Decision on #947 
- [ ] Tests and ipython/ipykernel#412

**Comment by t-makaro** [comment]
I'll take another crack at #947 tomorrow. Otherwise, skip until a later release.

**Comment by MSeal** [comment]
Making the Changelog FYI, let's pause merging until the release is completed in the next day or two.

**Comment by MSeal** [comment]
No response on the ipykernel front... I'll try to dig into it Wednesday night to see if I can determine what's wrong there on my own.

**Comment by willingc** [comment]
@minrk If you have any free time, do you have any thoughts on ipython/ipykernel#412? Specifically, https://github.com/ipython/ipykernel/pull/412#issuecomment-516061759. Thanks :smile:

**Comment by minrk** [comment]
I think https://github.com/ipython/ipykernel/pull/419 fixes the shutdown issue

**Comment by MSeal** [comment]
Appears to make nbconvert run smoothly again with the current changes in ipykernel master. Thanks! I'll make an issue on ipykernel to organize a patch release there.

**Comment by MSeal** [comment]
Ok I'll work on getting a PR up tonight for the changelog -- I think we're on track to get a full release this week finally done :)
