### ISSUE TITLE
allowing shebang `#!` when converting to script

### ISSUE THREAD

**Issue by pfarndt** [jupyter/nbconvert#1059]
My first notebook cell starts with a shebang, e.g.:
```
#!/usr/bin/env julia
versioninfo()
```

When I convert this notebook to a `--to=script` the output starts with a new line followed by the she bang:

```

#!/usr/bin/env julia
versioninfo()
```

However the newline prevents the shebang to be interpreted as such. The first new line (0x0a) should be omitted.

**Comment by t-makaro** [comment]
Similar too: #376

It's an issue with [this template](https://github.com/jupyter/nbconvert/blob/master/nbconvert/templates/script.tpl).

Gobbling some of the whitespace might work. Like:
```
{%- extends 'null.tpl' -%}

{%- block input -%}
{{ cell.source }}
{% endblock input %}
```

**Comment by pfarndt** [comment]
If this would do the trick it would be cool!
