### ISSUE TITLE
Equations exported in markdown don't render in some markdown viewers

### ISSUE THREAD

**Issue by tbhaxor** [jupyter/nbconvert#1072]
I have a notebook with some markdown and latex

## Input
```
**What happens in linear regression ?**

It generally fits a line with equation $y = mx + b$

Where,

$m \to slope$

$b \to y\;intercept$
```

## Expected Output

 
𝑚 → 𝑠𝑙𝑜𝑝𝑒

𝑏 → 𝑦 𝑖𝑛𝑡𝑒𝑟𝑐𝑒𝑝𝑡

## Actual Output

**What happens in linear regression ?**

It generally fits a line with equation $y = mx + b$

Where,

$m \to slope$

$b \to y\;intercept$

**Comment by tbhaxor** [comment]
My options for **download as**

![image](https://user-images.githubusercontent.com/28386721/62076885-6b699280-b266-11e9-96e2-510c0b2029c8.png)

**Comment by t-makaro** [comment]
To what format are you converting? I cannot reproduce.

**Comment by tbhaxor** [comment]
> To what format are you converting? I cannot reproduce.

Markdown

**Comment by tbhaxor** [comment]
@t-makaro  i have referenced the solution

**Comment by t-makaro** [comment]
> #1072
> 
> Replace all the latex with the image
> You can use https://latex.codecogs.com/gif.latex
> The latex text y = mx + b should be replaced with https://latex.codecogs.com/gif.latex?y=mx+b
> Which will evaluate to ![image](https://camo.githubusercontent.com/2cc22497187add30e976c4c866612be5e133595b/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f793d6d782b62)

This could be achieved with a custom preprocessor.

But I would consider this a limitation of your markdown viewer. The Jupyter markdown viewer renders the latex just fine.

**Comment by tbhaxor** [comment]
> > #1072
> > Replace all the latex with the image
> > You can use https://latex.codecogs.com/gif.latex
> > The latex text y = mx + b should be replaced with https://latex.codecogs.com/gif.latex?y=mx+b
> > Which will evaluate to ![image](https://camo.githubusercontent.com/2cc22497187add30e976c4c866612be5e133595b/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f793d6d782b62)
> 
> This could be achieved with a custom preprocessor.
> 
> But I would consider this a limitation of your markdown viewer. The Jupyter markdown viewer renders the latex just fine.


But when exported as .md it doesn't :wink: I referenced a solution. Since I can't devote time in implementation

**Comment by t-makaro** [comment]
When exported as .md, some markdown viewers can render the latex just fine. Not rendering equations is a limitation in whatever markdown viewer that you are using. 

I also wouldn't want to explicitly rely on an online source for converting latex to images since the file won't be readable offline.
