### ISSUE TITLE
Replace the latex string in with image when converting ipynb to markdown

### ISSUE THREAD

**Issue by tbhaxor** [jupyter/nbconvert#1078]
#1072 

Replace all the latex with the image 
You can use https://latex.codecogs.com/gif.latex

The latex text `y = mx + b` should be replaced with `https://latex.codecogs.com/gif.latex?y=mx+b`

Which will evaluate to ![](https://latex.codecogs.com/gif.latex?y=mx+b)

**Comment by tbhaxor** [comment]
Let me give it a try...

If i couldn't i will inform you here

**Comment by t-makaro** [comment]
Closing as a duplicate issue of #1072
