### ISSUE TITLE
Image attachment not shown when converting to PDF

### ISSUE THREAD

**Issue by t-makaro** [jupyter/nbconvert#1079]
[image_test.ipynb.zip](https://github.com/jupyter/nbconvert/files/3459000/image_test.ipynb.zip)

Running ```Jupyter nbconvert --to pdf image_test.ipynb``` on a notebook with an attachment ```![image.png](attachment:image.png)```, the resulting image is not shown. Similar too #699.

In nbconvert 5.5 a pdf is still produced, after #1053 this throws an error.

**Comment by ghayth82** [comment]
I am facing the same issue, any solution or workaround?

**Comment by alelom** [comment]
Also by doing
```latex
\begin{figure}[h!]
\includegraphics[scale=1.7]{myImage.png}
\end{figure}
```
the exported PDF does not show any image.

**Comment by thiagogjt** [comment]
Isn't the case to use the notebook path as a working directory instead of a temporary one? Are there any restrictions on doing that?

**Comment by tashrifbillah** [comment]
Okay folks--finding no other way, I ended up breaking down my markdown cells as markdown--python--markdown cells with the middle one as:

```python
from IPython.display import display, Image
display(Image(filename="a.png", height=400, width=400))
```

Now `jupyter-nbconvert --to PDFviaHTML notebook.ipynb` properly converts to `notebook.pdf`.

**Comment by khurchla** [comment]
Struggling with this to brand jupyter notebook output with a logo

**Comment by zachbellay** [comment]
@tashrifbillah Thank you for your solution! This worked for me. Hopefully this is resolved soon as this is a pretty common use case.

**Comment by joernhees** [comment]
i don't think this is a PDF exporting issue only, for me HTML export with images that were pasted into markdown (attached to cell metadata) also doesn't work...

from what i can tell this seems related to #1057 and seems to have been fixed after #699, #780, #980 ...
is this maybe a regression?

**Comment by Dr-Dum** [comment]
@tuncbkose  I believe this issue is still present as of v7.4.0 in which #1978 should have been merged if I'm not mistaken (please correct me if I'm wrong).

I'm using jupyter notebook version 6.5.4. I'm embedding the image with the following:
```
5. Consider the following simple graph <br> <img src = "plot.png" style = "width:200px;height:100px;"> <br>Write down the graph Laplacian matrix and find the eigenvectors associated with the zero eigenvalues. Explain how you find out the number of disconnected clusters in the graph and identify these disconnected clusters using these eigenvectors.
```

Which looks like this:
![Screenshot in Markdown](https://github.com/jupyter/nbconvert/assets/101877538/28123cf5-8203-4454-8687-15a3b36babe5)

However, when I convert the notebook, I get the following:
![Rendered PDF](https://github.com/jupyter/nbconvert/assets/101877538/1a3c23cc-45ec-4d3f-a295-860459514645)

**Comment by tuncbkose** [comment]
The fix above applies to PDF generation via LaTeX (`--to pdf`). Does that work for you?

I don't exactly remember the state of PDF via HTML because I didn't use it much. Also are your relative paths the same? You have both `./data/` and `../data/`.

**Comment by normanius** [comment]
Okay. Thanks. Will do it.

**Comment by sanjay-906** [comment]
This worked for me:
1. Upload the file to Google Colab.
2. In each instance where there is an image, remove that line "![data](data.jpg)" and click "Insert image" (this option will appear in the title bar of the markdown cell); upload the image from your local
3.This will embed the image data as base64 in the cell.
4. Now, download the notebook and convert it to pdf as before.

**Comment by sanjay-906** [comment]
Convert that image to base64 and then pass it.
```python
import base64
with open("numpylogo.jpeg", "rb") as img:
    img_data = str(base64.b64encode(img.read()))[2:-1]
``` 

now just print that. then copy that huge string (without the single quotes), and replace it where you want to see the markdown image:

`![image](data:image/jpeg;base64,that_big_base64_content)`

remove that _that_big_base64_content_ and paste your content (after the comma), and run.

This worked for me
