### ISSUE TITLE
Slides export not rendering html tag style specifications

### ISSUE THREAD

**Issue by artur-deluca** [jupyter/nbconvert#1110]
I currently use jupyter (6.0.1) to make some presentations, namely along with RISE (5.4.1) to edit and check the slides as I go.

Sometimes I use Html tags to customize some parts. It works fine rendering with RISE, but once I use nbconvert, tags such as `<p style="font-size:0.8em;"><i>Hey</i></p>` do not render properly, not loading the style configurations.

Can anyone shed some light on this? 

**Nbconvert version:** 5.6.0

**Comment by mfrata** [comment]
Guys, anyone else had this problem? Can only use the Slides cell types due to this error...

**Comment by artur-deluca** [comment]
Solved. Instead of `<i>`, I ended up using `font-style: italic;`
