### ISSUE TITLE
Can't modify data_png section with tplx template

### ISSUE THREAD

**Issue by collinmccarthy** [jupyter/nbconvert#1127]
I posted this question on Jupyter Discourse [here](https://discourse.jupyter.org/t/help-using-custom-nbconvert-template-for-latex-figures/2520) 5 days ago, but haven't gotten a reply, so I'm posting here as well.

I’ve gone over the documentation on how to create a custom latex template for nbconvert, and I found a few good ones to work from, most notably Julius Schulz post [here](http://blog.juliusschulz.de/blog/ultimate-ipython-notebook#templates). Everything seemed to be working a couple of weeks ago, using the `![caption](path.png)` markdown syntax and a template similar to the one from his website, but now all of the figures are simply using the same default behavior, presumably from Pandoc. No matter what I put in the ((*- block data_png -*)) section, it makes no impact on the converted latex - every PNG always uses the formatting here:

```
\begin{figure}
\centering
\includegraphics{path.png}
\caption{caption}
\end{figure}
```
Assuming I’m the only one having this issue recently, can anyone help me understand what could be going on? The only way I can get the \begin{figure} block to change is to override ((*- block markdowncell -*)) or an input group higher up, but I would have thought something like
```
((*- block data_png -*))
<My LaTeX code>
((* endblock *))
```
would override Pandoc’s behavior for any PNG image and allow me to use my code instead.

Thank you!

**Comment by MSeal** [comment]
Sorry for not paying close attention to the discourse topic, I also sometimes take a couple of days to catch up on github issues sometimes.

What version of nbconvert are you using? If it was working a few weeks ago, could you try a few earlier versions and see if it was a particular version chance? There were some minor template changes over the past several releases that might have changed behavior. @t-makaro is likely going to be able to help more readily with latex issues in templates, but if we isolate to the version that changed behavior I can probably help isolate it.

**Comment by t-makaro** [comment]
The tplx data block for pngs is only used for cell outputs. For markdown pngs, they have always been passed through pandoc. There were some asthetic changes in 5.6 I believe, but those were done with header changes to improve style consistency with the notebook.

**Comment by collinmccarthy** [comment]
Thank you both. That makes sense then, I must have modified figures from cell outputs. Is there any way to intercept mardown or html <img src> pngs then with a tplx file? Or do I need to only be using cell outputs if I want to use tplx files to tweak my figures?

**Comment by t-makaro** [comment]
You could use a custom Jinja filter on the markdown blocks. Unfortunately, that would take a fair bit of work to parse correctly.

**Comment by collinmccarthy** [comment]
Okay, I'll stick with the cell outputs for now. Thank you again.
