### ISSUE TITLE
Removing all but tagged ...

### ISSUE THREAD

**Issue by pylang** [jupyter/nbconvert#1132]
I have notebooks i'd like to split into separate files.  I see from the [docs](https://nbconvert.readthedocs.io/en/latest/removing_cells.html#removing-pieces-of-cells-using-cell-tags) that `nbconvert` can remove unwanted content with certain criteria.

In my case, I have one tagged object.  Everything else I'd like to delete.  Is there way to `remove_all_untagged` objects?

**Comment by takluyver** [comment]
I don't think there's a way to do that. But it would be pretty easy to write a script to [load a notebook file](https://nbformat.readthedocs.io/en/latest/api.html#), iterate through the cells and do something with only cells that have tags.

**Comment by pylang** [comment]
Ah.  I see I can try to make a new notebook with the API.  Thanks.
