### ISSUE TITLE
Typo in customizing nbconvert doc page

### ISSUE THREAD

**Issue by letmerecall** [jupyter/nbconvert#1136]
**Description**
I guess there is a typo in section **Converting a notebook to an (I)Python script and printing to stdout** of https://github.com/jupyter/nbconvert/blob/master/docs/source/customizing.ipynb

Just above the 2nd code cell in the statement:
```
In this case, if you wanted to remove code cells from the output, you could use the TemplateExporter.exclude_markdown traitlet directly, as below.
```

**Expected Behaviour**

~~`code`~~ sould be replaced by `non-code`

**Comment by MSeal** [comment]
Wanna make a PR with the text change?

**Comment by letmerecall** [comment]
Sure, will do that :+1:
