### ISSUE TITLE
Please remove package 'grffile' from latex/base.tplx - it breaks with XeLaTeX

### ISSUE THREAD

**Issue by cholmcc** [jupyter/nbconvert#1140]
Hi, 

Dear Maintainer,

Please remove the lines

    \usepackage{grffile} % extends the file name processing of package graphics
                         % to support a larger range
    \makeatletter % fix for grffile with XeLaTeX
    \def\Gread@@xetex#1{%
      \IfFileExists{"\Gin@base".bb}%
      {\Gread@eps{\Gin@base.bb}}%
      {\Gread@@xetex@aux#1}%
    }
    \makeatother

from

    nbconvert/templates/latex/base.tplx

Even though upstream tried to fix it, grffile is broken (latest version
on github https://github.com/ho-tex/grffile is a stub).  The result is,
that notebooks exported to LaTeX or PDF will show _no_ images unless
one tells, e.g., matplotlib _explicitly_ to generate PDFs

    %matplotlib inline
    try:
        from IPython.display import set_matplotlib_formats
         set_matplotlib_formats('png','pdf')
    except Exception as e:
        pass

The attached notebook illustrates the problem.  Simply load and do **File->Export...->PDF** and one get the result shown in attachment _Bug-nofix.pdf_.  With `fix = True` at the top, one get _Bug-withfix.pdf_. 

**NBConvert version**: 5.6.0-1 (Debian 'sid')

Thanks.

Christian 
[Bug.ipynb.txt](https://github.com/jupyter/nbconvert/files/3823899/Bug.ipynb.txt)
[Bug-nofix.pdf](https://github.com/jupyter/nbconvert/files/3823902/Bug-nofix.pdf)
[Bug-withfix.pdf](https://github.com/jupyter/nbconvert/files/3823904/Bug-withfix.pdf)

**Comment by njapke** [comment]
It also breaks with LuaLaTeX. Moreover, it seems `grffile` has been deprecated and is now a stub, which is causing the problems. What that package did before is now supported by default, so it should definitely be removed from the template for future versions.

**Comment by t-makaro** [comment]
It looks like a fairly recent change to both grffile and graphicx. This is great news, but I don't think we can assume that everyone has the most recent versions of those packages just yet (our CI might not even pick it up yet). I've written code for checking the package dates before, so I could do something with that. Also, this will require testing against ```\usepackage[Export]{adjustbox}``` which modifies ```\includegraphics```.
