### ISSUE TITLE
AttributeError: module 'nbconvert.exporters' has no attribute 'EncodedPythonExporter'

### ISSUE THREAD

**Issue by prfraanje** [jupyter/nbconvert#1143]
After upgrading nbconvert through pip I get "500: Internal Server" errors when opening any ipynb notebook on my Ubuntu 19.04 machine. I remove jupyter, ipython, nbconvert through apt and pip, and tried to get a clean user install with `pip install jupyter --user.` But still I get the same error. It seems that the attribute `EncodedPythonExporter` is not available in `nbconverter.exporters`. 

For more information, see this [gist](https://gist.github.com/prfraanje/7ec1bfc89d4df7d44cf113e0e377f598).

**Nbconvert version:** 5.4.1 (but same error with 5.6.1)

**Comment by MSeal** [comment]
This looks like it may more be a https://github.com/jupyter/notebook issue or an issue in your setup with a custom exporter? Perhaps you are expecting https://github.com/ttung/nbencdec/blob/e2008b1fd20da6ab02eb2b3c727bb40569d80537/nbencdec/exporters/encoded_python.py to be installed as an extension that nbconvert doesn't normally know about? Locally I can't reproduce the errror with nbconvert cli calls and that class doesn't exist in nbconvert.

**Comment by prfraanje** [comment]
Thank you! The issue has been solved by installing `nbencdec`: `pip3 install --user nbencdec`.
