### ISSUE TITLE
nbconvert 6.0 alpha release

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/nbconvert#1144]
How about we tag a pre-release from the 6.0 branch so that we can start targeting such a version downstream (e.g. in Voilà).

Are there major changes that we would like to make for the 6.0 milestone?

cc @MSeal @maartenbreddels

**Comment by MSeal** [comment]
Yes, here's the issue on the subject: https://github.com/jupyter/nbconvert/issues/1045. Major changes left that are committed to are python 3 only (mostly done?), moving execute preprocessor out of nbconvert, and fixing up the latex / pdf conversion story as it's really bad atm.

I'd be ok with an alpha release, let's at least double check the python 3 only change is all good first. We could do an alpha release for each major milestone issue completed.

**Comment by SylvainCorlay** [comment]
Thanks! Closing to keep the conversation in #1045.
