### ISSUE TITLE
LaTeX output cell breaks markdown rendering in LaTeX/PDF

### ISSUE THREAD

**Issue by mstimberg** [jupyter/nbconvert#1151]
When a code cell outputs LaTeX, all following markdown cells will use typewriter font.

An [example notebook](https://gist.github.com/mstimberg/d6087a0e7f0cd4611f309780d98a48f6) renders like this in PDF:

![screenshot_nbconvert_latex_issue](https://user-images.githubusercontent.com/1381982/70793981-e4443380-1d9c-11ea-9e47-a194f3109bb9.png)

Note that the markdown cell after the code output uses a typewriter font, even though the markdown code does not ask for it.

The example uses the `sympy` package to generate LaTeX output, but any other package generating LaTeX output should be fine (using `IPython.display.display_latex` directly will generate a cell of a different type and therefore not show the issue).

From looking at the LaTeX code, the issue seems that for non-latex output, the `\prompt` command displaying the `[1]` is wrapped in a `tcolorbox` environment, whereas for latex output it isn't. Since `\prompt` switches the font to `\ttfamily`, this affects all the following text not explicitly setting a font.

This was tested in a Python 3.8 conda environment, but with using `pip install -e '.[all]'` in the master branch of `nbconvert`.

**Nbconvert version:** 6.0.0a0.dev0

**Comment by t-makaro** [comment]
Interesting. It's probably an incorrect grouping or placement of ```\ttfamily```, since the font should automatically switch back after the prompt group exits.

**Comment by mstimberg** [comment]
Indeed, the problem might be simply that there is no group:
https://github.com/jupyter/nbconvert/blob/ee8c90ef522cea63fcf81d21d47a4c42ddc6afdf/share/jupyter/nbconvert/templates/latex/style_jupyter.tex.j2#L105-L107

Replacing this simply by (additional curly braces in line 2)
```latex
    \newcommand{\prompt}[4]{
        {\ttfamily\llap{{\color{#2}[#3]:\hspace{3pt}#4}}\vspace{-\baselineskip}}
    }
```
seems to do the trick?

**Comment by t-makaro** [comment]
@mstimberg Sounds right to me. Do you want to submit a PR?

**Comment by mstimberg** [comment]
Happy to submit a PR. However, I'm not quite sure how the test suite works – or is this "simple enough" to fix without adding a test?

**Comment by mbaudin47** [comment]
Is there a workaround for this issue?
