### ISSUE TITLE
jupyter_nbconvert_config.py is ignored through 'Download As... PDF via LaTeX (.pdf)' menu option.

### ISSUE THREAD

**Issue by csevast** [jupyter/nbconvert#1154]
The jupyter_nbconvert_config.py file seems to be ignored when nbconvert is invoked through the 'Download As... PDF via LaTeX (.pdf)' menu option.

The problem is observed in Windows 10.  A jupyter_nbconvert_config.py file created and changed in \Users\<username>\.jupyter directory. A c.TemplateExporter.template_file customization added. Also, a c.TemplateExporter.exclude_code_cell customization activated. Both of them are ignored when the 'Download As...PDF via LaTeX (.pdf)' menu option in Jupyter Notebook is selected. Executing nbconvert in CLI the behavior is as expected. Even copying the jupyter_nbconvert_config.py in the notebook under conversion directory didn't have any positive result.

**Nbconvert version: 5.6.1**

**Comment by t-makaro** [comment]
For use from jupyter notebook, place settings in the ```jupyter_notebook_config.py``` file.

**Comment by csevast** [comment]
Thank you very much.
