### ISSUE TITLE
Extending `rst.tpl` fails in current master and 6.0.0a0

### ISSUE THREAD

**Issue by matthew-brett** [jupyter/nbconvert#1158]
Extending `rst.tpl` with a DictLoader has worked up until the 6.0.0a0 alpha release, but now fails, in 6.0.0a0 as in current master (b31a5af4).

```python
import nbconvert
import nbformat
from jinja2 import DictLoader

DL = DictLoader({'rst_plus_stuff.tpl': """\
{%- extends 'rst.tpl' -%}
"""})


class MyExporter(nbconvert.RSTExporter):
    template_file = 'rst_plus_stuff.tpl'

exporter = MyExporter(extra_loaders=[DL])

nb = nbformat.v4.new_notebook()
output, resources = exporter.from_notebook_node(nb)
```

This succeeds on current stable on pip (5.6.1), but fails for current master, with:

```
Traceback (most recent call last):
  File "/Users/mb312/tmp/nbconvert_check.py", line 17, in <module>
    output, resources = plots_exporter.from_notebook_node(nb)
  File "/Users/mb312/dev_trees/nbconvert/nbconvert/exporters/templateexporter.py", line 357, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/Users/mb312/.virtualenvs/test3/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/mb312/.virtualenvs/test3/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/mb312/.virtualenvs/test3/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mb312/.virtualenvs/test3/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
jinja2.exceptions.TemplateNotFound: rst.tpl
```

**Nbconvert version:**
* 6.0.0a0
* Current master (b31a5af4)

**Comment by MSeal** [comment]
Yes, the 6.0.0 alpha has changes to the template patterns. Specifically templates now have directories with jinja (.j2) files. We released the alpha so libraries could start catching these issues early.

In this case `'rst.tpl'` becomes `'rst/index.rst.j2'` and the DictLoader will go back to working correctly.

**Comment by mgeier** [comment]
@matthew-brett This is the corresponding fix in `nbsphinx`, created by @takluyver: https://github.com/spatialaudio/nbsphinx/pull/344.

**Comment by matthew-brett** [comment]
Thanks - I'll try that fix.   I wonder how many of your upstream users are using `--pre` test envs?  Is there any way of softening the backwards compatible break here?   Like a DeprecationWarning, and auto-replace of `rst.tpl` (etc) with the new values?

**Comment by maartenbreddels** [comment]
I'm thinking about making it backwards compatible, I think that's easy to
do.

(from mobile phone)

**Comment by MSeal** [comment]
We could try to emit a deprecation warning and convert the path when we detect an old-style path. That's probably a good idea for 6.0.0 and let's us wait until 6.1 to drop the older pattern completely.

**Comment by maartenbreddels** [comment]
#1173 is an alternative way to fix this. I think I should have done this from the start but didn't think it would be that simple to provide backward compatibility.

**Comment by matthew-brett** [comment]
Excellent - thanks - that is helpful.
