### ISSUE TITLE
What to determine failure of cell execution: error iopub message or execute_reply with error status

### ISSUE THREAD

**Issue by BoPeng** [jupyter/nbconvert#1160]
There has been some discussions in the context of papermill what should be used to determine the failure of cell execution (https://github.com/nteract/papermill/issues/337), which referred to the following trunk of code

https://github.com/jupyter/nbconvert/blob/b31a5af48ee159f579c021b897727374f28a0800/nbconvert/preprocessors/execute.py#L475-L479 

That is to say, nbconvert considers a cell to be failed if a kernel sends an `error` message through `ioPub`, **OR** if the kernel returns `execute_reply` with a `status` of `error`. In the meantime, papermill only uses `error` message, not `execute_reply` (https://github.com/nteract/papermill/blob/0ee0da7fe7a9e8a8334011e1b1606fa86bd0ed8e/papermill/preprocess.py#L58).

I believe `execute_reply` should be the only message used because this is how Jupyter behaves with "Run all cells". That is to say, papermill should stop if a kernel sends an `execute_reply` with `error` status (but without an `error` message, https://github.com/nteract/papermill/issues/337) , and neither papermill nor nbconvert should stop if a kernel sends an `error` message, and an `execute_reply` message with `ok` status. My argument for the latter is that a kernel might want to sends an `error` message to **demonstrates or document an error** and still returns an `execute_reply` with an `ok` status so that the document could be executed successfully in batch mode.

**Comment by MSeal** [comment]
@mpacer @minrk Would like your input, but I believe @BoPeng's logic is correct and behavior should change in nbconvert 6.0 (nbexecute) and papermill should match that behavior.

**Comment by mpacer** [comment]
I think that this is correct logic, however I don't know if we can say clearly one way or the other based on the protocol itself: https://jupyter-client.readthedocs.io/en/stable/messaging.html#execution-errors

> When an error occurs during code execution

> 
> Message type: error:
> 
> ```
> content = {
>    # Similar content to the execute_reply messages for the 'error' case,
>    # except the 'status' field is omitted.
> }
> 
> ```

> Changed in version 5.0: pyerr renamed to error

Given that the semantics are specifically pointed out as being similar I think there's an argument in both directions. 

I get that idea for a use case also imagine having a case where an error comes in from IOPub and it assumes that any error that is raised should immediately exit and by continuing computation state/data/&c. becomes corrupted. Of the two, I think nbconvert's behaviour is the more conservative of the two options.

I think in this case we may need to rely more on what behaviour we think should exist and we think others expect to exist to guide our decision rather than in terms of what logically makes sense. 

Do we know any kernels that currently send an error message on IOPub but then do not return an error on the execute reply?

**Comment by BoPeng** [comment]
> I think in this case we may need to rely more on what behaviour we think should exist 

I think the "Run all cells" behavior should be the guiding "batch" behavior for nbconvert and papermill. At least for me, "Run all cells" is how I re-run the entire notebook and I was surprised to see papermill (and nbconvert) behaved differently.

> Do we know any kernels that currently send an error message on IOPub but then do not return an error on the execute reply?

I encountered a problem with papermill with my [SoS kernel](https://github.com/vatlab/sos-notebook) because SoS sends `execute_reply` with an `error` status without sending an `error` message when an exception happens. The consequence was that whereas Jupyter would error out during "Run all cells", papermill would exit with code 0 because no `error` message exists in the notebook. This is of course a bug with SoS (that I have fixed) but it seems that @vinaykumar80 encountered the same problem with another kernel (https://github.com/nteract/papermill/issues/337).

Another example is the `%env --expect-error` magic of `SoS` that negates the `status` of `execute_reply` so that a notebook with error could continue to execute in `Run all cells` (see an example [here](https://vatlab.github.io/sos-docs/doc/user_guide/parameter_statement.html#Optional-and-required-parameters)). The magic worked in Jupyter and JupyterLab but failed with papermill (and nbconvert) because of the `error` message. It is arguable if this is a valid use case of the `error` message, but generally speaking I think users would expect nbconvert and papermill to behave the same as Jupyter and JupyterLab in batch mode.

**Comment by MSeal** [comment]
> but generally speaking I think users would expect nbconvert and papermill to behave the same as Jupyter and JupyterLab in batch mode.

I believe that aligns with @mpacer's comment:

> I think in this case we may need to rely more on what behaviour we think should exist and we think others expect to exist to guide our decision rather than in terms of what logically makes sense.

Let's attempt to make the change so the behavior aligns with the most common interfaces (lab and classic). If there's a slight deviation from documentation I can get the official documentation updated as well to align to how it's actually used.
