### ISSUE TITLE
Export to latex gives wrong math mode format

### ISSUE THREAD

**Issue by scimax** [jupyter/nbconvert#1172]
I experienced a problem with the export to *latex*. Initially I tried to export to pdf but realized that the error originates from the exported *.tex* file.

Environment
- Windows 10 1809
- Miktex 2.9.7206
- Jupyter version:   
```bash
jupyter --version
jupyter core     : 4.6.1
jupyter-notebook : 6.0.2
qtconsole        : 4.5.5
ipython          : 7.9.0
ipykernel        : 5.1.3
jupyter client   : 5.3.4
jupyter lab      : 1.0.9
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3
```

Output from pdf export in the GUI (same on the command line):
```
nbconvert failed: PDF creating failed, captured latex output:
Failed to run "xelatex .\notebook.tex -quiet" command:
notebook.tex:397: Missing $ inserted
notebook.tex:398: Missing $ inserted
```

When I exported it to Latex first, the relevant line is:
```
This is some math output: \$ \Delta x= \int B\_y dz \$
```
Isn't that wrong? To me it seems like it should not have the backslashes in front of the *$*. So when I remove the backslashes to: `This is some math output: $ \Delta x= \int B_y dz $` it compiles to pdf properly. Am I doing wrong something in the export step? Do I have an old version? I was looking for a similar issue but could not find one. Most of the other pdf export error are also related to MikTex but I think this one is more related to nbconvert isn't it? I also updated the miktex packages.

I'm thankful for any help!

**Comment by mgeier** [comment]
You should mention the original text you were using.
I assume it was this:

    This is some math output: $ \Delta x= \int B\_y dz $

If that assumption is correct, you should try to remove the spaces after the opening and before the closing `$` sign:

    This is some math output: $\Delta x= \int B\_y dz$

This is because `nbconvert` uses `pandoc`, see https://nbsphinx.readthedocs.io/en/0.5.0/markdown-cells.html#Equations and https://pandoc.org/MANUAL.html#math.

**Comment by scimax** [comment]
You're absolutely right! Thanks for pointing me in the right direction! 
There were two or three other smaller problems which I could easily fix but I didn't where to look for this one. Thanks!
