### ISSUE TITLE
use object as basename for --output 

### ISSUE THREAD

**Issue by svdvliet** [jupyter/nbconvert#1180]
I'm trying to convert my .ipynb to .html using an object as a basename using the following code:

```r
outputfile = re.search(".*(?=\.)", "inputfilename.xlsx, flags=0)
!jupyter nbconvert check_xlsx.ipynb --output outputfile
```
this results in a file: "outputfile.html" instead of "inputfilename.html" this is nog what I expect.
Is this a bug? or am I using the incorrect syntax?

**Comment by MSeal** [comment]
I am guessing this is running inside a notebook given the `!` syntax. If so you need to change outputfile to a variable expansion by adding a `$`: `--output $outputfile`

**Comment by svdvliet** [comment]
Thanks alot :) I was not aware this was due to it being executed as a terminal command
