### ISSUE TITLE
Using nbconvert --no-input does not indent code output properly

### ISSUE THREAD

**Issue by Juan-132** [jupyter/nbconvert#1189]
When the notebook is converted using `--no-input` the code output is not indented properly.

I converted the attached notebook.
Run it using `jupyter nbconvert notebook.ipynb`
And using `jupyter nbconvert --no-input notebook.ipynb`.

[notebook.txt](https://github.com/jupyter/nbconvert/files/4193136/notebook.txt)

With a standard convert, the output is indented properly:
![output](https://user-images.githubusercontent.com/59505296/74349540-acfdfd00-4db4-11ea-85b7-f972fe9c6863.PNG)

But using --no-input, the output is not indented properly:
![output --no-input](https://user-images.githubusercontent.com/59505296/74349536-ac656680-4db4-11ea-9467-2a54d0a27144.PNG)

**Nbconvert version: 5.6.1

**Comment by Juan-132** [comment]
This is the workaround I found elsewhere
`jupyter nbconvert --TemplateExporter.exclude_input=True --no-prompt notebook.ipynb`

**Comment by MSeal** [comment]
Thanks for reporting I'll try to tag this for 6.0 release and see if we can get some focus on it before that goes out of alpha.

**Comment by sgranade** [comment]
Adding `'exclude_input_prompt': True` to the `no-input` value in `nbconvertapp.py` will fix it as per the previously-mentioned workaround:

> `jupyter nbconvert --TemplateExporter.exclude_input=True --no-prompt notebook.ipynb`

**Comment by t-makaro** [comment]
> Adding 'exclude_input_prompt': True to the no-input value in nbconvertapp.py will fix it

Funny. When ```--no-input``` was added, this was discussed and deemed redundant/an anti-pattern that we didn't want to support. See https://github.com/jupyter/nbconvert/pull/825#issuecomment-402013138. However, since this is an easy fix to the problem, I'd be open to merge it if someone wants to submit a pull request.

**Comment by joyceerhl** [comment]
Hi @t-makaro, I submitted a pull request for this: https://github.com/jupyter/nbconvert/pull/1444 😊

**Comment by MSeal** [comment]
The work-around has been merged, I'm going to close for now but if other rendering issues related come up with no-input feel free to create a new issue.
