### ISSUE TITLE
Getting: No module named 'TagRemovePreprocessor'

### ISSUE THREAD

**Issue by benholtzmansmith** [jupyter/nbconvert#1194]
Following instructions here: https://github.com/jupyter/nbconvert/blob/129bdbf5bc81c97c326c45b08f0331bff773d167/docs/source/removing_cells.rst

I use this code: 
```
from traitlets.config import Config
from nbconvert.exporters import HTMLExporter

c = Config()

c.TagRemovePreprocessor.remove_input_tags = ('remove_input',)

# Configure and run out exporter
c.HTMLExporter.preprocessors = ["TagRemovePreprocessor"]
HTMLExporter(config=c)
```

And get the following error:
```
~/path/to/my/python/site-packages/traitlets/utils/importstring.py in import_item(name)
     40     else:
     41         # called with un-dotted string
---> 42         return __import__(parts[0])

ModuleNotFoundError: No module named 'TagRemovePreprocessor'
```

Python: 3.7
nbconvert: 5.6.1
traitlets: 4.3.3

Anything I am doing wrong here?

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/getting-no-module-named-tagremovepreprocessor/3385/1

**Comment by e-sr** [comment]
I have the same problem.
a workaround is register the preprocessor using the exporter `register_preprocessor` method

```python
c = Config()
c.TagRemovePreprocessor.remove_all_outputs_tags = ('remove_output',)
exporter = MarkdownExporter()
exporter.register_preprocessor(TagRemovePreprocessor(config=c),True)
```

**Comment by t-makaro** [comment]
I think that I found your issue. You need a full importable name (or an object that is a class) when using
```c.Exporter.preprocessors = ```
like
```['nbconvert.preprocessors.TagRemovePreprocessor']```
See https://github.com/jupyter/nbconvert/blob/06c12da59c50c6f554c6f84123d897fd13a4843e/nbconvert/exporters/exporter.py#L76

However this is actually not needed. The ```c.Exporter.preprocessors = ``` setting is for user created preprocessors. All of the defaults are loaded but may be turned off. To turn it on you can use:
```python
c.TagRemovePreprocessor.enabled=True
```
See https://github.com/jupyter/nbconvert/blob/06c12da59c50c6f554c6f84123d897fd13a4843e/nbconvert/exporters/exporter.py#L258

**Comment by yuanzhaoYZ** [comment]
Thanks, @t-makaro .  I was able to get it working. 

```python
from traitlets.config import Config
import nbformat as nbf
from nbconvert.exporters import NotebookExporter
from nbconvert.preprocessors import TagRemovePreprocessor
c = Config()

# Configure our tag removal
c.TagRemovePreprocessor.remove_cell_tags = ("remove_cell",)
c.TagRemovePreprocessor.remove_all_outputs_tags = ('remove_output',)
c.TagRemovePreprocessor.remove_input_tags = ('remove_input',)
c.TagRemovePreprocessor.enabled = True


# Configure and run out exporter
c.NotebookExporter.preprocessors = ["nbconvert.preprocessors.TagRemovePreprocessor"]

exporter = NotebookExporter(config=c)
exporter.register_preprocessor(TagRemovePreprocessor(config=c),True)

exporter.from_filename("XXXXX.ipynb")

```

**Comment by summerswallow-whi** [comment]
This is very helpful and works. I'd recommend updating the documentation for the present version. If it gets fixed you can change it back. Also as a practical matter, it would be helpful to either include the code to write the output or link to another page that does. One shouldn't have to spend an hour on the internet to hunt down the complete solution to a simple example.

**Comment by lwasser** [comment]
The full solution in case anyone is trying to export to html! the above got me so close! i figured i'd save others the time in figuring out how to export to html. :)
 +1 on the docs update if there is time for it. 
The features in nbconvert to hide parts of a notebook are really nice!!

```python
from traitlets.config import Config
import nbformat as nbf
from nbconvert.exporters import NotebookExporter
from nbconvert.preprocessors import TagRemovePreprocessor

# Setup config
c = Config()

# Configure tag removal - be sure to tag your cells to remove using the words below! 
c.TagRemovePreprocessor.remove_cell_tags = ("remove_cell",)
c.TagRemovePreprocessor.remove_all_outputs_tags = ('remove_output',)
c.TagRemovePreprocessor.remove_input_tags = ('remove_input',)
c.TagRemovePreprocessor.enabled = True

# Configure and run out exporter
c.HTMLExporter.preprocessors = ["nbconvert.preprocessors.TagRemovePreprocessor"]

exporter = HTMLExporter(config=c)
exporter.register_preprocessor(TagRemovePreprocessor(config=c),True)

# Configure and run out exporter - returns a tuple - first element with html, second with notebook metadata
output = HTMLExporter(config=c).from_filename("your-notebook-file-path.ipynb")

# Write to output file
with open("your-output-file-name.html",  "w") as f:
    f.write(output[0])
```

**Comment by lwasser** [comment]
hi @yuvipanda ! are you open to a PR with the above [fix to the docs](https://nbconvert.readthedocs.io/en/latest/removing_cells.html)?? i'm so excited that nbconvert runs notebooks and hides cells. I have been using a work around for years not thinking this had been integrated :) Such awesome work! 

I just stole (borrowed) :) the code above provided by @yuanzhaoYZ  and then added the write output part.

**Comment by yuvipanda** [comment]
@lwasser absolutely! Happy to put some time into reviewing that :)

**Comment by lwasser** [comment]
ok wonderful.  I'll  submit something either tonight or tomorrow @yuvipanda !
