### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by davidbrochart** [jupyter/nbconvert#1206]
When do you plan to make a release? We need one in order to have async execution in Voila (https://github.com/voila-dashboards/voila/pull/541).

**Comment by MSeal** [comment]
https://github.com/jupyter/nbconvert/issues/1045 -- I've been focused on getting other major releases out (nbclient being a dependency for the 6.0 release). With those done I can help focus on getting 6.0 shippable. The next alpha release will be after we change the execute PreProcessor to be nbclient based (and may change PreProcessors to Processors)

**Comment by MSeal** [comment]
@davidbrochart 6.0.0a1 is out now with current master changes as an alpha release.

**Comment by SylvainCorlay** [comment]
Closing and refering to #1045.
