### ISSUE TITLE
svg to pdf with Inkscape 1.0

### ISSUE THREAD

**Issue by XanderDW** [jupyter/nbconvert#1210]
As of macOS Catalina (10.15), 32-bit apps are no longer allowed, so Inkscape users are forced to use Inkscape 1.0, which is currently still in beta.

There are 2 changes that are relevant to `nbconvert` to work with Inkscape 1.0:

- `--export-pdf` should be changed to `--export-file`
- The binary is now located in '/Applications/Inkscape.app/Contents/MacOS/inkscape'

I fixed the code on my local machine, but I'm not sure how to write it such that it works for both Inkscape 0.x users and 1.0 users (and for mac users and non-mac users), so perhaps someone can take a look at this.

Much appreciated!

**Comment by MSeal** [comment]
https://github.com/jupyter/nbconvert/pull/1205 I believe solves this and should go out with the next alpha release.

**Comment by XanderDW** [comment]
Thanks! Indeed this solves it.
