### ISSUE TITLE
Declare the type of code when converting notebook to markdown

### ISSUE THREAD

**Issue by Bennett-Yang** [jupyter/nbconvert#1219]
I mean the code block in markdown converted from notebook should be
````
```python
# python code here
```
````
instead of
````
```
# python code here
```
````
which cannot display highlight properly.

**Comment by MSeal** [comment]
Because no one has implemented it yet :) -- it's a good idea, though you'll need to grab the langage name from the notebook metadata since it might not be python always. Would be a good first feature for someone.

**Comment by Bennett-Yang** [comment]
I get it. Thanks for your answer!

**Comment by MSeal** [comment]
Closing as the issue should be resolved in 6.x releases.
