### ISSUE TITLE
dependency on IPython in ipython2python

### ISSUE THREAD

**Issue by aaren** [jupyter/nbconvert#122]
There is a dependence on `IPython.core` in [filters.strings](https://github.com/jupyter/nbconvert/blob/2ffe7cb2661532db40a8f463a61252e89d5ed973/nbconvert/filters/strings.py#L20]. This isn't listed in the requirements though. 

This means that I need to require ipython as well as nbconvert if my package only has a dependence on nbconvert.

**Comment by minrk** [comment]
We should remove the dependency, rather than express it. (#123)
