### ISSUE TITLE
Config option `template_path` not recognized by `NotebookExporter`.

### ISSUE THREAD

**Issue by joelostblom** [jupyter/nbconvert#1229]
When I run `jupyter nbconvert --to notebook test.ipynb`, the following warning appears:

```
[NbConvertApp] WARNING | Config option `template_path` not recognized by `NotebookExporter`.
```

The notebook is still exported fine, but it would be nice to silence the warning if possible. It does not occur with any of the other export formats I tested (python, markdown, pdf, slides, html).

I don't think I have set `template_path` manually anywhere, grepping `~/.jupyter/` only shows a single commented out occurrence in `jupyter_notebook_config.py` (so not same as https://github.com/jupyter/nbconvert/issues/895):

```
150:# c.NotebookApp.extra_template_paths = []
```

Package versions:

```
nbconvert           5.6.1
notebook            6.0.3
IPython             7.12.0
jupyter_client      5.3.4
jupyter_core        4.6.3
jupyterlab          1.2.6
-----
Python 3.8.1 | packaged by conda-forge | (default, Jan 29 2020, 14:55:04) [GCC 7.3.0]
Linux-5.5.13-arch1-1-x86_64-with-glibc2.10
```

**Comment by MSeal** [comment]
I think this is already fixed in master and possibly the 6.0.0a0 alpha release.

**Comment by joelostblom** [comment]
Thank you! I can confirm that the warning is gone on 6.0.0a1.

**Comment by GF-Huang** [comment]
Issue still `6.0.7`.

**Comment by Arm-lalala** [comment]
> Issue still `6.0.7`.

I met the same problem. I install nbconvert 6.0.7, but when I run `jupyter-notebook` and open a new notebook in the browser, there will be such kind of error in the terminal:
```
[W 23:12:49.294 NotebookApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 23:12:49.322 NotebookApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
```
Then I reinstall nbconvert of  version 5.6.1, then everything is OK!
```
conda install -c anaconda nbconvert=5.6.1
```
