### ISSUE TITLE
Import location for CellExecutionError has changed

### ISSUE THREAD

**Issue by mgeier** [jupyter/nbconvert#1237]
Previously, I could use this as `nbconvert.preprocessors.execute.CellExecutionError`.

With the current `master` version, this has changed to `nbconvert.preprocessors.CellExecutionError`.

I have nothing against the new location, but what about importing the class in the old place as well to avoid backwards-compatibility problems?

It doesn't really cost anything, does it?

**Comment by MSeal** [comment]
I'm ok including the import there -- though one of the last things left on our 6.0 roadmap was to change preprocessor into just processor so the import path is likely the change regardless. Would you want the exception to be importable from wherever `execute` ends up?

**Comment by mgeier** [comment]
I'm currently doing `import nbconvert` and then I simply use `nbconvert.preprocessors.execute.CellExecutionError`.

It would be nice if this would continue to work.

If not, I'll have to catch an `ImportError`, which isn't a big deal, just a minor inconvenience:

https://github.com/mgeier/nbsphinx/commit/b90cfb5d2a8cabf70d5dd21d1c105e71a334dc06

But if you are removing/renaming the whole `preprocessors` sub-module, I'll have to re-do my imports anyway.

**Comment by mgeier** [comment]
Since #1289 has been rejected, is this now staying at `nbconvert.preprocessors.CellExecutionError`?

And will `nbconvert/preprocessors/execute.py` stay around?

If yes, why not just keep the old import?

To be clear, what I'm suggesting is:

in `nbconvert/preprocessors/execute.py`, add:

```python
from nbclient.exceptions import CellExecutionError
```

... and in `nbconvert/preprocessors/__init__.py` restore the old behavior (which was changed in e7bf8350435a66cc50faf29ff12df492be5d7f57):

```python
from .execute import ExecutePreprocessor, CellExecutionError
```

... and remove the then obsolete lines:

```python
# Backwards compatability for imported name
from nbclient.exceptions import CellExecutionError
```

**Comment by mgeier** [comment]
Turns out this has recently be done, see 2cbae6eef584cc7841af9da636da157f31278724 and #1288.

**Comment by MSeal** [comment]
Yep I had the same conclusion :)
