### ISSUE TITLE
How am I supposed to use new template system?

### ISSUE THREAD

**Issue by rubendibattista** [jupyter/nbconvert#1240]
I have this:
```
class MyMdExporter(TemplateExporter):
    file_extension = ".md"
    template_file = "markdown/index.md.j2"
```

But it fails since in the file `index.md.j2`, there's an `{% extends display_priority.j2 %}` instead of `{% extends base/display_priority.j2 }%` (and also recursively, in `display_priority.j2`, the reference to `null.j2`}
```
jinja2.exceptions.TemplateNotFound: display_priority.j2
```

What I did is this:
```
diff --git a/share/jupyter/nbconvert/templates/base/display_priority.j2 b/share/jupyter/nbconvert/templates/base/display_priority.j2
index beaa196a..56ad7cde 100644
--- a/share/jupyter/nbconvert/templates/base/display_priority.j2
+++ b/share/jupyter/nbconvert/templates/base/display_priority.j2
@@ -1,4 +1,4 @@
-{%- extends 'null.j2' -%}
+{%- extends 'base/null.j2' -%}
 
 {#display data priority#}
 
diff --git a/share/jupyter/nbconvert/templates/markdown/index.md.j2 b/share/jupyter/nbconvert/templates/markdown/index.md.j2
index 8906eff8..f4421520 100644
--- a/share/jupyter/nbconvert/templates/markdown/index.md.j2
+++ b/share/jupyter/nbconvert/templates/markdown/index.md.j2
@@ -1,4 +1,4 @@
-{% extends 'display_priority.j2' %}
+{% extends 'base/display_priority.j2' %}
 
 
 {% block in_prompt %}
```

Is it correct? Or do I need to copy the `markdown/index.md.j2` into `compatibility/markdown.tpl`?

**Comment by MSeal** [comment]
There was some refactoring of template code before the last alpha release for 6.x release. I think the change you made is correct to resolve the issue at hand. The compatibility directory is to continue supporting the old template / file naming conventions for some time.
