### ISSUE TITLE
Weird space between equation and text from ipynb to html

### ISSUE THREAD

**Issue by rosgori** [jupyter/nbconvert#1242]
### Description

There is a weird space between an equation and text when you use `nbconvert` from `ipynb` to `html`.

### Can you list steps to reproduce this issue?

Copy this to your favorite text editor

<details><summary>Code</summary>

```
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "This is a test with mathematical formulas:\n",
    "\n",
    "$P(a \\lt X \\lt b) =  \\int_a^b \\mathrm{pdf}(x) \\, dx.$\n",
    "\n",
    "Although it is better in this form, so much better, better even that better, better even that better, better even that better, better even that better:\n",
    "\n",
    "$$P(a \\lt X \\lt b) =  \\int_a^b \\mathrm{pdf}(x) \\, dx.$$\n",
    "\n",
    "More of this just to show the weird space between this line and the equation that follows, in other words, the next equation:\n",
    "\n",
    "$$p(x \\mid a,b) = \n",
    "\\begin{cases} \n",
    "    \\dfrac{1}{b-a} & \\text{for $a \\le x \\le b$,} \\\\ \n",
    "    0 & \\text{for the world.} \n",
    "\\end{cases}$$\n",
    "\n",
    "Pay attention to this line. Pay attention to this line. Pay attention to this line. Pay attention to this line. Pay attention to this line. Pay attention to this line. Pay attention to this line. Pay attention to this line. Pay attention to this line. Pay attention to this line. Pay attention to this line. Pay attention to this line, seriously:\n",
    "\n",
    "$$\n",
    "p(x \\mid a,b) = \n",
    "\\begin{cases} \n",
    "    \\dfrac{1}{b-a} & \\text{for $a \\le x \\le b$,} \\\\\n",
    "     0 & \\text{for the world.} \n",
    "\\end{cases}\n",
    "$$\n",
    "\n",
    "You could expect a weird output if this line is very long, really, really, really, really, really, really, really, really, really, really, really, really, really long.\n",
    "\n",
    "$$p(x \\mid \\mu) = \\dfrac{\\mu^{x} e^{-\\mu}}{x!}.$$\n",
    "\n",
    "This is a sentence, just sentence that should be long. Repeat that several times. Repeat that several times. Repeat that several times.\n",
    "\n",
    "$$f(\\mathbf{x}\\ |\\ \\mu, \\Sigma^{-1}) = (2 \\pi)^{-k/2} |\\Sigma|^{-1/2} \\exp\\left(-\\frac{1}{2} (\\mathbf{x} - \\mu)^{\\top} \\Sigma^{-1} (\\mathbf{x} - \\mu)\\right).$$"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Nothing to see\n"
     ]
    }
   ],
   "source": [
    "print('Nothing to see')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
```
</details>

and save it as `test-nb-ht.ipynb` (or you could select another name for the file). Then run

`jupyter nbconvert test-nb-ht.ipynb`.

Open the file `test-nb-ht.html` with a web browser and look closely at each equation and the text before that formula.

![formula-mala](https://user-images.githubusercontent.com/33338133/80335809-ffc74c80-881a-11ea-9b37-74990ef41fbf.png)

It is really weird. Now, upload that Jupyter notebook somewhere, let's say Github and use the site https://nbviewer.jupyter.org/ to see that notebook (I have already done that [here](https://nbviewer.jupyter.org/github/rosgori/Pruebas/blob/master/test-nb-ht.ipynb)) and look closely at each equation.

![formula-buena](https://user-images.githubusercontent.com/33338133/80335701-becf3800-881a-11ea-92d3-7621c6712890.png)

It looks perfect! So my questions are: Is this a bug? Is it related to `nbconvert` or to one of the tools that `nbconvert` uses?

**Nbconvert version:** 5.6.1

**Comment by MSeal** [comment]
Do you mean that the footer/header space around text relative to the equations is shorter? Likely the css being generated needs some attention. You should try the 6.0.0a1 alpha release and see if it's improved. There were some template improvements in there but I don't remember if html styling for equations was one.

**Comment by rosgori** [comment]
With `nbconvert: 6.0.0a1`, I get:

![mala-formula2](https://user-images.githubusercontent.com/33338133/80454065-0fb06080-88ef-11ea-8f25-2ad1d7cad306.png)

By the way, I have always assumed that https://nbviewer.jupyter.org/ uses `nbconvert`, is that right? Because the output is good (the space between the equation and the text before the equation).

**Comment by MSeal** [comment]
It does, but it has it's own templates: https://github.com/jupyter/nbviewer/blob/f69705373d1402afd924a77712e7c63659e2b57f/nbviewer/templates/notebook.html
which probably accounts for the style change. If you'd be willing it might be nice to cross post an issue over there to see if folks have a desire to pull template improvements into nbconvert (we're pretty short on active devs for this project in particular atm so all the help we can get is appreciated).

**Comment by rosgori** [comment]
Perfect! I will ask them because I see two styles https://github.com/jupyter/nbviewer/blob/f69705373d1402afd924a77712e7c63659e2b57f/nbviewer/templates/notebook.html#L52 and I would like to know which one they are using.

**Comment by rosgori** [comment]
This feels... I am using MathJax v2.7.5 (Firefox, although I don't know how to change the version) and I have always selected `Math Settings -> Math Renderer -> HTML-CSS`. If I change to `Common HTML`, the weird space is gone.

![buena-formula](https://user-images.githubusercontent.com/33338133/80565413-00e0b100-89b6-11ea-903e-c4826f734f39.png)

Still, the weird space is still there with the option `HTML-CSS`.

**Comment by rosgori** [comment]
@MSeal I think I have found a solution. Should I make a pull request to `master` or to the branch `5.x`?

**Comment by MSeal** [comment]
Sorry if I wasn't super responsive to your questions, but thank you so much for tracking down the issue and submitting a PR!
