### ISSUE TITLE
Can extra_arguments be made configurable in ExecutePreprocessor?

### ISSUE THREAD

**Issue by tdpetrou** [jupyter/nbconvert#1254]
In the `ExecutePreprocesor` class, the `extra_arguments` traitlet is not configurable (i.e. we cannot do `c.ExecutePreprocessor.extra_arguments = [commands here]`) because it is not defined with `.tag(config=True)`.

I'm guessing there is a reason for this.

I see that I can set it with the constructor `ExecutePreprocessor(extra_arguments=[commands here])`, but it seems like one of the only traitlets that's not configurable.

**Comment by MSeal** [comment]
This is probably an oversight afaik. However this code now lives in https://github.com/jupyter/nbclient/blob/master/nbclient/client.py#L136 if you wanted to make a PR there.

**Comment by tdpetrou** [comment]
Thanks, I'll create an issue/PR over there.
