### ISSUE TITLE
Respect isolated metadata flag when converting to HTML

### ISSUE THREAD

**Issue by takluyver** [jupyter/nbconvert#129]
The live notebook looks for an `"isolated": true` flag in the metadata to put SVG/HTML in an iframe. However, conversion to static HTML appears to ignore this flag.

I suspect that this is the cause of IRkernel/IRkernel#198.

**Comment by flying-sheep** [comment]
maybe this can work with static documents by doing `<iframe src="data:...">`

**Comment by takluyver** [comment]
It looks like there's a srcdoc attribute, so you can do `<iframe srcdoc="<h1>Boo</h1>"/>`. Ugly, but better than a base-64 data URL. Not supported in IE, though.

**Comment by flying-sheep** [comment]
neither does it support `src`, so IE users are out of luck anyway.

`srcdoc` sounds good. we only need to escape `"` and put it into `srcdoc` then?

**Comment by flying-sheep** [comment]
maybe we should special-case SVG and use `<img src="data:...">`?

**Comment by takluyver** [comment]
I think the srcdoc approach we described before is nicer than base64-ing text data.

**Comment by flying-sheep** [comment]
i meant using imgs generally for SVG. but the most important thing is to get it in :wink:

**Comment by michaelpacer** [comment]
Is this still open? 

Also, given the concerns elsewhere (https://github.com/jupyter/nbconvert/issues/328) that seem pro data URIs why is there anti data URI sentiment here? Is that not a valid solution?

**Comment by flying-sheep** [comment]
the other thread doesn’t mention srcdoc, so that should work.

HTML/XML attribute values (strings) can span multiple lines, so we just need to think about quoting. would it be enough to

1. replace (in the HTML code) `&` with `&amp;` (so no entities will be expanded in the string)
2. replace `"` with `&quot;` (so the string isn’t ended prematurely)

this would result in this doc

```html
<div title="baz&quot;">
  &hellip;
</div>
```

being emedded like so:

```html
<iframe srcdoc="<span title=&quot;baz&amp;quot;&quot;>
    &amp;hellip;
</span>"></iframe>
```

which makes it still more readable than base64 encoded data

**Comment by takluyver** [comment]
@michaelpacer data URIs are an OK if somewhat ugly way of embedding binary data like images into a text-based format like HTML. Encoding HTML, which is already text, into unreadable base64 data seems rather inelegant. That's why I prefer the srcdoc approach.

**Comment by mpacer** [comment]
I can revisit this if desired after the 5.2 release.

**Comment by flying-sheep** [comment]
this is definitely still wanted!

**Comment by MSeal** [comment]
Removing milestone altogether as no one is pushing this change into PR form.

**Comment by MSeal** [comment]
Closing as @Nihiue 'd PR for this is in the new 6.1 release
