### ISSUE TITLE
Output to folder

### ISSUE THREAD

**Issue by MarcoGorelli** [jupyter/nbconvert#1299]
If I have a directory structure as follows:
```

├── build
├── notebooks
│   └── demo_notebook.ipynb
```

I'd like to be able to, from the root directory, convert a notebook from `notebooks` to html and save it in `build`.

```
jupyter nbconvert notebooks/demo_notebook.ipynb --output build/
```

I can currently achieve this with
```
jupyter nbconvert notebooks/demo_notebook.ipynb
mv notebooks/demo_notebook.html build/
```

----

Would a feature of this kind be welcome? Am happy to work on a pull request if so

**Comment by t-makaro** [comment]
I think that the ```--output-dir``` argument will do this. https://nbconvert.readthedocs.io/en/latest/config_options.html#cli-flags-and-aliases:~:text=output%2Ddir%20(FilesWriter.build_directory)

**Comment by MarcoGorelli** [comment]
@t-makaro you're right, thank you! I was looking at https://nbconvert.readthedocs.io/en/latest/usage.html#supported-output-formats expecting to find it there, but I should've checked the config options first, will do so in the future
