### ISSUE TITLE
Using `--execute` results in `TagRemovePreprocessor` being ignored

### ISSUE THREAD

**Issue by MarcoGorelli** [jupyter/nbconvert#1300]
If I run
```
jupyter nbconvert notebooks/demo_notebook.ipynb \
--TagRemovePreprocessor.enabled=True \
--TagRemovePreprocessor.remove_input_tags='{"remove-input"}' \
--TagRemovePreprocessor.remove_all_outputs_tags='{"remove-output"}'
```
then, as expected, the output from the cell where I've added the `remove-output` tag is hidden.

On the other hand, if I run
```
jupyter nbconvert notebooks/demo_notebook.ipynb \
--TagRemovePreprocessor.enabled=True \
--TagRemovePreprocessor.remove_input_tags='{"remove-input"}' \
--TagRemovePreprocessor.remove_all_outputs_tags='{"remove-output"}' \
--execute
```
then its output is no longer hidden.

[demo_notebook.txt](https://github.com/jupyter/nbconvert/files/4809349/demo_notebook.txt)

First case:
![image](https://user-images.githubusercontent.com/33491632/85223249-803ca080-b3b9-11ea-956d-1b2677b564c4.png)

Second case:
![image](https://user-images.githubusercontent.com/33491632/85223256-99455180-b3b9-11ea-8c25-4f7d9dc4827a.png)

**Nbconvert version:**
```
$ jupyter nbconvert --version
5.6.1
```

**Comment by MSeal** [comment]
So the underlying issue is that the preprocessors being added on your behalf are un-ordered, so by unlikely chance the `--execute` turning on the `ExecutePreprocessor` is getting applied after the `TagRemovePreprocessor`. To fix this you can set the preprocessors to use in an explicit order by doing:

```
jupyter nbconvert demo_notebook.ipynb --TagRemovePreprocessor.remove_input_tags='{"remove-input"}' --TagRemovePreprocessor.remove_all_outputs_tags='{"remove-output"}' --Exporter.preprocessors='["nbconvert.preprocessors.ExecutePreprocessor","nbconvert.preprocessors.TagRemovePreprocessor"]' --to notebook
```

(Note I tested this on the 6.0.0a4 alpha and not 5.6.1 but it should work the same in both cases)

**Comment by MSeal** [comment]
Also apologies that I didn't see this issue earlier. I'm not able to keep up with all the open issue threads these days.

**Comment by MarcoGorelli** [comment]
Cool, thanks for your help!
