### ISSUE TITLE
Inkscape doesn't accept "--without-gui" option anymore

### ISSUE THREAD

**Issue by fabmazz** [jupyter/nbconvert#1304]
The inkscape command line options changed with the latest version:
[https://wiki.inkscape.org/wiki/index.php/Using_the_Command_Line](https://wiki.inkscape.org/wiki/index.php/Using_the_Command_Line)

The --without-gui and --export-pdf options are not recognized anymore and make the conversion fail.

**Comment by MSeal** [comment]
This issue should be fixed in the prelease version (6.0.0a3). We're trying to tackle the last of the milestone issues before doing a full 6.0 release.

**Comment by fabmazz** [comment]
Ok thanks. I'll wait for the new release then.
