### ISSUE TITLE
where is custom.css in the generated html file from nbconvert 

### ISSUE THREAD

**Issue by gepolv** [jupyter/nbconvert#1306]
I am using nbconvert to convert my jupyter notebook to html by

>jupyter nbconvert my.ipynb --to html

Then it says:

> [NbConvertApp] Converting notebook my.ipynb to html
> [NbConvertApp] Writing 407497 bytes to my.html

Then in the generated `my.html`, I can see it requires `custom.css`: 

    
    <link rel="stylesheet" href="custom.css">
    
    
    
        <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_HTML"></script>
        
        <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
            tex2jax: {
                inlineMath: [ ['$','$'], ["\\(","\\)"] ],
                displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
                processEscapes: true,
                processEnvironments: true
            },
            // Center justify equations in code and markdown cells. Elsewhere
            // we use CSS to left justify single line equations in code cells.
            displayAlign: 'center',
            "HTML-CSS": {
                styles: {'.MathJax_Display': {"margin": 0}},
                linebreaks: { automatic: true }
            }
        });
        </script>

Info:
nbconvert version is `5.6.1`

Thanks

**Comment by MSeal** [comment]
IIRC that's there so you can define a custom.css file alongside the output if you wanted to further style the document. I believe it's benign otherwise and not set. If you add a file to the `config_dir, 'custom', 'custom.css'` path it will inline the css into the html output.
