### ISSUE TITLE
Proposal: restore executenb 

### ISSUE THREAD

**Issue by akhmerov** [jupyter/nbconvert#1319]
`nbconvert.preprocessors.execute.executenb` was removed in #1211. This will require downstream libraries that relied on this to adjust (here's my own example https://github.com/jupyter/jupyter-sphinx/issues/139). At the same time this backwards compatibility breaking could be avoided, it seems, by a single line:

```python
from nbclient.client import execute as executenb`
```

Would this be acceptable?

**Comment by maartenbreddels** [comment]
Yes, I am much in favor of not breaking when we can, if we don't have to
jump through hoops. As long as in the code it is explained why the function
is there,  and it comes with a test with the same explanation I think we
should do this.

(from mobile phone)

**Comment by MSeal** [comment]
Yeah, we're trying to keep is as backwards compatible as we can. Should we put a warning that users should probably import nbclient directly instead if they use the executenb import? It'd be fairly easy to do that.
