### ISSUE TITLE
ExecutePreprocessor(resources={'metadata': {'path': run_path}}) not working

### ISSUE THREAD

**Issue by PeterFogh** [jupyter/nbconvert#1330]
I'm trying to specify the execution path for a notebook using `ExecutePreprocessor(resources={'metadata': {'path': run_path}})` like the documentation shows is possible at:
- https://nbconvert.readthedocs.io/en/latest/execute_api.html?highlight=%27path%27#executing-notebooks-using-the-python-api-interface, and
- https://nbconvert.readthedocs.io/en/latest/api/preprocessors.html?highlight=%27path%27#nbconvert.preprocessors.ExecutePreprocessor

I have constructed the attached zip file, containing a folder with my failed example. It contains everything to reproduce the issue, from my Conda environment to the Python script and executed Jupyter notebook.
[AA-1938_notebook_exe_path_failure_example.zip](https://github.com/jupyter/nbconvert/files/4947044/AA-1938_notebook_exe_path_failure_example.zip)

**Note that** the script tries to specify the notebook execution path to be the folder "test_folder" but as the executed notebook "notebook_executed_from_script.html" shows, the execution path is still the root folder "AA-1938_notebook_exe_path_failure_example".

As the conde YAML file show I'm using **Nbconvert version:** 5.6.1

Looking forward to get an answer on this issue, of whether it is a bug or there is an error in how I'm using the package.

**Comment by mgeier** [comment]
You have to pass the `resources` to the `preprocess()` method, not to the constructor.

Something like `ExecuteProcessor().preprocess(my_notebook, {'metadata': {'path': run_path}})`.

**Comment by PeterFogh** [comment]
Hi @mgeier. Thanks a lot and it works.
I thought that, I already had tried that, but apparently not :)

There is the diff of what I needed to change from the attached code example: "AA-1938_notebook_exe_path_failure_example.zip":
[diff_for_making_it_work.txt](https://github.com/jupyter/nbconvert/files/4952238/diff_for_making_it_work.txt)

I just needed to:
- remove the `resources` from the class object constructor, and
- use the correct path (`path_nb_execution_dir`) in the `resources ` parameter parsed to the `preprocess()` method.
