### ISSUE TITLE
docx --TemplateExporter.exclude_input=True doesn't remove input cells

### ISSUE THREAD

**Issue by WysokiStudent** [jupyter/nbconvert#1331]
Creating a docx file from a notebook with the --TemplateExporter.exclude_input=True option doesn't remove input cells. It works as advertised for other output files (pdf, latex, html are the ones I tested).

Note, original post is here https://github.com/jupyter/notebook/issues/5623

Steps to reproduce
```bash
jupyter nbconvert --to docx --TemplateExporter.exclude_input=True Untitled.ipynb  
```

[Untitled.ipynb](https://github.com/jupyter/nbconvert/files/4958120/Untitled.txt)
[Untitled.docx](https://github.com/jupyter/nbconvert/files/4958124/Untitled.docx)

An expected output in pdf format
[Untitled.pdf](https://github.com/jupyter/nbconvert/files/4958125/Untitled.pdf)

**Nbconvert version:**
5.6.1

**Comment by t-makaro** [comment]
Where are you getting your docx exporter? nbconvert does not natively support docx.

**Comment by WysokiStudent** [comment]
Good catch. I didn't realize I had previously installed [jupyter-docx-bundler ](jupyter-docx-bundler)via pip. Is there any trick I can use with nbconvert to get around the issue or should I head directly to https://github.com/m-rossi/jupyter-docx-bundler and ask for help there?

**Comment by WysokiStudent** [comment]
Ok, after looking at the jupyter-docx-bundler page I came to the conclusion that all I needed to do was tag the cells I wanted gone with an "nbconvert-remove-input" tag. After that everything went smooth. Thank you for your time!

**Comment by t-makaro** [comment]
Dev note: I looked at that package. It looks like they inherit from Exporter and not TemplateExporter, so that would be why our flags don't work for them. Interesting enough though, it does use the HTML exporter.

I might take a deeper look there later.
