### ISSUE TITLE
--EmbedImagesPreprocessor.embed_images=True does not embed images

### ISSUE THREAD

**Issue by n4562** [jupyter/nbconvert#1332]
Hello,

I am running nbconvert 5.6.1.

I have a sample notebook (notebook.py), with 1 cell:
```python
from IPython.core.display import HTML
display(HTML('<img src="a.png">'))
```

I then run
```bash
 jupyter nbconvert --to html --EmbedImagesPreprocessor.embed_images=True \
notebook.ipynb
```

A notebook.html is created, but unfortunately the image is not embedded, I get on line 11769:
```html
<div class="output_html rendered_html output_subarea ">
<img src="a.png">
</div>
```

That behaviour was different (i.e. it worked fine) on my previous environment (python 3.6 with pretty up to date nbconvert).

Any ideas of how I can fix it?

Thanks,

**Comment by t-makaro** [comment]
Where are you getting the EmbedImagesPreprocesser? It is not a native nbconvert preprocessor. Also, what should it do differently from the normal conversion? Images from outputs should already be imbedded into the html file.

**Comment by n4562** [comment]
Yes, you're right sorry. Wrong repo. I am referring to this: https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/exporting.html.

```
This Preprocessor replaces kernel code in markdown
cells with the results stored in the cell metadata.

The preprocessor is installed by default. To enable embedding images
with NbConvert, you need to set the configuration parameter
EmbedImagesPreprocessor.embed_images=True
```

**Comment by t-makaro** [comment]
Ah that's cool. Turns a referenced image in markdown to an attachment, but you're sample notebook is using an output image and not a markdown image.

 I imagine that's good for portability. Though some of our exporters still have problems with attachments. See #473, #1079, and #1057

**Comment by n4562** [comment]
If somebody lands here, my current workaround is the following:
```python
import base64, io, IPython
from PIL import Image as PILImage

def embed_src(path):
    image = PILImage.open(path)
    output = io.BytesIO()
    image.save(output, format='PNG')
    encoded_string = base64.b64encode(output.getvalue()).decode()
    src = "data:image/png;base64,{}".format(encoded_string)
    return src
```

which I then use:
```python
from IPython.core.display import HTML
display(HTML(f'<img src="{embed_src("a.png"}">'))
```

**Comment by tashrifbillah** [comment]
@n4562 , what's the `display()` function?

**Comment by tashrifbillah** [comment]
Again, I believe your comment has a bracket mismatch. It should be:

```python
display(HTML("<img src=\"{}\"".format(embed_src("a.png"))))
```

**Comment by tashrifbillah** [comment]
Overall, the last line does not show anything in my notebook. The cell executes without any error by the look of it though.

**Comment by tashrifbillah** [comment]
Just this works for me by the way:
```python
from IPython import display
display.display(display.Image(filename="a.png"))
```
