### ISSUE TITLE
Deprecation warning due to invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [jupyter/nbconvert#1336]
Deprecation warnings are raised due to invalid escape sequences. This can be fixed by using raw strings or escaping the literals. pyupgrade also helps in automatic conversion : https://github.com/asottile/pyupgrade/

```
find . -iname '*.py' | grep -Ev 'vendor|example|doc|tools|sphinx' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./nbconvert/filters/tests/test_citation.py:33: DeprecationWarning: invalid escape sequence \c
  """:  """
./nbconvert/filters/tests/test_markdown.py:211: DeprecationWarning: invalid escape sequence \c
  """$m$
./nbconvert/filters/tests/test_markdown.py:219: DeprecationWarning: invalid escape sequence \o
  """$r=\overline{1,n}$
./nbconvert/exporters/tests/test_latex.py:118: DeprecationWarning: invalid escape sequence \d
  """
```

**Nbconvert version:** master

**Comment by MSeal** [comment]
Thanks for raising -- those all look fairly straightforward to fix and are isolated to generating test inputs so are low risk changes. I'll mark the issue as a good first issue. If you have time to make that quick fix I'd happily merge that change. If not I probably won't get to this for a bit.
