### ISSUE TITLE
DOC: errors in example notebooks

### ISSUE THREAD

**Issue by mgeier** [jupyter/nbconvert#1339]
After #1292 has already exposed a few bugs (which have been fixed), there are still a few errors left.

Those are not detected during CI because they don't raise exceptions.

In https://nbconvert.readthedocs.io/en/latest/nbconvert_library.html, in code cell # 12, the output is supposed to be much shorter.

When building Sphinx, this related warning is shown:

```
[IPKernelApp] WARNING | Config option `start` not recognized by `PelicanSubCell`.
[IPKernelApp] WARNING | Config option `end` not recognized by `PelicanSubCell`.  Did you mean `enabled`?
```

It would be great if we could turn this IPython warning into a Sphinx warning, because then we could detect this problem in CI.

See also https://github.com/jupyter/nbconvert/pull/1292#issuecomment-656599554.

In https://nbconvert.readthedocs.io/en/latest/customizing.html, in code cell # 4, there is an error message:

    jinja2.exceptions.TemplateNotFound: simplepython.py.j2

This is not a "real" exception, but only the exception text printed on `stdout`, so it isn't detected either.

BTW, shouldn't this be on `stderr`?

On the same page (https://nbconvert.readthedocs.io/en/latest/customizing.html), in code cell # 7, there is an error message (where there should actually be some HTML code) including an error similar to the one mentioned above:

    TemplateNotFound: mytemplate.html.j2

Again, this is not detected, this time because it's just interpreted as HTML code.

**Comment by MSeal** [comment]
> I'm more interested in using the ExecutePreprocessor, but a CLI option would of course also make sense.

If you build it in the CLI it usually forces it to be present on all interfaces, so I usually start with CLI changes to make sure it's widely available.

**Comment by SylvainCorlay** [comment]
> [IPKernelApp] WARNING | Config option `start` not recognized by `PelicanSubCell`.
> [IPKernelApp] WARNING | Config option `end` not recognized by `PelicanSubCell`.  Did you mean `enabled`?

This is now fixed in master. Config values were set with `config='True'` instead of `config=True`

**Comment by SylvainCorlay** [comment]
Closing as the other issues with customizing.html don't apply anymore, and the suggestion to turn warning into sphinx errors is the subject of a different issue.
