### ISSUE TITLE
Is it possible to control the work directory of the notebook when executing it?

### ISSUE THREAD

**Issue by dclong** [jupyter/nbconvert#1343]
A jupyter notebook can be executed using the following command. By default, the work directory of the notebook is the directory containing it. However, is this configurable? Can I specify a different work directory for a notebook when executing it?
```
jupyter nbconvert --to notebook --execute mynotebook.ipynb
```

**Comment by MSeal** [comment]
Sorry I missed this thread originally. No, you can specify the output directory where things will be deposited:

> --output-dir=<Unicode> (FilesWriter.build_directory)
    Default: ''
    Directory to write output(s) to. Defaults to output to the directory of each
    notebook. To recover previous default behaviour (outputting to the current
    working directory) use . as the flag value.

**Comment by dclong** [comment]
Do you think this is a valid feature to support? Sometimes, code in a notebook must be in a specific directory. Howeve
