### ISSUE TITLE
CWD seem to have been inadvertently removed from template_path

### ISSUE THREAD

**Issue by Carreau** [jupyter/nbconvert#1347]
Template exporter declaration looks like:
```
template_paths = List(['.']).tag(config=True, affects_environment=True)
```

Though in default function:

```
@default('template_paths')
    def _template_paths(self, prune=True, root_dirs=None):
        paths = []
		...
```

I have the impression that recently CWD was still in there by default, maybe it's on purpose, sorry if that's the case.  Might dig into this later.

**Comment by MSeal** [comment]
It does appear we removed the working directory in that last refactor. @maartenbreddels @SylvainCorlay should we add `'.'` to the front of the default paths we generate?

**Comment by maartenbreddels** [comment]
It should be there, in your latest tests you test for this right?

(from mobile phone)

**Comment by SylvainCorlay** [comment]
Should cwd be in template_paths?

**Comment by SylvainCorlay** [comment]
The new template system isn't really meant for overriding templates in the cwd, but maybe there is a strong argument in favor of supporting `.` as a "highest precedence" template path.

**Comment by SylvainCorlay** [comment]
@Carreau @mseal @maartenbreddels 

I thought a lot about this, and I think that we should not add `.` as a template path. If we do so, there is a non-zero probability that an unrelated file in the cwd overrides content from underlying templates, such as `conf.json`, `index.html.j2`, content of a `static` subdirectory...

**Comment by Carreau** [comment]
> I thought a lot about this, and I think that we should not add `.` as a template path. If we do so, there is a non-zero probability that an unrelated file in the cwd overrides content from underlying templates, such as `conf.json`, `index.html.j2`, content of a `static` subdirectory...

But that's I believe the whole point of this, if you have a project with custom templates, you can "just" run nbconvert from within this directory and you will get this new template.

Many other tools function like that, like jekyll with _include, and _template.

**Comment by MSeal** [comment]
That's a good point... 

so making a local template file in 5.x style `lab.tpl`, this pattern works for specifying that template as a valid path:

```
jupyter nbconvert --to=html --template-file=./lab.tpl nbconvert/tests/files/notebook1.ipynb
```

but this pattern doesn't:

```
jupyter nbconvert --to=html --template-file=lab.tpl nbconvert/tests/files/notebook1.ipynb
```

I think this is ok, so long as we document how to reference local files in a backwards compatibility operation.

**Comment by MSeal** [comment]
> Many other tools function like that, like jekyll with _include, and _template.

We could set a default local directory to add to the path. I'd be good with including `_template` or `.nbconvert` as a working directory template path to include to avoid the issue @SylvainCorlay brought up and still support directory based builds.

**Comment by Carreau** [comment]
I'm fine either way, as long as we are aware of it.  I originally opened
the issue as this changed and appears to be not planned, but I agree that
even with CWD not in path few users will notice.

**Comment by MSeal** [comment]
Ok let's keep it in mind and we can do a patch release with some improvements if it comes up after 6.0 goes out.

**Comment by maartenbreddels** [comment]
This feature should work because of
https://github.com/jupyter/nbconvert/pull/1292/files#diff-43c2e238630461c0a2c422a0b09fae55R230
and should be tested by the tests in that PR by @MSeal.

**Comment by MSeal** [comment]
I found the underlying issue and it related to passing `template-file` without a absolute path or a path that starts with `.` because it replaces the `extra_template_basedirs` incorrectly. Patch pending in a minute
