### ISSUE TITLE
Also drop 3.6 ? 

### ISSUE THREAD

**Issue by Carreau** [jupyter/nbconvert#1348]
nbconvert 6.0 is soon out of the door, 
It feels like the right time think about also dropping python 3.6 support (IPython is already 3.7+ only as it follows [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html)), that will of course depends on whether you think minor release of nbconvert can drop minor version of Python or not, but with 3.9 being around soon, that will still be 3 minor version of Python supported.

**Comment by willingc** [comment]
First, I would keep CI testing Python 3.6. As to whether to drop 3.6 now or not, I would make this the last release to support 3.6 (specifically 3.6.12+ via documentation in the readme) or `python_requires>=3.6`. From a security standpoint, folks should be updating their Python version.

Perhaps identify that 3.6 is a limited support version similar to Python's security releases. The team will not guarantee fixes for 3.6 on 6.0 and beyond; though we will continue to run CI until 3.6 is fully dropped. This will give users a bit more time to move to 3.7+.

Perhaps adding something like below to the `README.md`:

```
nbconvert 6.0 provides limited support for Python 3.6. nbconvert 6.1 will drop support for Python 3.6. Limited support means we will test and run CI on Python 3.6.12 or higher. Issues that are found only affecting Python 3.6 are not guaranteed to be fixed. We recommend all users of nbconvert use Python 3.7 and higher.
```
