### ISSUE TITLE
Line breaks using \ get expanded when using --to script

### ISSUE THREAD

**Issue by pjayathissa** [jupyter/nbconvert#1349]
When one writes `jupyter nbconvert --to script myNotebook.ipynb` any line breaks using `\` get expanded into a full line without the `\`. This results in the final python script having lines longer than 79 which then fires up our linter

Have a cell, such as 
```
a = '1' + '2' + '3' + \
    '4' + '5'
```

then run `nbconvert`

the output is
```python
a = '1' + '2' + '3' +     '4' + '5'
```

**Nbconvert version:** 5.6.1

**Comment by MSeal** [comment]
So this is a result of `IPythonInputSplitter` translating IPython code to regular Python parsing. In re-emitting the code it does sometimes manipulate the arrangement of the code. Specifically https://github.com/jupyter/nbconvert/blob/master/nbconvert/filters/strings.py#L193-L211 is the call that does the conversion for the IPython case. @Carreau might know if there's a way to change the behavior for this instance but I don't believe there's an easy way to change this pattern and still enable capturing ipython patterns correctly. We are on a deprecated path for some the API calls we make still so possibly there's a difference in newer patterns I am not aware of that doesn't have this side-effect.

**Comment by willingc** [comment]
Thanks for the report and the comments @MSeal. Going to go ahead and close this in favor of https://github.com/jupyter/nbconvert/issues/1388 re: `IPythonInputSplitter`.
