### ISSUE TITLE
ModuleNotFoundError: No module named 'notebook.nbconvert'

### ISSUE THREAD

**Issue by yuliaUU** [jupyter/nbconvert#1356]
I am running` jupyter lab` command and get the error `ModuleNotFoundError: No module named 'notebook.nbconvert'`
it happened after I updated my windows 10. I am not sure how to solve this issue

**Comment by yuliaUU** [comment]
Here is info about jupyter
$ jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 6.1.3
qtconsole        : 4.7.6
ipython          : 7.18.1
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 2.2.6
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 5.0.0

**Comment by MSeal** [comment]
That would imply that the `nbconvert : 5.6.1` wasn't found. Is it possible you are launching `jupyter --version` from a different python environment than `jupyter lab`?

**Comment by yuliaUU** [comment]
I fixed it by re-installing miniconda3
