### ISSUE TITLE
ArchLinux Package Broken for 6.0: (Error when exporting to HTML: `TemplateNotFound: static/index.css`)

### ISSUE THREAD

**Issue by joelostblom** [jupyter/nbconvert#1358]
I am trying to export an empty notebook to HTML (`jupyter nbconvert --to html empty.ipynb `), but it fails with `TemplateNotFound: static/index.css` (full error message below). I tried b7 and master, and the error is still there; a1 and earlier works fine.

(A caveat is that depending on which version I was on before upgrading, I seemed to get inconsistent results, e.g. being on a1 and then updating to b7 sometimes worked, but being on a6 and upgrading to b7 caused the error. So to reproduce, run `pip install https://github.com/jupyter/nbconvert/archive/6.0.0a6.zip` and then `pip install https://github.com/jupyter/nbconvert/archive/6.0.0b7.zip`. Sometimes it works when upgrading to master, sometimes not. Is there a template file generated that is cleared by some versions maybe?) 

<details><summary>Error message</summary>
<pre>
[NbConvertApp] Converting notebook empty.ipynb to html
Traceback (most recent call last):
  File "/home/joel/miniconda3/envs/mds/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/home/joel/miniconda3/envs/mds/lib/python3.8/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/joel/miniconda3/envs/mds/lib/python3.8/site-packages/traitlets/config/application.py", line 838, in launch_instance
    app.start()
  File "/home/joel/miniconda3/envs/mds/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 345, in start
    self.convert_notebooks()
  File "/home/joel/miniconda3/envs/mds/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 519, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/joel/miniconda3/envs/mds/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 484, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/joel/miniconda3/envs/mds/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 413, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/joel/miniconda3/envs/mds/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 182, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/joel/miniconda3/envs/mds/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 200, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/joel/miniconda3/envs/mds/lib/python3.8/site-packages/nbconvert/exporters/html.py", line 122, in from_notebook_node
    return super().from_notebook_node(nb, resources, **kw)
  File "/home/joel/miniconda3/envs/mds/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 377, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/home/joel/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/joel/.local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/joel/.local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/joel/miniconda3/envs/mds/share/jupyter/nbconvert/templates/lab/index.html.j2", line 3, in top-level template code
    {% from 'jupyter_widgets.html.j2' import jupyter_widgets %}
  File "/home/joel/miniconda3/envs/mds/share/jupyter/nbconvert/templates/lab/base.html.j2", line 169, in top-level template code
    
  File "/home/joel/miniconda3/envs/mds/share/jupyter/nbconvert/templates/base/display_priority.j2", line 1, in top-level template code
    {%- extends 'base/null.j2' -%}
  File "/home/joel/miniconda3/envs/mds/share/jupyter/nbconvert/templates/base/null.j2", line 23, in top-level template code
    #}
  File "/home/joel/miniconda3/envs/mds/share/jupyter/nbconvert/templates/lab/index.html.j2", line 6, in block "header"
    <!DOCTYPE html>
  File "/home/joel/miniconda3/envs/mds/share/jupyter/nbconvert/templates/lab/index.html.j2", line 28, in block "html_head"
    {% endblock extra_css %}
  File "/home/joel/miniconda3/envs/mds/share/jupyter/nbconvert/templates/lab/index.html.j2", line 29, in block "notebook_css"
    
  File "/home/joel/miniconda3/envs/mds/lib/python3.8/site-packages/nbconvert/exporters/html.py", line 127, in resources_include_css
    code = """<style type="text/css">\n%s</style>""" % (env.loader.get_source(env, name)[0])
  File "/home/joel/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 488, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: static/index.css
</pre>
</details>

Tested on Linux and Windows

```
# Linux jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 6.1.3
qtconsole        : not installed
ipython          : 7.18.1
ipykernel        : 5.3.4
jupyter client   : 6.1.2
jupyter lab      : 2.2.6
nbconvert        : 6.0.0b7
ipywidgets       : not installed
nbformat         : 5.0.5
traitlets        : 5.0.0

# Windows jupyter --version
$ jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 6.1.3
qtconsole        : not installed
ipython          : 7.17.0
ipykernel        : 5.3.4
jupyter client   : 6.1.6
jupyter lab      : 2.2.5
nbconvert        : 6.0.0b7
ipywidgets       : not installed
nbformat         : 5.0.7
traitlets        : 4.3.3
```

**Comment by MSeal** [comment]
Sorry for missing this post originally -- let me dig into this now.

**Comment by joelostblom** [comment]
@MSeal Thank you! I just discovered that this only seems to be a problem when installing from .zip or .tar.gz. installing from a commit works.

So this works:

```
pip install git+https://github.com/jupyter/nbconvert.git@db0e589
```

but this does not 

```
pip install https://github.com/jupyter/nbconvert/archive/6.0.0rc0.zip
```

So you likely don't have to look into this before the 6.0 release, I edited my comment over there.

**Comment by MSeal** [comment]
Huh that is interesting. There are some lab template styling that get's fetched if it's missing. That might explain the discrepancy but I'll have to think on it more (having difficulty reproducing atm).

**Comment by joelostblom** [comment]
Just to be clear with exactly what I run since you're having issues reproducing:

```
conda create -n nbc-test jupyterlab
conda activate nbc-test
pip install https://github.com/jupyter/nbconvert/archive/6.0.0rc0.tar.gz
jupyter nbconvert --to html empty.ipynb
```

**Comment by joelostblom** [comment]
I also tried installing jupyterlab via pip, just to see if it was conda related for some reason, but it seems not to be, I get the same error when running this:

```
conda create -n nbc-test pip
conda activate nbc-test
pip install jupyterlab
pip install https://github.com/jupyter/nbconvert/archive/6.0.0rc0.tar.gz
jupyter nbconvert --to html empty.ipynb
```

**Comment by MSeal** [comment]
Ok yeah that reproduces on my machine -- I typically don't develop in conda and it doesn't reproduce in a pure venv setting.

**Comment by joelostblom** [comment]
I guess this is a pretty minor issue then, as it only affects people using conda together with installing a GitHub archive instead of a commit ref with pip.

**Comment by SylvainCorlay** [comment]
I don't know what pip assumes of a package when it comes across a zip file. If it treats it as a wheel, then it is clearly not correct.

**Comment by atsuoishimoto** [comment]
FYI, I got same error with my regacy utitiliy like this.

```python
import nbformat
from nbconvert.exporters import HTMLExporter
from traitlets.config import Config

json = nbformat.read(open("Untitled.ipynb"), nbformat.current_nbformat)

c = Config( { "TemplateExporter": {"template_file": "basic.tpl"}})
html, _ = HTMLExporter(c).from_notebook_node(json)
print(html)
```

This code works with nbconvert 5.6.1, but raises same error with 6.0.6.

Changing Config to

```python
c = Config({"TemplateExporter": {"template": "classic"}})
```

fixes problem in my case.

**Comment by JanFeld** [comment]
> 
> 
> I guess this is a pretty minor issue then, as it only affects people using conda together with installing a GitHub archive instead of a commit ref with pip.

When trying to convert a notebook i'll have this error too.

I've installed `jupyter-notebook` as well as `jupyter-nbconvert` via `pacman` on Arch Linux.

Current python version: `3.9.1`
Jupyter-Notebook Version: `6.2.0`
Jupyter-NBConvert Version: `6.0.7`

The installation directory for the nbconvert-templates (`/usr/share/jupyter/nbconvert/templates/..`) doesn't contain any `index.css`. These two are the only `*.css-files` found:

```
*/reveal/static/custom_reveal.css
*/classic/static/style.css
```

The only template files (`*.tpl`) found are:

```
*/compatibility/full.tpl
*/compatibility/display_priority.tpl
```

Are there some files missing?

**Comment by SylvainCorlay** [comment]
@JanFeld @atsuoishimoto it would be useful to know how you installed nbconvert.

**Comment by JanFeld** [comment]
> 
> 
> @JanFeld @atsuoishimoto it would be useful to know how you installed nbconvert.

I've installed everything via `pacman` an Arch Linux 5.10.11

```
pacman -S jupyter jupyter-notebook jupyter-nbconvert
```

**Comment by Ghabry** [comment]
Can confirm, have the same problem with Arch Linux.

Mildly annoying, because until two weeks ago I uploaded next to the ipynb a HTML for my students as the HTML version is easier to view.

**Comment by joelostblom** [comment]
Possibly of interest, I am also on Arch, but I installed it via conda and pip (as detailed above). I believe I tried Windows as well with the same result.

**Comment by juanscr** [comment]
I'm also having the same problem with Arch Linux. Creating as script as suggested by @atsuoishimoto it works out but the command line command for converting does not work.

**Comment by SylvainCorlay** [comment]
I think the pacman package is broken, which would explain the reports on Arch Linux.

**Comment by ettavolt** [comment]
> I think the pacman package is broken, which would explain the reports on Arch Linux.

[Pacman package builder](https://github.com/archlinux/svntogit-community/blob/packages/jupyter-nbconvert/trunk/PKGBUILD) simply runs ``python3 setup.py install``. From what I see in [setup.py](https://github.com/jupyter/nbconvert/blob/master/setup.py#L147), it hooks 'build' target (or phase?) but doesn't add anything for 'install' target (well, if it's phase, then should have inherited 'css' execution from 'build', but it seems it hasn't).

**Comment by SylvainCorlay** [comment]
The way to go for the pacman package maintainer is 

`python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv`

Generally, for packaging the Jupyter stack, I recommend looking at the recipes of the conda packages, which are maintainers by the package authors: https://github.com/conda-forge/nbconvert-feedstock/blob/master/recipe/meta.yaml#L13

**Comment by Ghabry** [comment]
So this must be a packaging bug that should be reported on https://bugs.archlinux.org/ (and then linked to this issue)

@joelostblom @juanscr anyone of you having an account already for the arch bugtracker? I'm not a fan of registering accounts that I will only use once, so would be great if someone with an account could file it there :/.

**Comment by joelostblom** [comment]
@Ghabry I opened an issue there a few days ago and just pasted the lasted comment from above also https://bugs.archlinux.org/task/69537

**Comment by endeavour** [comment]
Same issue on Manjaro

**Comment by vishnudevk** [comment]
Just observed the same issue in Arch. Does anyone know about any workarounds?

**Comment by juanscr** [comment]
> Just observed the same issue in Arch. Does anyone know about any workarounds?

Hey, for doing this I just did something similar as suggested by @atsuoishimoto. Just create a file called `notebook-to-html.py` and paste this

```python
import nbformat
from nbconvert.exporters import HTMLExporter
import sys 
from traitlets.config import Config

# Argument parsing
if len(sys.argv) < 3:
    print("An input file and a output file is needed.")
    sys.exit(1)
elif len(sys.argv) > 3:
    print("Warning: Only the first two arguments will be used")

# Open notebook
json = nbformat.read(open(sys.argv[1]), nbformat.current_nbformat)

# Config for html generation
c = Config({"TemplateExporter": {"template_name": "classic", "template_file":
                                 "base.html.j2"}})

# Generate HTML for notebook
html, _ = HTMLExporter(c).from_notebook_node(json)
with open(sys.argv[2], "w") as html_file:
    html_file.write(html)

```

Then just do the following in a terminal `python notebook-to-html.py /path/to/notebook.ipynb /path/to/html-file.html` and that's it.

**Comment by SylvainCorlay** [comment]
@vishnudevk @joelostblom @endeavour the Arch Linux package is broken. This is a packaging issue and not really an nbconvert issue.

**Comment by SylvainCorlay** [comment]
cc @keenerd

**Comment by joelostblom** [comment]
@SylvainCorlay  In addition to an Arch issue, is it also a Conda issue? Both [me](https://github.com/jupyter/nbconvert/issues/1358#issuecomment-689169023) and [MSeal](https://github.com/jupyter/nbconvert/issues/1358#issuecomment-689170333) can reproduce installing in a conda env (I am on Arch, but all my packages are installed in conda envs with either conda or pip)

**Comment by SylvainCorlay** [comment]
> @SylvainCorlay In addition to an Arch issue, is it also a Conda issue? Both me and MSeal can reproduce installing in a conda env (I am on Arch, but all my packages are installed in conda envs with either conda or pip)

I can't reproduce it and the conda package does include the expected `index.css` file.

Is it possible that you are actually using your arch package. What does `which jupyter` return?

**Comment by joelostblom** [comment]
I tried the steps in my comment above and it still reproduces. It also reproduces with the latest versions of nbconvert (6.0.7), but only when I install the tar.gz using pip in a conda environment. I tried installing the master and 6.0.7 tag with `pip git+...` and they work as intended so it is a relatively narrow issue and might lie with pip rather than nbconvert. I'm good with this issue remaining closed from my end.

**Comment by SnarkBoojum** [comment]
I'm packaging nbconvert 6.5.3 for Debian, and I added this patch to make testing pass:
```
--- /dev/null
+++ nbconvert/share/jupyter/nbconvert/templates/classic/static/style.css
@@ -0,0 +1 @@
+/* empty - just for autopkgtest success */
```
