### ISSUE TITLE
How to specify the language of code cells when converting to markdown?

### ISSUE THREAD

**Issue by NMZ0429** [jupyter/nbconvert#1359]
When I convert my notebook to markdown, it is correctly converted as a markdown file. However as I only use Jupyter Notebook with Python, I would like nbconvert to export code cells with python tags. For example, it exports code cells like 

> ```
> print('Hello')
> ```

Yet, I want it to render the cell as

>```python
>print('Hello')
>```

The only difference is that it has 'python' at the first line of code block. It is tedious to manually add it to all code blocks so is it possible to automate it?

**Comment by MSeal** [comment]
Sorry we missed this question before.

Today there's not a mechanism for achieving this today, but I could see an enhancement to adding that to markdown export based on the notebook languge specification. Would be a nice enhancement to make

**Comment by joyceerhl** [comment]
Hi @MSeal @t-makaro, I'd love to try implementing this functionality if you're open to contributions!

**Comment by MSeal** [comment]
@joyceerhl We are very open to contributions, though this issue does appear this has been fixed. From looking at the code changes I think it was supposed to be working from 5.x days but we must have had a bug in the branch I was using when this was reported. I'm going to close this particular issue since it's working from my testing atm.

**Comment by joyceerhl** [comment]
Awesome! In that case, I noticed a similar issue which might be addressed: https://github.com/jupyter/nbconvert/issues/1219

**Comment by MSeal** [comment]
Yep, this is making me realize we need to do some post 6.0 release cleanup of issues :sweat_smile:
