### ISSUE TITLE
`template_path` still appearing in docs, despite rename

### ISSUE THREAD

**Issue by jph00** [jupyter/nbconvert#1371]
Various places in the docs still say to use `template_path`, but it's been renamed to `template_paths`.

**Comment by MSeal** [comment]
Thanks for the report -- I'll get that fixed and noted that it's a contract change where we missed it in the docs.

**Comment by willingc** [comment]
Thanks @jph00. If you see any other errors or omissions in the docs, please file an issue and @-mention me.

**Comment by jph00** [comment]
OK @willingc will do :)
