### ISSUE TITLE
GitHub Issues not mentioned on website

### ISSUE THREAD

**Issue by jph00** [jupyter/nbconvert#1376]
@willingc FYI, the nbconvert "questions/suggestions" section has 4 links, none of which are to GitHub Issues.
https://nbconvert.readthedocs.io/en/latest/

The Google Group mentioned there doesn't seem to be followed closely.

My understanding from our discussion on Twitter is that GitHub Issues is a (the?) place for questions/suggestions. Therefore it might be good to add this to the above page.

**Comment by willingc** [comment]
Great suggestion.

**Comment by willingc** [comment]
Note to self: Add links to GH Issues as Discourse primary comm sites for bug reports (GH) and questions (Discourse).

**Comment by willingc** [comment]
Issue https://github.com/jupyter/jupyter.github.io/issues/382 tracking the progress on the two outstanding todo items
