### ISSUE TITLE
'basic' template not found after update to version 6.0.2

### ISSUE THREAD

**Issue by tzipperle** [jupyter/nbconvert#1393]
Hi,
I have updated the package to the version 6.0.2 and I get the following error: `ValueError: No template sub-directory with name 'basic' found in the following paths` when I convert a notbook to a plain html page.

Is there a way to get a plain html output with the version 6.x like the basic template in the version 5.x?

**Comment by MSeal** [comment]
There is but it's a little convoluted. This was brought up in https://github.com/jupyter/nbconvert/pull/1386 and I was hoping to discuss with the others on the project about best path forward in https://github.com/jupyter/nbconvert/pull/1387.

If you add `--template=classic --template-file=base.html.j2` you'll get the original base template behavior. I want to see if others, such as @SylvainCorlay and @maartenbreddels have opinions on how we want to document this / if we want to add `--template=base` back to the available template listing before I change anything.

**Comment by tzipperle** [comment]
@MSeal Thank you!

**Comment by MSeal** [comment]
Basic template was added back in 6.0.7 to resolve this issue.
