### ISSUE TITLE
nbconvert 6.0.2 breaks contextvars

### ISSUE THREAD

**Issue by crusaderky** [jupyter/nbconvert#1397]
Python 3.8.5
pytest 6.0.1
pytest-asyncio 0.12.0
nbconvert 6.0.2
Linux x64 / anaconda

I'm running an asyncio application which, among the many components, features a jupyter notebook.
The test for the notebook looks like this:
```python
import nbformat
import pytest
from nbconvert.preprocessors import ExecutePreprocessor


@pytest.mark.asyncio
async def test_nb():
    with open("mynotebook.ipynb") as fh:
        nb = nbformat.read(fh, as_version=nbformat.NO_CONVERT)
    ep = ExecutePreprocessor(timeout=600)
    loop = asyncio.get_running_loop()
    await loop.run_in_executor(None, ep.preprocess, nb)
```
The notebook interacts with an aiohttp server that is running in the main event loop.

After upgrading nbconvert from 6.0.1 to 6.0.2, any test that runs after the test above, even if itself doesn't involve a jupyter notebook in any way, fails on this section of my code:

```python
from contextvars import ContextVar

myvar = ContextVar("myvar", default=None)


async def f(x):
    tok = myvar.set(x)
    try:
        await asyncio.gather(<bunch of coroutines which internally spawn a bunch of tasks>)
    finally:
        tok.var.reset(tok)
```
```
>   tok.var.reset(tok)
E   ValueError: <Token var=<ContextVar name='myvar' default=None at 0x7f8087cd0450> at 0x7f7f16d65ec0> was created in a different Context
```
If I downgrade nbconvert from 6.0.2 to 6.0.1, the problem disappears.
If I skip the single test that invokes nbformat and nbconvert.preprocessors.ExecutePreprocessor, the problem disappears.

**Comment by MSeal** [comment]
Huh interesting. I'm not sure why ContextVar is angry here exactly. The ExecutePreprocessor does have some interaction with async to make the actual execution calls in nbclient. It's possible that's causing the context to be different but I'd expect the same problem to occur in 6.0.1 as well.

Question though, are you just using nbconvert to execute the entire notebook? If so you might want to change it to nbclient, as the logic has been moved out of nbconvert to that library and made to directly support async. We left the preprocessor in nbconvert as some people extend that interface and we didn't want to break behavior. 

```python
client = NotebookClient(nb, timeout=600)
await client.async_execute()
```

That being said I'll try to find some time to dig into why this changed in 6.0.2... @davidbrochart might know offhand as his async knowledge is better than mine

**Comment by davidbrochart** [comment]
The only thing I can think of right now is that `ContextVar` are natively supported in `asyncio` from Python 3.7. Could it be that you had Python < 3.7 when it was working fine, and Python >= 3.7 when it wasn't?

**Comment by crusaderky** [comment]
@MSeal using NotebookClient.async_execute causes the problem to disappear.

@davidbrochart The version of the nbconvert package is literally the only thing that changes between the working setup and the broken one. I can easily downgrade and see the issue disappear; upgrade and get the breakage again.
