### ISSUE TITLE
Since 6.0 Markdown in HTML divs render as LaTeX instead of being skipped

### ISSUE THREAD

**Issue by joelostblom** [jupyter/nbconvert#1401]
In 5.6.1, markdown inside HTML `<div>` tags was skipped in the nbconvert HTML output, which is not ideal, but was still readable. Since upgrading to 6.0, I have noticed that they are rendered as LaTeX math. In many cases, this makes the text ineligible, so this is quite a big issue (but possible to workaround by using HTML inside the div instead of markdown, although this means the same notebook can't be exported to both PDF and HTML without modifications).

As an example, the following code

````html
<div>

Testing HTML with `inline code` tags.<br>

```
I am a code block
```
    
</div>
````

Would show up like this (and [still does on GH](https://github.com/joelostblom/nbc-html-test/blob/master/Untitled.ipynb), which I guess has not update to 6.0)

![image](https://user-images.githubusercontent.com/4560057/93689200-08961480-fa81-11ea-9267-d1685bfcd127.png)

But since 6.0, it shows up like this

![image](https://user-images.githubusercontent.com/4560057/93689170-ccfb4a80-fa80-11ea-93ff-e708076e6612.png)

```
jupyter core     : 4.6.3
jupyter-notebook : 6.1.4
qtconsole        : not installed
ipython          : 7.18.1
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 2.2.6
nbconvert        : 6.0.3
ipywidgets       : not installed
nbformat         : 5.0.5
traitlets        : 5.0.4
```

For reference to the old skipping behavior, these are the currently open HTML markdown related issues:

- https://github.com/jupyter/nbconvert/issues/1037
- https://github.com/jupyter/nbconvert/issues/1165
- https://github.com/jupyter/nbconvert/issues/1146
- https://github.com/jupyter/nbconvert/issues/1125

**Comment by MSeal** [comment]
I'm not sure I will get time to dig into the HTML format issues referenced before I'm unavailable with a newborn... @t-makaro any chance you have some spare cycles to look into these? Also any new contributors that want to track this down we'd love to have more eyes on these open issues.

**Comment by nh273** [comment]
I can help with this as a first issue! Would love to get any pointers!

**Comment by MSeal** [comment]
Thanks for offering to help @nh273 !

Somewhere we're the code is not properly escaping characters or incorrectly passing them through a filter it shouldn't be using.

I'd get a local development version of nbconvert, install it with `pip install -e .` and try running a conversion command line call on the notebook code listed above. Then you can try changing code snippets / debug paths until the root issue is identified.

I'd especially look at [markdown2html](https://github.com/jupyter/nbconvert/blob/main/nbconvert/exporters/html.py#L110 ) and the lab [base](https://github.com/jupyter/nbconvert/blob/main/share/jupyter/nbconvert/templates/lab/base.html.j2) / [index.html](https://github.com/jupyter/nbconvert/blob/main/share/jupyter/nbconvert/templates/lab/index.html.j2) jinja files.

**Comment by nh273** [comment]
I'm setting up to debug on VSCode and ran into an issue, the VSCode debugger will not stop at my set breakpoints. It will at raised Exceptions though. This is my launch.json:
```{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "nbconvert",
            "type": "python",
            "request": "launch",
            "module": "jupyter",
            "args": ["nbconvert", "--to", "html", "Replicate_Error.ipynb"]
        }
    ]
}```
(Replicate_Error.ipynb is the notebook with the error)
Would be great if anyone know why, or let me know what's a better way to go about debugging this instead of VSCode debugger!

**Comment by MSeal** [comment]
NBconvert does a lot of subprocess shinigeans so sometimes the debugger can't inspect the subprocess below it. I usually debug with print statements for these complex projects, but I was able to setup VSCode debugger breakpoints successfully with this config. I think the `jupyter nbconvert` wrapper might be obscuring the actual Python process to the debugger as well in your example?:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "module": "nbconvert.__main__",
            "console": "integratedTerminal",
            "args": ["--to", "html", "/home/mseal/Workspace/papermill/papermill/tests/notebooks/no_parameters.ipynb"]
        }
    ]
}
```

**Comment by nh273** [comment]
Thanks for the config! That made the debugger work for me. I have found that changing the mathjax config in [templates/base/mathjax.html.j2](https://github.com/jupyter/nbconvert/blob/90b3911ed9b155e8ca3680ca4581d9344aa10be0/share/jupyter/nbconvert/templates/base/mathjax.html.j2#L2) from `TeX-MML-AM_**C**HTML-full,Safe` to `TeX-MML-AM_HTML-full,Safe` will fix the bug.
It doesn't look like this change break any test. @MSeal would love pointers on how to proceed.

**Comment by MSeal** [comment]
This looks like the commit responsible for that change: https://github.com/jupyter/nbconvert/commit/9bdfbead750910f4c666482c926ae025c8c09700

It seems like it was reusing CommonHTML settings from http://docs.mathjax.org/en/latest/output/html.html#html-output. There's some config settings related to that changelog for the mode that might be affected by changing back to HTML mode for MathJax we'd want to look into.

**Comment by MSeal** [comment]
@maartenbreddels @SylvainCorlay any suggestions on :point_up: -- I think going back to HTML from CHTML would make sense but I don't know well the possible ramifications of such a change.

**Comment by jasongrout** [comment]
I think the problem here is discussed in https://stackoverflow.com/a/62136137, i.e., the configuration is enabling asciimath, but shouldn't.
