### ISSUE TITLE
Documentation issue: removal of default output format not reflected in documentation

### ISSUE THREAD

**Issue by bkohrn** [jupyter/nbconvert#1424]
The removal of the default `--to html` is not reflected in the documentation (see https://nbconvert.readthedocs.io/en/latest/usage.html#default-output-format-html) or in the changelog for v6.0.0

**Nbconvert version:** >= 6.0.0

**Comment by bkohrn** [comment]
This has probably been an issue since #1192 was merged

**Comment by MSeal** [comment]
Yes, apologies we missed that and thanks for raising. I'll get a PR spun up to correct the documentation issue.
