### ISSUE TITLE
Regression: input numbers generated by `--execute` are no longer numerically increasing

### ISSUE THREAD

**Issue by itamarst** [jupyter/nbconvert#1440]
In nbconvert 5.6.1, the results of rendering cells with nbconvert gave each input an incremental number, e.g. `ipython-input-1-<hash>`, `ipython-input-2-<hash>`, `ipython-input-3-<hash>`, etc.. In 6.0.7, the input names are all number 1, `ipython-input-1-<hash>`, `ipython-input-1-<hash>`, `ipython-input-1-<hash>`.

I encountered this in a test that relies on nbconvert output.

Why is this meaningful?

I am working on a memory profiler that can run inside Jupyter (https://github.com/pythonspeed/filprofiler). It shows stack traces of where the highest allocating memory usage came from, and in order to figure out which cell code came from, those numerically increasing numbers are necessary.

As it is, if a user uses `nbconvert` the output will tell them effectively that all code came from input 1, which is not true.

For people not using my profiler, this can be problematic when, for example, one is looking at a traceback. See reproducer below

## Reproducing

In the attached notebook, if you run it in Jupyter notebook, the output looks like this:

![Screenshot from 2020-10-07 11-13-35](https://user-images.githubusercontent.com/3266662/95350648-65216e00-088e-11eb-9e9e-2bfac88a4652.png)

Notice that it correctly identifies `i_am_in_cell_3()` as coming from input 3.

However, when run with `jupyter nbconvert example.ipynb --execute --to html`, the traceback says the function came from input 1, which means debugging the failure is harder:

```
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
i_am_in_cell_3()
------------------

---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-1-fa76ef86aeb4> in <module>
----> 1 i_am_in_cell_3()

<ipython-input-1-3ce70813bd2c> in i_am_in_cell_3()   # <--- SHOULD BE input-3
      1 def i_am_in_cell_3():
----> 2     1/0

ZeroDivisionError: division by zero
ZeroDivisionError: division by zero
```

**Nbconvert version:** 6.0.7

## Reproducer notebook

[example.ipynb.txt](https://github.com/jupyter/nbconvert/files/5341746/example.ipynb.txt)

Compare output of running in Jupyter Notebook/Lab, to running with `nbconvert --execute`.

**Comment by MSeal** [comment]
Thanks for reporting. I see the root cause after some head scratching. I'll see about getting a patch in.

**Comment by itamarst** [comment]
Thank you!
