### ISSUE TITLE
IPython should be required

### ISSUE THREAD

**Issue by ricklamers** [jupyter/nbconvert#1443]
The lexer in IPython is used for HTML rendering of IPython source code.

It's included as `from IPython.lib.lexers import IPython3Lexer` in the template filter code (https://github.com/jupyter/nbconvert/blob/master/nbconvert/filters/highlight.py).

1. pip install nbconvert
2. Verify IPython package is missing (pip show IPython)
3. jupyter nbconvert <path-to-notebook> --to html
4. Verify incorrect syntax highlighting of IPython cells

Good example of incorrect syntax highlighting occurs when you're using bash in a cell.

E.g. `!ls /some/dir`

Correct (with IPython):
<img src="https://user-images.githubusercontent.com/1309307/95457773-a9396f00-0971-11eb-8adb-d7d873e23032.png" width="250px" />

Wrong (without IPython)
<img src="https://user-images.githubusercontent.com/1309307/95457770-a9396f00-0971-11eb-850d-bb12faabc5ea.png" width="250px" />

**Nbconvert version: 6.0.7**

Suggested solution:
Add IPython to requirements in setup.py

**Comment by MSeal** [comment]
IPython is a fairly heavy dependency. The reason it was left out was because not all Notebooks are IPython notebooks so forcing that dependency when it wasn't always needed, especially with work-around for processing IPython notebooks without it, was deemed the correct compromise if memory serves. To that end the library does emit a warning: `warn("IPython3 lexer unavailable, falling back on Python 3")` when this occurs so users know an optional dependency wasn't found for rendering.

I'd be inclined to leave the behavior as is because we'd get push-back increasing the dependency chain even more than it is. We could add another `extra` installation for `ipython` so one could do `pip install nbconvert[ipython]`, though I'm not sure it has a ton of value over the warning alone.

**Comment by ricklamers** [comment]
When I start from a clean environment (virtualenv - Python 3.8.6) with `pip install nbconvert` I get the following error when I try to use `nbconvert` to render to html `jupyter nbconvert Untitled.ipynb --to html`.

```
[NbConvertApp] WARNING | Config option `template_path` not recognized by `HTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
Traceback (most recent call last):
  File "/Users/ricklamers/workspace/pythonwarnings/venv/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/Users/ricklamers/workspace/pythonwarnings/venv/lib/python3.8/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/ricklamers/workspace/pythonwarnings/venv/lib/python3.8/site-packages/traitlets/config/application.py", line 837, in launch_instance
    app.start()
  File "/Users/ricklamers/workspace/pythonwarnings/venv/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/Users/ricklamers/workspace/pythonwarnings/venv/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 519, in convert_notebooks
    self.exporter = cls(config=self.config)
  File "/Users/ricklamers/workspace/pythonwarnings/venv/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 325, in __init__
    super().__init__(config=config, **kw)
  File "/Users/ricklamers/workspace/pythonwarnings/venv/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 114, in __init__
    self._init_preprocessors()
  File "/Users/ricklamers/workspace/pythonwarnings/venv/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 490, in _init_preprocessors
    super()._init_preprocessors()
  File "/Users/ricklamers/workspace/pythonwarnings/venv/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 266, in _init_preprocessors
    self.register_preprocessor(preprocessor, enabled=True)
  File "/Users/ricklamers/workspace/pythonwarnings/venv/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 227, in register_preprocessor
    preprocessor_cls = import_item(preprocessor)
  File "/Users/ricklamers/workspace/pythonwarnings/venv/lib/python3.8/site-packages/traitlets/utils/importstring.py", line 30, in import_item
    module = __import__(package, fromlist=[obj])
ModuleNotFoundError: No module named 'jupyter_contrib_nbextensions'
```

Which prompts me (as someone not to sure about the `nbconvert` dependency tree) to install `pip install jupyter_contrib_nbextensions` which installs `jupyter_latex_envs` which installs `ipython`.

Is `jupyter_contrib_nbextensions` not a required package for `nbconvert`? Why am I seeing the ModuleNotFoundError `jupyter_contrib_nbextensions`? Am I doing something wrong (might very well be)?

Just want to say I'm all for keeping requirements down to a minimum. But I'm trying to ascertain how well `nbconvert` currently runs without `IPython`.

My feeling is that a lot these implicit dependencies go unnoticed because a lot of people have both `IPython` and `nbconvert` installed in their Python environments.

**Comment by bollwyvl** [comment]
Looks like you may have some other config values (e.g. from jupyter
--paths, or entry_points from user site packages or...) sneaking in:
nbconvert doesn't know anything about the contrib stuff.

**Comment by ricklamers** [comment]
You're correct. I reviewed `jupyter --paths`, it contained configs prompting the import of `jupyter_contrib_nbextensions`. Without the config including additional preprocessors the behavior is as expected (it shows a warning about the missing IPython package).

I think the graceful degradation with a warning, and not having to depend on too many packages is a pretty good trade-off.

Consider this issue solved :) Thanks for your prompt response!

**Comment by jayqi** [comment]
> I'd be inclined to leave the behavior as is because we'd get push-back increasing the dependency chain even more than it is. We could add another extra installation for ipython so one could do pip install nbconvert[ipython], though I'm not sure it has a ton of value over the warning alone.

I disagree that having an extra has no value over the warning. Managing dependencies of nbconvert is an nbconvert concern and should be abstracted from users. Having users independently add ipython as a dependency means that this is leaking out of nbconvert and into the user's general dependency specification. For example, if a user decides they don't need nbconvert anymore, removing nbconvert would still leave a leftover separate dependency of ipython that they would need to remember to remove.
