### ISSUE TITLE
conda packaging with multiple outputs for optional/heavy dependencies?

### ISSUE THREAD

**Issue by bollwyvl** [jupyter/nbconvert#1446]
Hey, folks! As always, thanks for keeping the nbconvert ship afloat!

We have a couple things cooking related to offering more variants of `nbconvert` packages on conda-forge:
- https://github.com/conda-forge/staged-recipes/pull/12516#discussion_r502814168
  - `jupyter-book`, coming to a repo near you, would be even better with `webpdf`
- https://github.com/conda-forge/nbconvert-feedstock/issues/46#issuecomment-706593323
  - `nbconvert-core`, `nbconvert` (with `pandoc`) and `nbconvert-webpdf` (with `pyppeteer`)

In 2020, we still couldn't confidently offer an `nbconvert-latexpdf` without system packages, and `nbconvert-webpdf` would _also_ need some native `x11` deps on some platforms (e.g. bare-bones `docker`) but this might be a way forward that would be consistent for everyone, while giving users with special requirements some more options.

Nothing would change, on this repo, other than some docs updates, along the the lines of `[extras]` in the install language.

Further, there would be a transition time on `conda-forge` downstreams, as we worked through getting the lighter-weight `core` stuff into other feedstocks. The worst case here is, eventually, a user would install an environment that depends on `nbconvert-core` and _not_ get `pandoc` when they are expecting it, but there aren't a lot of ways to relax some of these requirements.

Thanks!

**Comment by MSeal** [comment]
That sounds like a good separation of concerns / ability to mirror the repo's `extras` installation pattern. Thanks for letting folks know, and I agree with the risk assessment for what might go wrong and that it's a reasonable change to risk disruption.

**Comment by bollwyvl** [comment]
For our sins, this is what it could look like:
https://github.com/conda-forge/nbconvert-feedstock/pull/47

**Comment by bollwyvl** [comment]
This happened a while back.
