### ISSUE TITLE
Nbconvert doesn't respect explicit line joining (Line breaks using \ the backslash)

### ISSUE THREAD

**Issue by yangziy** [jupyter/nbconvert#1449]
Nbconvert doesn't respect [explicit line joining](https://docs.python.org/3/reference/lexical_analysis.html#explicit-line-joining).

1. Create a new notebook, create a new code block, paste the following line, save the notebook (Or download it here [splitted_line.ipynb.txt](https://github.com/jupyter/nbconvert/files/5360470/splitted_line.ipynb.txt), kill the `.txt` suffix)
```
a = 1 + 1 \
    + 1
```
2. Use nbconvert to convert the notebook into python script. The backslash is lost and the two lines are incorrectly joined into one line.
`jupyter nbconvert --to python splitted_line.ipynb`

3. The output .py file is unexpected.

> Output:
> ```
> #!/usr/bin/env python
> # coding: utf-8
> 
> # In[ ]:
> 
> a = 1 + 1     + 1
> ```
> 
> Expected:
> ```
> #!/usr/bin/env python
> # coding: utf-8
> 
> # In[ ]:
> 
> a = 1 + 1 \
>     + 1
> ```

**Nbconvert version:** 6.0.7

BTW: As I verified, [jupytext](https://github.com/mwouts/jupytext) can produce the expected output.

**Comment by yangziy** [comment]
As I verified, jupytext can produce the expected output.

**Comment by MSeal** [comment]
This is a known issue, though I am struggling to find the original issue thread at the moment. If someone does find that exiting thread, let's close one as a duplicate.

**Comment by yangziy** [comment]
Thank you for confirming! As I have found just now, The previous issue is here https://github.com/jupyter/nbconvert/issues/1349

**Comment by Plinsboorg** [comment]
@MSeal Can you close this issue as a duplicate?
