### ISSUE TITLE
[RFC]: Print oriented webpdf output

### ISSUE THREAD

**Issue by iromero91** [jupyter/nbconvert#1464]
I've been working on a webpdf exported designed for printing the resulting pdfs. Would this be something the project would be interested in having integrated with the webpdf exporter or should it remain a separate exporter?

To clarify the following features are already implemented in my code:

* Pagination (using css to set the page size and margins). Your webpdf exporter intentionally attempts to make a single page PDF out of the notebook (see PR #1402 ). If we integrate i would split that behavior off into an option.
* Templated HTML page headers and footers. Using chrome/puppeteer facilities to inject HTML at the header and footer of each printed page we can have information like page numbers change dynamically.

**Comment by yuvipanda** [comment]
I would *really* like the option to turn pagination on / off. I think it should be in the default webpdf exporter, since that'll turn it into a full blown alternative to PDF via LaTeX

**Comment by yuvipanda** [comment]
Also if you have a link to your code, I'd appreciate that too :)

**Comment by yuvipanda** [comment]
Unfortunately, I had to get pagination working pretty soon for a class. So I opened https://github.com/jupyter/nbconvert/pull/1513. Very sorry about not waiting.

**Comment by iromero91** [comment]
@yuvipanda I guess that pretty much settles this. I will look into submitting a PR for headers and footers once the tempfile PR gets in.
