### ISSUE TITLE
Export Notebook to Webpdf 1MB limit

### ISSUE THREAD

**Issue by beatslikeahelix** [jupyter/nbconvert#1468]
So I'm really enjoying the Webpdf feature, however I'm noticing that if I have a notebook with many subplots, and the file size of the resulting pdf creeps up past 1MB, I am met with
```
nbconvert failed: Navigation Timeout Exceeded: 30000 ms exceeded.
```
 At first I thought there simply wasn't enough time for the pdf build to complete, so I changed the parameter `self._defaultNavigationTimeout` in  pyppeteer/pages.py to allow thrice this time, but soon realised that no matter the time, I am still met with this error for files above 1MB.

Is there something I can change to override this, be it in Pyppeteer or nbconvert?
Cheers.

**Comment by adelaba1** [comment]
Hello, I have a very similar issue with my notebook project. The sharing of a solution would be very welcomed.
Thank you and have a nice day!

**Comment by iromero91** [comment]
I have a solution for this but looks like nobody is looking at the PRs. Please check out my branch at https://github.com/iromero91/nbconvert/tree/webpdf-tempfile And see if that works for you.

**Comment by norweeg** [comment]
> I have a solution for this but looks like nobody is looking at the PRs. Please check out my branch at https://github.com/iromero91/nbconvert/tree/webpdf-tempfile And see if that works for you.

did you PR it here?  I don't see an open PR for this issue/fix, but I desperately need it!

**Comment by iromero91** [comment]
@norweeg i did not pr it yet because i wanted to get #1463 in first. Is there some other way i could ping maintainers to look at this?

**Comment by iromero91** [comment]
@norweeg if you can try that branch please let me know if the fix works for you. i have only tested it on linux (arch).

**Comment by norweeg** [comment]
> @norweeg if you can try that branch please let me know if the fix works for you. i have only tested it on linux (arch).

It worked for me!  Thank you!

**Comment by nealcoles** [comment]
I had the same problem and this fix worked for me - thanks! 
(running on Windows 10)

**Comment by ozichert** [comment]
It seems like the fix was not included into the master. I got the same issue within my project.
