### ISSUE TITLE
Dark theme broken when notebook contains widgets in metadata

### ISSUE THREAD

**Issue by cnydw** [jupyter/nbconvert#1506]
I followed the guide on https://blog.jupyter.org/the-templating-system-of-nbconvert-6-47ea781eacd2 to convert my notebooks to HTML with dark theme, using
```
jupyter nbconvert xleaflet.ipynb --to html --HTMLExporter.theme=dark
```

However some of the converted notebooks have the dark theme style for about 0.5 second, then the HTML page turns to the white theme automatically.
After some investigation I found out that it's only happening to the notebooks with widgets state in the metadata, which makes nbconvert add the following code snippet to the HTML page,
https://github.com/jupyter/nbconvert/blob/2e41429def702dd561586303356fdf1f9be7e95c/share/jupyter/nbconvert/templates/base/jupyter_widgets.html.j2#L3-L26

which in turn breaks the dark theme by updating the CSS properties.

**Nbconvert version:**

6.0.7

**Comment by italodamato** [comment]
I have the same issue. Did you find a workaround? @cnydw
