### ISSUE TITLE
Doc: tex installation recommendation out dated

### ISSUE THREAD

**Issue by we-taper** [jupyter/nbconvert#1518]
The package `texlive-generic-recommended` is no longer available in Ubuntu 20.04:

```bash
➜  ~ sudo apt-get install texlive-generic-recommended
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package texlive-generic-recommended is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'texlive-generic-recommended' has no installation candidate

```

But it is mentioned in [docs/source/install.rst](https://github.com/jupyter/nbconvert/blob/master/docs/source/install.rst).
What is the alternative package? Is it `texlive-latex-recommended`?

**Comment by mgeier** [comment]
According to the Debian package description (https://packages.debian.org/buster/texlive-generic-recommended), this is just a dummy package that makes sure that `	texlive-plain-generic` is installed.
