### ISSUE TITLE
Markdown LaTeX conversion issue

### ISSUE THREAD

**Issue by StevenClontz** [jupyter/nbconvert#1519]
Dollar signs are converted from Jupyter to LaTeX in an unexpected way.

In a markdown cell:

```
$x^2 + y^2 = z^2$
```

converts to this as intended:

```
\(x^2 + y^2 = z^2\)
```

However:

```
$ x^2 + y^2 = z^2 $
```

converts to this instead:

```
\$ x^2 + y^2 = z^2 \$
```

Note that both original Markdown cells are displayed in math mode as expected in the original notebook.

**Comment by t-makaro** [comment]
Duplicate of #749
