### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: slides_reveal.tpl

### ISSUE THREAD

**Issue by marioRaouf** [jupyter/nbconvert#1528]
I'm trying to create a slide show from a notebook.
i ran the command : jupyter nbconvert ford_explanatory.ipynb --to slides --template output-toggle.tpl --post serve

got an error : jinja2.exceptions.TemplateNotFound: slides_reveal.tpl

Thanks in advance.

**Comment by MSeal** [comment]
Your `output-toggle.tpl` is likely a 5.x template. You'll need to use nbconvert 5.x or upgrade your custom template to the [6.x pattern](https://nbconvert.readthedocs.io/en/latest/customizing.html).

**Comment by BastienTr** [comment]
I had the same issue and rolling back to nbconvert 5.x fixed the problem. Thanks @MSeal :+1:

**Comment by SylvainCorlay** [comment]
Closing as answered!

**Comment by Oma-san** [comment]
@BastienTr Please how did you roll back tp nbconvert 5.x

**Comment by Jerwuney** [comment]
@Oma-san with Python 3.7 or lower, you can install nbconvert 5.x. You might not need to specify the version of nbconvert with those Python versions, just
- pip install nbconvert or 
- conda install nbconvert
Depending on where you run your Python
