### ISSUE TITLE
Converting Google Colab notebooks to script lead to `.txt` output while `.py` file is expected

### ISSUE THREAD

**Issue by lyskov** [jupyter/nbconvert#1529]
When i try to convert Google Colab .ipynb file into script (with `--to script` used) i am getting text file (`<base name>.txt`) written instead. Inserting snippet below into `metadata` portion of .ipynb file "fixed" the issue. 

 ``` 
    "language_info": {
       "codemirror_mode": {
	"name": "ipython",
	"version": 3
       },
       "file_extension": ".py",
       "mimetype": "text/x-python",
       "name": "python",
       "nbconvert_exporter": "python",
       "pygments_lexer": "ipython3",
       "version": "3.7.0"
      },
``` 

notebook that trigger this issue: https://github.com/RosettaCommons/PyRosetta.notebooks/blob/5258471a90e4572d919e14d5640bb642687a3109/notebooks/01_01_PyRosetta_Google_Drive_Setup_a_wheel.ipynb
This was observed in Nbconvert 6.0.7.
Thanks,

**Comment by MSeal** [comment]
Unfortunately, if the notebook doesn't specify a language in it's metadata the script conversion doesn't know what extension to use. You may have an R notebook for example, so it defaults to text without any language specific modifiers when it's not provided.

**Comment by lyskov** [comment]
In other words this should be propagated to Colab team instead?

**Comment by t-makaro** [comment]
@lyskov You can use ```--to python``` and it will work fine, but ```--to script``` won't work unless google colab fixes their metadata.

**Comment by lyskov** [comment]
@t-makaro oh i did not know that, - thank you for pointing this out @t-makaro , - i will try it out!
