### ISSUE TITLE
customizing and nbconvert_library doc pages are missing 

### ISSUE THREAD

**Issue by Carreau** [jupyter/nbconvert#156]
Reported by @takluyver [here](https://github.com/jupyter/nbconvert/commit/183ac9b95f085ab8ef4e74499764e6c3c777da57#commitcomment-14215343)

Readthedocs should really make a build **fail**.

**Comment by takluyver** [comment]
We either need to:

- Keep the rst files checked in, remembering to only change the corresponding notebooks and regenerate them, or
- Do some more conf.py trickery to get them converted on RTD.
