### ISSUE TITLE
Release timeline?

### ISSUE THREAD

**Issue by kycutler** [jupyter/nbconvert#1563]
I'm looking for a few fixes that have gone in since the last release (6.0.7). It's been 7 months since that release, so I'm just wondering what's the plan for a new version?

**Comment by MSeal** [comment]
I think we should go through open issues / PRs and prepare a release. I believe most of the maintainers have been distracted with work / life so having someone champion running through this process would be especially helpful. @yuvipanda I know there were some PRs open we haven't fully addressed you might want resolved before a release?

@SylvainCorlay @maartenbreddels @davidbrochart Thoughts / anyone else we should ping about release prep?

**Comment by MSeal** [comment]
Let's also get https://github.com/jupyter/nbconvert/pull/1514 fixed and merged. It's been hanging for a while and there's a few duplicate PRs on that space.

**Comment by yuvipanda** [comment]
@Mseal - cool! I won't have much time to work on that though, would love for someone else to pick it up...

**Comment by MSeal** [comment]
If no one gets to it, I'll take a pass during or after PyCon. I understand not having time right now. Stay safe over there @yuvipanda !

**Comment by tobinjones** [comment]
When this goes ahead, may I suggest that #1495 be considered. A small change fixes a significant bug.

**Comment by kycutler** [comment]
Just checking in here since it has been a month. I get that no one has had time to work on this but I'm still waiting for the updates that have gone in.

If there are no regressions would it be okay to do a release as-is, and then another once the other issues / PRs mentioned here have been resolved?

**Comment by MSeal** [comment]
Apologies no one is sheparding this project well atm. I think all the
primary maintainers had major life events in the past year. I have some
time this weekend and can either get those recent PRs in and/or get the
release staged.

**Comment by MSeal** [comment]
I got a large number of PRs merged today and fixed resulting test issues. However, there's still a test issue for latex conversion on just ubuntu where inkscape < 1 seems to have the >= 1 argument convention that's blocking tests, and https://github.com/jupyter/nbconvert/pull/1576 needs more build passes to get the docs working again. I should have those two last things done tomorrow night and kick off an alpha release.

**Comment by MSeal** [comment]
@kycutler 6.1.0rc0 is released as a pre-release version. I'll let it sit for the week and we'll see if any bug reports come in on the new version and plan to release the final 6.1.0 after that cooling period. There were enough changes with complicated interactions, I wanted to give some of the automated builds that pull nbconvert downstream a chance to test it out first.

**Comment by kycutler** [comment]
@MSeal not to be pushy but are there any issues blocking the 6.1.0 release (or could we maybe do another RC)? I need the WebPDF fix from #1590

**Comment by MSeal** [comment]
Shoot, sorry that fix wasn't put out in a new RC promptly. I did some debugging on Windows this weekend, following on https://github.com/jupyter/nbconvert/issues/1588. There's one test failing locally on Windows but I'm pretty sure it's a pytest PATH issue with how we setup the test and I'm going to punt in fixing that as no actual blockers where found in RC. Given that I think I'm good to kick off the 6.1.0 release tonight.

**Comment by MSeal** [comment]
@kycutler 6.1.0 release is out now on PyPI (conda will build when it notices the change). Thanks for being patient with the timing.
