### ISSUE TITLE
Pandoc 2.11.2 requires calc LaTeX package

### ISSUE THREAD

**Issue by buergi** [jupyter/nbconvert#1566]
During export of jupyter notebook, I got loads of errors of the following kind

    notebook.tex:798: Missing number, treated as zero
    notebook.tex:798: Illegal unit of measure (
    notebook.tex:799: Missing number, treated as zero
    notebook.tex:799: Illegal unit of measure (
    notebook.tex:803: Missing number, treated as zero
    notebook.tex:803: Illegal unit of measure (

The notebook needs to contain markdown table of a certain width such as

    | AAAAAAAAAAAAAAAAA | BBBBBBBBBBBBBBBBB | CCCCCCCCCCCCCC | DDDDDDDDDDDDDD | EEEEEEEEEEEEEEEE | 
    | --- | --- | --- |--- |--- |

when exporting this notebook as PDF (`File > Download as > PDF via LaTeX (.pdf)`) the described errors appear.

The problem was introduced with Pandoc 2.11.2 with this commit https://github.com/jgm/pandoc/commit/bd7c9eb32be7c5499f4a50cb4b5f138f9eb919e8
To fix it we need to add `\usepackage{calc}` to [base.tex.j2](https://github.com/jupyter/nbconvert/blob/master/share/jupyter/nbconvert/templates/latex/base.tex.j2), ideally after the `\usepackage{booktabs}` line.

**Nbconvert version:** 6.0.7

**Comment by ivanov** [comment]
closed by #1686
