### ISSUE TITLE
nbconvert generates URL fragments with invalid characters

### ISSUE THREAD

**Issue by charmasaur** [jupyter/nbconvert#1580]
When headers in notebooks contain backslashes (for math, say), the generated URL fragments in the anchor links contain backslashes, which are invalid (https://datatracker.ietf.org/doc/html/rfc3986#section-3.5).

To reproduce, create a notebook with header: `# Pi $\pi$`.

This generates HTML code: `<h1 id="Pi-$\pi$">Pi $\pi$<a class="anchor-link" href="#Pi-$\pi$">&#182;</a></h1>`, which has in invalid fragment `#Pi-$\pi$` (due to the backslash).

See [pi.txt](https://github.com/jupyter/nbconvert/files/6543903/pi.txt).

**Nbconvert version:** 5.6.1 (edit: and 6.0.7)

(If the outcome here is just to tell me not to put math in headings, that's OK with me.)

Edit: note that this is similar, but not identical, to https://github.com/jupyter/nbconvert/issues/1233

**Comment by MSeal** [comment]
Can you try with nbconvert 6 instead of 5.6.1? There aren't any more patches going to the older major version.

In general better parsing for math elements would be appreciated if people have time to help -- 6.x had improvements to this but there's still edge cases present.

**Comment by charmasaur** [comment]
Same story with version 6. I can put it on my todo list to look into a fix here, not sure when I'll actually get to it but it's useful to know that contributions would be helpful (I'm never sure whether PRs from randoms like me are a help or a hinderance...).

**Comment by MSeal** [comment]
Nah, new contributor PRs aren't hindrance and almost always welcomed :)

Sometimes it's not clear how to resolve follow-up concerns right away but I wouldn't call that a hindrance as everyone would hit those anyway.
