### ISSUE TITLE
Warn if JS has been stripped

### ISSUE THREAD

**Issue by Carreau** [jupyter/nbconvert#16]
It would be nice to find a way when you remove Javascript from display_priority to have a prefiter and a template to ass a warning that JS has been disbled. 

Assigning to me, but I'll probably not have a look in the couple few weeks.

**Comment by captainsafia** [comment]
If you don't have time for this @Carreau, I can take a look at it.

Might be a good way to get familiar with the `nbconvert` codebase.

**Comment by Carreau** [comment]
Sure, I'm flying to France in 3h so you are safe for a few days.

Envoyé de mon iPhone

**Comment by MSeal** [comment]
Don't believe this is still relevant. Reopen if that's incorrect.
