### ISSUE TITLE
Webpdf can't be templated

### ISSUE THREAD

**Issue by marimeireles** [jupyter/nbconvert#1600]
When using: `jupyter nbconvert NetworkX\ Example.ipynb --template reveal --to webpdf`

```
ValueError: Unsupported mimetype 'application/pdf' for template 'reveal', mimetypes supported are: 
	text/html
```

**Nbconvert version:** Main

**Comment by marimeireles** [comment]
https://github.com/jupyter/nbconvert/pull/1601 offers a solution. Not sure if missing something.

**Comment by marimeireles** [comment]
Btw, this happens with other templates too, not only the reveal one.

**Comment by SylvainCorlay** [comment]
Closing as resolved.
