### ISSUE TITLE
6.2.0 release

### ISSUE THREAD

**Issue by marimeireles** [jupyter/nbconvert#1607]
Hello,

I'd like to know if `nbconvert` has some roadmap for releases?

I need a new version with the changes I recently added and I'd like to help with the release of a new minor version, if possible. :)

Thank you!

**Comment by jasongrout** [comment]
I would also like to help get a new version out with some recent changes that were merged.

@MSeal - I see the flurry of activity on the repo recently. Thanks for merging a bunch of things in! Do you have a timetable for a release? Can I help with anything? I'm happy to just do the release as well, especially if there are any special release instructions written down somewhere.

**Comment by marimeireles** [comment]
I think @SylvainCorlay had some plans for this. I'm not sure what's the current status.

**Comment by jasongrout** [comment]
@SylvainCorlay, @MSeal (or others): can you give me permissions on pypi to do a release, and I'll do a beta prerelease with current master?

**Comment by SylvainCorlay** [comment]
@jasongrout I just pushed a beta release, and saw your comment when coming here to notify folks on the issue. I just added you on PyPI as well.

**Comment by jasongrout** [comment]
> @jasongrout I just pushed a beta release, and saw your comment when coming here to notify folks on the issue. I just added you on PyPI as well.

Thanks!

**Comment by jasongrout** [comment]
> I just pushed a beta release

I see you pushed out 6.1.1b0 (thanks again!), but I think the next release should be 6.2.0 since we have some nice new features, not just bugfixes.

**Comment by SylvainCorlay** [comment]
Yes I was wondering what was the most appropriate version number.
We could make the next prerelease as a 6.2.0...

**Comment by MSeal** [comment]
I agree with 6.2.0 as the next release. @jasongrout https://nbconvert.readthedocs.io/en/latest/development_release.html?highlight=release has the release instructions, except the last step we were just posting to the discourse page rather than emailing to the list (we should update those instructions).

**Comment by jasongrout** [comment]
Thanks Sylvain and Matt. I'm happy to push forward with the release process. Matt, Sylvain, or other maintainers: were there any other PRs that you wanted to merge in before I cut a release candidate?

**Comment by jasongrout** [comment]
The changelog is now updated. I'll plan to release an RC tomorrow unless someone wants to hold off and get some more things in.

**Comment by MSeal** [comment]
I was hoping @SylvainCorlay or @maartenbreddels  could take a look at https://github.com/jupyter/nbconvert/issues/1401 and give input for the release. https://github.com/jupyter/nbconvert/pull/1632 looked like we should get in as well but both of those could be tackled after RC release if need be.

**Comment by jasongrout** [comment]
> take a look at #1401 and give input for the release

Fixed in #1640

**Comment by jasongrout** [comment]
I also merged #1632.

**Comment by jasongrout** [comment]
With those two issues taken care of, any objection to making an RC release?

**Comment by MSeal** [comment]
Go for it @jasongrout ! Ty

**Comment by jasongrout** [comment]
6.2.0rc0 is now up on pypi: https://pypi.org/project/nbconvert/6.2.0rc0/

**Comment by bsyouness** [comment]
Woohoo! Are we gonna publish an the RC as a conda package as well for our use?

**Comment by jasongrout** [comment]
Working on a conda-forge prereleae: https://github.com/conda-forge/nbconvert-feedstock/pull/59

**Comment by jasongrout** [comment]
6.2.0rc1 is now published on conda-forge: https://anaconda.org/conda-forge/nbconvert/files

**Comment by jasongrout** [comment]
Pinning the release issue for visibility that there is release activity going on, and so it's easy for me to find :).

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/nbconvert-6-2-0-release-candidate/10845/1

**Comment by jasongrout** [comment]
6.2.0rc2 is up on pypi, announced on discourse at https://discourse.jupyter.org/t/nbconvert-6-2-0-release-candidate/10845, and the conda-forge package is in progress. If there are no other issues, I'll plan to release final in one week to give time for community testing.

**Comment by jasongrout** [comment]
Install with `pip install --pre nbconvert`, or `conda install -c conda-forge/label/nbconvert_rc -c conda-forge nbconvert`

**Comment by jasongrout** [comment]
I just published 6.2.0 final to pypi. Conda-forge is coming up.

**Comment by SylvainCorlay** [comment]
Great!
Thank you for pushing this forward @jasongrout.

**Comment by SylvainCorlay** [comment]
It appears that 6.2 is breaking custom templates apparently because of PR https://github.com/jupyter/nbconvert/pull/1614.

The reason is that voila overrides the `jupyter_widgets` macro to be empty with the old number of argument, and we get the following error in templates making use of it:

```
TypeError: macro 'jupyter_widgets' takes not more than 2 argument(s)
```

**Comment by SylvainCorlay** [comment]
I made a patch release of Voilà to account for this.

**Comment by MSeal** [comment]
Thanks for getting this released @jasongrout !

**Comment by SylvainCorlay** [comment]
Closing as released!
