### ISSUE TITLE
When is the .nbconvert.ipynb generated?

### ISSUE THREAD

**Issue by sagar1025** [jupyter/nbconvert#1626]
Does the `--to notebook` option generate the `.nbconvert.ipynb` file after executing the original notebook or does it first create the `mynotebook.nbconvert.ipynb` file and then updates its cells as the cells in the original notebook are executed?

For example, suppose I have this command

`jupyter nbconvert --to notebook --execute mynotebook.ipynb`

The documentation says that it saves the result in a new `mynotebook.nbconvert.ipynb` file. I can verify that this is working as expected for me, but I'm trying to understand at what point during the execution of the `nbconvert` command the `mynotebook.nbconvert.ipynb` file is generated. 

Does it first execute the `mynotebook.ipynb` file and then creates and saves the outputs to a new `mynotebook.nbconvert.ipynb` or is this `mynotebook.nbconvert.ipynb` file created first then its contents are updated with the outputs of the `mynotebook.ipynb`?

**Comment by MSeal** [comment]
The notebook execution rewrites the notebook file todisk at the start of execution and after each cell is executed. So more the latter where it's created then updated with outputs gradually.

**Comment by sagar1025** [comment]
That's what I was looking for. Thanks!
