### ISSUE TITLE
Correct way to extend template to add IPython as import?

### ISSUE THREAD

**Issue by philippefutureboy** [jupyter/nbconvert#1628]
We are using nbconvert to generate ipy files as a poorman's way to have clear git diff in github PRs for our jupyter notebooks.
The problem we are facing is that the generated ipy files generate without the import statement for IPython, which result in issues when running automated qa tools like flake8.

I've read your tutorial on [customizing nbconvert](https://nbconvert.readthedocs.io/en/4.2.0/customizing.html) and also located the basic python template to be located in [share/jupyter/nbconvert/templates/python/index.py.j2](https://github.com/jupyter/nbconvert/blob/main/share/jupyter/nbconvert/templates/python/index.py.j2).

If I wish to add the import statement for IPython to the default python template, how should I go about it?

Should I copy the python template in my repository and extend it manually there? If so, will it resolve "null.j2" automatically?
Alternatively can I simply overwrite the header block from the python template?

Some guidance would be much much appreciated! 😄

**Comment by MSeal** [comment]
Yes you can copy the template. The null.j2 should resolve as it'll fall back to the provided templates from nbconvert if new ones aren't defined. You could also try overwriting the header block, but I would expect it to be similar levels of effort.

**Comment by philippefutureboy** [comment]
Lovely, thanks for your answer! :)
