### ISSUE TITLE
Wrong import statement in notebook execution Python API 

### ISSUE THREAD

**Issue by twhughes** [jupyter/nbconvert#1644]
In the example, there are instances of `import nbformat`
https://github.com/jupyter/nbconvert/blob/76bfbb53927e81cbea25da9d115710f59964fb22/docs/source/execute_api.rst
It seems rather `nbconvert` should be used, specifically in the import of `ExecutePreprocessor`

The following code works for me

```python
import nbconvert
import nbformat

from nbconvert.preprocessors import ExecutePreprocessor
ep = ExecutePreprocessor(timeout=600)
with open(fname) as f:
	nb = nbformat.read(f, as_version=4)
	ep.preprocess(nb, {'metadata': {'path': '.'}})
```

**Comment by jasongrout** [comment]
I don't see the problem with the example as it is written. This code gives no errors for me:

```python
import nbformat
from nbconvert.preprocessors import ExecutePreprocessor
```
As you saw, you need to import nbformat to use it in the context handler to read the notebook file.

Were you seeing an error if you did not do `import nbconvert` first?

**Comment by twhughes** [comment]
Hi Jason,
I think the code as written is ok.  I think i was a bit confused because i
did not import nbconvert initially and thought it might have been a typo.
Feel free to close the issue.

**Comment by jasongrout** [comment]
Thanks for following up here.

**Comment by twhughes** [comment]
Hi @jasongrout do you know whether there's a way to get the local variables of a notebook after execution using `nbconvert`?  For example if I have 
```a=1```
in the notebook and I run it using
```out = ep.preprocess(nb, {'metadata': {'path': run_path}})```
is there a way to get the value of `a`?

**Comment by MSeal** [comment]
@twhughes The https://nteract-scrapbook.readthedocs.io/en/stable/ project was made to allow for saving / loading jsonizable results from notebook executions, usually paired with papermill instead of nbconvert but it'll work with both.

**Comment by twhughes** [comment]
Great, thanks.  I'll take a look.
