### ISSUE TITLE
LaTeX newcommand does not propagate to tex document correctly

### ISSUE THREAD

**Issue by jackblyle** [jupyter/nbconvert#1650]
In a jupyter notebook markdown cell I can enter a new LaTex command like:

$\newcommand{\partials}[2]{\dfrac{\partial #1}{\partial #2}}$

and then use it as:

$$\partials{L'}{q_j}$$.

In the notebook, the newcommand line will be hidden and the use of the \partials command works as expected. It displays a nice partial derivative.

BUT when I download the notebook as PDF via LaTex I get an error:

! Undefined control sequence.
l.537 \[\partials
                 {L'}{q_j}\]
? 
! Emergency stop.

I can work around the error by downloading to TeX, opening the file in an editor (say GNOME LaTeX), and manually moving the line:

\\(\newcommand{\partials}[2]{\dfrac{\partial #1}{\partial #2}}\\)

from the document body up into the preamble and deleting the unneeded \( and \). I can then save the tex file and compile to get a correct display in the PDF document. A workaround that complex isn't much of a workaround.

I have tried putting the new command up in a RawNBConvert cell at the top of the notebook without the leading and trailing $ marks. That gets the new command into the tex file at the top of the document body, right after \maketitle. But to get it to work in the notebook I have to also define it in a markdown cell, and then LaTex throws an error at the second occurrence saying Command \partials already defined.

Searching finds many versions of this question being asked (some from years ago), and sadly no working answers. Is there a trick I'm missing, or is this a true bug that has existed for years with no fix?

Running on Fedora 34.  jupyter-notebook --version  = 6.4.0.  jupyter-nbconvert -- version = 6.0.7.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/how-to-define-a-macro-in-a-jupyter-cell/7967/3

**Comment by mgeier** [comment]
This is expected behavior.

See https://github.com/jupyterlab/jupyterlab/pull/5997 for more details.

**Comment by jackblyle** [comment]
Yes.  The use of ```$\gdef\part#1#2{\dfrac{\partial #1}{\partial #2}}$``` instead of ```\newcommand{\partials}[2]{\dfrac{\partial #1}{\partial #2}}``` works fine.  Both typesetting in both jupyter notebook and LaTeX to PDF looks great.

**Comment by newptcai** [comment]
> Yes. The use of `$\gdef\part#1#2{\dfrac{\partial #1}{\partial #2}}$` instead of `\newcommand{\partials}[2]{\dfrac{\partial #1}{\partial #2}}` works fine. Both typesetting in both jupyter notebook and LaTeX to PDF looks great.

However, it does not seem to work in jupyter-lab.

**Comment by mgeier** [comment]
@newptcai Did you try the solution suggested in https://github.com/jupyterlab/jupyterlab/pull/5997#issuecomment-475289432?

```
<div hidden>
\newcommand{\require}[1]{}

$\require{begingroup}\require{newcommand}$
$\gdef\vec#1{\boldsymbol{#1}}$

\vskip-\parskip
\vskip-\baselineskip

</div>
```
