### ISSUE TITLE
6.3.0 Release

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/nbconvert#1667]
Hello all,

Is there anything blocking a release of 6.3.0, which includes the filtering of widgets mime type when no widget state is present?

cc @MSeal @jasongrout @martinRenou @maartenbreddels

**Comment by jasongrout** [comment]
I don't know of any blockers for a 6.3.0 release. I'd suggest an RC period (I've been using a week).

**Comment by SylvainCorlay** [comment]
I have release a beta for 6.3.0.

**Comment by SylvainCorlay** [comment]
It does not seem that the world collapsed with the beta release. I may release 6.3.0 over the week end.

**Comment by SylvainCorlay** [comment]
6.3.0 is out!

**Comment by MSeal** [comment]
Thanks for pushing the release through @SylvainCorlay !
