### ISSUE TITLE
Output of cell in Markdown as plain text

### ISSUE THREAD

**Issue by yuanx749** [jupyter/nbconvert#1681]
When converting a notebook to Markdown, the output of a cell is indent 4 spaces, hence it is rendered as a code block. I was wondering if it is possible to add an option to convert the output to regular text in Markdown, in which case the output is better differentiated from the input of a cell.

For example, a cell is rendered as below in markdown:
```python
print('hello')
print('world')
```

    hello
    world
    

Alternatively, I would expect
```python
print('hello')
print('world')
```

hello  
world

I notice that function `indent` is used in the template [`index.md.j2`](https://github.com/jupyter/nbconvert/blob/bc9802c98c2a03393d40a7bbbe2871acc8122c25/share/jupyter/nbconvert/templates/markdown/index.md.j2#L37). I was thinking instead of indention. adding 2 spaces to the end of each line in the output text could be a solution. Any hints to implement this behavior?

**Comment by powill** [comment]
Commenting on a bit of an old issue, but I am also having a similar problem converting Jupyter notebook files into markdown while differentiating input and output cells, and was curious if you ever found a solution. Thanks.
