### ISSUE TITLE
ExecutePreprocessor should (optionally) stop and propagate the error

### ISSUE THREAD

**Issue by mwaskom** [jupyter/nbconvert#17]
Migrating this issue from https://github.com/ipython/ipython/issues/8286 so it can be tracked here.

**Comment by tshead2** [comment]
+1 for this - I am using nbconvert to turn my notebooks into restructured text for documentation that appears automatically on readthedocs.org, and I want to know right away if anything fails.

**Comment by tshead2** [comment]
A temporary workaround that doesn't require patching and should be future-proof: use nbconvert to convert the notebook to vanilla python code, execute that to confirm it doesn't fail, then use nbconvert a second time to do the "real" conversion.  Slow, but effective.

Cheers,
Tim

**Comment by takluyver** [comment]
This got added in 4.0 by PR #33. Now errors should be propagated by default, and you can use the `--allow-errors` flag for the previous behaviour.
