### ISSUE TITLE
Cannot render plotly plot

### ISSUE THREAD

**Issue by jcrichard** [jupyter/nbconvert#170]
Hi, 

I use plotly with cufflinks for plotting data. Everithing is ok in the notebook but when I convert to slides, the plot are not showed and I have a message "Drawing..." in place.

Any idea what I am doing wrong ? (it is working with matiplot, bokeh ...)

**Comment by thhancock** [comment]
Just wondering if you (or anyone) ever solved this?

I beat by head against a wall for a while today, but...

...just solved what was going wrong for me by simply placing a plotly.js file in the directory I am running nbconvert in.  It seems that --to html will add the plotly js to the HTML file, but --to slides does not.  It searches for the file when serving the slides instead.

Hope that helps for anyone having this issue in the future.

**Comment by jcrichard** [comment]
thank you. No I didn't solve this yet. I used matiplot instead.

**Comment by damianavila** [comment]
Do you have an example to be able to replicate? @jcrichard

**Comment by jcrichard** [comment]
I didn't try again plotly. I will give an example if the problem is still running.

**Comment by damianavila** [comment]
OK, I will close this one now, but feel free to reopen if you actually see the issue again.
