### ISSUE TITLE
[BUG] module 'jinja2.utils' has no attribute 'escape'

### ISSUE THREAD

**Issue by aiwalter** [jupyter/nbconvert#1736]
Today released `jinja2` version has deprecated `jinja2.utils.escape`. 
See here: https://github.com/pallets/jinja/issues/1626

Not directly, it raises on `readthedocs` when building docs from notebooks:
https://readthedocs.org/projects/sktime/builds/16457301/

**Nbconvert version:**
latest

**Comment by davidism** [comment]
This doesn't appear to be an issue with nbconvert. There are no lines that start with `from jinja2` and include `escape` in the imports.

You need to identify the library that's actually doing that import and report the issue to them. Using `pip-compile` to compile a requirements file with "nbconvert" as the only requirement shows no secondary dependencies on Jinja2 from nbconvert, so this is likely coming from elsewhere in your requirements.

**Comment by aiwalter** [comment]
yes its this code, so actually it is coming from `nbconvert` package, right?

**Comment by davidism** [comment]
I am not a maintainer of this package.

**Comment by mriedem** [comment]
We're also seeing this, not sure if it's related but I'm chalking it up to the new jinja2 3.1.0 release:

```
Traceback (most recent call last):

  File "/opt/conda/bin/jupyter-nbconvert", line 6, in <module>

    from nbconvert.nbconvertapp import main

  File "/opt/conda/lib/python3.8/site-packages/nbconvert/__init__.py", line 4, in <module>

    from .exporters import *

  File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/__init__.py", line 3, in <module>

    from .html import HTMLExporter

  File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/html.py", line 12, in <module>

    from jinja2 import contextfilter

ImportError: cannot import name 'contextfilter' from 'jinja2' (/opt/conda/lib/python3.8/site-packages/jinja2/__init__.py)
```

**Comment by SylvainCorlay** [comment]
cc @MSeal @davidbrochart FYI

**Comment by davidism** [comment]
https://github.com/jupyter/nbconvert/blob/1211cb25a9c123eafce669e64b64316397c88a10/setup.cfg#L12-L14

If nbconvert adds `filterwarnings = error` to this section, they can respond proactively to warnings. The previous "warnings as errors" PR was only in relation to their own documentation builds.
