### ISSUE TITLE
ansigray or ansigrey?

### ISSUE THREAD

**Issue by mgeier** [jupyter/nbconvert#174]
I don't know if this is ever used, but I happened to notice that in nbconvert you use "ansigrey":
https://github.com/jupyter/nbconvert/blob/241ad6468bf89418460dcf698a3a59a8d2c06cf1/nbconvert/filters/ansi.py#L27
https://github.com/jupyter/nbconvert/blob/241ad6468bf89418460dcf698a3a59a8d2c06cf1/nbconvert/filters/tests/test_ansi.py#L43

In the `notebook` package (whose CSS, I guess, is used in nbconvert), however, "ansigray" is used:
https://github.com/jupyter/notebook/blob/b10326e93c93a8f79589e963ae48bbaac285e2f1/notebook/static/base/js/utils.js#L219
https://github.com/jupyter/notebook/blob/932f85c7593b2eada7a2095bd1f30d3f6ea48115/notebook/static/notebook/less/ansicolors.less#L13

I guess both packages should use the same spelling, right?

**Comment by Carreau** [comment]
hum... likely yes.

**Comment by mgeier** [comment]
BTW, in the meantime I found out that this is actually used for the little hat symbol (`^`) that marks the column number in the tracebacks.
