### ISSUE TITLE
test for .jpe issue in mimetypes

### ISSUE THREAD

**Issue by minrk** [jupyter/nbconvert#176]
We should add a test for the issue fixed by #175

**Comment by takluyver** [comment]
The function added is so simple I'm not sure it's really worth testing, so I'm inclined to close this unless we want to leave it as a simple task for a new contributor to work on?

**Comment by WillEngler** [comment]
New contributor here looking for a simple task. I'm going to claim this issue for JupyterDay Chicago.

I hear what @takluyver is saying with
> The function added is so simple I'm not sure it's really worth testing

So I'm thinking of writing a test for `ExtractOutputPreprocessor.preprocess_cell` that confirms it succeeds on a simple cell with a .jpeg in it.

**Comment by WillEngler** [comment]
Looking closer at the existing test code, it seems like the preferred style is making a fixture notebook and doing a more integration-level test than what I'd suggested, so I'll go that route instead and make a notebook with a .jpeg. (By the way, lovely test organization! I love all the helpers.)

**Comment by minrk** [comment]
closed by #251
