### ISSUE TITLE
HTML converter fails to handle inline links with URLs containing pairs of parentheses in Markdown cells

### ISSUE THREAD

**Issue by tueda** [jupyter/nbconvert#1804]
Though it is unclear how they should be handled from the [original Markdown specification](https://daringfireball.net/projects/markdown/syntax#link) and there are [known workarounds](https://stackoverflow.com/q/13824669/9105334), I thought `nbconvert --to html` should correctly convert inline links with URLs containing pairs of parentheses in Markdown cells (at least, Jupyter Notebook, Google Colaboratory 
 and GitHub Markdown correctly render them), for example:

```markdown
[Python](https://en.wikipedia.org/wiki/Python_(programming_language))
```

But the corresponding HTML output was:

```html
<p><a href="https://en.wikipedia.org/wiki/Python_(programming_language">Python</a>)</p>
```

**Steps to reproduce this issue**:
```bash
curl -L https://github.com/jupyter/nbconvert/files/9035582/test-jupyter-nbconvert.ipynb.txt -o test-jupyter-nbconvert.ipynb
jupyter nbconvert --to html test-jupyter-nbconvert.ipynb
grep Python_ test-jupyter-nbconvert.html
```

**Minimum notebook that reproduces this issue**: [test-jupyter-nbconvert.ipynb.txt](https://github.com/jupyter/nbconvert/files/9035582/test-jupyter-nbconvert.ipynb.txt)

**Screenshots**: In Jupyter Notebook, it is correctly rendered:

![image](https://user-images.githubusercontent.com/1481665/177059309-d9dbec78-39c3-4acd-b97c-1f6b834aef66.png)

while the converted HTML has a broken link:

![image](https://user-images.githubusercontent.com/1481665/177059347-8d50ae30-8f4f-4b29-97d8-799f5ddf3929.png)

**Nbconvert version:**

I tried both 6.5.0 and 7.0.0rc2.

**Comment by TiagodePAlves** [comment]
Markdown links can appear inside parentheses:
```markdown
([Python](https://en.wikipedia.org/wiki/Python_(programming_language)))
```
Which should *ideally* appear as `(Python)`.

And the user may very well want a trailing parenthesis:
```markdow
- [Question 1](link.to/question/1)) Answer One.
- [Question 2](link.to/question/2)) Answer Two.
```
This should be rendered as:
```html
<ul>
<li><a href="link.to/question/1">Question 1</a>) Answer One.</li>
<li><a href="link.to/question/2">Question 2</a>) Answer Two.</li>
</ul>
```

This is very hard, if not impossible, for the parser to know. 

The only solution I can think of is trying reaching every possible link and choosing the first one that works, but that could be too slow for Jupyter. Also, the rendering could change depending on which network you're connected. 

Anyway, we use [mistune](/lepture/mistune) for parsing markdown. If you still think the behaviour is wrong, I recommend you try discussing it there.

**Comment by TiagodePAlves** [comment]
@blink1073 I believe this issue should be closed.

**Comment by blink1073** [comment]
Makes sense, thanks @TiagodePAlves for the investigation.
