### ISSUE TITLE
Converted plots will no longer load in recent Chrome/FF

### ISSUE THREAD

**Issue by willingc** [jupyter/nbconvert#182]
Reported by Mark on google group mailing list:

I am trying to convert an ipython notebook to html. The converted plots (which were embedded as images in the html file) were previously displayed. Due to recent upgrade in chrome and firefox browsers, the images are no longer displayed. The following is the error I get on the browser.

Refused to load the image 'data:image/png;base64,AAANSUhEUgAAAg8AAAHaCAYAA......'  because it violates the following Content Security Policy directive: "img-src 'self'".

Has anyone stumbled upon this problem and managed to find a workaround?

**Comment by takluyver** [comment]
Can anyone reproduce this? The images from data URLs still display for me in Firefox 44 and Chrome 48.

**Comment by willingc** [comment]
I'm going to go ahead and close this since there have been no further reports the past month. If anyone has further information, please do reopen this issue.
