### ISSUE TITLE
Backport div_id fix in 6.5.x

### ISSUE THREAD

**Issue by veghdev** [jupyter/nbconvert#1838]
@martinRenou Hi,
There was a small bug in div id generation, which I fixed in #1761.
We would like to use those ids in our projects, I would be appreciated if you could backport that fix in 6.5.x.

**Comment by blink1073** [comment]
Fixed in https://github.com/jupyter/nbconvert/pull/1839

**Comment by veghdev** [comment]
> Fixed in #1839

Thanks a lot!

**Comment by veghdev** [comment]
@martinRenou Could you please make the 6.5.4 release?

**Comment by blink1073** [comment]
@veghdev I'll cut a release tomorrow.

**Comment by veghdev** [comment]
@blink1073 Thank you
