### ISSUE TITLE
Only able to generate pdf through terminal/commandline

### ISSUE THREAD

**Issue by BaseBeginner** [jupyter/nbconvert#1870]
Hello, new user to JupyterLab here. Currently using JupyterLab 3.3.2 on my MacBook Pro running macOS Monterey. 

My issue is, per the title, that I can only convert notebooks to pdfs through the terminal (by running `jupyter nbconvert notebook.ipynb --to pdf`. When I try generating a pdf using the menu bar as so:

<img width="1723" alt="Screenshot 2022-09-27 at 17 31 18" src="https://user-images.githubusercontent.com/114346072/192596336-b0cfd415-99cf-435a-9608-d4208d91563b.png">

I get the following error:

`nbconvert failed: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.
`

I have already tried all of the advice (applicable to macOS users) suggested in [this thread.](https://github.com/jupyter/nbconvert/issues/799) More specifically, I have already installed latex on my system using the MacTex distribution. And I have added to my $PATH variable with the following instruction:

`export PATH=/Library/TeX/texbin:$PATH 
`

Finally, I have installed texlive (with the homebrew package manager). And I am also able to run xelatex through the terminal, so it is definitely on my system.

None of this has resolved my issue and I remain unable to generate pdfs except through the terminal. 

I realise this is a somewhat trivial issue since I can still generate pdfs even if it is somewhat less convenient, but I would still like to eliminate that inconvenience if possible. 

Thanks in advance.

**Comment by JWock82** [comment]
I generate pdf's by first converting to HTML using the following command at in the last cell of my notebook:

!jupyter nbconvert "Untitled.ipynb" --to=html --TagRemovePreprocessor.remove_input_tags={"hide_input"} --TagRemovePreprocessor.remove_cell_tags={"hide_cell"} --no-prompt

Save your notebook prior to running that cell. It prints the last saved state. Once it's in HTML I can print to pdf by opening it in a web browser. The tag remove preprocessors allow you to skip printing cells or inputs having those tags in your notebook.

Alternatively you can use --to=webpdf, which will convert to HTML and then from HTML to pdf. This option doesn't allow for much in the way of formatting margins though, and it requires installation of a few other packages (pyppeteer and chromium).

**Comment by BaseBeginner** [comment]
Sorry for the late response. But I've followed your instructions, and can now print to webpdf through the menu bar. This simplifies my workflow massively so thanks for that.

Just out of curiosity though, what is the difference, if any, between pdf and webpdf? In terms of output, I mean. Is there a reason why JupyterLab offers both options?

Again, thanks.

**Comment by JWock82** [comment]
I don't know why there's two options for pdf exactly. They produce very different results. I think webpdf is a newer feature. The direct pdf conversion goes through the latex templates, whereas the webpdf conversion goes through the html templates when formatting. I think the webpdf looks cleaner when it's done. I usually just use --to=html and then print the resulting file to pdf from my web browser. The browser gives me more control over the margins and the fit on the page.

**Comment by BaseBeginner** [comment]
Alright. I suppose I'll just be using webpdf from now on.

Thanks for the response. And thanks again for helping me with my issue.
