### ISSUE TITLE
nbconvert [Math Processing Error]

### ISSUE THREAD

**Issue by JWock82** [jupyter/nbconvert#1871]
`nbconvert` produces [Math Processing Error] in some cases where Jupyter Lab renders the Latex just fine.

Steps the reproduce the error:

1. Run the following Latex in a markdown cell:
$\begin{array}{lpwidth{0.25\linewidth} lpwidth{0.5\linewidth} lpwidth{0.25\linewidth}} \small{\textsf{Bar Diameter: }} & \small{d_{b}=6/8 \ in} & \small{\textsf{}} \\ \small{\textsf{Bar Spacing: }} & \small{s=12 \ in} & \small{\textsf{}} \\ \small{\textsf{Vertical Bar Area: }} & \small{A_{s}=\dfrac{0.44 \ in^2}{s}=0.44 \ in²/ft} & \small{\textsf{}} \\ \small{\textsf{Bar Depth: }} & \small{d=18 \ in-2.5 \ in=15.5 \ in} & \small{\textsf{}} \\ \small{\textsf{Compression Zone Depth: }} & \small{a=\dfrac{A_{s} \cdot{}f_{y}}{0.85 \cdot{}f^{\prime}_{c}}=0.647 \ in} & \small{\textsf{}} \\ \small{\textsf{Parme Beta Factor: }} & \small{\beta _{1}=0.85 \textsf{ if } f^{\prime}_{c}\le4000 \ psi \newline\hspace{1cm}\textsf{else } 0.85-0.05 \cdot{}\dfrac{f^{\prime}_{c}-4000 \ psi}{1000 \ psi} \textsf{ if } f^{\prime}_{c}\le8000 \ psi \newline\hspace{1cm}\textsf{else } 0.65\newline\hspace{0.5cm}=0.85} & \small{\textsf{ACI 350-20, Section 10.2.7.3}} \\ \small{\textsf{Neutral Axis Depth: }} & \small{c=\dfrac{a}{\beta _{1}}=0.761 \ in} & \small{\textsf{ACI 350-20, Section 10.2.7.1}} \\ \small{\textsf{Tensile Strain at Failure: }} & \small{\epsilon _{t}=\dfrac{0.003}{c} \cdot{}d-0.003=0.05808} & \small{\textsf{}} \\ \small{\textsf{Strength Reduction Factor: }} & \small{\phi =0.9 \textsf{ if } \epsilon _{t}\ge0.005 \newline\hspace{1cm}\textsf{else } 0.65+\dfrac{0.25}{0.005-\dfrac{f_{y}}{E_{x}}} \cdot{}\left(\epsilon _{t}-\dfrac{f_{y}}{E_{s}}\right) \textsf{ if } \epsilon _{t}>\dfrac{f_{y}}{E_{s}} \newline\hspace{1cm}\textsf{else } 0.65\newline\hspace{0.5cm}=0.9} & \small{\textsf{}} \\ \small{\textsf{Moment Strength of Vertical Bars at Cutoff: }} & \small{\phi M_{n}=\phi \cdot{}A_{s} \cdot{}f_{y} \cdot{}\left(d-\dfrac{a}{2}\right)=30.0 \ kip} & \small{\textsf{}} \\ \end{array}$ 
3. You should see this:
![image](https://user-images.githubusercontent.com/33323539/192794154-2005237e-c421-4e5a-aa9f-02b59e7714fe.png)
3. Now try to convert the notebook to html using the code below in another cell (change the notebook name if necessary):
!jupyter nbconvert "Untitled.ipynb" --to=html
5. Have a look at the HTML file. You should see this:
![image](https://user-images.githubusercontent.com/33323539/192794492-b8081fe1-eaf2-40e2-8a54-61b03ae94cec.png)

**Nbconvert version: 7.0.0**

**Comment by JWock82** [comment]
I figure it out. `nbconvert` does not handle `\newline` properly. I found if I replace `\newline`  with `\\` it does the line break.

**Comment by tuncbkose** [comment]
This seems to me to be a case of MathJax/LaTeX difference, but glad it worked out.
