### ISSUE TITLE
Bibtex execution in pdf exporter

### ISSUE THREAD

**Issue by jcfschulz** [jupyter/nbconvert#193]
I'm currently trying to get the bibtex execution running. While this is included in the pdf exporter, bibtex is not being run.
When I look at the code in  nbconvert/nbconvert/exporters/pdf.py  in line 132 it says `if not rc:` where `rc` is the return value of the latex command execution before, which should always be true if no error occurs. Therefore bibtex is never executed?
Unless I completely don't get this part of the code, I guess the `not` should be removed in lines 132 and 134.
Greetings, Julius

**Comment by takluyver** [comment]
I think you're right. I guess at some point the code was getting the exit code from the subprocess, where 0 means success, but now we've added an abstraction layer that turns that into True/False. Do you want to make a PR?

**Comment by jcfschulz** [comment]
okay, i created a pull request in #194

**Comment by minrk** [comment]
closed by #194
