### ISSUE TITLE
Is it possible to pass additional arguments in to ExecutePreprocessor to execute a notebook?

### ISSUE THREAD

**Issue by YarShev** [jupyter/nbconvert#1933]
Hi there,

Is it possible to pass some parameters in to ExecutePreprocessor to modify (or add additional parameters to) `argv` in kernel.json file?

Thanks in advance!

**Comment by YarShev** [comment]
cc @blink1073

**Comment by blink1073** [comment]
I don't believe it is possible.  What you could do is make a copy of the kernel directory, modify the `argv`, and then pass that as `--ExecutePreprocessor.kernel_name=my_custom_name`.

**Comment by YarShev** [comment]
@blink1073, I do not see that [ExecutePreprocessor](https://nbconvert.readthedocs.io/en/latest/api/preprocessors.html#nbconvert.preprocessors.ExecutePreprocessor) has a parameter `kernel_name`, which I could use. What do you mean exactly by `modify the argv, and then pass that as --ExecutePreprocessor.kernel_name=my_custom_name`?

**Comment by blink1073** [comment]
Here are the docs: https://nbconvert.readthedocs.io/en/latest/execute_api.html?highlight=kernel_name#execution-arguments-traitlets

1. `jupyter kernelspec list`
2. Copy the `python3` directory to `my_custom_name`
3. Edit `my_custom_name/kernel.json` to change the `argv`
4. Run `jupyter nbconvert --to notebook --execute --ExecutePreprocessor.kernel_name=my_custom_name my_notebook.ipynb`

**Comment by blink1073** [comment]
Yes, that should work

**Comment by blink1073** [comment]
You are welcome!
