### ISSUE TITLE
nbconvert --to notebook --output out.ipynb filename incorrect

### ISSUE THREAD

**Issue by ksunden** [jupyter/nbconvert#1970]
Outputs to a file called "out.nbconvert.ipynb" instead of "out.ipynb" as expected.

The expected behavior was the case prior to v7.3, likely related to #1967, though not super obvious how this behavior emerges, looking at the diff as an outsider to this codebase.
My guess is that it is related to stripping the extension off there.

A similar change does not seem to happen for other conversions, e.g. `md` or `pdf`

Steps to reproduce:

Any ipynb will do, I just made a new, empty, ipynb file and called it "test.ipynb"

```bash
$ ls
test.ipynb
$ jupyter nbconvert --to notebook --output out.ipynb test.ipynb 
[NbConvertApp] Converting notebook test.ipynb to notebook
[NbConvertApp] Writing 617 bytes to out.nbconvert.ipynb
```

This is currently breaking matplotlib's tests, which rely on the expected output path being valid.

**Comment by ksunden** [comment]
Gentle ping since our (for me, matplotlib, but others who have linked PRs here as well) current workaround is to avoid the versions with the change, and the new release today means we have to update that.

If this is intended behavior that will be kept going forward, knowing that would be appreciated so we can implement a more complete workaround.

**Comment by tuncbkose** [comment]
This looks like unintended behavior to me, so I made a PR to restore old behavior. Hopefully a maintainer can take a look at it soon.
