### ISSUE TITLE
Cannot convert equally named notebooks in different directories in-place

### ISSUE THREAD

**Issue by Felerius** [jupyter/nbconvert#1979]
This command used to work before 7.3.0:

```bash
jupyter nbconvert --clear-output --inplace a/nb.ipynb b/nb.ipynb
```

but now reports the following error:

```
ValueError: Conversion would override an already generated output. This is probably due to --output or output_base configuration leading to non-unique output names. Output notebook names were: ['nb', 'nb']
```

The check that is failing was introduced in #1967. As a workaround running the command for each notebook individually works, but it would be nice if this could work as it did before.

**Comment by tuncbkose** [comment]
Can you check if #1974 fixes this?

**Comment by Felerius** [comment]
> Can you check if #1974 fixes this?

Still produces the same error for my example.

**Comment by tuncbkose** [comment]
Thanks for checking. I'll try to edit #1974 to fix this as well.
