### ISSUE TITLE
Dev Install not working

### ISSUE THREAD

**Issue by nahanoo** [jupyter/nbconvert#1982]
The instructions for building the pip package from source are not working for me.
`pip install -e .` is looking for a `setup.py` file which can not be found.

I have no experience with Hatch so it would be nice to have correct building instructions.

As always, thanks for developing.

**Comment by tuncbkose** [comment]
`pip install -e .` on a newly cloned repo is working fine for me.

**Comment by maartenbreddels** [comment]
What version of pip do you both have? My guess is that upgrading pip will fix this.

**Comment by nahanoo** [comment]
I was on `pip 21.2.4`. You were right, upgrading pip did fix this. I should have suspected that myself. Anyways, thanks for the help.

**Comment by maartenbreddels** [comment]
I have been there myself many times, that's why I thought about it :)
