### ISSUE TITLE
support for pandoc > 3.0.0

### ISSUE THREAD

**Issue by MarDiehl** [jupyter/nbconvert#1996]
pandoc 3.0.0 has been released early 2023:

https://pandoc.org/releases.html

I get a warning about a non-supported version, but for my use case (converting jupyter notebooks for sphinx via https://nbsphinx.readthedocs.io) I did not encounter any issues yet.

**Comment by MZuhairKhan** [comment]
Running nbconvert from a python script does cause issues. I had to downgrade to pandoc 2.19 to get it to work properly. However, the command line conversion did work with pandoc 3.0.0.

**Comment by tuncbkose** [comment]
@MZuhairKhan Can you provide an example?

**Comment by MZuhairKhan** [comment]
@tuncbkose Sorry, I have already downgraded to pandoc 2.19. However, it is easy to test:
1) Upgrade to the latest pandoc.
2) jupyter nbconvert --to pdf notebook.ipynb
3) Output:
nbconvert does not support pandoc >= 3.0.0
However, notebook.pdf is produced anyway.
N.b. My notebook.pdf only had text.

**Comment by tuncbkose** [comment]
Okay, so it is just a warning, which I can reproduce. If someone encounters an error, feel free to ping me.
