### ISSUE TITLE
Markdown renders differently in lab and nbconvert's html output

### ISSUE THREAD

**Issue by divyansshhh** [jupyter/nbconvert#2009]
Consider the following Markdown - 
```markdown
The following text contains a list:

- This
list doesn't
- format properly
- in
nbconvert
```

When we render it in lab, it renders as - 
![image](https://github.com/jupyter/nbconvert/assets/30082866/4d4d5e63-9866-4454-a225-830f3a81f029)

When converting it to html using nbconvert, it renders as - 
![image](https://github.com/jupyter/nbconvert/assets/30082866/c3d1df0e-732d-43ad-ad36-9fb33a095d3e)

I tried the same snippet in github's markdown editor and the output was the same as the output from lab.

**Comment by krassowski** [comment]
This appears to be an issue in the default markdown parser, mistune v2. nbconvert [7.6](https://github.com/jupyter/nbconvert/releases/tag/v7.6.0) released two weeks ago supports mistune 3 which seems to parse it well enough (and pandoc does even better job):

Mistune 2:

```html
<p>The following text contains a list:</p>
<ul>
<li>This</li>
</ul>
<p>list doesn't</p>
<ul>
<li>format properly</li>
<li>in</li>
</ul>
<p>nbconvert</p>
```

Mistune 3:

```html
<p>The following text contains a list:</p>
<ul>
<li>This
list doesn't</li>
<li>format properly</li>
<li>in
nbconvert</li>
</ul>
```

Pandoc:

```html
<p>The following text contains a list:</p>
<ul>
<li>This list doesn’t</li>
<li>format properly</li>
<li>in nbconvert</li>
</ul>
```

Does updating to mistune 3/installing pandoc solves the issue?

**Comment by divyansshhh** [comment]
Yes upgrading to mistune 3 fixes this issue for us. Thanks!
