### ISSUE TITLE
nbconvert export omits markdown cells

### ISSUE THREAD

**Issue by janr85** [jupyter/nbconvert#2017]
I have noticed that newer _base_ and _minimal_ docker images on dockerhub do not export markdown cells to asciidoc format. It seems that this problem has been introduced at some point of version 7.5.0.

For further details, please have a look at this [stackoverflow question](https://stackoverflow.com/questions/76580643/jupyter-notebook-export-omits-markdown).

**Comment by janpfeifer** [comment]
Similar here, when running `jupyter nbconvert --execute -to asciidoc some_notebook.ipynb` and the notebook outputs even the most trivial `text/markdown` MIME data  (just a simple "hello world" message), nbconvert will output empty instead.

Curiously this is part of a [test for GoNB, a Go Kernel](https://github.com/janpfeifer/gonb/blob/main/examples/tests/gonbui.ipynb), and it used to work just a few weeks ago. All that changed in between were potentially versions of Jupyter and nbconvert.

JupyterLab version: 4.0.6
jupyter nbconvert --version: 7.8.0
jupyter server --version: 2.7.3

**Comment by janpfeifer** [comment]
I should also mention that if using `nbconvert --to=html` it works just fine, it will convert the output of markdown. It's an issue only with `--to=asciidoc`.

**Comment by saf-dmitry** [comment]
By converting to Asciidoc nbconvert outputs following error messages for each Markdown cell:

```
Unknown option --atx-headers.
Try pandoc --help for more information.
```

It seems, the problem is that nbconvert uses obsolete pandoc option `--atx-headers` instead of `--markdown-headings=atx`.

**Comment by thomasjm** [comment]
Hello, would someone like to try the fix here? https://github.com/jupyter/nbconvert/pull/2152

**Comment by janpfeifer** [comment]
> Hello, would someone like to try the fix here? #2152

Many thanks for the fix!!

I'd be happy to try it for GoNB test. Is it part of a pip package already ?

**Comment by thomasjm** [comment]
No, I'm not a maintainer here. You'll have to use my branch.

I've tested it myself now and it seems to work.

If you happen to use Nix, you can build a working `nbconvert` with this patch: https://github.com/codedownio/nixpkgs/commit/7968f56301f6fe8448bd4b2643571faa71fde741

**Comment by jeffmelville** [comment]
I'm having this issue as well. I haven't tried the fix verbatim, but modifying the pandoc arguments to ``--markdown-headings=atx`` is working as a temporary workaround. +1 for getting this fix in
