### ISSUE TITLE
7.9.0 release is missing tests

### ISSUE THREAD

**Issue by mgorny** [jupyter/nbconvert#2052]
The 7.9.0 release has removed tests from sdist archives. This makes it impossible to use these archives for packaging since packagers rely on the ability to run tests. Furthermore, since it relies on generated data is present in the archive but not in the git repository, GitHub archives are incredibly painful to use an alternative.

**Comment by blink1073** [comment]
Thanks for the heads up!  #2053

**Comment by mgorny** [comment]
Thank you!
