### ISSUE TITLE
Allow pre-fetching of css files?

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [jupyter/nbconvert#2093]
As far as I can tell, nbconvert cannot be built on non-internet connected systems, such as in an automated build system on an airgapped node. In hatch_build.py, it tries to download each css file (on at least one system I'm working on, the `urlopen(url).read()` function hangs indefinitely) _before_ checking for an existing copy. Would it be possible to check for the destination file before trying to download it? In my use case (installing through Spack), it's fine to stage the files in advance so they're available at install time.

**Comment by blink1073** [comment]
Hi @AlexanderRichert-NOAA, that sounds reasonable, would you be able to submit a PR?

**Comment by AlexanderRichert-NOAA** [comment]
@blink1073 yes, please see #2095
