### ISSUE TITLE
Rendering to HTML generates an error in bleach.clean

### ISSUE THREAD

**Issue by AMNakamura** [jupyter/nbconvert#2097]
When using nbconvert to render to html (e.g., jupyter nbconvert myfile.ipynb --to html, I get the following TypeError: clean() got an unexpected keyword argument 'css_sanitizer'.

**Comment by blink1073** [comment]
Hi @AMNakamura, can you please give the output of `pip list`?

**Comment by AMNakamura** [comment]
Thank you so much for getting back to me so quickly, Steven. I really appreciate all of the incredible work of you and your team. Here's my pip list. 
 
Kindest regards, 
 
Ann  
 
Package                       Version
 
----------------------------- ------------
 
anaconda-anon-usage           0.4.3
 
anaconda-client               1.12.2
 
anaconda-cloud-auth           0.1.4
 
anaconda-navigator            2.5.2
 
anyio                         3.5.0
 
argon2-cffi                   21.3.0
 
argon2-cffi-bindings          21.2.0
 
asn1crypto                    1.5.1
 
asttokens                     2.0.5
 
async-lru                     2.0.4
 
attrs                         23.1.0
 
Babel                         2.11.0
 
backcall                      0.2.0
 
backports.functools-lru-cache 1.6.4
 
backports.tempfile            1.0
 
backports.weakref             1.0.post1
 
beautifulsoup4                4.12.2
 
bleach                        4.1.0
 
boltons                       23.0.0
 
Bottleneck                    1.3.5
 
Brotli                        1.0.9
 
CacheControl                  0.13.1
 
certifi                       2023.11.17
 
cffi                          1.16.0
 
chardet                       4.0.0
 
charset-normalizer            2.0.4
 
clean-text                    0.4.0
 
click                         8.1.3
 
clyent                        1.2.2
 
colorama                      0.4.6
 
comm                          0.1.2
 
commonmark                    0.9.1
 
conda                         23.5.0
 
conda-build                   3.25.0
 
conda-content-trust           0.2.0
 
conda_index                   0.3.0
 
conda-package-handling        2.2.0
 
conda_package_streaming       0.9.0
 
conda-repo-cli                1.0.75
 
conda-token                   0.4.0
 
conda-verify                  3.4.2
 
contourpy                     1.1.0
 
cryptography                  41.0.7
 
cycler                        0.11.0
 
cyclonedx-python-lib          2.7.1
 
debugpy                       1.6.7
 
decorator                     5.1.1
 
defusedxml                    0.7.1
 
emoji                         1.7.0
 
et-xmlfile                    1.1.0
 
exceptiongroup                1.0.4
 
executing                     0.8.3
 
fastjsonschema                2.16.2
 
filelock                      3.12.2
 
fonttools                     4.40.0
 
ftfy                          6.1.3
 
future                        0.18.3
 
glob2                         0.7
 
great-tables                  0.1.4
 
html5lib                      1.1
 
htmltools                     0.5.1
 
idna                          3.4
 
importlib-metadata            7.0.1
 
importlib-resources           5.12.0
 
ipykernel                     6.25.0
 
ipython                       8.15.0
 
jaraco.classes                3.2.1
 
jedi                          0.18.1
 
Jinja2                        3.1.2
 
json5                         0.9.6
 
jsonpatch                     1.32
 
jsonpointer                   2.1
 
jsonschema                    4.19.2
 
jsonschema-specifications     2023.7.1
 
jupyter_client                8.6.0
 
jupyter_core                  5.5.0
 
jupyter-events                0.8.0
 
jupyter-lsp                   2.2.0
 
jupyter_server                2.10.0
 
jupyter_server_terminals      0.4.4
 
jupyterlab                    4.0.8
 
jupyterlab-pygments           0.1.2
 
jupyterlab_server             2.25.1
 
keyring                       23.13.1
 
kiwisolver                    1.4.4
 
libarchive-c                  2.9
 
markdown-it-py                3.0.0
 
MarkupSafe                    2.1.3
 
matplotlib                    3.7.1
 
matplotlib-inline             0.1.6
 
mdurl                         0.1.2
 
menuinst                      1.4.19
 
metakernel                    0.30.1
 
mistune                       0.8.4
 
mkl-fft                       1.3.8
 
mkl-random                    1.2.4
 
mkl-service                   2.4.0
 
more-itertools                10.1.0
 
navigator-updater             0.3.0
 
nbclient                      0.8.0
 
nbconvert                     5.6.1
 
nbformat                      5.9.0
 
nest-asyncio                  1.5.6
 
networkx                      3.1
 
notebook                      7.0.6
 
notebook_shim                 0.2.3
 
numexpr                       2.8.7
 
numpy                         1.25.0
 
openpyxl                      3.1.2
 
oscrypto                      1.3.0
 
overrides                     7.4.0
 
packageurl-python             0.11.1
 
packaging                     23.1
 
pandas                        1.5.3
 
pandocfilters                 1.5.0
 
parso                         0.8.3
 
pathlib                       1.0.1
 
patsy                         0.5.3
 
pexpect                       4.8.0
 
pickleshare                   0.7.5
 
Pillow                        10.0.1
 
pip                           23.3.1
 
pip-api                       0.0.30
 
pip_audit                     2.5.6
 
pip-requirements-parser       32.0.1
 
pkce                          1.0.3
 
pkginfo                       1.9.6
 
platformdirs                  3.10.0
 
plotly                        5.15.0
 
pluggy                        1.0.0
 
ply                           3.11
 
prometheus-client             0.14.1
 
prompt-toolkit                3.0.43
 
psutil                        5.9.0
 
ptyprocess                    0.7.0
 
pure-eval                     0.2.2
 
pyarrow                       10.0.1
 
pycosat                       0.6.6
 
pycparser                     2.21
 
pycryptodomex                 3.18.0
 
pydantic                      1.10.12
 
Pygments                      2.15.1
 
PyJWT                         2.4.0
 
pyOpenSSL                     23.2.0
 
pyparsing                     3.1.0
 
PyQt5                         5.15.10
 
PyQt5-sip                     12.13.0
 
PySocks                       1.7.1
 
python-dateutil               2.8.2
 
python-dotenv                 0.21.0
 
python-json-logger            2.0.7
 
pytz                          2023.3.post1
 
pywin32                       305.1
 
pywin32-ctypes                0.2.0
 
pywinpty                      2.0.10
 
PyYAML                        6.0.1
 
pyzmq                         25.1.0
 
QtPy                          2.4.1
 
referencing                   0.30.2
 
requests                      2.31.0
 
requests-toolbelt             1.0.0
 
rfc3339-validator             0.1.4
 
rfc3986-validator             0.1.1
 
rich                          13.4.2
 
rpds-py                       0.10.6
 
ruamel.yaml                   0.17.21
 
ruamel.yaml.clib              0.2.6
 
ruptures                      1.1.9
 
SAS-kernel                    2.4.13
 
saspy                         5.4.0
 
scipy                         1.11.1
 
seaborn                       0.12.2
 
semver                        2.13.0
 
Send2Trash                    1.8.2
 
session-info                  1.0.0
 
setuptools                    68.2.2
 
sip                           6.7.12
 
six                           1.16.0
 
sniffio                       1.2.0
 
snowflake-connector-python    3.0.3
 
soupsieve                     2.5
 
stack-data                    0.2.0
 
statsmodels                   0.14.0
 
stdlib-list                   0.10.0
 
tableone                      0.8.0
 
tabulate                      0.9.0
 
tenacity                      8.2.2
 
terminado                     0.17.1
 
testpath                      0.6.0
 
tinycss2                      1.2.1
 
tomli                         2.0.1
 
toolz                         0.12.0
 
tornado                       6.3.3
 
tqdm                          4.65.0
 
traitlets                     5.7.1
 
typing_extensions             4.7.1
 
tzdata                        2023.3
 
ujson                         5.4.0
 
Unidecode                     1.3.8
 
urllib3                       1.26.18
 
wcwidth                       0.2.13
 
webcolors                     1.13
 
webencodings                  0.5.1
 
websocket-client              0.58.0
 
wheel                         0.41.2
 
win-inet-pton                 1.1.0
 
zipp                          3.17.0
 
zstandard                     0.19.0

**Comment by blink1073** [comment]
I'd suggest updating your version of bleach: `pip install  --no-deps bleach==6.1.0`

**Comment by AMNakamura** [comment]
Thank you so much. Yes, that fixed the issue. 
 
Kind regards, 
 
Ann

**Comment by blink1073** [comment]
Glad to hear it!
