### ISSUE TITLE
jupyter/nbconvert/templates only has latex

### ISSUE THREAD

**Issue by komal98** [jupyter/nbconvert#2101]
$ ls <sys-prefix>/share/jupyter/nbconvert/templates
only gives latex other templates are missing. 

I have tried uninstalling and installing nbconvert, cloning from git. I have macOS Sonoma, Python 3.11 and Jupyter Lab jupyterlab       : 4.0.10 and latest nbconvert version 7.14.2

Any idea how I can install other templates?

**Comment by komal98** [comment]
@blink1073 
<> ~ % python3 --version
Python 3.11.7
<> ~ % ls  <sys>/Library/Python/3.11/share/jupyter/nbconvert/templates
latex

For installing nbconvert I used pip3 install nbconvert

**Comment by blink1073** [comment]
Hi @komal98, it isn't recommended to use the brew python as your user python: https://justinmayer.com/posts/homebrew-python-is-not-for-you/.

I'd suggest either using a Python from [python.org](https://www.python.org/downloads/macos/), or if you want to try sticking with brew:

```bash
pip3 uninstall -y nbconvert
pip3 install -v nbconvert
```

And paste the output here.

**Comment by komal98** [comment]
@blink1073 I uninstalled the brew version of Python and used Python from python.org and it worked!!! Thank you so much.

**Comment by blink1073** [comment]
Great!  No problem
