### ISSUE TITLE
Compatibility with pandoc version on ReadTheDocs

### ISSUE THREAD

**Issue by adamjstewart** [jupyter/nbconvert#2126]
The newest version of Ubuntu available on ReadTheDocs is Ubuntu 22.04, which comes with pandoc 2.9.2.1. However, nbconvert does not support this version of pandoc, resulting in the following (harmless) warning:
```
/home/docs/checkouts/readthedocs.org/user_builds/torchgeo/envs/1903/lib/python3.12/site-packages/nbsphinx/__init__.py:1058: RuntimeWarning: You are using an unsupported version of pandoc (2.9.2.1).
Your version must be at least (2.14.2) but less than (4.0.0).
Refer to https://pandoc.org/installing.html.
Continuing with doubts...
  nbconvert.utils.pandoc.check_pandoc_version()
```
It looks like the lower bound was changed in #1997, but I don't actually see any changes that require newer versions of pandoc. Is it possible to re-enable support for older versions of pandoc? At least until a newer version of pandoc becomes available on Ubuntu?

@tuncbkose @blink1073

**Comment by blink1073** [comment]
We changed it to reflect what we are actually testing against.  It could be that we are compatible with earlier versions, but I think the warning is appropriate.

**Comment by adamjstewart** [comment]
Would it be possible to test against multiple versions of pandoc? In [TorchGeo](https://github.com/microsoft/torchgeo/blob/main/.github/workflows/tests.yaml), we test against both the newest and oldest supported version of our dependencies.

**Comment by blink1073** [comment]
We do test the min version explicitly, I opened https://github.com/jupyter/nbconvert/pull/2128 to try our test suite against 2.9.2.
