### ISSUE TITLE
Error: `403 : Forbidden  The error was:  '_xsrf' argument missing from GET` on JupyterHub >= 4.1

### ISSUE THREAD

**Issue by jrdnbradford** [jupyter/nbconvert#2132]
### Problem

`JupyterHub>=4.1` has increased strictness and requires XSRF tokens be passed in `GET` requests. On these versions of JupyterHub users receive  `403 : Forbidden  The error was:  '_xsrf' argument missing from GET`  when using `nbconvert`, at least `7.14.0`.

See https://github.com/jupyterhub/nbgitpuller/issues/344 for a similar issue after these updates, it includes the full hub and lab environments.

### Steps to Reproduce

1. On a hub >= 4.1, go to `File` -> `Save and Export Notebook As...`
2. Select any option

**Comment by krassowski** [comment]
Can you test JupyterHub 4.1.4 which was just released? It could have been fixed by https://github.com/jupyterhub/jupyterhub/pull/4759.

**Comment by jrdnbradford** [comment]
@krassowski confirming that `jupyterhub` `4.1.4` resolved this issue for `the-littlest-jupyterhub` `1.0.0`. I can test a K8s-based hub later and report back.

**Comment by jrdnbradford** [comment]
@krassowski as far as I can tell, `jupyterhub` `4.1.4` resolves this. See my comments in https://github.com/jupyterlab/jupyterlab/issues/16040. Thanks!
