### ISSUE TITLE
textcomp issue when using --to pdf

### ISSUE THREAD

**Issue by amueller** [jupyter/nbconvert#220]
I have trouble rendering this in a markup:
```
Much `tex` such `'markup'`
```
It will result in this tex code:
```
    Much \texttt{tex} such
\texttt{\textquotesingle{}markup\textquotesingle{}}
```
which will lead to the latex error
```
Untitled.tex:251: Undefined control sequence \textquotesingle.
Untitled.tex:251: leading text: ...extquotesingle{}markup\textquotesingle{}}
```
It seems the ``textcomp`` package is not included.
Adding ``\usepackage{textcomp}`` at the start of the file solves the problem.

**Comment by minrk** [comment]
Makes sense. PR?

**Comment by amueller** [comment]
I was just wondering if there was something odd with my setup, as I would have expected that problem to show up earlier, if it was a missing ``\usepackage``.

**Comment by amueller** [comment]
Actually, it's only inside backticks, so maybe that doesn't happen that often.
