### ISSUE TITLE
nbconvert to notebook doesn't respect newline at the end of file

### ISSUE THREAD

**Issue by akhmerov** [jupyter/nbconvert#236]
To reproduce:

1. create a notebook `test.ipynb`
2. `jupyter nbconvert test.ipynb --to notebook --out test2.ipynb`
3. diff test.ipynb test2.ipynb

Observed output for me:
```bash
34c34
< }
---
> }
\ No newline at end of file
```

Desired behavior: both notebooks should be identical. I've encountered this setting up filters for git, and there such things obviously matter. Alternatively, all notebooks produced by `nbconvert` should respect unix file format and end with a newline.

Version: nbconvert 4.1.0

**Comment by takluyver** [comment]
Fixed in #213, will be in 4.2. :-)
