### ISSUE TITLE
Editing documentation: Configuration options

### ISSUE THREAD

**Issue by karldw** [jupyter/nbconvert#237]
I'd like to add a little to the documentation, particularly https://nbconvert.readthedocs.org/en/latest/config_options.html, but I can't find the source file.  The Readthedocs page points here: https://github.com/jupyter/nbconvert/blob/master/docs/source/config_options.rst

I'm sure I'm missing something dumb, but could you point me toward the right documentation file?  Thanks!

**Comment by takluyver** [comment]
The config options docs are autogenerated from config options throughout the code - they look like this:
https://github.com/jupyter/nbconvert/blob/1df9ca1e112d49773f416c629c0918598e040415/nbconvert/preprocessors/execute.py#L41

The script that generates the document is here:
https://github.com/jupyter/nbconvert/blob/master/docs/autogen_config.py

**Comment by karldw** [comment]
Thank you!
