### ISSUE TITLE
16 ANSI colors?

### ISSUE THREAD

**Issue by mgeier** [jupyter/nbconvert#245]
In #225 I'm proposing to change the LaTeX rendering of a Python exception from

![LaTeX rendering before](https://cloud.githubusercontent.com/assets/705404/13032940/02371276-d306-11e5-81a6-221618246301.png)

to

![LaTeX rendering after](https://cloud.githubusercontent.com/assets/705404/13032943/0de8b912-d306-11e5-9ae6-2510bc58b58d.png)

... which I think is quite an improvement. But I was wondering if we should go a step further ...

ANSI escape sequences allow 16 "default" colors, which are basically 8 distinct colors and then the same 8 colors in a brighter version. Typically, the brighter version is used for bold text, but it can also be used independently (and as a background color).

The Jupyter Notebook, however, only supports 8 default colors and maps the other 8 colors back to the first 8.
Does anyone have an idea why this is done?

What about re-enabling all 16 color but then *choosing nice ones*?

The exact color values are implementation-defined, their names are: Black Red Green Yellow Blue Magenta Cyan White.
The bright version of "Black" is sometimes called "Darkgray", the "normal" (= dark) version of "Yellow" is sometimes called "Brown", the "normal" (= dark) version of "White" is sometimes called "Gray".
See https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

The currently used CSS classes are ansiblack ansired ansigreen ansiyellow ansiblue ansipurple ansicyan ansigray, which seem to be the "official" names, except "gray" is used instead of "white".
We could just add "bright" versions of those and then choose reasonable default colors in the default CSS.
For LaTeX, we can then probably just use the same color names and the same color values.

Or is this a bad idea?

**Comment by takluyver** [comment]
Re only defining 8 colours: I would guess that it was a 'good enough' kind of thing. i.e. once ANSI colour translation was basically working, other things became higher priority and it got forgotten about. Thanks for coming back to this stuff!

**Comment by mgeier** [comment]
Also, the ANSI color codes 90–97 and 100–107 should be implemented, see https://github.com/jupyter/nbconvert/issues/228#issuecomment-188828027.

**Comment by mgeier** [comment]
This has been implemented in #259, closing.
