### ISSUE TITLE
[Migration from ipython nbconvert to jupyter nbconvert] - 

### ISSUE THREAD

**Issue by sieben** [jupyter/nbconvert#247]
While try to migrate from ipython nbconvert to jupyter nbconvert I've stumble upon the following problem:
AttributeError: 'InteractiveShell' object has no attribute 'input_transformer_manager'

As a reference, here is the complete log of my build : 
https://travis-ci.org/sieben/makesense/builds/110089905

here is the diff : 
https://github.com/sieben/makesense/pull/26/files

**Comment by takluyver** [comment]
I think you need to install a newer version of IPython. Nbconvert should probably have an explicit dependency on that.

**Comment by michaelpacer** [comment]
@sieben Is this still an issue with the version of IPython that you installed after you updated? Or can I close this issue?

**Comment by sieben** [comment]
I think you can close it. Worst case scenario, I will reopen it with the most recent version of nbconvert.
