### ISSUE TITLE
Allow configuration of markdown2html filter

### ISSUE THREAD

**Issue by TomAugspurger** [jupyter/nbconvert#248]
[Here](https://github.com/jupyter/nbconvert/blob/241ad6468bf89418460dcf698a3a59a8d2c06cf1/nbconvert/filters/markdown.py#L69), the default markdown to HTML filter is assigned to be the mistune filter. I'm trying to use pandoc's new image attribute syntax described [here](https://github.com/jgm/pandoc/commit/244cd5644b44f43722530379138bd7bb9cbace9b), which mistune apparently doesn't support.

Is it possible to configure the filter to be used? By manually setting the filter to the pandoc one, I get the expected result.

Example notebook [here](https://gist.github.com/TomAugspurger/145e9baf71d7f1aa55c1), and requires at least pandoc 1.16 or greater.

**Comment by takluyver** [comment]
There's a [config option](http://nbconvert.readthedocs.org/en/latest/config_options.html) `TemplateExporter.filters`. Configuring that as `{'markdown2html': 'nbconvert.filters.markdown.markdown2html_pandoc'}` should do it.

**Comment by TomAugspurger** [comment]
Ah, yes. I thought I tried that, but looking back now I set the key to `"foo"` and not `'markdown2html'` :flushed: 

Is there a way to specify that at the command line? Or must it be done in the config file? I haven't looked, but in my experimenting it seems like you can't specify dict-like values at the command line.

Leave this open as a doc issue? This could be a good example for the configuration section.

**Comment by takluyver** [comment]
I think you can specify dictionaries at the command line with the right amount of quoting and escaping, but it's definitely fiddly.

**Comment by TomAugspurger** [comment]
That would be traitlets doing the actual parsing of command line string to object? I'll do some digging.

**Comment by TomAugspurger** [comment]
Very fiddly indeed

```bash
jupyter nbconvert --to=html image-attrs.ipynb \
    --TemplateExporter.filters=\{\'markdown2html\':\'nbconvert.filters.markdown.markdown2html_pandoc\'\}
```

I'll leave it up to you whether this would make a good example to include in the docs, or whether you'd rather just steer people to using config files. I could see this being included in, say, a Makefile where you want all the configuration in one place but you're not typing it out by hand.

**Comment by takluyver** [comment]
Is it any easier if you surround it in double quotes? Yes, it's traitlets.config that parses it.

**Comment by TomAugspurger** [comment]
It is, thanks.

```bash
jupyter nbconvert --to=html image-attrs.ipynb \
    --TemplateExporter.filters="{'markdown2html': 'nbconvert.filters.markdown.markdown2html_pandoc'}"
```

I could have sworn that was the first thing I tried, although perhaps I swapped the single and double quotes, which the shell would have eaten.

**Comment by takluyver** [comment]
Great. I'm going to close this for now, because I can't think off the top of my head where to put it in the docs. But if you can find a place where you think it would fit, PRs welcome.
