### ISSUE TITLE
how to change pdf title

### ISSUE THREAD

**Issue by randy3k** [jupyter/nbconvert#249]
Besides changing the name of the ipynb file, is there any way to change the title of the saved pdf?

I know that I could first convert the file to .tex and compile the latex file by myself. But this is not what I want. I am looking for an automatic solution.

**Comment by Carreau** [comment]
There is no (simple) automatic solution. 
You need a custom conversion pipeline. 

The simple way is to use a preprocessor. append it to the list of preprocessor add change `resource['metadata']['name']` to the title you like.

**Comment by michaelpacer** [comment]
Now there is a way for you to do this: use the --output flag 

For example:

```bash
jupyter nbconvert mynotebookname.ipynb --to pdf --output yourpdftitle.pdf
```

**Comment by liushapku** [comment]
@randy3k, when you mentioned pdf title, is it the title in the first page of the pdf, not the filename of the pdf as mentioned by @mpacer? Did you get any way of doing this?

**Comment by randy3k** [comment]
@liushapku yes, it is what I meant. Not sure why @mpacer closed it. I had to convert it to `.tex` and fixed it myself.

**Comment by mpacer** [comment]
sorry! Misunderstood!

**Comment by liushapku** [comment]
@randy3k I have the same need. Currently, I use the API and call `exporter.from_notebook_node(nb, resources={'metadata': {'name': title}})` to achieve this. An alternative way is to call `preprocessor.preprocess` and pass the resource as the second argument. Hope this feature can be added to the cmdline tool.

**Comment by mpacer** [comment]
#672 will make it easier if you set the title metadata in the notebook itself (meaning that `exporter.from_notebook_node(nb, resources={})` would work if you had already set the notebook metadata.title field.

**Comment by agarnitin86** [comment]
Hi,
I am new to this. Can someone explain in a bit detail, how to convert ipynb to .tex to pdf file with custom title. I an using jupyter for creating ipynb files.

**Comment by JacquotLeHaricot** [comment]
@agarnitin86 I know my answer comes late, but for the others that would have had the same question :
- File > Export Notebook As... > Latex
- you will get a zip file ; extract it somewhere
- open the .tex file inside : you will see something like 
`% Document parameters
    \title{TITLE_YOU_WANT_TO_CHANGE}`
- edit TITLE_YOU_WANT_TO_CHANGE to the title of your choice

**Comment by whitstd** [comment]
I used the following commands in a Makefile (Ubuntu):

```
notebook:
	cp $(file).ipynb '$(title).ipynb'
	jupyter nbconvert '$(title).ipynb' --to=pdf --output=$(file)
	rm '$(title).ipynb'
```

Then call it with:
```
make notebook file=yourfile title="Your Title"
```

Basically, copy the file you want to re-title to a file with the name of the title. Convert it, then delete the copied notebook. You can use quotes around the filename if you need to add spaces.

**Comment by t-makaro** [comment]
#672 Defines a way for this to be set. 

From Jupyter notebook: ```Edit -> Edit Notebook Metadata``` then add a new field like:
```json
"title":"This is the new title",
```

Tagging this as documentation.

**Comment by buergi** [comment]
@t-makaro's solution works perfectly, an UI option for setting the title would be great, but apart from that this issue could be closed I guess.

**Comment by MSeal** [comment]
:)

**Comment by jgrocha** [comment]
> #672 Defines a way for this to be set.
> 
> From Jupyter notebook: `Edit -> Edit Notebook Metadata` then add a new field like:
> 
> ```json
> "title":"This is the new title",
> ```
> 
> Tagging this as documentation.

Good point @t-makaro. Looking into the [code](https://raw.githubusercontent.com/jupyter/nbconvert/master/share/jupyter/nbconvert/templates/latex/base.tex.j2), I also found out how to change the author:

```json
{
  "kernelspec": {
  },
  "language_info": {
  },
  "title": "It's a woodpecker from space",
  "authors": [
    { "name": "Jorge Gustavo Rocha"  },
    { "name": "Matilde Rocha" }
  ]
}
```

**Comment by J-Guby** [comment]
I use this trick.

!jupyter nbconvert --output-dir='./Output' --to pdf --no-input defaultname.ipynb
# The pdf will be called defaultname.pdf

individualname = 'better'
import os
os.rename('Output/defaultname.pdf', f'Output/{individualname }.pdf')
# Now the pdf will be called better.pdf

**Comment by msr8** [comment]
> #672 Defines a way for this to be set.
> 
> From Jupyter notebook: `Edit -> Edit Notebook Metadata` then add a new field like:
> 
> ```json
> "title":"This is the new title",
> ```
> 
> Tagging this as documentation.

Cant find this option in jupyter lab, any solutions?

**Comment by ejjunju** [comment]
i have added the suggested solution to my Notebook metadata but when i export html there is still no title!

**Comment by nckz** [comment]
Based on this discussion and my own needs for modifying the latex output, I've generated a module [jupyter-pdf-report](https://github.com/nckz/jupyter-pdf-report) for creating "no-code" reports from Jupyter notebooks.  The purpose is to create a professional data-report that has a customizable 'title', 'author', 'date', 'header' and 'footer'.  -hopefully others find it useful.

**Comment by varunkas** [comment]
> i have added the suggested solution to my Notebook metadata but when i export html there is still no title!

I have the same problem!
