### ISSUE TITLE
Some characters (#,%,>) cause errors when converting R notebook to LaTeX/pdf  

### ISSUE THREAD

**Issue by dandawg** [jupyter/nbconvert#254]
I have recreated my issue in simple form. Following, is a summary of the problem and solution. My two "fixes" were not ideal, and I'm wondering if this can be fixed at the nbconvert code level. 

First, I open a Jupyter notebook running the R kernel. Then, I define the following data frame (note the symbols #,%, and >): 

```
desc <- data.frame(variable=c("school",
                              "apps",
                              "grad",
                              "top"),
                   description=c("school name",
                                 "# of applications",
                                 "% graduate","school rank > 100"))
desc
```

Shift+Enter outputs the table: 

```
    variable    description
1   school      school name
2   apps        # of applications
3   grad        % graduate
4   top         school rank > 100
```

I save my notebook, but when I try to convert it to pdf, I get errors because of the special symbols in the table (#,%). 

```
>ipython nbconvert --to pdf simple_R_example.ipynb
...
! You can't use `macro parameter character #' in restricted horizontal mode.
<recently read> ##

l.242   2 & apps & #
                    of applications\\
?
! Emergency stop.
```

We see that the "#" throws a latex error. Another error results if we remove it; this one with the "%".  
My possible solutions were: 
1) remove the "#" and "%" from the data frame 
2) Convert the notebook to latex and use a latex editor to debug: 
`ipython nbconvert --to latex <my file>`
In the corresponding .tex file the output table is defined as 

```
    \begin{tabular}{r|ll}
  & variable & description\\
\hline
    1 & school & school name\\
    2 & apps & # of applications\\
    3 & grad & % graduate\\
    4 & top & school rank > 100\\
\end{tabular}
```

Commenting out the special characters with a "\", and then running pdflatex to produce a pdf gets rid of the errors (I replaced # with # and % with \%), and a pdf is created; however, the ">" is still an issue because it is replaced in the output pdf by an upside down question mark. 

Searching around, I found this post
http://tex.stackexchange.com/questions/2369/why-do-the-less-than-symbol-and-the-greater-than-symbol-appear-wrong-as

that says that adding a package to the latex code fixes the issue with the  ">":
`\usepackage[T1]{fontenc}`

Adding the package makes the ">" show correctly.

**Comment by takluyver** [comment]
I think the first issue will be fixed by IRkernel/repr#23. The second I think is something for nbconvert.

**Comment by laicheeonn** [comment]
I faced the similar problem. Somehow i was able to workaround by putting the array object in print() function to output it instead.

for example, the following will halt the conversion to pdf
x <- c(1, 2, 3) ; x
names( _foo_ )
dim( _foo_)
predict( _foo_ )

Putting these array objects in print() will solve the problem in generating pdf, 
x <- c(1, 2, 3) ;  print(x)
print(names( _foo_ ))
print(dim( _foo_ ))
print(predict( _foo_ ))

**Comment by t-makaro** [comment]
Closing as the upstream issue appears fixed, and own latex template does use fontenc. Please comment asking to reopen if this is still an issue.
