### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by takluyver** [jupyter/nbconvert#26]
Making an issue so it doesn't get forgotten. @jhamrick volunteered on Hackpad to take the lead here, and @jdfreder and I are willing to help.

There's a simple skeleton of docs there, but we should:

- [x] Update stuff (e.g. it's now `jupyter nbconvert` instead of `ipython nbconvert`)
- [x] Flesh out the descriptive info
- [x] Config docs (steal machinery from [jupyter_console](https://github.com/jupyter/jupyter_console/tree/master/docs) to generate these).
- [x] Create API docs
- [x] Get it building on RTD

**Comment by takluyver** [comment]
Started in #31

**Comment by jhamrick** [comment]
Continuing in #32

**Comment by takluyver** [comment]
All the points here are done now, thanks @jhamrick
