### ISSUE TITLE
nbconvert notebook to pdf

### ISSUE THREAD

**Issue by seansmckinley** [jupyter/nbconvert#266]
You guys might have an issue with nbconvert, I am using jupyter 4.06 on Windows x64. I was attempting to convert a notebook (.ipynb) to pdf and running into an error. The error itself was `TypeError: environment can only contain strings`. You can see it  attached. 
![output0](https://cloud.githubusercontent.com/assets/9561322/13618357/8c62aaca-e538-11e5-855a-b17fa1d86536.png)

Knowing this I inserted a `print(env)` to find the culprit, because when I inspected my path, there were no unicode strings. 
```
        shell = (sys.platform == 'win32')
        if shell:
            command = subprocess.list2cmdline(command)
        env = os.environ.copy()
        env['TEXINPUTS'] = os.pathsep.join([self.texinputs, env.get('TEXINPUTS', '')])
        with open(os.devnull, 'rb') as null:
            stdout = subprocess.PIPE if not self.verbose else None
            for index in range(count):
                print(env)
                p = subprocess.Popen(command, stdout=stdout, stdin=null, shell=shell, env=env)
                out, err = p.communicate()
                if p.returncode:
                    if self.verbose:
                        # verbose means I didn't capture stdout with PIPE,
                        # so it's already been displayed and `out` is None.
                        out = u''
                    else:
                        out = out.decode('utf-8', 'replace')
                    log_function(command, out)
                    return False # failure
        return True # success
```
So I altered the code:
```
        shell = (sys.platform == 'win32')
        if shell:
            command = subprocess.list2cmdline(command)
        env = os.environ.copy()
        print(type(self.texinputs))
        env['TEXINPUTS'] = os.pathsep.join([str(self.texinputs), str(env.get('TEXINPUTS', ''))])
        with open(os.devnull, 'rb') as null:
            stdout = subprocess.PIPE if not self.verbose else None
            for index in range(count):
                p = subprocess.Popen(command, stdout=stdout, stdin=null, shell=shell, env=env)
                out, err = p.communicate()
                if p.returncode:
                    if self.verbose:
                        # verbose means I didn't capture stdout with PIPE,
                        # so it's already been displayed and `out` is None.
                        out = u''
                    else:
                        out = out.decode('utf-8', 'replace')
                    log_function(command, out)
                    return False # failure
        return True # success
```

Here is the output now.

![output1](https://cloud.githubusercontent.com/assets/9561322/13617914/ff484a34-e535-11e5-933a-5aaaf0c39b88.png)

Notice that the type of `self.texinputs` is unicode. This will break in `subprocess.Popen()` function. Thank you for your time and sorry if this is a duplicate. Casting it to string is a work-around but probably not the most interoperable solution.

**Comment by Carreau** [comment]
Are you using Python 2 ? Can you try in a Py3  environment also ?

**Comment by seansmckinley** [comment]
I am using Python 2.7, I will create a Python 3.4 environment and test.

**Comment by seansmckinley** [comment]
Issue not reproducible with Python 3.5

**Comment by Carreau** [comment]
> Issue not reproducible with Python 3.5

Ok, great thanks a lot ! 
I know that the `os.environ` + Py2 + Windows can be tricky to get right. 
We'l try to see what we can do !

**Comment by takluyver** [comment]
This should be fixed in master by #165, but there isn't a release including that fix yet.

**Comment by Carreau** [comment]
Ah, thanks. I missed/forgot this one !

**Comment by seansmckinley** [comment]
Good to know guys, thanks.
