### ISSUE TITLE
Python exporter creates HistoryManager database despite configuration

### ISSUE THREAD

**Issue by tbekolay** [jupyter/nbconvert#273]
IPython manages command history in `~/.ipython/profile_default/history.sqlite`. You can disable this history by placing `c.HistoryAccessor.enabled = False` in `~/.ipython/profile_default/ipython_config.py`. With this, starting an interactive IPython session does not create the `~/.ipython/profile_default/history.sqlite` file.

However, when I export a notebook to Python (e.g., `jupyter nbconvert my_notebook.ipynb --to python`) `~/.ipython/profile_default/history.sqlite` is created. This is an issue for me because sometimes I do this at the same time in two threads, which can cause an error if the threads both attempt to access the `sqlite` file at the same time.

It took a while to track down that it was the Python exporter that is creating the file, and looking at the code for the Python exporter it looks like the only point in which it uses `IPython` itself is the `IPythonInputSplitter` in `nbconvert/filters/strings.py`. Am I missing something? Where might the Python exporter be accessing something in IPython that is creating the history file, and ignoring the user's configuration file?

**Comment by takluyver** [comment]
Aha, I think this might have been fixed already by #229, but the fix has not yet been released. I think we're aiming to do nbconvert 4.2 before too long, which should include that. If it's convenient, can you test with master to confirm that that fixes the issue?

**Comment by tbekolay** [comment]
I just tested with master, and the issue has indeed been fixed! Thanks @takluyver!
