### ISSUE TITLE
bug exporting to HTML

### ISSUE THREAD

**Issue by jonathan-taylor** [jupyter/nbconvert#280]
Running `jupyter nbconvert` on http://web.stanford.edu/~jtaylo/nb_convert/Regression_revisited.ipynb

It runs fine in the notebook (needs data file http://web.stanford.edu/~jtaylo/nb_convert/pearson_lee.csv), and renders on 
`nbviewer`: http://nbviewer.jupyter.org/url/web.stanford.edu/~jtaylo/nb_convert/Regression_revisited.ipynb

I get the following when trying to export it to HTML:

~/Desktop/git-repos/stats60/build/nbconvert_ex (master) $ jupyter nbconvert --to html Regression_revisited.ipynb 
...
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 364: ordinal not in range(128)

~/Desktop/git-repos/stats60/build/nbconvert_ex (master) $ jupyter --version

4.0.6

**Comment by takluyver** [comment]
For reference from the email on this, the error is raised in `nbconvert.filters.ansi.ansi2html`.

**Comment by minrk** [comment]
This is a regression in the recent ansi filter rewrite, probably an errant str somewhere. Should be fixed by #285
