### ISSUE TITLE
ImportError: No module named 'entrypoints'

### ISSUE THREAD

**Issue by josephcslater** [jupyter/nbconvert#289]
Line 9 of export.py fails with the above error. I'm not sure where the module 'entrypoints' should be to be found, but it's certainly not in my installation. I can't find this error in my brief looking around.

**Comment by minrk** [comment]
entrypoints is a dependency of nbconvert. It should be included when you install nbconvert (`pip install nbconvert` pulls in entrypoints as a dependency). If it isn't, you can install it after the fact with

    pip install entrypoints

**Comment by josephcslater** [comment]
Thanks. I didn't use pip to search for it (googled.. and it failed after quite a substantial search). 

Odd that the dependency failed. My install was via MacPorts, so I need to pass this dependency up the chain.

**Comment by chipmuenk** [comment]
I have / had a similar problem: PDF export from GUI failed silently or with a 404 error, only in the console I received the message  "The 'entrypoints>=0.2.2' distribution was not found and is required by nbconvert". The strange thing is: The version 0.2.2-py35_0  *was* installed. Doing a `conda install entrypoints` (updating to 0.2.3) still solved the problem.

I've got the following versions installed: 
ipykernel                 4.5.0                    py35_0
ipython                   5.1.0                    py35_0
ipython_genutils     0.1.0                    py35_0
ipywidgets              5.2.2                    py35_0
jupyter                    1.0.0                    py35_3
jupyter_client          4.4.0                    py35_0
jupyter_console      5.0.0                    py35_0
jupyter_core            4.2.0                    py35_0

nb_conda                  2.0.0                    py35_0
nb_conda_kernels     2.0.0                    py35_0
nb_config_manager  0.1.3                    py35_0    anaconda-nb-extensions
nbbrowserpdf           0.2.2                    py35_0    anaconda-nb-extensions
nbconvert                 5.2.1                    py35_0
nbformat                  4.1.0                    py35_0
nbpresent                 3.0.2                    py35_0

**Comment by takluyver** [comment]
That sounds like a problem with building the conda packages.
