### ISSUE TITLE
nbconvert does not honor "isolate" property of display_data

### ISSUE THREAD

**Issue by janschulz** [jupyter/nbconvert#290]
The R kernel sends svg plots with the "isolate" metadata set. This is used in the notebook to embed the svg in an iframe. nbconvert does not do this, the svg is inserted directly in the exported html, which causes it to be garbled :-/:

Example: https://stackoverflow.com/questions/35827734/trouble-when-exporting-notebook-to-html-on-jupyter-with-r-kernel/36605462#36605462

You can find a notebook and an exported html file here: https://gist.github.com/janschulz/247597c6a09382987475647e4964702d

-> The second plot displays nicely in the notebook, but has garbled x axis labels in the exported html.

@flying-sheep: did I mention that I hate our current plotting type defaults? I think I did :-)

**Comment by flying-sheep** [comment]
text, PNG, and SVG seems perfectly sane. the only problem is that you can’t simply plot thousands of dots without lagging, but that’s OK since there’s no way you could understand thousands of dots in a plot, so you have to do some statistic anyway.

**Comment by takluyver** [comment]
I already filed #129 about this, so closing as a duplicate. We worked out a way forwards in that issue if someone wants to work on it.

I'm staying neutral on the default plot formats for now :P

**Comment by janschulz** [comment]
Sorry my bad, only searched for "isolate", but it's actually "isolated" and github doesn't find partial words :-(

**Comment by takluyver** [comment]
No problem, these things happen.
