### ISSUE TITLE
nbconvert's setup reliance on a CDN for some CSS forbids its installation in proxy-protected environments

### ISSUE THREAD

**Issue by laurentalsina** [jupyter/nbconvert#294]
I work in an environment that is quite well isolated by proxies...

Is there any way for me to install nbconvert? I will not get authorization to punch through the proxies to some CDN from this Linux machine. From my laptop I can browse to https://cdn.jupyter.org/notebook/4.1.0/style/style.min.css, but this does not help. The only way I see is to monkey-patch the setup code to refer to a local copy of the CDN's file, but that's a bit more effort than I can dedicate time to right now.

(MyEnv)myuser@myserver:~/MyEnv/nbconvert-master> pip install -e . 
_... various Requirement already satisfied..._
Installing collected packages: nbconvert
  Running setup.py develop for nbconvert
    Complete output from command  MyEnv/bin/python -c "import setuptools, tokenize; __file__='MyEnv/nbconvert-master/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
    MyEnv/lib/python2.7/site-packages/setuptools/dist.py:282: UserWarning: Normalizing '4.3.0.dev' to '4.3.0.dev0'
      normalized_version,
    running develop
    running css
    Failed to download css from https://cdn.jupyter.org/notebook/4.1.0/style/style.min.css: [Errno socket error] [Errno 97] Address family not supported by protocol
    Downloading CSS: https://cdn.jupyter.org/notebook/4.1.0/style/style.min.css
    error: None
    
    ----------------------------------------
    Command "MyEnv/bin/python -c "import setuptools, tokenize; __file__='MyEnv/nbconvert-master/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in MyEnv/nbconvert-master

Any idea on the best course of action?
Thanks a lot

**Comment by takluyver** [comment]
I think it's included with the released packages, so if the released version is sufficient, you should be able to `pip install nbconvert` OK.

If you need the development version, maybe the easiest way is to make a tarball on a machine that's not behind the proxy (`python setup.py sdist`) then copy it across. If that restriction is going to be common, we could make nightly tarballs.

**Comment by laurentalsina** [comment]
Yes indeed, it works with released packages, good enough for my need so I close the issue.
Thanks a lot
