### ISSUE TITLE
Load configuration when setting up handlers

### ISSUE THREAD

**Issue by ryanlovett** [jupyter/nbconvert#297]
One can configure the nbconvert application via command-line or config file, e.g.
`$ jupyter nbconvert --PDFExporter.latex_command='["xelatex", "{filename}"]' --to pdf has_unicode.ipynb`

or

```
$ cat ~/.jupyter/jupyter_nbconvert_config.py                                               
c.PDFExporter.latex_command = [u"xelatex", u"{filename}"]
$ jupyter nbconvert --to pdf has_unicode.ipynb
```

however this does not affect the notebook handler (File > Download as > PDF via LaTeX (.pdf)).
From @minrk at https://gitter.im/jupyter/notebook?at=5718d4f2b129b59c56da3552:

> the nbconvert config file isn't loaded because config loading is done at the "application" level, in this case "notebook".
> 
> We should load nbconvert config when setting up the nbconvert handlers, though.

**Comment by mpacer** [comment]
I know that the notebooks server does not load `jupyter_nbconvert_config.py` if it is local, and I believe it will also defer to its use if it's lower in the config hierarchy. I'm going to close this, but if this is still an issue @ryanlovett I'm happy to reopen.
