### ISSUE TITLE
Executing notebooks on TravisCI

### ISSUE THREAD

**Issue by tritemio** [jupyter/nbconvert#300]
Hi,

I have a library which contains a few notebook. I want to execute them on travisCI to make sure there are no execution errors. However, running notebooks via nbconvert fails on travis for py34 and py27 (while it is working for py35). The error happens while importing tables or matplotlib and is related to a wrong numpy version. The installation seems to work as travis can execute the notebook saved as a plain python script. However, executing the notebook thorugh nbconvert fails.

The problem may be somewhere between anaconda, travis ci and nbconvert. I'm starting opening an issue here to see if I can get some suggestion (I have to start somewhere!).

The library is this [phconvert](https://github.com/Photon-HDF5/phconvert), and the updated files are in the [test branch](https://github.com/Photon-HDF5/phconvert/tree/test).  I'm executing the notebooks with [this script](https://github.com/Photon-HDF5/phconvert/blob/test/tests/nbrun.py) which boils down to:

```
ep = ExecutePreprocessor(timeout=timeout, **execute_kwargs_)
ep.preprocess(nb, {'metadata': {'path': './'}})
```

The last line executes the notebook. When the notebooks imports `tables` I get the error:

```
------------------
import tables
------------------
ValueError: numpy.dtype has the wrong size, try recompiling
```
 If, I import matplotlib first, the error is:

```
------------------
import matplotlib.pyplot as plt
------------------
RuntimeError: module compiled against API version a but this version of numpy is 9
```

You can see the full log here (for py27):

https://travis-ci.org/Photon-HDF5/phconvert/jobs/125893500#L523

(the line the link points to is where the test section starts)

As you can see the python version is ok, numpy, tables and matplotplib and nbconvert are imported with no error by `print_versions.py` and the notebook saved as python script `Convert_ns-ALEX_Becker-Hickl_files_to_Photon-HDF5.py` runs with no error. But the next line which executes the same notebook with nbconvert results in an error.

I tried reproducing the issue on a local linux machine, creating the environment as done on travis, but locally it works.

So at this point I'm seeking some help as I don't know what else to try.

PS: Ironically, running the same notebooks on appveyor works [like a charm](https://ci.appveyor.com/project/tritemio/phconvert/build/1.0.14)!

**Comment by takluyver** [comment]
I think I've run into this before, and the cause was something from the virtualenv that Travis creates. I can't think which project I ran into this on, but try to deactivate the virtualenv before activating the newly created conda env.

**Comment by tritemio** [comment]
@takluyver, thanks! Deactivating the virtual environment solved the problem. I had to deactivate it before installing conda because conda's `deactivate` shadows virtualenv's `deactivate`.

Thanka a lot!

**Comment by takluyver** [comment]
You're welcome, glad my memory was correct.
