### ISSUE TITLE
pdflatex not in PATH

### ISSUE THREAD

**Issue by jackjameshoward** [jupyter/nbconvert#301]
I intentionally don't have pdflatex in my path because i'm running everything portable.
Is there a way to direct nbconvert to the correct directory to find pdflatex?

> nbconvert failed: pdflatex not found on PATH

I tried to add a line to `\.jupyter\jupyter_nbconvert_config.py`

```
c.PDFExporter.latex_command = ['\\..\\Program Files (x86)\\MikTex\\miktex\\bin\\pdflatex', '{filename}']
```

but I still get the same error, its like it never even recognised i'd added the config. 

> nbconvert failed: pdflatex not found on PATH

I then tried to add the path of pdflatex to `\Lib\site-packages\nbconvert\exporters\pdf.py`

```
latex_command = List([u"\\..\\Program Files (x86)\\MikTex\\miktex\\bin\\pdflatex", u"{filename}"], config=True, 
   help="Shell command used to compile latex.")
```

At least the error changed.

> nbconvert failed: ..\Program Files (x86)\MikTex\miktex\bin\pdflatex not found on PATH

Can anybody suggest a way to direct nbconvert to a specific directory?

**Comment by takluyver** [comment]
If you're doing it from the notebook,  the config goes in `jupyter_notebook_config.py`, which would be why the config is not taking effect.

I don't think a path starting with `\..` makes sense - if you want to use a relative path, leave off the initial `\`, and note that it will be relative to the working directory when you run it. It may be simpler to use an absolute path.

**Comment by t-makaro** [comment]
Closing as answered / stale.
