### ISSUE TITLE
HTML Export does not show underline characters

### ISSUE THREAD

**Issue by torwag** [jupyter/nbconvert#304]
Hi,
seems that the exporting to HTML and the preview function does somehow eat-up underline characters.
ORIGINAL
My_test_for_this = 1 
a = my_little_function(a_1=2)

will be depicted as
HTML
My test for this = 1
a = my little function(a 1=2)

Pdf is fine.
This is particular problematic if you work with students who still learn about python syntax... believe me I had a funny lecture ;)

Using jupyter 4.1.0.

**Comment by takluyver** [comment]
The underscores are still there for me.

Can you show an exported HTML file? The first thing to work out is whether it's a problem with creating the file itself, or with rendering it - i.e. are the underscores there but not showing up for some reason?

**Comment by torwag** [comment]
I have to apologize,
it seems that firefox is to blame for this issue. After an update to a newer version and a firefox restart, underlines are there....
Sorry for the noise.
