### ISSUE TITLE
ascii_only in base.tplx breaks non-ascii titles

### ISSUE THREAD

**Issue by ozancaglayan** [jupyter/nbconvert#306]
Hi,

When I name a file in notebook with Turkish characters and save it as PDF through the notebook, the Turkish characters are garbled and replaced with `?`. After removing the `ascii_only` filter in `templates/latex/base.tplx` the PDF is correctly rendered. Is there an obstacle for removing that filter?

**Comment by Carreau** [comment]
Would need to be tested on more platform, like windows, and make sure it always work. 

It would be good to use `git blame`  to see the reason of the addition.

**Comment by minrk** [comment]
That was added in https://github.com/ipython/ipython/pull/5194, to fix a unicode issue. It's possible that has been fixed in another way by something else, and the harsh ascii-only transform is no longer required.

**Comment by minrk** [comment]
...especially since we now use `xelatex` by default!

**Comment by michaelpacer** [comment]
@minrk what would you want to see in terms of a test in order for us to be able to remove that? And would it be more appropriate to change this here or in `ipython` directly? would it *have* to be changed in `ipython`?

**Comment by minrk** [comment]
There should be no changes in IPython, since nbconvert has moved here. That was just a link to the original source of the change when nbconvert was part of IPython.

**Comment by t-makaro** [comment]
Fixed by #1039
