### ISSUE TITLE
DataFrames output in Jupyter notebook - nbconvert to pdf error 

### ISSUE THREAD

**Issue by clayms** [jupyter/nbconvert#314]
migrated from [DataFrames](https://github.com/JuliaStats/DataFrames.jl/issues/967) and [jupyter-js-notebook](https://github.com/jupyter/jupyter-js-notebook/issues/219) as this is likely the more appropriate place to post this issue.

Converting output of Jupyter notebook with DataFrames output to a pdf with nbconvert causes the a 500 error.  reporting `Unknown Unicode character 9474 = U+2502,`.  

 When I clear the DataFrame output that generates these characters, nbconvert works just fine.  However, `nbconvert` should be able to deal with this unicode character.

**Comment by minrk** [comment]
The switch from pdflatex to xelatex in master may fix this.

**Comment by Shaun1818** [comment]
Thanks minrk. I am having the same issue. Could you explain what you mean by ' master may fix this'

**Comment by clayms** [comment]
@Shaun1818 look at  [use xelatex by default](https://github.com/jupyter/nbconvert/commit/1db4edc503269dd2e42ce07abb1b20aa35d18029)

I updated `nbconvert` but still get this
```
[NbConvertApp] Running pdflatex 3 times: ['pdflatex', 'notebook.tex']
[NbConvertApp] CRITICAL | p failed: pdflatex notebook.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (MiKTeX 2.9 64-bit)
```
from `jupyter nbconvert --help-all`, one of the options under `PDFExporter options`  is
```
--PDFExporter.latex_command=<List>
    Default: ['pdflatex', '{filename}']
    Shell command used to compile latex.
```
So from the console
```
jupyter nbconvert --to pdf --PDFExporter.latex_command=(xelatex Example.ipynb)
```
where `Example.ipynb` is the name of your notebook.

However, this just opens up the notebook in TeXworks.

**Comment by takluyver** [comment]
To set that config option, one of the arguments actually needs to be `{filename}`. Nbconvert will generate a `.tex` file from the notebook file and then pass that filename to latex in place of `{filename}`. It's probably easier to set it in a config file than to work out what combination of quoting and escapes you need to pass it at the command line.

**Comment by clayms** [comment]
Setting up a config file `nbConvertConfig2.py` containing one of the following:
`latex_command = ['xelatex', '{filename}']`   
`latex_command = ["xelatex", "{filename}"]`    
`latex_command = [u"xelatex", u"{filename}"]` 

then running `jupyter nbconvert --to pdf --config nbConvertConfig2.py Examples.ipynb` does not cause an any errors, but I still get the following:  

```
[NbConvertApp] Converting notebook Examples.ipynb to pdf
[NbConvertApp] Support files will be in Examples_files\
[NbConvertApp] Making directory Examples_files
[NbConvertApp] Making directory Examples_files
[NbConvertApp] Writing 43852 bytes to notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running pdflatex 3 times: ['pdflatex', 'notebook.tex']
[NbConvertApp] CRITICAL | p failed: pdflatex notebook.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (MiKTeX 2.9 64-bit)
...
```
Which of course still results in the same `Unknown Unicode character 9474 = U+2502` error that started this.

**Comment by takluyver** [comment]
Great, I'm glad you got it working. In that case, I think this should be fixed by changing the default to xelatex, so I'll close this issue.
