### ISSUE TITLE
unicode support via xelatex for PDFExporter

### ISSUE THREAD

**Issue by amueller** [jupyter/nbconvert#317]
Hey.
I just noticed that having unicode in your notebook doesn't work with the PDFExporter
```
Package ucs Error: Unknown Unicode character 9500 = U+251C,
```
Compiling with xelatex instead of latex seems to solve the issue.
Is it possible to move nbconvert to xelatex? I'm not sure what the consequences would be.

**Comment by amueller** [comment]
hm I just saw #303. I think I was using master. Let me check.

**Comment by amueller** [comment]
seems like I ran that before updating. Sorry for the noise (and for fixing a problem two weeks before I report it ;)

**Comment by minrk** [comment]
Yeah, we need to push out a release. I'll work on that.
