### ISSUE TITLE
Most default Latex templates do not work

### ISSUE THREAD

**Issue by clayms** [jupyter/nbconvert#318]
With the following in a config file named `nbConvertConfig.py`

```
c = get_config()
c.PDFExporter.latex_command = ['xelatex', '{filename}']  
c.NbConvertApp.export_format = 'pdf'
c.Exporter.template_file = 'report'
```
and running `jupyter nbconvert --config nbConvertConfig.py  Examples.ipynb` from the console converts `Examples.ipynb` into the `report` format just fine.    

Specifying the `article` template converts the notebook into the `article` format, and commenting out `c.Exporter.template_file = 'report'` from the config file converts `Examples.ipynb` into the default format.  

However, If I try to specify any of the other Latex templates in the config file, errors are thrown.  Other templates include `base`, `document_contents`, `style_bw_ipython`, `style_bw_python`, `style_ipython`, and `style_python`. 

These are the errors for everything but `document_contents.tplx`
```
! LaTeX Error: \usepackage before \documentclass.
See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...
l.8     \usepackage[T1]{
                        fontenc}
?
! Emergency stop.
 ...
l.8     \usepackage[T1]{
                        fontenc}
```

This is the error for `document_contents.tplx`
```
! Undefined control sequence.
l.5     \subsection
                   {Simple Example}\label{simple-example}
?
! Emergency stop.
l.5     \subsection
                   {Simple Example}\label{simple-example}
```

All fail if I put any of the most recent `*.tplx` files from this git repo in the same folder as the notebook to be converted, or point to a folder with `c.TemplateExporter.template_path = ['.', r"C:\path\to\tplx\files"]` in the config file.

**Comment by clayms** [comment]
Should be noted, that everything works fine when I create my own template with the [Gregory Ashton's](https://ga7g08.github.io/2015/06/25/ipython-nbconvert-latex-template-to-hide-code/) `nocode` example and run the same console command with the same config file that refers to `nocode`.

So it seems like I am doing the right thing, it's just that some of the standard templates are not working.  What do I need to edit in them to prevent the errors noted above?

**Comment by takluyver** [comment]
I think `article` and `report` are the only templates intended to be used directly; the others are used through template inheritance, to avoid duplicating template structure. This should probably be documented somewhere.

**Comment by clayms** [comment]
Thanks @takluyver
