### ISSUE TITLE
DataFrames rendered with Python Markdown {{ }} do not convert

### ISSUE THREAD

**Issue by clayms** [jupyter/nbconvert#320]
DataFrames refered to with the Python Markdown `{{Table1}}` notation display just fine inside the notebook.  However, they do not convert into a pdf with nbconvert.  All I see is the `{{Table1}}` Python Markdown reference.

Do I need to add a special code block in a latex .tplx template file?  If so, any idea what that code would be?

**Comment by clayms** [comment]
Actually none of the variables referred to in markdown cells with the Python Markdown {{}} notation work.

**Comment by clayms** [comment]
Also, I did try adding `--execute` to the console command which did not help.

**Comment by juhasch** [comment]
Did you check if the `PyMarkdownPreprocessor` is called from nbconvert ?
If not, see https://github.com/ipython-contrib/IPython-notebook-extensions/tree/master/nbextensions/usability/python-markdown
It should work for both HTML and PDF

**Comment by clayms** [comment]
I added the following to my config file but still get errors.  Don't think I have `pre_pymarkdown.py` in the right place.

```
c = get_config()
c.Exporter.preprocessors = ['pre_pymarkdown.PyMarkdownPreprocessor']
```

**Comment by juhasch** [comment]
`pre_pymarkdown.py` is a Python file, so you need to have it in your Python path or add it to `PYTHONPATH`.

**Comment by clayms** [comment]
Thanks @juhasch, yes.  I thought it would have installed by default.  Was not anywhere on my file system.  Downloaded from [github](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/master/extensions/pre_pymarkdown.py) and put in Anaconda folder, which is the Python path on my system.  Closing this now.

**Comment by mooneyme** [comment]
@juhasch I'm having the same issue for all notebooks generated using nbconvert. My pre_markdown.py is in my PYTHONPATH, so that's not the issue. I'm thinking is has something to do with the `PyMarkdownPreprocessor`, though I'm not entirely sure. 

Any thoughts on whats going on? (The link you posted is no longer active.)

**Comment by juhasch** [comment]
Documentation is available here: http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/

If you install the PyPi or conda-forge packages, you should not need to set PYTHONPATH or do any manual configuration. Feel free to open a new issue at the https://github.com/ipython-contrib/jupyter_contrib_nbextensions repo.
