### ISSUE TITLE
Failure to modify output directory with FilesWriter.build_directory

### ISSUE THREAD

**Issue by danjump** [jupyter/nbconvert#324]
I wrote a simple `~/.jupyter/jupyter_nbconvert_config.py` to customize a notebook conversion. As part of my configuration it contains the following:
``` python
c = get_config()
c.FilesWriter.build_directory = OUT_DIR
```
But when i convert a notebook, all the customizations work except for this. It just writes the output to the same directory as the input notebook as if `OUT_DIR = ''` (but I carefully checked that it does not)

So I dug in to `nbconvert/nbconvert/nbconvertapp.py` to see if I could figure out what was going on or if I was making any mistakes and it seems (to my admittedly novice self) that there is a simple bug going on here. I was able to modify `nbconvertapp.py` to properly accept a `FilesWriter.build_directory` argument as I'll describe below. But as I said, I'm not an expert and I'm only using this for one case of converting single notebooks. So I don't know if my fix will work well generally or might introduce bugs in other use cases. I thought I'd bring the issue and my fix up here and let someone more closely involved decide what to do.

Here's what I did in `nbconvertapp.py`:

I noticed that the `if` statement in `init_writer()` concerning the `build_directory` seemed like it was not doing the right thing. What does `use_output_suffix` have to do with `build_directory`? I would guess maybe some lines got accidentally deleted between 287 and 288 at some point? At any rate, to fix my use case, I deleted these conditional lines here:
``` python
  283     def init_writer(self):                                                       
  284         """Initialize the writer (which is stateless)"""                         
  285         self._writer_class_changed({ 'new': self.writer_class })                 
  286         self.writer = self.writer_factory(parent=self)
  del         if hasattr(self.writer, 'build_directory') and self.writer.build_directory != '':
  del             self.use_output_suffix = False 
```

and I added the same conditional that did what I want later in `write_single_notebook()`:

``` python
  370     def write_single_notebook(self, output, resources): 
...
  391         notebook_name = resources['unique_key']                                  
  new         if hasattr(self.writer, 'build_directory') and self.writer.build_directory != '': 
  new             if self.writer.build_directory[-1] != '/':                           
  new                 self.writer.build_directory += '/'                               
  new             notebook_name = self.writer.build_directory + os.path.basename(notebook_name) 
  new              
  392         if self.use_output_suffix and not self.output_base:                      
  393             notebook_name += resources.get('output_suffix', '')                  
  394                                                                                  
  395         write_results = self.writer.write(                                       
  396             output, resources, notebook_name=notebook_name)                      
  397         return write_results
```

This solved my problems and the conversion output was properly output to a different directory. 

As I said, I don't know if this will work well as a general fix, but something definitely has to be done to fix broken functionality here

**Comment by michaelpacer** [comment]
Does this address your concern? 

https://github.com/jupyter/nbconvert/pull/377

also had it worked before when you tried passing `--output-dir` as a command line argument?

**Comment by michaelpacer** [comment]
Closing this, can reopen if that fix doen't work.
