### ISSUE TITLE
--quiet switch?

### ISSUE THREAD

**Issue by debjan** [jupyter/nbconvert#327]
Hi,

jupyter nbconvert writes `[NbConvertApp] Converting notebook into html` message to stderr, while it seems it does not provide "quiet" switch to disable writing non-errors to stderr.

Is there a workaround w/o disabling strerr pipe?

**Comment by takluyver** [comment]
If you pass `--log-level WARN`, only logging messages at warning level and above will be shown (those messages are at info level). The named values are:

```
DEBUG INFO WARN ERROR CRITICAL
```
