### ISSUE TITLE
Julia DataFrames format in latex/pdf

### ISSUE THREAD

**Issue by clayms** [jupyter/nbconvert#332]
How can I get a DataFrame in a Julia Notebook to output to a pdf with nbconvert and control the formatting?

```
using DataFrames
A = DataFrame(randn(10, 7))
```

With the code above, the pdf from nbconvert shows "10Œ7 DataFrames.DataFrame" followed by an un-formatted table. 
Although `display(A)` and `print(A)` show different outputs in the notebook, nbconvert shows the same output as the code above does in the notebook.

The Python Markdown Notebook Extension, displays a formatted table in the notebook, but in the nbconvert pdf output, the data from the DataFrame comes through as one long column, not as a table.

Also on [StackOverflow](http://stackoverflow.com/questions/38291020/julia-dataframes-format-in-pdf-with-nbconvert)

**Comment by juhasch** [comment]
For the markdown notebook extension, you need to specify a preprocessor, so nbconvert will replace  `{{A}}` with the desired contents. 
See: https://github.com/ipython-contrib/IPython-notebook-extensions/tree/master/nbextensions/usability/python-markdown

As for Pandas, I don't know. have you looked at http://stackoverflow.com/questions/20685635/pandas-dataframe-as-latex-or-html-table-nbconvert ?

**Comment by clayms** [comment]
thanks @juhasch 

I had the preprocessor installed and specified before asking this question.  Every plain regular instance of `{{variable}}` converts as it's supposed to with nbconvert to pdf.  It is just the tables that are misbehaving.

Additionally, the data of the tables comes through, just not as a table but a long single column list where every 'field' is on a separate line.

I am using the DataFrames package for Julia to generate the tables, not Pandas in Python.

**Comment by clayms** [comment]
@juhasch  are you telling me I have to create my own preprocessor?  Should I start with one of the preprocessors [here](https://github.com/jupyter/nbconvert/tree/master/nbconvert/preprocessors) ?

**Comment by juhasch** [comment]
Oh, now I understand. The difficulty is here, that nbconvert when converting the notebook to TeX (and then to PDF) does not understand HTML. For the Pandas table as cell output, there is an additional plain text representation (the HTML representation has priority so you don't see it displayed in the notebook), and this is what you see in the PDF output.

What you need to do generate an output that can be handled by nbconvert (i.e. the table as plain text or already renderd as graphics).

**Comment by clayms** [comment]
`print(B)` produces the output shown below, which nbconvert does turn into a table, just not a very nice looking table.

So I understand from what your telling me, that I need to find a way to get the tables to be output as formatted text and not html.  This is what the markdown notebook extension does by default, so I guess using the markdown notebook extension to output tables together with nbconvert to make pdf's is not going to work.

Is there a way to get tables to output as text with markdown notebook extension? Or will you always need to split your markdown cells up with a code cell that outputs the table so the table will be properly converted to tex by nbconvert to pdf when they are code cell output?  

Thanks @juhasch 



```
10×7 DataFrames.DataFrame
│ Row │ x1         │ x2        │ x3         │ x4         │ x5        │
├─────┼────────────┼───────────┼────────────┼────────────┼───────────┤
│ 1   │ -0.427782  │ 0.383049  │ -0.246328  │ -0.350851  │ -0.429302 │
│ 2   │ 0.0273606  │ 1.49586   │ -0.0383807 │ 0.182732   │ 1.39306   │
│ 3   │ 0.333862   │ -0.338611 │ 1.37093    │ -0.711005  │ 0.329573  │
│ 4   │ -1.12359   │ 0.693245  │ 0.702964   │ -0.356184  │ 1.46039   │
│ 5   │ 0.579341   │ 0.0796032 │ -1.32279   │ 0.774341   │ -0.590157 │
│ 6   │ -0.300496  │ -1.25103  │ 1.18116    │ 1.07272    │ -0.499508 │
│ 7   │ -0.358822  │ 0.155829  │ 0.156422   │ -0.408265  │ 0.055784  │
│ 8   │ -0.243596  │ -0.525525 │ -1.91371   │ -0.0243501 │ -1.456    │
│ 9   │ -1.18314   │ -0.439126 │ -0.0993209 │ -1.389     │ 0.450373  │
│ 10  │ -0.0167186 │ 0.607967  │ 0.182868   │ 0.29049    │ 0.188136  │

│ Row │ x6         │ x7        │
├─────┼────────────┼───────────┤
│ 1   │ 0.715016   │ 1.14093   │
│ 2   │ 1.04527    │ 0.956439  │
│ 3   │ 1.26505    │ 1.1143    │
│ 4   │ -1.1378    │ -0.147627 │
│ 5   │ -1.41111   │ -0.543337 │
│ 6   │ -1.63825   │ 1.35898   │
│ 7   │ -1.60534   │ -0.306898 │
│ 8   │ -0.0863654 │ 0.721877  │
│ 9   │ 0.534904   │ 0.354924  │
│ 10  │ -0.188771  │ 2.60315   │
```

**Comment by juhasch** [comment]
The advantage of a code cell output compared to markdown is that it can have more than one output format, i.e. text and html, or png and pdf. This allows nbconvert to select the format it wants to use.

So one could have the python-markdown extension store all generated output formats too, and the nbconvert preprocessor then returning the preferred one for the conversion. The extension currently mindlessly selects one format and strips all others.

For me, this is beyond the scope of what I intended with the extension, but feel free to go this route.

**Comment by clayms** [comment]
So my next question would be, what Julia functions can output a Julia DataFrame so nbconvert can make a nice pdf with it?  I have tried `print()`, `show()`, and `showall()` which return ascii text tables.  Then nbconvert just turns them into very plain text files.  Not exactly something your would want to publish or share.  

If I create my own ascii text table with a few tweaks, nbconvert does a great job making a nice latex table.

However, this is not a nbconvert issue directly, so I will close this issue here.

This question is on [stackoverflow](http://stackoverflow.com/questions/38341004/julia-dataframe-output-functions).
