### ISSUE TITLE
nbconvert now outputs to input directory instead of default directory?

### ISSUE THREAD

**Issue by dgua** [jupyter/nbconvert#337]
All of a sudden my code broke because the following command:
jupyter nbconvert input_path --output output_file

now saves the file into the same directory as input_path instead of in os.getcwd()

WHY???

**Comment by michaelpacer** [comment]
I believe this is due to https://github.com/jupyter/nbconvert/commit/e07ef9a67273bc647b2077df5cadf5fd3f9ec182

If you wish to make it relative to your current working directory you can add `--output-dir .` and you will recover your desired functionality.

This relates to #293.
