### ISSUE TITLE
Config nbconert - fonts and margins (pdf)

### ISSUE THREAD

**Issue by jmarcellopereira** [jupyter/nbconvert#339]
Two questions:
How to change the size and type font
Changing the margins

**Comment by takluyver** [comment]
Most customisation is by overriding templates ([docs](http://nbconvert.readthedocs.io/en/latest/customizing.html), [base templates](https://github.com/jupyter/nbconvert/tree/master/nbconvert/templates)). The details of how to change things depend on the format you're converting to.

**Comment by jmarcellopereira** [comment]
hi takluyver.
 I saw the doc, but I did not understand well.

**Comment by takluyver** [comment]
Offering customisation this way means it's very flexible, but also quite complex if you just want simple changes. You need to know how to do what you want in the target format (if you're talking about fonts and margins, I assume that's HTML or Latex), and then write the necessary bits into a template.

**Comment by jmarcellopereira** [comment]
hi takluyver.
 used the conversion latex and edited margins. after I generated PDF. so it worked.

**Comment by takluyver** [comment]
Great :)

**Comment by hoogenm** [comment]
Idea for a shell script `to_pdf.sh` that customizes the .pdf output:

```
jupyter nbconvert --to latex $1.ipynb
sed -r -i 's/documentclass\[11pt\]\{article\}/documentclass[8pt]{extarticle}/' $1.tex
sed -r -i 's/geometry\{verbose,tmargin=1in,bmargin=1in,lmargin=1in,rmargin=1in}/geometry{verbose,tmargin=0.5in,bmargin=0.5in,lmargin=0.2in,rmargin=0.2in}/' $1.tex
pdflatex $1
rm $1.tex; rm $1.out; rm $1.aux; rm $1.log
```

On Linux, call the script with the filename of the .ipynb file _without the extension_.
