### ISSUE TITLE
slides display problem: reveal.js version conflict?

### ISSUE THREAD

**Issue by cranmer** [jupyter/nbconvert#34]
I'm using IPython 3.0.0 and having various issues with slide conversion.
(I had to manually install mistune (pip installed  mistune.__version__ '0.5.1')

Scenario 0:
`ipython nbconvert --to slides TestSlides.ipynb --post serve`
This works, but you see it is getting an old reveal 2.6.2
`[NbConvertApp] Redirecting reveal.js requests to https://cdn.jsdelivr.net/reveal.js/2.6.2`

Note, if you use nbviewer it uses reveal 3.1.0

The problem is that you can't put these on a live server unless it is has reveal.js installed in that local directory.

Scenario 1:
```
ipython nbconvert --to slides TestSlides.ipynb
python -m SimpleHTTPServer 8000
````
This browser sees the html, but they don't act as slides b/c reveal.js isn't found. 

Scenario 2:
```
ipython nbconvert --to slides TestSlides.ipynb
wget https://github.com/hakimel/reveal.js/archive/3.0.0.tar.gz
tar -xvf 3.0.0.tar.gz
mv reveal.js-3.0.0 reveal.js
python -m SimpleHTTPServer 8000
```
Now the browser sees the reveal.js (js and css) resources, but for some reason it renders as a blank screen. It also still has problem that you can't deploy without making a copy of reveal.js in the corresponding directory on the live server.

Scenario 3:
```
ipython nbconvert --to slides TestSlides.ipynb  --reveal-prefix https://cdn.jsdelivr.net/reveal.js/2.6.2
python -m SimpleHTTPServer 8000
```

This works now locally and on live server, but with old reveal.js

Scenario 4:
```
ipython nbconvert --to slides TestSlides.ipynb  --reveal-prefix http://cdn.bootcss.com/reveal.js/3.1.0
python -m SimpleHTTPServer 8000
```
This gives similar behavior as Scenario 2, the resources are there but the browser renders an empty screen. In both Scenario 2 & 4 I see these errors in the console:
```
[Error] ReferenceError: Can't find variable: Reveal
	global code (TestSlides.slides.html, line 333)
[Error] Error: Mismatched anonymous define() module: function () {
			root.Reveal = factory();
			return root.Reveal;
		}
http://requirejs.org/docs/errors.html#mismatch
	da (require.min.js, line 8)
	w (require.min.js, line 12)
	M (require.min.js, line 15)
	(anonymous function) (require.min.js, line 26)
```

**Comment by takluyver** [comment]
Scenario 1 is intentional/known, I think - if you do it with `ipython nbconvert --to slides TestSlides.ipynb --post serve` it runs the server with a proxy that points to reveal.js in the correct place. Nbconvert doesn't download it locally for you.

@damianavila , are you aware of an issue with Reveal 3.1?

**Comment by cranmer** [comment]
Hi, yes I added Scenario 1 just as a starting point for the discussion. Also to confirm that things aren't completely broken on my machine.

**Comment by damianavila** [comment]
yes... @takluyver, we have discussed a little bit during the afternoon with @cranmer 
I asked to open this issue to remind me about going in depth on this...
I will try to investigate during the weekend if something is broken with reveal 3.1.0

**Comment by akhmerov** [comment]
@damianavila it seems to be an issue with reveal >=3.0 (pointing to a cdn has the same effect). The console shows that `Reveal` isn't defined after loading reveal 3.0, and this seems due to https://github.com/hakimel/reveal.js/pull/869 which changed the way Reveal is loaded.

**Comment by cranmer** [comment]
That is consistent with what I was seeing.

**Comment by damianavila** [comment]
Interesting... thanks @akhmerov for the pointer, I will take a look

**Comment by cjrh** [comment]
I've added PR #62 for this issue.
