### ISSUE TITLE
Hidden \includegraphics[]{} latex call

### ISSUE THREAD

**Issue by kapilsh** [jupyter/nbconvert#340]
I was trying to override the report.tplx template to add a cover page to it.

I had to use \includegraphics with width and height that equaled the page width and page height.

However, due to the code below:

```
\let\Oldincludegraphics\includegraphics
% Set max figure width to be 80% of text width, for now hardcoded.
\renewcommand{\includegraphics}[1]{\Oldincludegraphics[width=.8\maxwidth]{#1}}

```

the command was hidden.

I had to dig through the code to figure out that I could call \Oldincludegraphics.

**Comment by michaelpacer** [comment]
This was introduced in https://github.com/jupyter/nbconvert/pull/178 as a way of making the default `\includegraphics` command print figures specifically that would not span the page. 

It may be possible to use [`\xparse`](https://www.ctan.org/pkg/xparse) to make this customisable, but it is nontrivial to make it the standard `\includegraphics` work with arguments while also having this nicer default. 

Perhaps some mention of this should be added to the documentation? @willingc where in the documentation would you think this would most appropriately fit?

**Comment by JosefAssad** [comment]
This trips up quite a few other things one might be doing with a LaTeX nbconvert template. I just ran into this issue now while setting a background png for all pages. It looks to me like any package calling `\includegraphics` is keeling over and dying.

**Comment by mpacer** [comment]
I'm still not sure how to resolve this. One possibility would be to create a custom filter for the pandoc to LaTeX conversion? @takluyver  do you have any thoughts?

**Comment by takluyver** [comment]
Maybe we could put the conflicting code in our template (the code @kapilsh identified) into its own block, so that custom templates can override that specifically.

**Comment by MSeal** [comment]
No one is pushing implementation here. Removing milestone until someone actively picks it up.

**Comment by t-makaro** [comment]
Dev note: [This tex.stackexchange](https://tex.stackexchange.com/questions/83020/set-standard-default-scaling-of-includegraphics) might help. Apparently, ```\setkeys``` can be used to set defaults. I will try it out when I have time.
