### ISSUE TITLE
make 'output_files_dir' configurable

### ISSUE THREAD

**Issue by btel** [jupyter/nbconvert#341]
Currently, the 'output_files_dir' resource (which contains the path where figures are saved) is hard-coded in the `NbConvertApp` implementation:

`resources['output_files_dir'] = '%s_files' % notebook_name`

https://github.com/jupyter/nbconvert/blob/cc7a2dd7ccb430c3545b153a5790cf7c289eb4e3/nbconvert/nbconvertapp.py#L332

Such that changing it requires subclassing the `NbConvertApp` or running the whole conversion process manually. It would be useful to make the 'output_files_dir' configurable, so that we can select the directory, where to save the files or disable generating the figure files (by setting `output_files_dir` to `None`). 

For example, I configure the path to export notebooks with figure into Sphinx documentation tree. Currently, I implement it by using the nbconvert API directly  (see this [gist](https://gist.github.com/btel/837b56748698a795a632e081e2e58e23)).

**Comment by minrk** [comment]
Indeed it should be, and should be careful to resolve:

- relative paths relative to the notebook
- absolute paths correctly as well

**Comment by michaelpacer** [comment]
Relative paths relative to the notebook or to the working directory c.f. #293? This seems related to some outstanding issues related to the definition of `--output`.

**Comment by btel** [comment]
@michaelpacer Good point. The current implementation (see PR #377 which closed this issue) tacitly assumes that the relative paths are relative to the notebook.
