### ISSUE TITLE
Timeout that depends on cell content

### ISSUE THREAD

**Issue by j2kun** [jupyter/nbconvert#346]
I would like to set the ExecutePreprocessor timeout to a callable that computes the timeout based on the contents of the cell.

I see the place in the code that would make this change very easy:

```
    def run_cell(self, cell):
        msg_id = self.kc.execute(cell.source)
        self.log.debug("Executing cell:\n%s", cell.source)
        # wait for finish, with timeout
        while True:
            try:
                timeout = self.timeout
                if timeout < 0:
                    timeout = None
                msg = self.kc.shell_channel.get_msg(timeout=timeout)
```

Instead using something like

```
    def run_cell(self, cell):
            ...
            try:
                if callable(self.timeout):
                    timeout = self.timeout(cell.source)
                else:
                    timeout = self.timeout
                ...
```

I'm not submitting a PR because I also noticed that the attributes have some [strange type-checking](https://github.com/jupyter/nbconvert/blob/master/nbconvert/preprocessors/execute.py#L48) that I don't understand. If someone showed me how to do the proper type checking with a callable, I could submit a PR.

**Comment by minrk** [comment]
That sounds interesting. I wouldn't add further complex cases to the `timeout` trait, but a separate `timeout_func` that returns an integer or None as an `Any` trait should be doable.

**Comment by j2kun** [comment]
This feature was merged into master. Closing.
