### ISSUE TITLE
slides: fragment followed by unitialized - fails

### ISSUE THREAD

**Issue by bollwyvl** [jupyter/nbconvert#35]
Downstream issue:
https://github.com/jupyter/nbviewer/issues/466

Minimal test case:
https://gist.github.com/9a387ff6c870a59889c2.git

Error occurs here:
https://github.com/ipython/ipython/blob/3.x/IPython/nbconvert/preprocessors/revealhelp.py#L54

Possible fixes:
do two passes through the cells, first with the current:
https://github.com/ipython/ipython/blob/3.x/IPython/nbconvert/preprocessors/revealhelp.py#L34-37
then repeat the loop with the rest of the loop.

**Comment by takluyver** [comment]
pinging @damianavila for a slides related issue. See also PR #36, which I assume is related.

**Comment by damianavila** [comment]
#36 already reviewed, should be merged soon...
