### ISSUE TITLE
Test failure in jack-of-none builds

### ISSUE THREAD

**Issue by takluyver** [jupyter/nbconvert#350]
Problem running Latex:

```
Package ifplatform Warning: 
    shell escape is disabled, so I can only detect \ifwindows.

))

! Package minted Error: You must invoke LaTeX with the -shell-escape flag.

See the minted package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.67     \usepackage
                    [normalem]{ulem} % ulem is needed to support strikethrou...

? 
! Emergency stop.
 ...                                              
                                                  
l.67     \usepackage
                    [normalem]{ulem} % ulem is needed to support strikethrou...

No pages of output.
Transcript written on notebook.log.
```

[Test log](https://jenkins.jupyter.org/job/jack-of-none/372/console)

**Comment by takluyver** [comment]
I have reproduced this locally.

**Comment by amueller** [comment]
just saw this, too.

**Comment by flying-sheep** [comment]
ah! @takluyver [has an idea](https://github.com/jupyter/nbconvert/pull/353#issuecomment-238916469) why this might not have been caught:

> I suspect Latex isn't installed on Travis, so those tests are skipped. I don't know enough about latex to know if this is the right fix. @michaelpacer, your input would be welcome :-)

maybe it should be installed at least on one test machine if this is in fact the case

**Comment by takluyver** [comment]
We do have it on [our Jenkins server](https://jenkins.jupyter.org/), which is why I filed this bug. But that doesn't test PRs unless we specifically ask it to.

**Comment by michaelpacer** [comment]
So everything I can find on this would suggest this as fine as anything else (in that what we're doing is allowing LaTeX to have access to the shell directly through the use of the `\write18{}` command). If we don't trust one of the third party libraries that we're using by default, it's probably better we run into that problem in a Travis build than on a user build.
