### ISSUE TITLE
LaTeX Error: File `adjustbox.sty' not found.

### ISSUE THREAD

**Issue by Tagar** [jupyter/nbconvert#357]
Getting following error in jupyter logs when trying to save jupyter notebook as a PDF.

> [I 15:23:19.317 NotebookApp] Writing 62956 bytes to notebook.tex
> [I 15:23:19.317 NotebookApp] Building PDF
> [I 15:23:19.318 NotebookApp] Running pdflatex 3 times: [u'pdflatex', u'notebook.tex']
> [C 15:23:19.388 NotebookApp] pdflatex failed: [u'pdflatex', u'notebook.tex']
>     This is pdfTeXk, Version 3.141592-1.40.3 (Web2C 7.5.6)
>      %&-line parsing enabled.
>     entering extended mode
>     (./notebook.tex
>     LaTeX2e <2005/12/01>
>     Babel <v3.8h> and hyphenation patterns for english, usenglishmax, dumylang, noh
>     yphenation, arabic, basque, bulgarian, coptic, welsh, czech, slovak, german, ng
>     erman, danish, esperanto, spanish, catalan, galician, estonian, farsi, finnish,
>      french, greek, monogreek, ancientgreek, croatian, hungarian, interlingua, ibyc
>     us, indonesian, icelandic, italian, latin, mongolian, dutch, norsk, polish, por
>     tuguese, pinyin, romanian, russian, slovenian, uppersorbian, serbian, swedish,
>     turkish, ukenglish, ukrainian, loaded.
>     (/usr/share/texmf/tex/latex/base/article.cls
>     Document Class: article 2005/09/16 v1.4f Standard LaTeX document class
>     (/usr/share/texmf/tex/latex/base/size10.clo))
>     (/usr/share/texmf/tex/latex/graphics/graphicx.sty
>     (/usr/share/texmf/tex/latex/graphics/keyval.sty)
>     (/usr/share/texmf/tex/latex/graphics/graphics.sty
>     (/usr/share/texmf/tex/latex/graphics/trig.sty)
>     (/usr/share/texmf/tex/latex/config/graphics.cfg)
>     (/usr/share/texmf/tex/latex/pdftex-def/pdftex.def)))
> 
>     ! LaTeX Error: File `adjustbox.sty' not found.
> 
>     Type X to quit or <RETURN> to proceed,
>     or enter new name. (Default extension: sty)
> 
>     Enter file name:
>     ! Emergency stop.
>     <read *>
> 
>     l.19     \usepackage
>                         {color} % Allow colors to be defined^^M
>     !  ==> Fatal error occurred, no output PDF file produced!
>     Transcript written on notebook.log.
> 
> [I 15:23:19.390 NotebookApp] Running bibtex 1 time: [u'bibtex', u'notebook']
> [W 15:23:19.406 NotebookApp] bibtex had problems, most likely because there were no citations
> [I 15:23:19.408 NotebookApp] Running pdflatex 3 times: [u'pdflatex', u'notebook.tex']
> [C 15:23:19.457 NotebookApp] pdflatex failed: [u'pdflatex', u'notebook.tex']
>     This is pdfTeXk, Version 3.141592-1.40.3 (Web2C 7.5.6)
>      %&-line parsing enabled.
>     entering extended mode
>     (./notebook.tex
>     LaTeX2e <2005/12/01>
>     Babel <v3.8h> and hyphenation patterns for english, usenglishmax, dumylang, noh
>     yphenation, arabic, basque, bulgarian, coptic, welsh, czech, slovak, german, ng
>     erman, danish, esperanto, spanish, catalan, galician, estonian, farsi, finnish,
>      french, greek, monogreek, ancientgreek, croatian, hungarian, interlingua, ibyc
>     us, indonesian, icelandic, italian, latin, mongolian, dutch, norsk, polish, por
>     tuguese, pinyin, romanian, russian, slovenian, uppersorbian, serbian, swedish,
>     turkish, ukenglish, ukrainian, loaded.
>     (/usr/share/texmf/tex/latex/base/article.cls
>     Document Class: article 2005/09/16 v1.4f Standard LaTeX document class
>     (/usr/share/texmf/tex/latex/base/size10.clo))
>     (/usr/share/texmf/tex/latex/graphics/graphicx.sty
>     (/usr/share/texmf/tex/latex/graphics/keyval.sty)
>     (/usr/share/texmf/tex/latex/graphics/graphics.sty
>     (/usr/share/texmf/tex/latex/graphics/trig.sty)
>     (/usr/share/texmf/tex/latex/config/graphics.cfg)
>     (/usr/share/texmf/tex/latex/pdftex-def/pdftex.def)))
> 
>     ! LaTeX Error: File `adjustbox.sty' not found.
> 
>     Type X to quit or <RETURN> to proceed,
>     or enter new name. (Default extension: sty)
> 
>     Enter file name:
>     ! Emergency stop.
>     <read *>
> 
>     l.19     \usepackage
>                         {color} % Allow colors to be defined^^M
>     !  ==> Fatal error occurred, no output PDF file produced!
>     Transcript written on notebook.log.
> 

The version of the notebook server is 4.1.0 and is running on:
Python 2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

**Comment by Tagar** [comment]
Also created https://github.com/ipython/ipython/issues/9858

**Comment by takluyver** [comment]
You need the necessary latex packages, which we can't install for you. On my Fedora system, there's a texlive-adjustbox package. You may need others as well.

**Comment by Tagar** [comment]
Thank you @takluyver. I don't see texlive-adjustbox is available on RHEL.. Is this part of some of the following packages? :

> $ sudo yum list | grep texlive
> texlive.x86_64             2007-60.el6_7     @rhel6-x86_64-2016q2
> texlive-dvips.x86_64       2007-60.el6_7     @rhel6-x86_64-2016q2
> texlive-latex.x86_64       2007-60.el6_7     @rhel6-x86_64-2016q2
> texlive-texmf.noarch       2007-39.el6_7     @rhel6-x86_64-2016q2
> texlive-texmf-dvips.noarch 2007-39.el6_7     @rhel6-x86_64-2016q2
> texlive-texmf-errata.noarch
> texlive-texmf-errata-dvips.noarch
> texlive-texmf-errata-fonts.noarch
> texlive-texmf-errata-latex.noarch
> texlive-texmf-fonts.noarch 2007-39.el6_7     @rhel6-x86_64-2016q2
> texlive-texmf-latex.noarch 2007-39.el6_7     @rhel6-x86_64-2016q2
> texlive-utils.x86_64       2007-60.el6_7     @rhel6-x86_64-2016q2
> texlive-afm.x86_64         2007-60.el6_7     rhel6-server_optional-x86_64-2016q2
> texlive-context.x86_64     2007-60.el6_7     rhel6-server_optional-x86_64-2016q2
> texlive-dviutils.x86_64    2007-60.el6_7     rhel6-server_optional-x86_64-2016q2
> texlive-east-asian.x86_64  2007-60.el6_7     rhel6-server_optional-x86_64-2016q2
> texlive-texmf-afm.noarch   2007-39.el6_7     rhel6-server_optional-x86_64-2016q2
> texlive-texmf-context.noarch
> texlive-texmf-doc.noarch   2007-39.el6_7     rhel6-server_optional-x86_64-2016q2
> texlive-texmf-east-asian.noarch
> texlive-texmf-errata-afm.noarch
> texlive-texmf-errata-context.noarch
> texlive-texmf-errata-doc.noarch
> texlive-texmf-errata-east-asian.noarch
> texlive-texmf-errata-xetex.noarch
> texlive-texmf-xetex.noarch 2007-39.el6_7     rhel6-server_optional-x86_64-2016q2
> texlive-xetex.x86_64       2007-60.el6_7     rhel6-server_optional-x86_64-2016q2
>

**Comment by takluyver** [comment]
It might be! Sorry, I don't know much about Redhat packages or Texlive. However, if those `2007` numbers indicate a year, that's a pretty old version of the code. You might need to use a third party repo to get a newer version.

**Comment by Tagar** [comment]
> However, if those 2007 numbers indicate a year, that's a pretty old version of the code.
Redhat is overconservative when it comes to versions :-) 

Thanks anyway. Will report here if I figuire this out.

**Comment by gnestor** [comment]
I was able to resolve this error by installing the full version of [mactex](https://tug.org/mactex/mactex-download.html) vs. [basictex](https://tug.org/mactex/morepackages.html) (I'm using OS X so you would need to find the equivalent packages for Linux). See https://github.com/jupyter/notebook/issues/1674#issuecomment-247434332. Let us know what works for you!

**Comment by Tagar** [comment]
Thank you @gnestor -  I will give it a try.

First quick look at list of available packages doesn't reveal an equivalent for a "full version" like mactex:

> $ sudo yum list | grep tex | grep -v text
> tex-preview.noarch                   11.85-10.el6           @rhel6-x86_64-2016q2
> texlive.x86_64                       2007-60.el6_7          @rhel6-x86_64-2016q2
> texlive-dvips.x86_64                 2007-60.el6_7          @rhel6-x86_64-2016q2
> texlive-latex.x86_64                 2007-60.el6_7          @rhel6-x86_64-2016q2
> texlive-texmf.noarch                 2007-39.el6_7          @rhel6-x86_64-2016q2
> texlive-texmf-afm.noarch             2007-39.el6_7          @rhel6-server_optional-x86_64-2016q2
> texlive-texmf-dvips.noarch           2007-39.el6_7          @rhel6-x86_64-2016q2
> texlive-texmf-errata.noarch          2007-7.1.el6           @rhel6-x86_64-2016q2
> texlive-texmf-errata-afm.noarch      2007-7.1.el6           @rhel6-server_optional-x86_64-2016q2
> texlive-texmf-errata-dvips.noarch    2007-7.1.el6           @rhel6-x86_64-2016q2
> texlive-texmf-errata-fonts.noarch    2007-7.1.el6           @rhel6-x86_64-2016q2
> texlive-texmf-errata-latex.noarch    2007-7.1.el6           @rhel6-x86_64-2016q2
> texlive-texmf-fonts.noarch           2007-39.el6_7          @rhel6-x86_64-2016q2
> texlive-texmf-latex.noarch           2007-39.el6_7          @rhel6-x86_64-2016q2
> texlive-utils.x86_64                 2007-60.el6_7          @rhel6-x86_64-2016q2
> emacs-auctex.noarch                  11.85-10.el6           rhel6-x86_64-2016q3
> emacs-auctex-doc.noarch              11.85-10.el6           rhel6-server_optional-x86_64-2016q3
> emacs-auctex-el.noarch               11.85-10.el6           rhel6-server_optional-x86_64-2016q3
> ghc-texmath.x86_64                   0.6.0.6-1.el6          epel
> ghc-texmath-devel.x86_64             0.6.0.6-1.el6          epel
> gnuplot-latex.noarch                 4.2.6-2.el6            rhel6-server_optional-x86_64-2016q3
> gnuplot44-latex.x86_64               4.4.2-2.el6            epel
> jadetex.noarch                       3.13-8.el6             rhel6-x86_64-2016q3
> latex2emf.x86_64                     1.0.0-9.el6            epel
> latex2html.noarch                    2008-4.el6             rhel6-server_optional-x86_64-2016q3
> latex2rtf.x86_64                     2.3.10-1.el6.1         epel
> mimetex.x86_64                       1.74-1.el6             epel
> openoffice.org-ooolatex.x86_64       4.0.0-0.13.beta2.el6   epel
> passivetex.noarch                    1.25-11.el6            rhel6-x86_64-2016q3
> root-cintex.x86_64                   5.34.36-1.el6          epel
> rubygem-robotex.noarch               1.0.0-12.el6           epel
> rubygem-robotex-doc.noarch           1.0.0-12.el6           epel
> tetex-tex4ht.x86_64                  1.0.2008_09_16_1413-6.el6
> tex-cm-lgc.noarch                    0.5-17.1.el6           rhel6-x86_64-2016q3
> tex-kerkis.noarch                    2.0-23.el6             rhel6-x86_64-2016q3
> texi2html.noarch                     1.82-5.1.el6           rhel6-server_optional-x86_64-2016q3
> texinfo.x86_64                       4.13a-8.el6            rhel6-x86_64-2016q3
> texinfo-tex.x86_64                   4.13a-8.el6            rhel6-server_optional-x86_64-2016q3
> texlive-afm.x86_64                   2007-60.el6_7          rhel6-server_optional-x86_64-2016q3
> texlive-dviutils.x86_64              2007-60.el6_7          rhel6-server_optional-x86_64-2016q3
> texlive-east-asian.x86_64            2007-60.el6_7          rhel6-server_optional-x86_64-2016q3
> texlive-texmf-doc.noarch             2007-39.el6_7          rhel6-server_optional-x86_64-2016q3
> texlive-texmf-east-asian.noarch      2007-39.el6_7          rhel6-server_optional-x86_64-2016q3
> texlive-texmf-errata-doc.noarch      2007-7.1.el6           rhel6-server_optional-x86_64-2016q3
> texlive-texmf-errata-east-asian.noarch
> texlive-texmf-errata-xetex.noarch    2007-7.1.el6           rhel6-server_optional-x86_64-2016q3
> texlive-texmf-xetex.noarch           2007-39.el6_7          rhel6-server_optional-x86_64-2016q3
> texlive-xetex.x86_64                 2007-60.el6_7          rhel6-server_optional-x86_64-2016q3
> xmltex.noarch                        20020625-16.el6        rhel6-x86_64-2016q3
> xmlto-tex.noarch                     0.0.23-3.el6           rhel6-x86_64-2016q3
>

**Comment by gnestor** [comment]
@Tagar You're right. I created https://github.com/jupyter/nbconvert/issues/411 to add TeX installation instructions to the docs. Let's move the conversation there and once you have the right package(s) installed, we can revisit this issue.
