### ISSUE TITLE
The highlight.py filter uses IPython -- setup.py doesn't declare it

### ISSUE THREAD

**Issue by SnarkBoojum** [jupyter/nbconvert#358]
While packaging nbconvert for Debian, I was hit by the fact that its setup.py doesn't declare any dep on ipython, even though (1) it does have a dep on it and (2) it needs to be a recent enough ipython.

Indeed, when checking my nbconvert package with my ipython 5.0.0 package available at home, everything went smoothly, but when I sent the result for validation to the Debian build bots, they only found the ancient ipython 2.4.1 package and the tests failed at each place "from IPython.lib.lexers import ..." was used, as there is no module lexers in there.

I suggest setup.py should declare a suitable versioned dep.

**Comment by minrk** [comment]
IPython is not strictly a dependency. IPython lexers are loaded only if IPython is used in the given notebook, so IPython is only a dependency if IPython is already being used in notebooks.

**Comment by SnarkBoojum** [comment]
A weak dep would be : try to open a notebook and get a clear and clean error message stating what I lack to actually run it. Here I actually get a crash, so I think it's a pretty strict dep.

**Comment by michaelpacer** [comment]
@minrk Is there a way to declare a conditional dependency? I.e., if `ipython` is available at all it must be of version ≥x?

**Comment by minrk** [comment]
The dependency depends on what language the notebooks are in. This error doesn't come up if you use Julia or Ruby notebooks, for example.

You can express conditional dependencies via setuptools' 'extras' feature, but I don't think that's what we should do here.

I opened #405 to turn the import errors into warnings, so it's clearer that it's optional and an enhancment, not a dependency.
