### ISSUE TITLE
Better support metadata overriding script export with externally provided exporter

### ISSUE THREAD

**Issue by takluyver** [jupyter/nbconvert#361]
At IRkernel/IRkernel#394, we're discussing providing a custom script exporter, to be declared in notebook metadata in the `nbconvert_exporter` field. We would provide this as a separate package and register the exporter as an entry point. However, if someone attempts to nbconvert to a script without the exporter package installed, I think it will currently fail.

We could:
- Catch the failure in `ScriptExporter` and fall back to plain script export.
- Add a metadata field to specify a Python package to install for the exporter. However, we'd have to work out how to present this, because doing it the obvious way opens an arbitrary code execution hole from nbconvert.

**Comment by michaelpacer** [comment]
@takluyver Is there a reason for this to be on 4.3 instead of 5.0? I think 5.0 is being released soon and this would seem to be more than a tiny bug fix (i.e., it should involve a few tests regardless of how we decide to implemement it), meaning that it would fit better with the main release. 

As for actually delivering on the feature, is there an example of a custom exporter in the vein of `nbconvert_export_r` per https://github.com/IRkernel/IRkernel/issues/394 to use in the development of this feature? If not, might this even be better as a 5.1 release since developing it and making sure it not only works in that case but for at least two kinds of custom exporter… 

Also, could you say more about the obvious way to do it and why that would create an arbitrary code execution hole? It would seem that the example given in [the "registering custom exporters as entry points" docs](http://nbconvert.readthedocs.io/en/latest/external_exporters.html#registering-a-custom-exporter-as-an-entry-point) would open this hole as well.

**Comment by takluyver** [comment]
Milestones: my assignment wasn't anything definite or final, especially if we're planning nbconvert 5 soonish. I just didn't want it lingering too long.

Examples: at present, [tpllib](https://pypi.python.org/pypi/tpllib/0.0.1) is the only example of a separately packaged exporter I know of, and it doesn't declare an entry point. We should be able to knock together an example easily enough, though.

Security holes: Again, it's a matter of expectations and trust. If you `pip install` an external package for an exporter, we presume you understand the implications of installing a package from the internet.

The 'obvious way' I was referring to would be to add a field to the kernel info metadata, e.g. `"script_exporter_package": "nbconvert_export_r"`. When you did `jupyter nbconvert --to script`, it would automatically `pip install nbconvert_export_r` before trying to load the exporter. This is problematic because nbconvert is not an operation you expect to start installing and executing arbitrary code.

A slightly better way would be to present a message along the lines of:

> This notebook requests the package nbconvert_export_r to export it to a script. To use that: pip install nbconvert_export_r

That way the user has to explicitly install something, but there's still a risk that they think it's part of nbconvert, and don't consider that the notebook might be trying to get them to install something malicious.

**Comment by michaelpacer** [comment]
So what would this require changing? 

Adding the field to the metadata, and then adding a function to the script exporter that catches if the required package does not exist?

**Comment by takluyver** [comment]
If we're happy with the idea of showing a message suggesting the user installs a third party package, then yes, that should be it. Though it would be catching the absence of an entry point rather than a package, because the entry point is what it will look for.

**Comment by michaelpacer** [comment]
The change to the kernel info metadata, that would happen where? in the notebook repo? nbformat repo?  

To test the nbconvert compatibility with this feature would just require having a notebook with custom metadata of the correct form that raises the correct kind of error when it is called? Then everything else is a matter of the extension being written correctly…i.e., nothing more falls on nbconvert?

so in terms of action items 

- [ ] script exporter needs to look for "script_exporter_package" key
- [ ] script exporter needs to attempt to load value associated with "script_exporter_package"
- [ ] if no exporter is found for the value, it should err and tell people to pip install
- [ ] script exporter needs to be shortcircuited to use the correct exporter if an appropriate exporter is found

I think the last one is going to be trickiest.

**Comment by takluyver** [comment]
The only actual changes to code would be in nbconvert, I think, but we'd probably make docs changes in jupyter_client for the messages ([here](http://jupyter-client.readthedocs.io/en/latest/messaging.html#kernel-info)) and in nbformat ([here](http://nbformat.readthedocs.io/en/latest/format_description.html#notebook-metadata) - currently missing `language_info` entirely).

> script exporter needs to attempt to load value associated with "script_exporter_package"

Not quite. The script exporter [already attempts to find](https://github.com/jupyter/nbconvert/blob/fe7b0370d7c7ec35806f777c073c495612f9f61f/nbconvert/exporters/script.py#L24) an exporter based on the `nbconvert_exporter` package, i.e. using entry points. The only change should be that if that fails, and there is a key `nbconvert_exporter_package`, it gives an error message suggesting that the user `pip install {nbconvert_exporter_package}`.

**Comment by michaelpacer** [comment]
It looks like that metadata documentation for the `nbformat` needs a lot of love. I made https://github.com/jupyter/nbformat/issues/47 and will fix that. 

Also, I see what you're getting at now…I'm having difficulty thinking of how to test this without a functioning `nbconvert_exporter_package` that isn't part of the core. I could take the time to figure out how to write a generic one, but it feels like that shouldn't be necessary to get this off the ground…

however, this approach is way simpler than what I was thinking, so a PR should be on its way soon.

**Comment by takluyver** [comment]
For automated tests, we can just create a notebook with faked metadata like:

```json
"nbconvert_exporter": "this_doesnt_exist",
"nbconvert_exporter_package": "do_you_see_me",
```

Then try converting it to a script, and check that the error message includes something like `install do_you_see_me`.

**Comment by Carreau** [comment]
Hum, would it be better to have entry points that map language to exporters for "Script"  instead of doing on a per-notebook thing ?

I would assume if you install `nbconvert_export_r` you want all your R notebook to use that, right ?

**Comment by Carreau** [comment]
Also we should remove the `python`  special casing in favor of this map as well.

**Comment by takluyver** [comment]
I don't think we do special case Python - it already uses this mechanism:

https://github.com/jupyter/nbconvert/blob/master/nbconvert/exporters/script.py

**Comment by michaelpacer** [comment]
I don't know how to proceed on this. 

I'm going to start the release process for 5.0. If this is something we want to have included, @Carreau it would help if we could sit down and talk through what you both are suggesting as the improved solution.

**Comment by MSeal** [comment]
I am removing the milestone as it keep creeping up but no development has been made to implement any of the ideas above.

**Comment by rgbkrk** [comment]
Since this has been on the docket since 2016 with no progress, I'm just closing this. Feel free to re-open if you think it's good for someone to tackle.

**Comment by pvtodorov** [comment]
Is it still impossible to use nbcovert with IRkernel?
