### ISSUE TITLE
rst template does not respect language notebook is written when creating code blocks

### ISSUE THREAD

**Issue by michaelpacer** [jupyter/nbconvert#366]
Based on @takluyver in https://github.com/jupyter/nbconvert/issues/47#issuecomment-113670318 it seems that the rst template is wrong. 

We need to change 
https://github.com/jupyter/nbconvert/blob/master/nbconvert/templates/rst.tpl#L12 to infer the language of the notebook, but should it be inferring the language the notebook is written in on the basis of `metadata.kernelspec.language`, `metadata.language_info.codemirror_mode.name` or `metadata.language_info.name`?

@takluyver or @Carreau can you point to another instance where the jinja template inspects the notebook metadata directly? I'd rather learn jinja bit by bit rather than trying to understand it all at once, so basing this off a known example would be better than trying to figure out how to do this from scratch (especially if there is more than one way to do this).

**Comment by takluyver** [comment]
I think the language names in rst are used to identify pygments lexers, so it should use `pygments_lexer` first and then fall back to `name` if that's not defined. Both `pygments_lexer` and `codemirror_mode` are used to specify overrides if name doesn't identify the correct higlighting for the respective systems.

**Comment by michaelpacer** [comment]
So in the test notebook files, many of them have neither a `pygments_lexer` nor a `codemirror_mode` key in their JSON representation. GitHub seems to be displaying them without difficulty (e.g., [notebook2](https://github.com/jupyter/nbconvert/blob/master/nbconvert/tests/files/notebook2.ipynb) has no mention of `pygments` `codemirror` or even an associated kernel), so I'm guessing these are not required by the notebook format spec, and am not sure where the formatting instructions are coming from. 

Should I be using some other set of notebooks other than the test notebooks to be thinking through this problem? I figured since they were backing our tests that they were the notebooks I should turn to in order to ensure that I'm following all currently supported versions of the notebook formatting spec. 

Also, if you can't point me to an example of where jinja pulls arguments from the notebook's metadata, could you point me to the pieces of code that handle processing the notebook through jinja? I can try to figure out how that works and reverse engineer the changes that need to be made to fix this case?

**Comment by takluyver** [comment]
>  many of them have neither a pygments_lexer nor a codemirror_mode key ...  I'm guessing these are not required by the notebook format spec

Right, they're only necessary if they have to be something other than `language_info.name`. http://jupyter-client.readthedocs.io/en/latest/messaging.html#kernel-info . In most cases, the string we're using as the language name should work to identify its highlighting, so we don't the extra keys.

However, notebooks created with the IPython kernel should have at least `codemirror_mode`, and if the notebooks you're looking at don't, it may simply be that they haven't been opened and saved for quite a long time.

> can you point to another instance where the jinja template inspects the notebook metadata directly?

Here you are:
https://github.com/jupyter/nbconvert/blob/20c5aa1dd93677f8d8c7c79106be54be0ee80b83/nbconvert/templates/markdown.tpl#L11

**Comment by michaelpacer** [comment]
Ah so by `name` you meant `language_info.name`, got it. 

So, if you look at [notebook2](https://raw.githubusercontent.com/jupyter/nbconvert/master/nbconvert/tests/files/notebook2.ipynb), it has none of `language_info.name`, `codemirror_mode`, and `pygments_lexer` keys.

Should that be raising an error? Is this not important enough to worry about it since we could fix it just by opening and resaving the example notebooks?

And grazie for the example. Where are the variable names defined as they'll be shown to jinja; are they just passed through in [coalescestreams.py](https://github.com/jupyter/nbconvert/blob/master/nbconvert/preprocessors/coalescestreams.py#L31)?

**Comment by takluyver** [comment]
> So, if you look at notebook2, it has none of language_info.name, codemirror_mode, and pygments_lexer keys.

And it does have 'signature' in the metadata, which we no longer write into the notebook. That hasn't been saved in a while.

> Should that be raising an error? Is this not important enough to worry about it since we could fix it just by opening and resaving the example notebooks?

We're generally more tolerant of differing info in metadata than in the rest of the notebook format, because metadata is a place to put arbitrary info. So it shouldn't raise an error on loading the notebook. Maybe some more automation or checks to keep the test notebooks up to date would be useful, but not necessarily.

> And grazie for the example. Where are the variable names defined as they'll be shown to jinja; are they just passed through in coalescestreams.py?

- `nb` and `resources` are explicitly [passed in](https://github.com/jupyter/nbconvert/blob/20c5aa1dd93677f8d8c7c79106be54be0ee80b83/nbconvert/exporters/templateexporter.py#L209) to the template rendering.
- Parts of the notebook, like `cell` and `output`, are defined by loops in one of the base template files.
- Functions the template can use are 'filters'; template exporters have a [default_filters()](https://github.com/jupyter/nbconvert/blob/20c5aa1dd93677f8d8c7c79106be54be0ee80b83/nbconvert/exporters/templateexporter.py#L272) method defining these.

**Comment by michaelpacer** [comment]
So, the example you linked to makes me think that that actually is not going to respect the `pygments_lexer` or `codemirror_mode` values, should that also be fixed as part of a PR solving this?

**Comment by takluyver** [comment]
I don't think so. For rst, we ~know that the language will be used by
docutils to select a pygments lexer, so it makes sense to use
pygments_lexer if it's present. I don't know of any other systems to render
rst. Markdown can be rendered by many different systems, which may use
neither Pygments nor CodeMirror, so using the generic language name makes
sense.

**Comment by michaelpacer** [comment]
maybe could we specify a hierarchy of specificity? The reason I suggest it is that it might be an indirect way to handle the original issue wrt code blocks that are initialised with a magic. If there is a hierarchy in place that determines the highlighting for specific cells then it would be a matter of matching the specified magic to a pygments_lexer/generic language name.

**Comment by michaelpacer** [comment]
Closed by #372 and https://github.com/jupyter/nbconvert/pull/378
