### ISSUE TITLE
Use import_item from traitlets

### ISSUE THREAD

**Issue by juhasch** [jupyter/nbconvert#369]
`export_item` from ipython_genutils does not like Unicode under Python 2.7 files, which breaks nbconvert reading JSON config files:
https://github.com/ipython/ipython_genutils/pull/8

Use `export_items` from traitlets instead.
@takluyver : Should I create a PR for this ?

**Comment by takluyver** [comment]
Yup, if you could make a PR, that would be great, thanks. If you haven't
already, also make an issue/pr on traitlets to document it as explicitly
public API. Thanks!

**Comment by juhasch** [comment]
See
https://github.com/jupyter/nbconvert/pull/370
and
https://github.com/ipython/traitlets/pull/283

**Comment by takluyver** [comment]
Fixed by #370
