### ISSUE TITLE
Anchors in reveal

### ISSUE THREAD

**Issue by akhmerov** [jupyter/nbconvert#37]
Markdown heading anchors carry over to slides, where they have no effect due to being overridden. Their presence leads to visual junk on mouseover, and the slides jump to start when an anchor is accidentally clicked.

I guess removing anchor generation in `markdown2html` would be a solution.

**Comment by damianavila** [comment]
I agree... it could be some visual junk... removing anchors is an option... we can do it also by css I guess... we should explore both solutions...

**Comment by akhmerov** [comment]
As a hotfix, putting `a.anchor-link{display:none}` into custom.css removes them, but perhaps modifying the filters would be a cleaner solution. Reveal is quite reasonable to edit in source, which means there's merit in keeping the source code minimal.

**Comment by damianavila** [comment]
> As a hotfix, putting a.anchor-link{display:none}

Yes, this is the fix we use in RISE, although I agree the other solution can be cleaner... but less "customizable" also. I guess I will explore the filter solution to see if I am happy enough :wink:

**Comment by akhmerov** [comment]
Seems like making a subclassed `IPythonRenderer` by removing `add_anchor` from https://github.com/jupyter/nbconvert/blob/master/nbconvert/filters/markdown_mistune.py#L105 should be sufficient. Unfortunately I don't quite have time to figure out how to install the `master` of everything, and I don't know where would the modification belong.

**Comment by damianavila** [comment]
Yes, it is a possible solution... but I feel it adds too much complexity for something easy to fix with one line css modification in the slides_reveal template...

**Comment by akhmerov** [comment]
It's probably under 10 lines of code, and it does produce cleaner output. The reveal output already has multiple css overrides, and piling them up seems a fragile implementation.

**Comment by damianavila** [comment]
Well... fragile as any of the other css overrides... but ok, maybe I thinking this in a complex way? I will try to research into your idea...
