### ISSUE TITLE
Download as pdf and nbconvert to pdf fail

### ISSUE THREAD

**Issue by michael-nichols** [jupyter/nbconvert#373]
Using OS X El Cap 10.11.6. 

Failed to convert .ipynb to .pdf using "Download As pdf via LateX" using the menu commands. Also failed to convert using jupyter nbconvert --to=pdf Notebook.ipynb via terminal. I can't recall the first error in the long line of errors but I've installed BasicTex for Mac, Pandoc, and "all" fonts using tlmgr update --all . I tried using XeLateX. I think the font issue is worked out (still not 100% convinced though). I CAN convert to LateX using  jupyter nbconvert --to=latex Notebook.ipynb. The error I get when converting to pdf is as follows (same error for browser and command line): 

nbconvert failed: PDF creating failed, captured latex output:
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./notebook.tex
LaTeX2e <2016/03/31>
Babel <3.9r> and hyphenation patterns for 22 language(s) loaded.
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/base/size11.clo))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/base/fontenc.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/base/t1enc.def))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/psnfss/palatino.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/pdftex-def/pdftex.def
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/oberdiek/ltxcmds.sty))))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/caption/caption.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/caption/caption3.sty))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/adjustbox/adjustbox.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/xkeyval/xkvutils.tex)))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/adjustbox/adjcalc.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/adjustbox/trimclip.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/collectbox/collectbox.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/adjustbox/tc-pdftex.def)))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/graphics-cfg/color.cfg))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/tools/enumerate.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/amsfonts/amssymb.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/base/textcomp.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/base/ts1enc.def))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/upquote/upquote.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/eurosym/eurosym.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/ucs/ucs.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/ucs/data/uni-global.def))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/base/inputenc.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/ucs/utf8x.def))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
Style option:`fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
<2008/02/07> (tvz))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/oberdiek/grffile.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/oberdiek/etexcmds.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.s
ty
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/oberdiek/hobsub-generic.st
y)) (/usr/local/texlive/2016basic/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/url/url.sty))

Package hyperref Message: Driver (autodetected): hpdftex.

(/usr/local/texlive/2016basic/texmf-dist/tex/latex/hyperref/hpdftex.def
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty)
) (/usr/local/texlive/2016basic/texmf-dist/tex/latex/tools/longtable.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/booktabs/booktabs.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/ulem/ulem.sty)
No file notebook.aux.
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/base/ts1cmr.fd)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/psnfss/t1ppl.fd)
(/usr/local/texlive/2016basic/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/local/texlive/2016basic/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/oberdiek/grfext.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg
)) (/usr/local/texlive/2016basic/texmf-dist/tex/latex/caption/ltcaption.sty)
_geometry_ driver: auto-detecting
_geometry_ detected driver: pdftex
_geometry_ verbose mode - [ preamble ] result:
- driver: pdftex
- paper: <default>
- layout: <same size as paper>
- layoutoffset:(h,v)=(0.0pt,0.0pt)
- modes: 
- h-part:(L,W,R)=(72.26999pt, 469.75502pt, 72.26999pt)
- v-part:(T,H,B)=(72.26999pt, 650.43001pt, 72.26999pt)
- \paperwidth=614.295pt
- \paperheight=794.96999pt
- \textwidth=469.75502pt
- \textheight=650.43001pt
- \oddsidemargin=0.0pt
- \evensidemargin=0.0pt
- \topmargin=-37.0pt
- \headheight=12.0pt
- \headsep=25.0pt
- \topskip=11.0pt
- \footskip=30.0pt
- \marginparwidth=59.0pt
- \marginparsep=10.0pt
- \columnsep=10.0pt
- \skip\footins=10.0pt plus 4.0pt minus 2.0pt
- \hoffset=0.0pt
- \voffset=0.0pt
- \mag=1000
- \@twocolumnfalse
- \@twosidefalse
- \@mparswitchfalse
- \@reversemarginfalse
- (1in=72.27pt=25.4mm, 1cm=28.453pt)

(/usr/local/texlive/2016basic/texmf-dist/tex/latex/ucs/ucsencs.def)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/oberdiek/gettitlestring.st
y)) (/usr/local/texlive/2016basic/texmf-dist/tex/latex/amsfonts/umsa.fd)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/amsfonts/umsb.fd)

LaTeX Warning: No \author given.

(/usr/local/texlive/2016basic/texmf-dist/tex/latex/psnfss/t1pcr.fd)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/psnfss/ts1pcr.fd) [1{/usr/lo
cal/texlive/2016basic/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]
<output_7_1.png, id=18, 373.395pt x 256.96pt> <use output_7_1.png> [2]
Underfull \hbox (badness 10000) in paragraph at lines 374--375

<output_9_1.png, id=25, 373.395pt x 256.96pt> <use output_9_1.png> [3 <./output
_7_1.png>]
Underfull \hbox (badness 10000) in paragraph at lines 400--401

<output_11_1.png, id=32, 373.395pt x 256.96pt> <use output_11_1.png> [4 <./outp
ut_9_1.png>]
Underfull \hbox (badness 10000) in paragraph at lines 426--427

<output_13_1.png, id=39, 368.37625pt x 256.96pt> <use output_13_1.png> [5 <./ou
tput_11_1.png>]
Underfull \hbox (badness 10000) in paragraph at lines 452--453

<output_15_1.png, id=46, 368.37625pt x 256.96pt> <use output_15_1.png> [6 <./ou
tput_13_1.png>]
Underfull \hbox (badness 10000) in paragraph at lines 479--480

<output_17_1.png, id=53, 373.395pt x 256.96pt> <use output_17_1.png> [7 <./outp
ut_15_1.png>]
Underfull \hbox (badness 10000) in paragraph at lines 507--508

[8 <./output_17_1.png>] <output_19_1.png, id=67, 425.59pt x 281.05pt>
<use output_19_1.png>
Underfull \hbox (badness 10000) in paragraph at lines 546--547

<output_20_0.png, id=68, 787.94376pt x 278.03876pt> <use output_20_0.png>
Underfull \hbox (badness 10000) in paragraph at lines 556--557

<output_22_0.png, id=69, 554.07pt x 101.37875pt> <use output_22_0.png> [9 <./ou
tput_19_1.png> <./output_20_0.png>]
Underfull \hbox (badness 10000) in paragraph at lines 569--570

Underfull \hbox (badness 10000) in paragraph at lines 592--592
[]\T1/ppl/b/n/10.95 Random Ex-plo-ration: Affine trans-for-ma-tions Pic-ture cr
edit:

Overfull \hbox (83.86125pt too wide) in paragraph at lines 592--592
\T1/ppl/b/n/10.95 https://en.wikipedia.org/wiki/Transformation_matrix#/media/Fi
le:2D_affine_transformation_matrix.svg 
<output_26_0.png, id=77, 456.70625pt x 608.2725pt> <use output_26_0.png>
[10 <./output_22_0.png>]
Underfull \hbox (badness 10000) in paragraph at lines 602--603

Overfull \hbox (215.87263pt too wide) in paragraph at lines 606--606
[]\T1/ppl/b/n/10.95 Picture Credit: http://scikit-image.org/docs/dev/api/skimag
e.transform.html?highlight=affine#skimage.transform.AffineTransform 
[11 <./output_26_0.png>] <output_28_0.png, id=92, 688.5725pt x 695.59875pt>
<use output_28_0.png>
Underfull \hbox (badness 10000) in paragraph at lines 616--617

[12 <./output_28_0.png>] <output_30_0.png, id=99, 271.0125pt x 256.96pt>
<use output_30_0.png>
Underfull \hbox (badness 10000) in paragraph at lines 642--643

<output_34_0.png, id=100, 557.08125pt x 204.765pt> <use output_34_0.png>
Underfull \hbox (badness 10000) in paragraph at lines 660--661

[13 <./output_30_0.png> <./output_34_0.png>]
<output_36_0.png, id=111, 685.56125pt x 145.54375pt> <use output_36_0.png>
Underfull \hbox (badness 10000) in paragraph at lines 698--699

! Missing $ inserted.
<inserted text> 
                $
l.706 ...(u+v)\cdot u +(u+v)\cdot v) \$(u+v)\cdot
                                                  (u+v) =
? 
! Emergency stop.
<inserted text> 
                $
l.706 ...(u+v)\cdot u +(u+v)\cdot v) \$(u+v)\cdot
                                                  (u+v) =
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on notebook.log.

Any help would be greatly appreciated. Thanks.

**Comment by michael-nichols** [comment]
I'm finally getting somewhere (at least I'm getting new errors). Turns out the formatting of the inline Latex has to be  just right to not throw errors. For example:

NO GOOD FORMATTING
###  "Standard unit vectors" for the positive coordinate axes of the XY plane are: 
$ e_1 =
\begin{bmatrix}
    1 \\[0.3em]
    0 
\end{bmatrix}
$ 

in the direction of the x-axis and 

$ e_2 =
\begin{bmatrix}
    0 \\[0.3em]
    1
\end{bmatrix}$ 

in the direction of the y-axis.

ACCEPTABLE FORMATTING 
###  "Standard unit vectors" for the positive coordinate axes of the XY plane are: $e_1=\begin{bmatrix}1\\[0.3em]0\end{bmatrix}$ in the direction of the x-axis and $e_2=\begin{bmatrix}0\\[0.3em]1\end{bmatrix}$ in the direction of the y-axis.

After fixing those errors, I am now getting the following error:

! TeX capacity exceeded, sorry [parameter stack size=10000].
\x@protect #1->
               \ifx \protect \@typeset@protect \else \@x@protect #1\fi 
l.807 ...atrix\} in the direction of the y-axis.}}
                                                  \label{standard-unit-vecto...

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on notebook.log.

**Comment by michael-nichols** [comment]
Turns out the culprit is the matrices. When all of the matrix code is removed, I can download as a pdf.

**Comment by michael-nichols** [comment]
Here is the markdown cell code and the error I get when trying to download as pdf:

Markdown cell code:

### "Standard unit vectors" for the positive coordinate axes of the XY plane are: $e_1=\begin{bmatrix}1\\0\end{bmatrix}$ in the direction of the x-axis and $e_2=\begin{bmatrix}0\\1\end{bmatrix}$ in the direction of the y-axis.

Error code:

! Argument of \@sect has an extra }.
<inserted text> 
                \par 
l.810 ...atrix\} in the direction of the y-axis.}}
                                                  \label{standard-unit-vecto...

? 
! Emergency stop.
<inserted text> 
                \par 
l.810 ...atrix\} in the direction of the y-axis.}}
                                                  \label{standard-unit-vecto...


I've tried formatting the markdown cell a bunch of different ways to no avail. Any help would be appreciated.

**Comment by michaelpacer** [comment]
Did you try to add proper column breaks (`&`) and line breaks (`\\`) to
your bmatrix environment?

Also, you have single backslashes in some odd places. E.g., I don't think
\1 should work as a valid LaTeX command. This is why things like \@ne had
to exist. If you fix those does that fix your problem?

Did you prototype your LaTeX code in LaTeXit first?

**Comment by michael-nichols** [comment]
Hello. Thanks for catching that. When I copied and pasted my code from my notebook to this comment, the comment treated my code as markdown code and is not displaying it correctly. I attempted to drag a screen shot of my code into this comment instead so it is clear what I've written. 

![screen shot 2016-08-23 at 9 29 22 pm](https://cloud.githubusercontent.com/assets/15163311/17915472/b950becc-6978-11e6-977e-a63e049990f3.png)

As you can see, the single backslashes are actually double backslashes (line breaks). Also, the matrices I'm working with are vectors and don't have any need for ('&'). 

The code actually works (formats) in Jupyter as shown below. 

![screen shot 2016-08-23 at 9 36 03 pm](https://cloud.githubusercontent.com/assets/15163311/17915599/b8dbb662-6979-11e6-8dac-bfb7eaa76541.png)

It just refuses to download as a pdf. 

I have prototyped in ShareLatex as well. That is how I narrowed my problem down to the matrices. I was able to fix/eliminate a bunch of the errors Jupyter threw at me using by going back and forth between Jupyter and ShareLatex. 

Thanks for your help.

**Comment by michaelpacer** [comment]
Hi @michael-nichols, so I just ran your example, and I have no issues building a pdf with it. 

![image](https://cloud.githubusercontent.com/assets/2482408/18371190/4375c14a-75e7-11e6-9628-61ba30bc7906.png)

![image](https://cloud.githubusercontent.com/assets/2482408/18371181/35ccdace-75e7-11e6-90d2-befa32a2f6bc.png)

Did you try this on master?

**Comment by michael-nichols** [comment]
Please excuse my ignorance as I'm a git noob. I am not sure where I am relative to the master branch as I installed Jupyter using Anaconda. For good measure I just ran:
conda update conda
and 
conda update jupyter 
These did not help the pdf problem. I also noticed that your running Python 3 while I am using:
Python 2.7.12 :: Anaconda 4.1.1 (x86_64)

Here is a screenshot of Jupyter.
![screen shot 2016-09-09 at 4 46 51 pm](https://cloud.githubusercontent.com/assets/15163311/18402436/560f9184-76ad-11e6-969c-2307e40ba5bc.png)

Thanks again for your help. I recently started using a workaround where I download the notebook as html and then convert that to pdf. Unfortunately the python code ends up black and white using this method.  

Below is the error I get when trying to download as pdf using the same example your ran.

nbconvert failed: PDF creating failed, captured latex output:
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./notebook.tex
LaTeX2e <2016/03/31>
Babel <3.9r> and hyphenation patterns for 22 language(s) loaded.
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/base/size11.clo))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/base/fontenc.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/base/t1enc.def))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/psnfss/palatino.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/pdftex-def/pdftex.def
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/oberdiek/ltxcmds.sty))))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/caption/caption.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/caption/caption3.sty))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/adjustbox/adjustbox.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/xkeyval/xkvutils.tex)))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/adjustbox/adjcalc.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/adjustbox/trimclip.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/collectbox/collectbox.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/adjustbox/tc-pdftex.def)))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/graphics-cfg/color.cfg))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/tools/enumerate.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/amsfonts/amssymb.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/base/textcomp.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/base/ts1enc.def))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/upquote/upquote.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/eurosym/eurosym.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/ucs/ucs.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/ucs/data/uni-global.def))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/base/inputenc.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/ucs/utf8x.def))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
<2008/02/07> (tvz))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/oberdiek/grffile.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/oberdiek/etexcmds.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty))
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.s
ty
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/oberdiek/hobsub-generic.st
y)) (/usr/local/texlive/2016basic/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/url/url.sty))

Package hyperref Message: Driver (autodetected): hpdftex.

(/usr/local/texlive/2016basic/texmf-dist/tex/latex/hyperref/hpdftex.def
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty)
) (/usr/local/texlive/2016basic/texmf-dist/tex/latex/tools/longtable.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/booktabs/booktabs.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/ulem/ulem.sty)
No file notebook.aux.
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/base/ts1cmr.fd)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/psnfss/t1ppl.fd)
(/usr/local/texlive/2016basic/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/local/texlive/2016basic/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/oberdiek/grfext.sty)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg
)) (/usr/local/texlive/2016basic/texmf-dist/tex/latex/caption/ltcaption.sty)
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
*geometry* verbose mode - [ preamble ] result:
* driver: pdftex
* paper: <default>
* layout: <same size as paper>
* layoutoffset:(h,v)=(0.0pt,0.0pt)
* modes: 
* h-part:(L,W,R)=(72.26999pt, 469.75502pt, 72.26999pt)
* v-part:(T,H,B)=(72.26999pt, 650.43001pt, 72.26999pt)
* \paperwidth=614.295pt
* \paperheight=794.96999pt
* \textwidth=469.75502pt
* \textheight=650.43001pt
* \oddsidemargin=0.0pt
* \evensidemargin=0.0pt
* \topmargin=-37.0pt
* \headheight=12.0pt
* \headsep=25.0pt
* \topskip=11.0pt
* \footskip=30.0pt
* \marginparwidth=59.0pt
* \marginparsep=10.0pt
* \columnsep=10.0pt
* \skip\footins=10.0pt plus 4.0pt minus 2.0pt
* \hoffset=0.0pt
* \voffset=0.0pt
* \mag=1000
* \@twocolumnfalse
* \@twosidefalse
* \@mparswitchfalse
* \@reversemarginfalse
* (1in=72.27pt=25.4mm, 1cm=28.453pt)

(/usr/local/texlive/2016basic/texmf-dist/tex/latex/ucs/ucsencs.def)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/local/texlive/2016basic/texmf-dist/tex/generic/oberdiek/gettitlestring.st
y)) (/usr/local/texlive/2016basic/texmf-dist/tex/latex/amsfonts/umsa.fd)
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/amsfonts/umsb.fd)

LaTeX Warning: No \author given.

! Missing $ inserted.
<inserted text> 
                $
l.283 ...atrix\} in the direction of the y-axis.}}
                                                  \label{standard-unit-vecto...

? 
! Emergency stop.
<inserted text> 
                $
l.283 ...atrix\} in the direction of the y-axis.}}
                                                  \label{standard-unit-vecto...

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on notebook.log.

**Comment by michaelpacer** [comment]
Just checked with a python 2 kernel and it also works. 

If you want to see if it works on master but you don't want to use the master for your everyday coding experiences (instead preferring a stable release), I would suggest creating a new conda env and use `pip install git+https://github.com/jupyter/nbconvert@master` to build the most recently released version from master. 

I think if you just wanted to update to master in place what you would do is add `-U` to that command, but I don't actually know how pip handles upgrades in the context of git sourced packages. My guess is since it's a higher version number (`5.0.0dev`) it'll work, but I don't really know.

**Comment by michaelpacer** [comment]
Hi Michael, did using 

pip install git+https://github.com/jupyter/nbconvert@master

and attempting to do this again fix your problem?

**Comment by michael-nichols** [comment]
​Hello Michael,

Sorry I am taking so long to give your fix a try. School has started and is
monopolizing all of my time. I will try to get to this as soon as I can.
Thanks a bunch. ​

*Mike Nichols*
University of Maine
Electrical Engineering
Orono, ME 04469
emailmikenichols@gmail.com

**Comment by t-makaro** [comment]
Closing as stale. Please comment asking to re-open if this is still an issue for you.

**Comment by Spandan-Madan** [comment]
Have the same issue. Here is my error stack -

```

Underfull \hbox (badness 10000) in paragraph at lines 612--613

[6]
Underfull \hbox (badness 10000) in paragraph at lines 617--618


Underfull \hbox (badness 10000) in paragraph at lines 622--623

[7]
Underfull \hbox (badness 10000) in paragraph at lines 627--628


! Package amsmath Error: \begin{align*} allowed only in paragraph mode.

See the amsmath package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.634     \(\begin{align*}
                           P(b=b_1,v=v_1) &= \frac{e^{-\theta_b}\theta_b^{b_...

? 
! Emergency stop.
 ...                                              
                                                  
l.634     \(\begin{align*}
                           P(b=b_1,v=v_1) &= \frac{e^{-\theta_b}\theta_b^{b_...

Output written on notebook.pdf (7 pages).
Transcript written on notebook.log.
```

I am guessing it has a problem handling my \begin{align*}\end{align*} blocks. Any tips on what might be going wrong?

**Comment by mgeier** [comment]
@Spandan-Madan If you use math *environments* (like `\begin{align*}`), you should *not* surround them by dollar signs.
