### ISSUE TITLE
Markdown convert adds empty row as first row

### ISSUE THREAD

**Issue by chrisalbon** [jupyter/nbconvert#376]
When converting an notebook to markdown, nbconvert adds a blank row as the first row of the file. Is there a reason for this?

To be honest my reasons for not wanting this first row are totally selfish. I convert many notebooks to markdown to use in Pelican and Pelican's md->html convert requires the first line be the title of the blog post (e.g. `Title: Beautiful Soup Basic HTML Scraping`) which is currently annoying via nbconvert because I have to manually delete the first row after nbconverting, before running pelican.

**Comment by takluyver** [comment]
I don't think it's deliberate, but probably an incautiously written [template](https://github.com/jupyter/nbconvert/blob/master/nbconvert/templates/markdown.tpl). Templating systems are most often used for HTML, where whitespace mostly doesn't matter, so it can be easy to overlook.
