### ISSUE TITLE
Local documentation build documentation out of date

### ISSUE THREAD

**Issue by mpacer** [jupyter/nbconvert#379]
The second instruction states to build the docs using a `requirements.txt` file that does not currently exist.

Right now there's an error due to the use of a bdist_egg based on however the docs are being built currently, which I have yet to suss out.

**Comment by willingc** [comment]
@michaelpacer The instructions are out of date and written before the use of conda in building on RTD. There is an out of date `requirements.txt` in the `docs` directory.

nbconvert is by far the most complicated build that we have. To build locally, I typically create a conda environment using ``conda env create -f environment.yml`` and then activate it.

Let's work together over the next couple of weeks to refine the instructions for building locally and on RTD and cobble together a short screencast/webcast specific to nbconvert.

**Comment by michaelpacer** [comment]
@willingc  That sounds like a good plan. I'll put it on the 5.1 milestone then.

**Comment by michaelpacer** [comment]
Also, I don't think that there is an out of date `requirements.txt` at least not that I can see…this is partly what evinced the extremity of my initial title, as the first line of the docs readme mentioned a file that was clearly not in the directory like it said it was.

**Comment by willingc** [comment]
You are absolutely correct that the out of date `requirements.txt` is no longer in the repo. Sorry! I had completely forgotten that we removed earlier this year in this PR #222 https://github.com/jupyter/nbconvert/pull/222/files

**Comment by takluyver** [comment]
The bit about `requirements.txt` got fixed - is there anything else to do for this, or can we close it?

**Comment by willingc** [comment]
Don't remember. I'm cool with closing if @mpacer agrees.

**Comment by MSeal** [comment]
Closing ticket as no one has chimed in on other missing out-of-date docs. Please reopen if there's anything still missing.
