### ISSUE TITLE
Unicode error leads to fatal error using MiKTeX

### ISSUE THREAD

**Issue by ThirstyGeo** [jupyter/nbconvert#384]
Hello, this is a similar issue to the one described at:
https://github.com/jupyter/nbconvert/issues/314#issuecomment-222130808

I am using the tqdm python library to display progress in a loop (see copy/paste below)
`100%|████████████████████████| 5000/5000 [00:09<00:00, 520.21it/s]`

Unfortunately this leads to a unicode error when using MiKTeX and _Download_ As--> _PDF via LaTeX_ (error replicated below). I see that the solution for issue#314  is to include a config file in the notebook directory. However, could it be requested to find a solution that instead allows nbconvert to handle this unicode character?

>    ! Package ucs Error: Unknown Unicode character 9608 = U+2588,
    (ucs)                possibly declared in uni-37.def.
    (ucs)                Type H to see if it is available with options.

    See the ucs package documentation for explanation.
    Type  H <return>  for immediate help.
     ...

    l.750 ...\ufffd█| 5000/5000 [00:09<00:00, 503.90it/s]

    ?
    ! Emergency stop.
     ...

    l.750 ...\ufffd█| 5000/5000 [00:09<00:00, 503.90it/s]

    !  ==> Fatal error occurred, no output PDF file produced!
    Transcript written on notebook.log.

**Comment by takluyver** [comment]
Did you try this in master, or a released version? In master, we have switched the default latex processor we use to xelatex, which is supposed to handle unicode better. So it may already be fixed.

**Comment by ThirstyGeo** [comment]
I'm currently using nbconvert 4.2.0

**Comment by ThirstyGeo** [comment]
An embarrassingly simple question: How to use pip for installing master? 
I'm new to git and command line package management, so hunted around for a method.
Most pip installs seem to point at a .zip or @branch..
Am I looking for something like this?

pip install https://github.com/jupyter/nbconvert/tree/master/nbconvert

**Comment by michaelpacer** [comment]
this should work: pip install git+https://github.com/jupyter/nbconvert@master

**Comment by michaelpacer** [comment]
and to be clear…not embarrassingly simple…I needed to look it up and just used the modified solution from: http://stackoverflow.com/questions/20101834/pip-install-from-github-repo-branch

**Comment by ThirstyGeo** [comment]
All is working fine after an update to version 5.0

Many thanks @takluyver and @michaelpacer
