### ISSUE TITLE
Arbitrary html is lost when notebooks are exported to LaTeX & PDF

### ISSUE THREAD

**Issue by dvigneshwer** [jupyter/nbconvert#388]
There are few problems I am facing with the export pdf function.

The PDF is getting generated but,
1. The markdown code is coming as such in the final pdf, the output is not populated in the pdf. ex: HTML output is not coming and html code is what's coming in the pdf format.
2. When the cell length is more than the width of the window (ie it's a big line of code), the pdf generated cuts the code which is not visible in the display.

How do i rectify these PDF export errors?

Simillar problems expressed with examples in https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jupyter/wGXAKnJKsuc/J9qJocVyEAAJ

**Comment by avinashmaheshjoshi** [comment]
Hi,

I have faced similar issues as well. Attaching a sample output from RStudio using RMarkdown and Jupyter using R kernel. Added a cell on top with html code to highlight the first problem. Also attached the snapshot of the notebook.

Notice the indentation offset in the Jupyter export to pdf.

![jupyter_notebook_snapshot](https://cloud.githubusercontent.com/assets/1736298/18190190/5ec52c1e-70de-11e6-8699-710a5b7ce7b0.png)
[test.pdf](https://github.com/jupyter/nbconvert/files/451036/test.pdf)

**Comment by takluyver** [comment]
Can you also attach the notebook you're converting from?

**Comment by avinashmaheshjoshi** [comment]
I am unable to upload the format. Tried zipping it as well. Doesn't allow me to upload here.

**Comment by takluyver** [comment]
Stick it in a gist or something.

**Comment by avinashmaheshjoshi** [comment]
Uploaded it on my public repo - https://github.com/avinashmaheshjoshi/avinash/blob/master/sample_R.ipynb

**Comment by michaelpacer** [comment]
@dvigneshwer @avinashmaheshjoshi 

Are you running off of the master branch or are you working off of the stable version. If you are working off of the stable version, could you check that it works using the nbconvert master?

Additionally, could you see if this occurs if you use a more limited set of html markup? I.e., if it is a problem with a particular feature that is causing the entire conversion pipeline to burst rather than something general, it will save a lot of time to know which feature is causing that.

**Comment by michaelpacer** [comment]
@avinashmaheshjoshi So I was suspicious when I saw that GitHub wasn't rendering your file, that there might be something wrong with it. 

When I try to open it on a notebook server, I'm told that it is not a properly formatted notebook json file

Specifically, `NotJSONError("Notebook does not appear to be JSON: '\\n<!DOCTYPE HTML>\\n<html>\\n\\n<head>\\n`

could you upload a version of your notebook that is appropriately formatted?

**Comment by michaelpacer** [comment]
It looks like you saved the notebook by using the browser's save feature, which saved it as an html document. This is not how you want to save a notebook. Use the save button under the File menu and upload that instead.

**Comment by avinashmaheshjoshi** [comment]
Sorry my bad. Uploaded the right notebook - https://github.com/avinashmaheshjoshi/avinash/blob/master/sample_R.ipynb

**Comment by michaelpacer** [comment]
@takluyver @Carreau So the issue seems to be that it is choking on the opening block which is plain html that happens to be in a markdown cell. Is the LaTeX converter supposed to handle arbitrary html markup as formatting to be interpreted as a LaTeX command? or just pure markdown formatting? I don't know if this is what's affecting @dvigneshwer but my guess is that the current markdown → LaTeX → pdf conversion is not able to handle arbitrary html which is why @avinashmaheshjoshi is running into problems.

**Comment by dvigneshwer** [comment]
Yeah @michaelpacer you make sense, I feel the same the html code in markdown cell is rendered properly in the browser but while in conversion it's not working and the same html code is being shown, as its not being handled.

But html gives the user more flexibility to make custom headers than markdown, so its an important feature to have.

Can you suggest me any hacks by which I can get the pdf converted properly so that I can share and print my research work.

**Comment by labeebee** [comment]
I stumbled upon this issue while researching on ways to format my notebook so that it doesn't truncate my markdown areas while trying to convert my notebook to pdf. I am facing a problem exactly same as that of @dvigneshwer  Any update in this regard? I also see that certain bullet styles fail in the pdf.

**Comment by jeb2239** [comment]
This is still an issue.

**Comment by gaurav-kaushik** [comment]
I am also experiencing this issue. 

jupyter --version
4.2.0
ipython --version
5.1.0

**Comment by ilemhadri** [comment]
As a temporary workaround, you may try converting your notebook to .html format first, then convert the .html to .pdf. This has solved the truncation issues I had been facing.

**Comment by labeebee** [comment]
Yes, that would temporarily solve the problem, I guess.

**Comment by mpacer** [comment]
nbconvert uses pandoc under-the-hood to do markdown → LaTeX conversion.

If you want that support you will need to talk to the [jgm/pandoc](https://github.com/jgm/pandoc) community, not nbconvert.

There is currently no separate plan to for nbconvert to support converting arbitrary html to LaTeX  to pdf conversion. Accordingly, I'm going to close & retitle this issue.

@ilemhadri if you're experiencing truncation issues, that shouldn't be related to using raw html in your markdown cells, could you open a different issue to track this as it is likely that it is unrelated? Thanks!

**Comment by mpacer** [comment]
All who were following this, I'm sorry that nbconvert won't be able to solve this problem for you. If you have suggestions for specific ways to address particular pieces of this problem, please open new issues or PRs either here or in pandoc. 

Additionally, if your issues are unrelated to including arbitrary html in your markdown cells, please open different issues that are more specifically tied to your concerns. We want to support your use cases, but in general the html → LaTeX problem is intractable and probably does not have unique solutions.

**Comment by ltatgnacode** [comment]
What about just printing the notebook via the browsers print function and then use a PDF driver. Im  doing that and it works fine - lost colors though

**Comment by takluyver** [comment]
There are tools that can automate that, like weasyprint and wkhtmltopdf. It would be possible to make an nbconvert PDF exporter which converts to HTML and uses one of those tools to make a PDF, if anyone is interested in having a go.
