### ISSUE TITLE
What is `_template_file_changed` used for?

### ISSUE THREAD

**Issue by michaelpacer** [jupyter/nbconvert#393]
This doesn't seem to be called by anything else in the codebase. Is it safe to remove since it was a private, unused API?

**Comment by minrk** [comment]
This is part of traitlets, and is called automatically whenever `template_file` changes.

**Comment by michaelpacer** [comment]
What is the context in which it would be used were it to be used? Just for caching and lazily reëxecuting things?

**Comment by minrk** [comment]
> What is the context in which it would be used were it to be used?

It is triggered when users specify a template other than the default.

**Comment by michaelpacer** [comment]
Does that mean it's triggered only at the command line? Or is it also triggered when nbconvert is used as a library/module? In the latter case, is it triggered on any "change" or just the first time because only the first time does it change from the default?

**Comment by takluyver** [comment]
It's triggered when nbconvert is used from Python as well, and on every change. If you do `x.template_file = 'foo.tpl'`, `_template_file_changed` is called.
