### ISSUE TITLE
No easy way to disable output prompts in HTML templates

### ISSUE THREAD

**Issue by takluyver** [jupyter/nbconvert#40]
The `output_prompt` block doesn't do anything in the HTML templates - there's a comment saying:

```
{# 
  output_prompt doesn't do anything in HTML,
  because there is a prompt div in each output area (see output block)
#}
```

The output prompts are generated inside the `output` block for an execute_result output, but there's no easy way (that I can see) to disable them in a subclass template.

**Comment by mpacer** [comment]
#554 takes care of this! Now you just say `--no-prompt` :)
