### ISSUE TITLE
More render options to paged media

### ISSUE THREAD

**Issue by ppKrauss** [jupyter/nbconvert#402]
Can I post an enhancement suggestion here?

---

LaTeX format is not an element of the  "HTML ecosystem" of open format standards.

Today with [CSS Fragmentation Module Level 3](https://www.w3.org/TR/css-break-3/) for paged media (and good EPUBs), not make sense to use LaTeX... But to generating [better (professional) PDF with with HTML+CSS](http://stackoverflow.com/a/21345708)  we need also good CSS control.  

Ideal is to offer  PDF options to use [other tools](https://print-css.rocks/intro.html), to render PDF with the new  CSS properties &mdash; as `break-before` and `break-after` and traditional   `@page` directives.

**Comment by takluyver** [comment]
I'm torn on which I dislike more, Latex or CSS ;-)

Thanks for the links, though. I have been contemplating other ways to convert notebooks to PDF, and I'll have a look at that info tomorrow.

**Comment by takluyver** [comment]
There is a new cert now, valid until 2018. Thanks, whoever sorted it out!

**Comment by takluyver** [comment]
Sorry, commenting in wrong tab...

**Comment by t-makaro** [comment]
Closing this issue as stale. There are other open issues talking about alternatives to convert to PDF.

**Comment by WolfgangFahl** [comment]
see #607  please reopen to make sure a page break solution is created that will cover HTML, PDF, Latex at the same time. I wonder how issues that are so important and 5-6 years old are simply closed for being stale.
