### ISSUE TITLE
Download as PDF: "nbconvert failed: pdflatex not found on PATH" on OS X El Capitan

### ISSUE THREAD

**Issue by gnestor** [jupyter/nbconvert#406]
It appears that the TeX binaries are are protected by OS X El Capitan's *rootless* feature and as a result `pdflatex` and others are not included in the PATH anymore ([source](http://tex.stackexchange.com/a/249967)). 

The workaround is to add the path to these binaries to the user path: `PATH=$PATH:/Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin` or permanently add it to the PATH by adding the following to `~/.bash_profile`:

```
### TeX
export PATH="/Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin:$PATH"
```

Follow up: Do all supported OSs (Linux, OS X, Windows) ship with `pdflatex` and provide it in the PATH by default? How can we make this work out-of-the-box for OSs that don't?

**Comment by takluyver** [comment]
> Do all supported OSs (Linux, OS X, Windows) ship with pdflatex and provide it in the PATH by default?

They very definitely do not. AFAIK most desktop Linux distros do not include Latex in a default install (though it's readily available), and Windows certainly doesn't.

> How can we make this work out-of-the-box for OSs that don't?

Reimplement Latex in pure Python? ;-)

Short of that, we probably cannot make it work out of the box in general.

**Comment by michaelpacer** [comment]
I would not consider OS X to ship a functioning version of a TeX distribution out of the box.

I don't know if any major OS does. 

However a lot of development goes into making the TeX package solutions like MacTeX and (TeXLive more generally) things that you can just install and will work in the face of system integrity protection or the rootless feature.

**Comment by gnestor** [comment]
Before installing anything, I received the `nbconvert failed: pdflatex not found on PATH` error. After installing basictex, I received the `File 'adjustbox.sty' not found` error. After upgrading to regular mactex, I was able to download a notebook as PDF.

I am closing this and creating https://github.com/jupyter/nbconvert/issues/411 to suggest adding TeX install instructions to the docs.

**Comment by tsando** [comment]
I still had to export the path as outlined by @gnestor to make it work, even after installing regular mactex
