### ISSUE TITLE
How to expose custom templates

### ISSUE THREAD

**Issue by mpacer** [jupyter/nbconvert#407]
From Conversation with @takluyver 

Include 
- [ ] boilerplate python code for custom exporter 
- [ ] mini-entrypoint explanation

Almost an infographic way of specifying that

**Comment by takluyver** [comment]
@michaelpacer here's a rough sketch of what I was thinking when I said infographic. The Python layer probably doesn't work exactly as I've sketched it at the moment, but the idea is to show how the different layers connect up.

![spr_176_r5016091511530](https://cloud.githubusercontent.com/assets/327925/18549482/a625a9b8-7b46-11e6-8c31-ed54d0eee750.jpg)

**Comment by t-makaro** [comment]
Closing as inactive / closed by #1028 which makes is easier to add custom templates.
