### ISSUE TITLE
Totally broken by recent change to traitlets

### ISSUE THREAD

**Issue by takluyver** [jupyter/nbconvert#41]
The default value for `Type` when no default specified changed from `None` to `object`, to make validation more consistent. However, nbconvert relies on the default for `NbconvertApp.postprocessor_factory` being None (or Falsy, at least).

This is simple to fix, I'm just contemplating the best way to do it.

**Comment by minrk** [comment]
Not sure, but `Type(None, allow_none=True)`?

**Comment by Carreau** [comment]
@parleur was looking for some easy to get started issues.
