### ISSUE TITLE
In exported Jupyter Notebooks, how do I disable the ¶?

### ISSUE THREAD

**Issue by nfultz** [jupyter/nbconvert#412]
Following up from my [SO question](http://stackoverflow.com/questions/39518136/in-exported-jupyter-notebooks-how-do-i-disable-the?noredirect=1#comment66369347_39518136), is there a way to not put pilcrows on headers?

**Comment by takluyver** [comment]
Hello again ;-)

This is currently not configurable, but it makes sense as a feature request.

**Comment by michaelpacer** [comment]
This seems like it should be pretty easily possible using traitlets since they're intrinsically configurable, @Carreau, let's set a time for us to talk through traitlets again so I can try to implement this.

**Comment by johnmathews** [comment]
Hello all, 
Just to say, I'd really like to see this feature added.

**Comment by nfultz** [comment]
@johnmathews I was able to remove the pilcrows by patching the markdown renderer:

    import mistune
    import nbconvert
    nbconvert.filters.markdown_mistune.IPythonRenderer.header = mistune.Renderer.header

However, this will break the table of contents extension. 

This isn't something I feel comfortable shipping in the nb2mail plugin, though, so this ticket should remain open.
