### ISSUE TITLE
don't drop content silently

### ISSUE THREAD

**Issue by amueller** [jupyter/nbconvert#425]
While debugging a lot of the nbconvert issues I had when writing my book, a common problem was that some content was silently dropped. You need to proof-read quite carefully to see that a particular figure or equation is missing.

Would it be possible to ensure that everything is rendered, or if not, (optionally) a warning is given?
I think what happened was usually that the template / exporter had no way to render a specific mime-type.

**Comment by takluyver** [comment]
Yes, it should be possible to add a warning in that case. The code that filters output types is here:
https://github.com/jupyter/nbconvert/blob/master/nbconvert/filters/datatypefilter.py

**Comment by michaelpacer** [comment]
Is #426 sufficient to address this issue?

**Comment by amueller** [comment]
awesome, thanks @michaelpacer! I'll check if that solves all my problems
