### ISSUE TITLE
Current docs build fails without tornado; does not create an editable install of nbconvert

### ISSUE THREAD

**Issue by michaelpacer** [jupyter/nbconvert#431]
The current documentation instructions will fail for two reasons:

1. tornado is not included in the environment.yml file and therefore ServePostProcessor cannot be imported resulting in an error. 
2. when you build the environment anew, it will download the stable version of nbconvert, which is likely undesirable if you are building the current docs off of master. 

It is easy enough to solve 1 (see #432).
I am less confident about 2, I'll look into it.

**Comment by michaelpacer** [comment]
Ok. Two paths are not working: 

A. Tried to look into automated building of an environment.yml — no dice. Two reasons
     1. It does not store the pip executable command as a raw string that could be passed to the command line
            a. On an editable install it points to the local file path (which is not exportable) and the version number 
            b. there is no version number for an editable install since it could change as you switch between branches/tags. Therefore we cannot trust the output of that to provide us with the right info. 
     2. They actually discourage automatically building `environment.yml` files with conda env export
B. Tried looking into how they recommended doing an editable install — came upon `conda develop` +  Separately building nbconvert with conda.
     1. This could be a solution, but it would add another layer to the instructions that I would prefer not to add.
     2. It actually appears that conda develop might have been deprecated but no one said anything anywhere. It's in the current stable documentation but its gone from the latest version of the documentation. But it was always just a short shim to the `main()` function of  `conda_build.main_develop`, which makes me worry that this might be a wild goose chase.

Next I'll try to figure out how they are parsing the `environment.yml`. If I need to I may try to contribute something upstream. Either that or we need to abandon using a single `environment.yml` file to install everything. This may require first uninstalling the `nbconvert` that is `conda` installed as part of the current build. This kind of workflow clumsiness is why I'm considering taking the effort to contribute upstream. We really should be able to just include a relative path and a editable install command.

**Comment by michaelpacer** [comment]
Ok a compromise. It fixes 2. but isn't strictly speaking desirable, since it doesn't create an editable install.

**Comment by takluyver** [comment]
I think that's OK, thanks.
