### ISSUE TITLE
ExecutePreprocessor.preprocess is slow

### ISSUE THREAD

**Issue by gbishop** [jupyter/nbconvert#438]
I copied the code from the [Executing Notebooks](https://nbconvert.readthedocs.io/en/latest/execute_api.html#executing-notebooks-using-the-python-api-interface) page and timed it. Each of the steps is just a very few milliseconds except preprocess which takes 1.2 seconds on an empty notebook. In contrast an empty python script takes about 20 milliseconds. This is all on a very fast computer with tons of memory, SSD, and Linux. 

The total clock time is 1.5 seconds with user time of 0.77 seconds. 

You can see my code here: https://gist.github.com/gbishop/5be81922d7521ce3e829565e28d71e0d

Am I missing something that would make this faster?

**Comment by takluyver** [comment]
I would expect that step to be slower because it starts a kernel process, establish communication with it, and shut it down. I'm a bit surprised it's that slow on a fast machine, but you're not doing anything obviously wrong.

**Comment by michaelpacer** [comment]
So can I close this? Is there anything more to be done?

**Comment by takluyver** [comment]
I think it can be closed, at least until someone works out that there's something specifically wrong to be fixed.
