### ISSUE TITLE
No Longer Working | nbconvert to slides

### ISSUE THREAD

**Issue by thhancock** [jupyter/nbconvert#444]
I've been using Jupyter and nbconvert for some time in creating slide decks at work.  I recently updated Anaconda / Jupyter / etc. and it appears that something in the update process broke the to slides functionality.

I am using a local reveal.js library in the same folder as my packages and .ipynb file and running the following command:

`jupyter nbconvert test_presentation.ipynb --to slides --post serve`

on a test presentation I found here: [https://anaconda.org/dhirschfeld/test_presentation/notebook](https://anaconda.org/dhirschfeld/test_presentation/notebook)

The command creates the slide html file, but the output is formatted like the following (all shoved to one side):

![image](https://cloud.githubusercontent.com/assets/22798619/19321005/ab617a56-9081-11e6-8306-787a29d91b4d.png)

![image](https://cloud.githubusercontent.com/assets/22798619/19321015/ba4e6394-9081-11e6-89eb-ffec3ce3bf04.png)

I have completely uninstalled / reinstalled Anaconda, etc. and even tried downgrading to older versions.  Things seem to work fine on other people's machines / installs.  Any ideas?

**Comment by michaelpacer** [comment]
Have you tried removing your local version of the reveal.js library? If you've installed and uninstalled anaconda/jupyter, that sounds like the most likely culprit.

**Comment by thhancock** [comment]
Yes I've removed the local reveal.js, but still incur the same issue. 

It was occurring before I did a clean and updated install of Anaconda, but I had recently run an update on several packages. That said, since I did a fresh install and it seemed to start occurring after package updates, I'm wondering if this is some sort of bug with the latest version of Jupyter / nbconvert / Anaconda. 

Does anyone have success with 'to slides' on the lastest install of Anaconda?

**Comment by thhancock** [comment]
Oh.  Live Reveal works just fine.

**Comment by takluyver** [comment]
@damianavila , any ideas?

**Comment by damianavila** [comment]
No idea, I just tested with the latest nbconvert conda package and works OK.

@thhancock can you try cleaning your browser cache or hard-reload the page to see if the cache is somehow affecting you?

**Comment by thhancock** [comment]
@damianavila

Cleared cache with the same result.  The slides.html file is malformed compared to what other's (at work) get when running nbconvert.  Something is going wrong with the construction of the html file.

**Comment by thhancock** [comment]
Removing my reveal.js, clearing cache, and then running works.  Seemed it was an issue with the reveal.js local library and cached data in the browser.

**Comment by damianavila** [comment]
@thhancock thanks for letting us know! Closing now.

**Comment by cglacet** [comment]
@thhancock  Can you explain how did you solve this?

- What is `reveal.js` and where is it?
- What cache did you have to clear and how?

Thanks.
