### ISSUE TITLE
Problem encountered when converting to any formats

### ISSUE THREAD

**Issue by rick47** [jupyter/nbconvert#455]
Hi,

I have been facing an issue recently:

  File "/Users/anaconda/lib/python2.7/site-packages/nbconvert/filters/highlight.py", line 122, in _pygments_highlight
    from IPython.lib.lexers import IPythonLexer
ImportError: No module named lexers

And frankly, I have no idea why this is happening. Can you help me, please?

**Comment by takluyver** [comment]
That sounds like `import` is finding an old version of IPython. The lexers module was moved to IPython.lib for IPython 3.1 (ipython/ipython#7954), and it's still there. I'm not sure where it would be picking up such an old version, but try uninstalling any copies of IPython you can find and installing the current version again.

**Comment by michaelpacer** [comment]
@rick47 was this solved by @takluyver's suggestions? I'm closing on the assumption that it was. Feel free to reopen if it didn't work.
