### ISSUE TITLE
timeout should respect allow-errors

### ISSUE THREAD

**Issue by gbishop** [jupyter/nbconvert#461]
When executing a notebook the first timeout kills nbconvert with a traceback instead of continuing to the next cell. 

I'm using the command like

`jupyter nbconvert --to=html --execute --ExecutePreprocessor.kernel_name=python --allow-errors --ExecutePreprocessor.timeout=30 input.ipynb`

Is there a work around? I'm running version 4.2.0

**Comment by takluyver** [comment]
`--allow-errors` was added for the case where you want to demonstrate an error message in a notebook. I don't think it makes sense to stop one cell because it's taking too long but then carry on with later cells, even with that flag specified.

**Comment by gbishop** [comment]
I'm using it to grade student submissions. It is common for one answer to not terminate but for others to succeed.

**Comment by takluyver** [comment]
I wonder if @jhamrick has got anything to handle that in nbgrader. (She's on holiday at the moment, so she may not respond for a while)

**Comment by gbishop** [comment]
I'll hack my system to use sigalrm.

**Comment by jhamrick** [comment]
Hmm, I think whenever I've used this in nbgrader it hasn't been a problem -- it interrupts the cell and then continues executing the other cells. I believe this is due to the `interrupt_on_timeout` option -- try running it with `jupyter nbconvert --ExecutePreprocessor.interrupt_on_timeout=True ...` instead?

**Comment by michaelpacer** [comment]
@gbishop Does using this option solve your problem? I'm closing for now, but will reopen if it's still an issue.
