### ISSUE TITLE
 convert to RST - cell magics in code blocks?

### ISSUE THREAD

**Issue by balacuit** [jupyter/nbconvert#47]
When converting a notebook to RST, code blocks with magics are still converted into python code blocks.  For example, this:

``` python
%%bash
git checkout master
```

... gets translated to this:

``` rst
.. code:: python
    %%bash
    git checkout master
```

Shouldn't it be converted to recognize the language specific cell magics, like the following?

``` rst
.. code:: bash
    git checkout master
```

**Comment by takluyver** [comment]
The [template](https://github.com/jupyter/nbconvert/blob/master/nbconvert/templates/rst.tpl#L10) doesn't look at the code of the cell at all, it just puts it all in a `.. code:: python` block (this is also wrong - it should match the language the notebook is written in).

You could write a custom template which would look at cell magics and produce appropriate rst directives. I think this would probably be useful for us too, now that we're converting notebooks into rst docs.

**Comment by Carreau** [comment]
> On Jun 20, 2015, at 01:23, Thomas Kluyver <notifications@github.com> wrote:
> 
> The template <https://github.com/jupyter/nbconvert/blob/master/nbconvert/templates/rst.tpl#L10> doesn't look at the code of the cell at all, it just puts it all in a .. code:: python block (this is also wrong - it should match the language the notebook is written in).
> 
> You could write a custom template which would look at cell magics and produce appropriate rst directives. I think this would probably be useful for us too, now that we're converting notebooks into rst docs.
> 
And what if you pass relevant option to the first line that are necessary for the comprehension of the program ?
Moreover magic are “just” syntactic sugar for actual function call as hist -t shows.

**Comment by michaelpacer** [comment]
It seems like there are two pieces to this issue, one part should be fixed (it should put the language the notebook is written in not `.. code:: python` as @takluyver points out) and the other would seem to require a level of code parsing beyond templating that, based on what @takluyver and @Carreau are saying, is not on the roadmap. 

The former should be dealt with for 5.0, the latter maybe no_action (or wishlist if it is something we plan to implement) is that right? 

I'm going to open a new issue for dealing with the former, and mark this as no_action.

**Comment by takluyver** [comment]
One possibility for the latter part is that we could specify the language as IPython, relying on our own [lexers](https://github.com/ipython/ipython/blob/master/IPython/lib/lexers.py) to deal with highlighting magics. I don't know how well they do currently with cell magics using other languages.

**Comment by MSeal** [comment]
Closing as there's no action taken and the complexity of the change is questionable.
