### ISSUE TITLE
Update Entrypoints requirement not to get AttributeError: ConfigParser instance has no attribute 'read_file'

### ISSUE THREAD

**Issue by livia-b** [jupyter/nbconvert#475]
Experienced on Mac, conda installation : 

nbconvert                 4.2.0
notebook                  4.2.3
jupyter                   1.0.0              
ipython                   5.1.0                 
python                    2.7.12                       

Even a simple `jupyter nbconvert  example.ipynb` was failing with `AttributeError: ConfigParser instance has no attribute 'read_file'` until I updated `entrypoints: 0.2-py27_1 --> 0.2.2-py27_0`

**Comment by minrk** [comment]
Good catch! @livia-b would you like to make a PR updating setup.py to require `entrypoints>=0.2.2`?

**Comment by livia-b** [comment]
Here it is!

**Comment by takluyver** [comment]
@livia-b Thanks! It looks like you've sent the PR to your own fork of the repository (`livia-b/nbconvert`). Could you have another go and see if you can make a new one against this (`jupyter/nbconvert`) repository?
