### ISSUE TITLE
ENH: slides without internet access

### ISSUE THREAD

**Issue by GregoryEAllen** [jupyter/nbconvert#483]
I frequently want to present slides without internet access. The generated foo.slides.html currently point to cloudflare for require.min.js and jquery.min.js. I'm currently using sed to fix the generated notebook:

    sed 's#https://.*/require.min.js#require.min.js#'
    sed 's#https://.*/jquery.min.js#jquery.min.js#'

Reveal can be made local, why not these? I propose a few flags to fix this:

    --local  refer to local `require.min.js` and `jquery.min.js`

That makes html like:

    <script src="require.min.js"></script>
    <script src="jquery.min.js"></script>

Perhaps another flag:

    --embed  embeds `require.min.js` and `jquery.min.js` directly in the html

If there are local copies of of these two js files, use them. Otherwise try to download them.

Obviously the actual flag names are a point of discussion.

I think this is probably a very minor change, and would benefit a lot of people who work or present without internet access.

**Comment by GregoryEAllen** [comment]
I forgot mathjax

    sed 's#https://.*/MathJax.js#mathjax/MathJax.js#'

**Comment by damianavila** [comment]
There is a previous discussion about this on the following issue: #296
I agree with you we need to offer a complete offline experience.

**Comment by damianavila** [comment]
Let's keep the discussion just in one place. Closing this one in favor of #296.
