### ISSUE TITLE
Minor documentation fixes?

### ISSUE THREAD

**Issue by sursh** [jupyter/nbconvert#486]
Although the documentation says this in a few places:

```ExecutePreprocessor.timeout
: Int
Default: 30

The time to wait (in seconds) for output from executions. If a cell execution takes longer, an exception (TimeoutError on python 3+, RuntimeError on python 2) is raised.

None or -1 will disable the timeout.
```

when I run it with `None` I get the following error: 

`traitlets.traitlets.TraitError: The 'timeout' trait of an ExecutePreprocessor instance must be an int, but a value of None <class 'NoneType'> was specified.`

Passing in `-1` seems to be working though. Perhaps this is something that worked in Python 2 and doesn't in Python 3, and the documentation is out of date?

Also, when I click the "Edit in Github" link on the top of [this page](http://nbconvert.readthedocs.io/en/latest/config_options.html) it throws a 404.

**Comment by takluyver** [comment]
Thanks, we'll look into that. What version of nbconvert are you using?

The config docs are autogenerated, that's why the 'edit' link doesn't work.

**Comment by takluyver** [comment]
It looks like nbconvert version 4.1 didn't allow `None` there. It should work with 4.2.

**Comment by sursh** [comment]
Yep, we're using version 4.1. Thanks! 

I'm not familiar enough with your docs setup to understand why autogenerated docs produce the wrong link, but if you're not concerned about that I'll close this issue.

**Comment by takluyver** [comment]
RTD tries to make a link back to the source file that the page is built from - e.g. if you try it on [this page](http://nbconvert.readthedocs.io/en/latest/usage.html) you'll see the rst file on Github. But for the config options page, we generate the source file as part of building the docs, so there's nothing there on Github.
