### ISSUE TITLE
`extra_loaders` broken in new release?

### ISSUE THREAD

**Issue by matthew-brett** [jupyter/nbconvert#490]
Hi,

As of today, my project tests started to fail because my code for using an in-memory jinja template for nbconvert is no longer working.  Here's a test snippet that worked yesterday, but not today (with version 5.0):

```
from jinja2 import DictLoader

try:
    from nbformat import v4
    import nbconvert
except ImportError:
    from IPython.nbformat import v4
    from IPython import nbconvert


my_loader = DictLoader({'my_template': "{%- extends 'rst.tpl' -%}"})


class MyExporter(nbconvert.RSTExporter):
    template_file = 'my_template'


exporter = MyExporter(extra_loaders=[my_loader])

nb = v4.new_notebook()

out, resources = exporter.from_notebook_node(nb)
```

In nbconvert 5.0, this gives `TemplateNotFound: my_template.tpl`.   I believe you now assume that the template is a filename, and do not allow specifying the template via jinja2 loaders.   This is inconvenient for me, because I want to build my template in memory.

**Comment by takluyver** [comment]
It looks like we assume that it should have an extension, but I think we still respect extra_loaders. Does it work if you use `my_template.tpl` as the key in the dict? Alternatively, I think you could set `template_extension = ''`.

**Comment by matthew-brett** [comment]
Ah yes, you're right, I'm sorry for my lazy diagnostics.   Maybe it would be worth relaxing the requirement for a `tpl` extension again, on the basis that the template need not be a file?

**Comment by takluyver** [comment]
Have a look at #491 :-)

**Comment by michaelpacer** [comment]
If #491 works for your case @matthew-brett, then I'll merge it as is.

**Comment by matthew-brett** [comment]
Too ungrateful to suggest adding a test, perhaps from my original report?

**Comment by michaelpacer** [comment]
Not hard to do if all you care is that it doesn't _break_ to use an memory template (thank you for giving such a nice MWE): e696578 takes care of that (fails on master, not on #491 for the right reasons). 

But it doesn't actually check that the content is appropriately converted. It happens to in this case, but it seems like it'd be out of scope for this test (and there should be a separate discussion about which content should be tested).

**Comment by willingc** [comment]
@michaelpacer Check out the recent doc builds on nbconvert and notebook master. Ideas?

**Comment by michaelpacer** [comment]
this push should fix it https://github.com/spatialaudio/nbsphinx/pull/94

**Comment by michaelpacer** [comment]
Also, working on #518 since this is a kind of behaviour that we shouldn't regress on.
