### ISSUE TITLE
Check about nbsphinx and whether it works on sphinx 1.5.2 

### ISSUE THREAD

**Issue by michaelpacer** [jupyter/nbconvert#492]
As of #484 nbsphinx had been incompatible with sphinx 1.5.0 and 1.5.1, with a fix expected to be included in 1.5.2 as described here: https://github.com/sphinx-doc/sphinx/pull/3224. 
However, https://github.com/spatialaudio/nbsphinx/pull/85 may fix the incompatibility with 1.5.1 so it may be enough to get around this problem to rely on a more recent version of nbsphinx.

**Comment by mgeier** [comment]
I've just released `nbsphinx` 0.2.12: https://pypi.python.org/pypi/nbsphinx/0.2.12

I hope it works now with Sphinx 1.5.1.
It should also work with Sphinx 1.5.0, but only when forcing `docutils<0.13.1`.

**Comment by michaelpacer** [comment]
Ok #493 and #494 should address this.
