### ISSUE TITLE
Incorrect conversion of inline math in markdown cell

### ISSUE THREAD

**Issue by matthew-brett** [jupyter/nbconvert#50]
I have the following notebook:

```
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "$s_i = s_{i}\n",
    "$"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
```

The math `$s_i = s_{i}$` renders correctly in the notebook interface, but `ipython nbconvert --to html bad_mathjax.ipynb` gives the following HTML for the math:

```
<p>$s<em>i = s</em>{i}
$</p>
```

So - the underscores in the math have been interpreted as markdown emphasis.  This does not occur when the closing dollar is on the same line as the rest of the inline math, and does not occur when using pandoc to convert the equivalent pure markdown file.

**Comment by takluyver** [comment]
I had assumed that you couldn't put a newline inside inline math, but it sounds like you can. #51 should fix it.
