### ISSUE TITLE
Test Jinja2.9

### ISSUE THREAD

**Issue by Carreau** [jupyter/nbconvert#510]
Jinja 2.9 has [major changes](https://www.palletsprojects.com/blog/jinja-29-released/) in the underlying machinery.

We should make sure it does not break some assumptions we make.

**Comment by michaelpacer** [comment]
running it locally (both python2 and 3), all tests pass. 

Also, I'm pretty sure since we don't specify any constraints on the version number in the `setuptools_args['install_requieres']` list that travis will have the most recently released jinja already included as part of our testing suite.

**Comment by Carreau** [comment]
Ok, good to know. If we have weird things, we should just remember that jinja2.9 changes a lot of things.

**Comment by Carreau** [comment]
Let's close.
