### ISSUE TITLE
Make extension tolerant loader more tolerant of non-extended templates

### ISSUE THREAD

**Issue by michaelpacer** [jupyter/nbconvert#517]
Regression introduced with #491 to deal with extension free templates. 

Should be fixable by adding try excepts on secondary template; solution should allow either specifying an extension free template or passing it and treat the two as equivalent (this was behaviour before 5.1.1).

**Comment by takluyver** [comment]
I'm having trouble understanding what the issue is (both here and on #518, which I assume is about this). Some concrete examples would help!

**Comment by takluyver** [comment]
Here's the example from nbsphinx that is going wrong:

```python
loader = jinja2.DictLoader({'nbsphinx-rst.tpl': RST_TEMPLATE})
        super(Exporter, self).__init__(
            template_file='nbsphinx-rst', extra_loaders=[loader],
            ...
```

I.e. defining a template in a custom loader with an extension, then specifying it without the extension.

1. Do we want to do extension munging for custom loaders? I wrote in #491 "assume anyone who is providing extra loaders knows what they're doing." (by which I meant, they will specify the extension exactly as it is). There's a case to be made for simply fixing it in nbsphinx. If we do want to muck around with file extensions from custom loaders, we can either wrap all loaders in `ExtensionTolerantLoader`, or get rid of ETL entirely and go back to doing it in TemplateExporter.
2. Is there any reason to allow the opposite (template declared without extension, then specified with)? #518 adds this, but I haven't seen any examples of people doing that, I don't believe it worked before, and it's extra complexity.

**Comment by takluyver** [comment]
I've just made a PR fixing it in nbsphinx (in a slightly different way to Mike's existing PR). If @mgeier is happy to merge that and do a new release soon, I think I'm inclined not to change anything in nbconvert. I'd like to try to keep the ambiguity around template names as little as possible, by minimising the number of cases in which we try with a variant of the name specified.

**Comment by mgeier** [comment]
I just merged @takluyver's PR. I can make a release shortly, say, tomorrow if nothing else comes up.

**Comment by takluyver** [comment]
Thanks :-)

**Comment by michaelpacer** [comment]
To me handling, this kind of extension munging makes for a more pleasant user experience for at least some users. 

Yes, more advanced users are the only ones who are using this today, and they _could_ figure out what's going wrong, but should they __have__ to? If we can handle it (& we can), why not ease friction wherever we can?

Also, I want to encourage more people to use in memory templates and template customization more generally — _ease_ of customizing output (not the power of the customization engine per se) is one of the things that makes Rmarkdown so attractive to many people. If I succeed in these efforts, that means less advanced users may be using this kind of code and I would rather they not need to pay attention to this. 

I'll try to think of an alternative way to structure a template loading fallback mechanism that might be more pleasant on the eyes even when it's doing a bit of extension munging.

**Comment by takluyver** [comment]
> Yes, more advanced users are the only ones who are using this today, and they could figure out what's going wrong, but should they have to? If we can handle it (& we can), why not ease friction wherever we can?

Allowing more possibilities is not the same as making it easier. Adding and removing extensions automatically makes it less obvious what's going on. It's easier to explain "a must be the same as b" than "a must be the same as b, but if b ends with '.tpl' (or '.tplx' if you're using the Latex export machinery), a may leave that off, though it doesn't have to".

It's also easier to avoid breaking things in the future if there are fewer possible ways to do the same thing.

Anyone working with code is used to the idea that two names have to match exactly.

**Comment by michaelpacer** [comment]
Currently the mechanism introduced by ExtensionTolerantLoader is
"a must be the same as b, but if b ends with '.tpl' (or '.tplx' if you're using the Latex export machinery), a may leave that off, though it doesn't have to, but b has to end with '.tpl' (or '.tplx' …) if a does".

the mechanism I was suggesting would be described as
"a and b need to have the same file name (ignoring the file extension)". The ease of explanation results from the parallelism introduced by covering the case you're saying we don't need to cover.

Regardless, nbsphinx will be fixed and if the _idea_ of covering this case is getting this much opposition (even after two others on the Jupyter team approved the idea and implementation); this starts to feel like I'm wasting my time. Accordingly, I'll close this issue and the PR.

**Comment by mgeier** [comment]
I've just created a new `nbsphinx` release: https://pypi.python.org/pypi/nbsphinx/0.2.13

Does one of you happen to know how to fix the `conda` error I recently get on RTD?
https://readthedocs.org/projects/nbsphinx/builds/4942832/

**Comment by takluyver** [comment]
Thanks!

I think you have to pin Python to 3.5 for now - it's trying to use Python 3.6, but not all of the necessary conda packages have a 3.6 build.

**Comment by mgeier** [comment]
Thanks a lot @takluyver, I would have never guessed that from the error message ...

Now I have a new problem, and since you are the author of `entrypoints`, I might as well ask you directly:
https://readthedocs.org/projects/nbsphinx/builds/4944903/

**Comment by takluyver** [comment]
Can you try with the [pip_install option](http://docs.readthedocs.io/en/latest/yaml-config.html#python-pip-install) instead of setup_py_install? In fact, entrypoints was already installed by conda, but I think the conda package is built in a way that means setuptools doesn't know about it. I'll work on fixing that.

**Comment by takluyver** [comment]
conda-forge/entrypoints-feedstock#7 should, I hope, fix the conda package so that pip/setuptools can see that it's already installed.

**Comment by mgeier** [comment]
Thanks @takluyver, now it works with both `setup_py_install` and `pip_install`!
