### ISSUE TITLE
Error when converting to PDF

### ISSUE THREAD

**Issue by cbrnr** [jupyter/nbconvert#527]
I want to convert [this notebook](https://github.com/cbrnr/python_intro/blob/master/0/0%20-%20Grundlagen.ipynb) to PDF, but I get the following error:

    ! Package ucs Error: Please activate option 'combine'.

    See the ucs package documentation for explanation.
    Type  H <return>  for immediate help.
     ...                                              
                                                      
    l.300 Der Plan fü
                       r dieses Semester sieht wie folgt aus:
    ? 
    ! Emergency stop.
     ...                                              
                                                      
    l.300 Der Plan fü
                       r dieses Semester sieht wie folgt aus:
    !  ==> Fatal error occurred, no output PDF file produced!

Is there an option I need to set to avoid this kind of error (which seems to be related to umlauts, even though there are other umlauts before this one)?

**Comment by cbrnr** [comment]
Never mind, it seems like the ü was actually some other character. I replaced it with a standard ü (as produced by hitting the ü key on my keyboard), and that particular error disappeared.

**Comment by takluyver** [comment]
I'd guess it was the decomposed form that was causing the error. There are two ways to make ü with unicode: a specific [u with diaresis](http://www.fileformat.info/info/unicode/char/fc/index.htm) code point, or an ascii u followed by the [combining diaresis codepoint](http://www.fileformat.info/info/unicode/char/0308/index.htm). The former 'composed' form is more common, and seemingly better handled by Latex.

(I know the accent is umlaut in German text, but the unicode names call it diaresis)

**Comment by cbrnr** [comment]
Thanks @takluyver - yeah, didn't know that UTF had two ways to implement diareses. Strange that these two variants occurred in the same notebook. Maybe copy & paste related, otherwise I can't explain the behavior.

**Comment by XNCV** [comment]
You can print Word to PDF and copy words from PDF. Success

**Comment by xhain** [comment]
> I want to convert this notebook to PDF, but I get the following error:

! Package ucs Error: Please activate option 'combine'.

See the ucs package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.300 Der Plan fü
                   r dieses Semester sieht wie folgt aus:
? 
! Emergency stop.
 ...                                              
                                                  
l.300 Der Plan fü
                   r dieses Semester sieht wie folgt aus:
!  ==> Fatal error occurred, no output PDF file produced!
Is there an option I need to set to avoid this kind of error (which seems to be related to umlauts, even though there are other umlauts before this one)?

I'm getting this but don't think thje fix is to re-type every single umlaut... Still looking for a fix.

**Comment by t-makaro** [comment]
Find and replace will help. 

If someone can convert their notebook to latex and then find a latex solution, it'd be worth taking a look. As someone who sticks with ascii, I'll leave it to someone with more non-ascii latex experience than me.

**Comment by xhain** [comment]
@t-makaro Duh. I realized it was only characters that I copied from the exercise sheet. All compiles fine now.
