### ISSUE TITLE
nbconvert to pdf fails with ucs error

### ISSUE THREAD

**Issue by Ken-B** [jupyter/nbconvert#532]
I'm trying to convert a notebook with Julia code to pdf but keep getting following error:
```
! Package ucs Error: Please activate option 'combine'.

See the ucs package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.298 ...}{(}\PY{n}{y}\PY{p}{,} \PY{n}{X}\PY{p}{)}
                                                  
? 
! Emergency stop.
 ...                                              
                                                  
l.298 ...}{(}\PY{n}{y}\PY{p}{,} \PY{n}{X}\PY{p}{)}
                                                  
!  ==> Fatal error occurred, no output PDF file produced!
```

In Julia I can use non-ascii symbols in code by using tab completion. For example, in a code block, when I type `a` and then `\hat + <TAB>` this will output the `â` symbol. I can use that for, say,  `â = 1`. However, a notebook with just this line will not convert.

I don't know how to set the `combine` option for `ucs` as proposed by the error message or whether this would solve the issue.

I'm using a clean anaconda 4.2 install on mac osx.

Let me know how I can assist to fix this. Thank you for any help!

**Comment by michaelpacer** [comment]
Do you mean a 4.2 nbconvert install? If so, try updating to 5.1, from 5
onward we use xelatex not pdflatex precisely for its better Unicode support.

**Comment by michaelpacer** [comment]
If you did mean anaconda 4.2, not nbconvert 4.2, and you want to keep using
conda to manage your packages, you can get the latest version from the
conda forge channel.

Otherwise, I'd recommend uninstalling your conda version of nbconvert and
instead installing from pip.

My guess is the Unicode character you're using is a combining character
which may not be supported by default in pdflatex.

**Comment by Ken-B** [comment]
I updated to 5.1.1 and now the error is gone and the pdf is created. 

However, the characters are missing from the output. Both unicode characters (like β) or combining ones (β̂) are gone from code fields. They're present in html output though. Are you able to replicate? 

I guess you can change the title of the issue (or I can open a new one, as you wish).

Let me know what I can do to assist, thanks!
