### ISSUE TITLE
enumerate environment incorrectly quoted in latex output for R list of vectors

### ISSUE THREAD

**Issue by nqr** [jupyter/nbconvert#534]
Consider an R notebook that simply contains the cell `list(1:2)`.

Converting this notebook with `jupyter nbconvert --to=latex` produces the following latex code, which is not valid as the `\item` in the first line has no surrounding enumerate environment:

```
    \textbackslash{}begin\{enumerate\} \item 

\begin{enumerate*}
\item 1
\item 2
\end{enumerate*}

\textbackslash{}end\{enumerate\}

```

The reason is of course that `\begin{enumerate}` and `\end{enumerate}` have been wrongly quoted.

The output was produced with jupyter-nbconvert version 5.1.1.

**Comment by takluyver** [comment]
It looks like we're putting Latex output through a markdown filter:
https://github.com/jupyter/nbconvert/blob/59bd15080a636c6c82a4a7f307b265af53bafa41/nbconvert/templates/latex/document_contents.tplx#L33

PR coming up
