### ISSUE TITLE
Same bug as notebook/#759 regarding correctly delimiting mathjax

### ISSUE THREAD

**Issue by mpacer** [jupyter/nbconvert#544]
This needs a solution similar to https://github.com/jupyter/notebook/pull/2220.

**Comment by mgeier** [comment]
Please consider *not* supporting `\(`, `\[`, `\\(`, `\\[` and similar, see https://github.com/jupyter/notebook/pull/2220#issuecomment-293883840.

**Comment by mpacer** [comment]
`\\(` and `\\[` are already supported, they just are not supported well. Deprecating them would invalidate many notebooks. `\(` and `\[` are not supported by core nbconvert, but I believe there are extensions that enable their support.

**Comment by mgeier** [comment]
> ... are already supported, they just are not supported well.

If they are not working correctly anyway, it shouldn't be a big deal to remove support for them.

**Comment by mpacer** [comment]
They *are* supported in the notebook, which means we should have parity in nbconvert.
