### ISSUE TITLE
SanitizeHTML Preprocessor is not import-able

### ISSUE THREAD

**Issue by tarzzz** [jupyter/nbconvert#549]
Hi Jupyter Team,

I am working on a custom Preprocessor, for which I need to subclass `SanitizeHTML` Preprocessor. 
It seems that it is not included in [`preprocessors/__init__.py`](https://github.com/jupyter/nbconvert/blob/master/nbconvert/preprocessors/__init__.py), hence I cannot import it externally.

```
In [3]: import nbconvert.preprocessors.sanitize.SanitizeHTML
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-0536154675e8> in <module>()
----> 1 import nbconvert.preprocessors.sanitize.SanitizeHTML

ImportError: No module named sanitize.SanitizeHTML

In [4]: from nbconvert.preprocessors.sanitize import SanitizeHTML
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-653c94da4e04> in <module>()
----> 1 from nbconvert.preprocessors.sanitize import SanitizeHTML

ImportError: No module named sanitize

In [5]: from nbconvert.preprocessors import SanitizeHTML
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-9f1a2b46f4fe> in <module>()
----> 1 from nbconvert.preprocessors import SanitizeHTML

ImportError: cannot import name SanitizeHTML
```

Is there a way to import that particular Preprocessor for use? I am happy to add the import statement in `preprocessors/__init__.py` if there isn't an alternative (as a PR)..

**Comment by minrk** [comment]
@tarzzz what version of nbconvert do you have? It's a recent addition, so make sure you are up to date. This import works for me with the latest release:

    from nbconvert.preprocessors.sanitize import SanitizeHTML

**Comment by tarzzz** [comment]
@minrk: I was using an old version:

```
In [2]: nbconvert.__version__
Out[2]: '4.2.0'
```

Updating solved the issue. Thanks!!
