### ISSUE TITLE
server takes an extremely long time to exit

### ISSUE THREAD

**Issue by haicen** [jupyter/nbconvert#564]
When running nbconvert --to slides --post serve, the server refuses to quit in a timely fashion when doing ctrl+c. Currently, the only ways I have to exit the server is to either close the command window, or kill the nbconvert and python processes. Waiting for ctrl+c to stop the server, takes approximately 5+ minutes. This makes things rather inconvenient when trying to make adjustments to slide shows.

This is on windows 10, and I am using Anaconda with relevant details below:

`Jupyter version: 4.3.0`

Server Information:

`The version of the notebook server is 4.4.1 and is running on:`
`Python 3.5.3 |Anaconda custom (64-bit)| (default, Feb 22 2017, 21:28:42) [MSC v.1900 64 bit (AMD64)]`

Current Kernel Information:

`Python 3.5.3 |Anaconda custom (64-bit)| (default, Feb 22 2017, 21:28:42) [MSC v.1900 64 bit (AMD64)]`

`IPython 5.3.0 -- An enhanced Interactive Python.`

**Comment by takluyver** [comment]
If you Ctrl-C and then try to refresh the slides, does the server quit immediately? It might be stuck in a system call listening on the socket, and getting it out of that will make it notice that you've interrupted it. We probably can't easily fix that, because serving slides uses the stdlib [http.server](https://docs.python.org/3/library/http.server.html) module.

**Comment by haicen** [comment]
Yes, it closes immediately after refreshing. I hadn't tried that.

**Comment by damianavila** [comment]
@haicen did you tried @takluyver suggestion?

**Comment by takluyver** [comment]
Sounds like s/he did and it worked. But I don't know where that gets us; I think it's probably a bug in the `http.server` module.

**Comment by haicen** [comment]
Yes, that did cause it to catch up and exit.

**Comment by damianavila** [comment]
OK, I agree with @takluyver around the bug upstream.
I don't see any actionable thing on nbconvert itself to fix this now (I don't think replacing http.server module is an option and any fix upstream is not in the nbconvert scope, IHMO).
Closing now.
