### ISSUE TITLE
how to import a markdown exported from notebook?

### ISSUE THREAD

**Issue by suredream** [jupyter/nbconvert#576]
why I only see exportation from notebook?

Suppose I exportation a series of notebook to markdown format,  do some edits and then I want to import them back to jupyter,  what to do?

**Comment by takluyver** [comment]
We focus on export because the translation loses some information, but have a look at third party tools like [notedown](https://pypi.python.org/pypi/notedown) and [ipymd](https://github.com/rossant/ipymd).
