### ISSUE TITLE
Execution randomly failing on Travis

### ISSUE THREAD

**Issue by hadim** [jupyter/nbconvert#581]
I use nbconvert to test notebooks execution on Travis for a custom Java kernel (https://github.com/hadim/scijava-jupyter-kernel). Notebooks run fine on my computer with nbconvert/notebook/lab but randomly failed on Travis and I don't know why... The failing notebook is also always different.

Here is the script that execute the notebooks : https://github.com/hadim/scijava-jupyter-kernel/blob/master/.travis/test.sh

Here is one of the failing Travis job : https://travis-ci.org/hadim/scijava-jupyter-kernel/builds/228066681?utm_source=email&utm_medium=notification

Here is the error message :

```
Traceback (most recent call last):
  File "/home/travis/conda/envs/scijava/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 259, in run_cell
    msg = self.kc.shell_channel.get_msg(timeout=timeout)
  File "/home/travis/conda/envs/scijava/lib/python3.6/site-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:
[...] 
  File "/home/travis/conda/envs/scijava/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 272, in run_cell
    raise exception("Cell execution timed out")
TimeoutError: Cell execution timed out
```

**Comment by takluyver** [comment]
It may be simply because Travis often runs really slowly compared to hardware you control, so it's more likely to hit timeouts.

**Comment by minrk** [comment]
From gitter: timeout can still be hit at 10 minutes, indicating that some event / message is not firing somewhere, not just that Travis needs more time.

**Comment by hadim** [comment]
CircleCI is failing the exact same way... :-(

**Comment by hadim** [comment]
It seems to work when enabling trusty on Travis... I am gonna close here since it's probably something you cannot fix.
