### ISSUE TITLE
UnicodeDecodeError under Python 2 & windows

### ISSUE THREAD

**Issue by flying-sheep** [jupyter/nbconvert#591]
When trying to convert the notebooks [here](https://github.com/Bioconductor-mirror/destiny/tree/master/vignettes), under python 2 on windows the following happens.

sadly i can’t give you more details, as this was manually created by a Bioconductor maintainer and not me (who might not be happy to run more stuff to debug), and i don’t have a windows install around.

needless to say that the notebook file doesn’t contain a `0xFF` byte

```pytb
$ jupyter nbconvert --template destiny-bib.tplx --to latex DPT.ipynb
[NbConvertApp] Converting notebook DPT.ipynb to latex
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\jupyter-nbconvert.EXE\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\python27\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "c:\python27\lib\site-packages\nbconvert\nbconvertapp.py", line 293, in start
    self.convert_notebooks()
  File "c:\python27\lib\site-packages\nbconvert\nbconvertapp.py", line 457, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "c:\python27\lib\site-packages\nbconvert\nbconvertapp.py", line 428, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "c:\python27\lib\site-packages\nbconvert\nbconvertapp.py", line 357, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "c:\python27\lib\site-packages\nbconvert\exporters\exporter.py", line 165, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "c:\python27\lib\site-packages\nbconvert\exporters\exporter.py", line 183, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "c:\python27\lib\site-packages\nbformat\__init__.py", line 141, in read
    return reads(fp.read(), as_version, **kwargs)
  File "c:\python27\lib\codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 10: invalid start byte
```

**Comment by takluyver** [comment]
The `.ipynb` files in that folder are symlinks. Windows doesn't do well with symlinks, and I believe git defaults to cloning them as text files containing a path. Is it possible to find out if the files the Windows user was trying to clone are the real ipynb files or the symlink fallback files from git?

If that error does come from converting a real notebook file, I think something must have gone wrong when writing it, because a notebook file should always be valid utf-8.

**Comment by flying-sheep** [comment]
thanks! i’ll check with them. 

> Windows doesn't do well with symlinks

actually there isn’t a problem at all with semi-recent windows version; so generally speaking, this would be a ridiculous fallback for git on windows.

when we assume that git behaves sanely, maybe that build server is ancient enough that it still has bad symlink handling, git detects that and falls back accordingly.

**Comment by takluyver** [comment]
> actually there isn’t a problem at all with semi-recent windows version

My understanding is that, although recent versions of Windows have symlinks, creating them requires a permission bit which normal processes don't have. Maybe this has changed in even more recent versions? Either way, I suspect that git has a default to not handle symlinks on Windows, rather than trying to detect whether it can.

**Comment by flying-sheep** [comment]
I just searched a bit, and git on windows can handle symlinks just fine.

mysysgit however creates those text files. let’s see.

**Comment by flying-sheep** [comment]
oh, sorry! the whole git stuff is irrelevant, as that’s just a mirror. bioconductor uses SVN.

**Comment by takluyver** [comment]
Git-for-Windows, which the official Git site points at, says:

> For those reasons, Git for Windows disables support for symbolic links by default

https://github.com/git-for-windows/git/wiki/Symbolic-Links

**Comment by flying-sheep** [comment]
oh. that’s dumb, but anyway i forgot that git is just a mirror of the Bioconductor SVN repo, so we’ll have to check SVN’s symlink support on windows.

**Comment by takluyver** [comment]
I would not be surprised if svn on Windows does something similar with symlinks. Especially since it's older, so it's going to have been used more on pre-Vista Windows which didn't support symlinks at all.

**Comment by flying-sheep** [comment]
i’ll ask him and get back to this issue when i know more.

**Comment by t-makaro** [comment]
Closing as stale. Please comment asking to reopen if this is still an issue.
