### ISSUE TITLE
cannot use reveal.js print-pdf option

### ISSUE THREAD

**Issue by simonbyrne** [jupyter/nbconvert#596]
I cannot get the `?pdf-print` option to work correctly. Usually the text overlaps, but in [this sample notebook](https://gist.github.com/simonbyrne/b047befe7f29c4897ba7632f462e9afa) I get a completely blank page.

The console shows the following:
```
> jupyter nbconvert test.ipynb --to slides --post serve
[NbConvertApp] Converting notebook test.ipynb to slides
[NbConvertApp] Writing 252901 bytes to test.slides.html
[NbConvertApp] Redirecting reveal.js requests to https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.1.0
Serving your slides at http://127.0.0.1:8000/test.slides.html
Use Control-C to stop this server
WARNING:tornado.access:404 GET /custom.css (127.0.0.1) 5.86ms
WARNING:tornado.access:404 GET /custom.css (127.0.0.1) 0.94ms

> jupyter nbconvert --version
5.2.1
```

**Comment by mpacer** [comment]
I don't fully understand — the command you demonstrate shouldn't product a pdf. It should produce `test.slides.html` and then immediately serve them. 

I also don't follow: what do you mean by the "text overlaps"?

**Comment by simonbyrne** [comment]
Sorry I was referring to [this feature](https://github.com/hakimel/reveal.js/#print-stylesheet).

After running `jupyter nbconvert test.ipynb --to slides --post serve` the usual presentation displays correctly. But when I go to `http://127.0.0.1:8000/test.slides.html?print-pdf`, all I get is a white page (the text briefly appears, but then disappears). Trying to print this gives a white page as well.

**Comment by mpacer** [comment]
Is the "special print stylesheet at `/css/print/pdf.css`" loaded? That may require a custom template (or something like that).

**Comment by simonbyrne** [comment]
It appears to be (when looking via the chrome developer tools).

**Comment by mpacer** [comment]
what happens if you just generate the slides and then don't serve using the postprocssor?

**Comment by simonbyrne** [comment]
Then all the text just prints on the one page (rather than one page per slide).

**Comment by mpacer** [comment]
Hrm… I don't know why that would be.

**Comment by simonbyrne** [comment]
Are you able to replicate, or is this a one-off?

**Comment by damianavila** [comment]
Yep, the print capability is fragile. I need to upgrade the reveal we are using in nbconvert and check the latest to see if we can get a good `printable` slide.

**Comment by damianavila** [comment]
I tested this with latest nbconvert 5.2.1 and with Chromium 58.0.3029.110 and it works as expected (I can not see any superposition). Can you check with the latest nbconvert in your system? And also report you Chromium/Chrome version? Thanks.

**Comment by damianavila** [comment]
ping @simonbyrne, otherwise I will close this one in the next few days.

**Comment by simonbyrne** [comment]
I still get the issue with the same versions (Chrome OS X instead of Chromium). The issue though seems to be that it is using an older version of reveal.js, as the log says

```
> jupyter nbconvert test.ipynb --to slides --post serve
[NbConvertApp] Converting notebook test.ipynb to slides
[NbConvertApp] Writing 252901 bytes to test.slides.html
[NbConvertApp] Redirecting reveal.js requests to https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.1.0
Serving your slides at http://127.0.0.1:8000/test.slides.html
Use Control-C to stop this server
WARNING:tornado.access:404 GET /custom.css (127.0.0.1) 7.72ms
WARNING:tornado.access:404 GET /custom.css (127.0.0.1) 0.78ms
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 1.38ms
WARNING:tornado.access:404 GET /custom.css (127.0.0.1) 1.37ms
WARNING:tornado.access:404 GET /custom.css (127.0.0.1) 1.10ms
...
```

When I run `jupyter nbconvert test.ipynb --to slides --reveal-prefix=https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.5.0 --post serve` it works fine. Why is it using the older version?

**Comment by damianavila** [comment]
> Why is it using the older version?

This was updated in my last #600 PR... so it should point to the latest Reveal.js in master.
