### ISSUE TITLE
error when trying to download jupyter's notebook as PDF

### ISSUE THREAD

**Issue by ethan1987-2** [jupyter/nbconvert#603]
500 : Internal Server Error

The error was:

nbconvert failed: PDF creating failed, captured latex output:
This is pdfTeX, Version 3.1415926-2.5-1.40.14 (MiKTeX 2.9 64-bit)
(Fatal format file error; I'm stymied)

**Comment by mpacer** [comment]
What version of nbconvert are you using?

**Comment by mpacer** [comment]
Note: if you're using pdfLaTeX the odds are good that you have an old version of nbconvert, please upgrade to the latest version and if you still have problems reopen your issue.
