### ISSUE TITLE
Greek Letters

### ISSUE THREAD

**Issue by einstein91** [jupyter/nbconvert#606]
Hi,
I actually faced a problem with greek letters:
If I write in a cell in jupyter for example \alpha (which then shows the greek symbol) = 5, etc...
And then I export the whole file to pdf via latex it does it successfully but the spot where the greek symbol should be is just a blank spot. By replacing \alpha to a f.e. everything works. If i export the file with the greek symbol in it to latex it automatically includes "\usepackage[mathletters]{ucs} % Extended unicode (utf-8) support" and then I can easily compile this document with pdflatex to the correct pdf file.
So in the end it work with via compiling the .tex file manually but it would be nice if the automatic export in jupyter notebook would do the same job.
Maybe I do something wrong then explain it to be, but I rather think that there is a bug which should be solved.

**Comment by takluyver** [comment]
What version of nbconvert are you using? We switched the default latex engine we use from pdflatex to xelatex, which is supposed to handle non-ascii characters better.

**Comment by einstein91** [comment]
stupid question: Where can I find out the nbconvert version?

**Comment by takluyver** [comment]
`jupyter nbconvert --version` in a command line.

**Comment by einstein91** [comment]
Thanks
It's 5.1.1

**Comment by takluyver** [comment]
OK, I think that's after the switch to xelatex, but you might want to try upgrading to 5.2.1, which is the latest. @mpacer may be able to give you more info.

**Comment by willingc** [comment]
@takluyver @mpacer I had a similar issue when downloading a IJulia notebook as a `.jl` file. Updating nbconvert to 5.2.1 as suggested resolved the issue with display of Greek characters. I'm going to go ahead and close this issue.

@einstein91 I'm going to close this issue, but please let us know if 5.2.1 does not resolve your issue. Thanks!
