### ISSUE TITLE
[ipynb2py] blanks in the front of the code disappear.

### ISSUE THREAD

**Issue by livc** [jupyter/nbconvert#620]
```
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": false,
    "editable": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "    print 'load dictionary...'\n",
    "    dict_dim = len(word_dict)\n",
    "    class_dim = 2\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}

```

`jupyter nbconvert --to python README.ipynb`, in README.py 

```python

# coding: utf-8

# In[1]:

print 'load dictionary...'
dict_dim = len(word_dict)
class_dim = 2

```

So as you see, the blanks in the front of the code disappear.

**Comment by Carreau** [comment]
Yes, that is expected, other IPython only constructs (like magics), will be lowered to their pure-python representations. For this particular case, this is because IPython allows to copy/past things and will do its best to execute it. For example if you have leading prompts:
```
>>> import os
...  print(os.path)
```

The `>>>` and `...` will be stripped as well. 

If these leading characters were not removed then file would not be valid Python.

**Comment by livc** [comment]
But my .ipynb file is like 

first cell:
```python
if __name__ == '__main__':
    xxx
```

second cell:
```python
    xxx
    xxxx
```

The feature makes the code in the second cell failed because of the wrong indentation.

**Comment by Carreau** [comment]
I'm sorry but indenting the code in the second cell does not make it part of the branch in the first cell:

<img width="426" alt="screen shot 2017-07-05 at 14 17 36" src="https://user-images.githubusercontent.com/335567/27863980-e962722e-618c-11e7-8a24-156a34ca4694.png">

The behavior of exporting to `.py` file make the execution of the python script and the `.ipynb` notebook file consistent. If we were to preserve indentation, then running the `.ipynb` and the `.py` file would differ in result – which would bring a lot more issues.

**Comment by livc** [comment]
Thanks for the reply.
