### ISSUE TITLE
adding a space to notebook title breaks conversion to pdf

### ISSUE THREAD

**Issue by clancia** [jupyter/nbconvert#633]
Hi there,

not sure if it qualifies as an issue.
I've just noticed that if the notebook title contains a space, then
```
jupyter nbconvert --to pdf note\ book.ipnb
```
fails if the notebook contains image output.

The error given by xelatex is

```
! Missing $ inserted.
<inserted text> 
                $
```
The issue is not present with Markdown-embedded images, but only with output images (e.g. generated by matplotlib.pyplot).

Please note that exporting to pdf via File > Download as > PDF via LaTeX works fine. Perhaps this is because spaces are replaced by +'s?
Anyway, a very simple solution is to avoid spaces in the notebook name and use a template for having a nicely formatted title when exporting to pdf.

Jupyter v. 4.3.0
Python 3.6.2 :: Anaconda custom (x86_64)
macOS 10.12.6

**Comment by mpacer** [comment]
If you go to tex directly and then convert it does this work?

**Comment by jpgrayson** [comment]
I am also observing this issue with jupyter-core 4.3.0. Running:

    jupyter-nbconvert --to pdf Notebook\ With\ Spaces.ipynb

produces a truncated, single-page pdf whereas `File > Download as > PDF via LaTeX` produces the correct (six-page) pdf.

> If you go to tex directly and then convert it does this work?

Yes, this workflow seems to produce the same output as the browser export:

    jupyter-nbconvert --to latex Notebook\ With\ Spaces.ipynb
    pdflatex Notebook\ With\ Spaces.tex

**Comment by clancia** [comment]
Seems to be xelatex related, as far as I understand

```
jupyter nbconvert --to latex note\ book.ipynb
xelatex note\ book.ipynb
```

throws the same error as `jupyter nbconvert --to pdf note\ book.ipynb`

**Comment by liamim** [comment]
this is related to spaces in the filename when calling the `\adjustimage` command.

**Comment by t-makaro** [comment]
See my closing comment [here](https://github.com/jupyter/nbconvert/issues/965#issuecomment-518875394).

**Comment by ytomar** [comment]
Work perfectly for me if we enclose the file name in double quotes

jupyter nbconvert --to pdf --TemplateExporter.exclude_input=True "Note book with spaces.ipynb"
