### ISSUE TITLE
how to handle translation in extension?

### ISSUE THREAD

**Issue by gabyx** [jupyter/nbconvert#635]
I have a extension which adds another download option (`html_embed`) in the download menu

```javascript
var dwm = $("#download_menu")
        var downloadEntry = $('<li id="download_html_embed"><a href="#">{% trans %}HTML Embedded (.html){% endtrans %}</a></li>')
        dwm.append(downloadEntry)
        downloadEntry.click(function () {
            that._nbconvert('html_embed', true);
        });
```
copied from menu `notebook/notebook/templates/notebook.html`
I am wondering how the translation stuff works for extensions?

What should I do to support translation for my download entry?

**Comment by takluyver** [comment]
The translation mechanism was only just merged into the notebook itself, so I'm afraid we haven't thought at all about how it would work for extensions.

**Comment by t-makaro** [comment]
Closing as a question for the notebook and out of the scope of nbconvert.
