### ISSUE TITLE
Add a template block in slides section to allow customisation of reveal.js

### ISSUE THREAD

**Issue by cjrh** [jupyter/nbconvert#64]
See my comment in PR #62.

Something else to consider: merely setting the theme for reveal.js is not enough, some of the CSS produced by nbconvert will override stuff in the reveal.js theme.  The fix might be as easy as moving the position of the revealjs `link` tag further down, but I haven't looked into it enough yet.

**Comment by damianavila** [comment]
As I said in #62, I think is a really good idea.

>Something else to consider: merely setting the theme for reveal.js is not enough, some of the CSS produced by nbconvert will override stuff in the reveal.js theme. The fix might be as easy as moving the position of the revealjs link tag further down, but I haven't looked into it enough yet.

But when you load the correct theme from the js side, is there a conflict too? I have seen problem with dark themes, but not too much with the "whity" ones... also which `link` (line) are you referring to?

**Comment by cjrh** [comment]
@damianavila Apologies, I somehow missed your comment in the lead-up to PyCon AU.

I need to play with the CSS stuff a bit more to see what is really going on.  Then I'll come back here and make a more intelligent-sounding comment :)

**Comment by damianavila** [comment]
I will close this one in favor of #77 which propose a more general approach at the time to split the template.
