### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jzf2101** [jupyter/nbconvert#646]
We should add our typical license to the repo, correct?

**Comment by takluyver** [comment]
There are two common files for the license info - in this repo, we're using COPYING instead of LICENSE: https://github.com/jupyter/nbconvert/blob/master/COPYING.md

**Comment by mpacer** [comment]
Is there a reason to not use LICENSE.md?

**Comment by jzf2101** [comment]
I assume we have standard language for licenses?

**Comment by mpacer** [comment]
@jzf2101 I'm not sure if that's been explicitly standardised or if it's more of an emergent phenomenon. But I also am not fully sure what you mean… do you mean the distinction between COPYING vs. LICENSE filenames or the actual content of the license?

**Comment by t-makaro** [comment]
Closed by #654.
