### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by cglong** [jupyter/nbconvert#647]
I'm trying to add Jupyter to Homebrew, a package manager for macOS (see Homebrew/homebrew-core#16718). One of Homebrew's policies is that, whenever possible, the default macOS install of Python (2.7.10 on my box) is used.

It looks like `jupyter-nbconvert` is failing in their test infrastructure due to a UTF-8 issue fixed in 77d4956ddd252f5d1c05f440acd5b53bd9d996c4. I was wondering when we can expect the next release of Nbconvert to hopefully get this fix into a release 🙂

**Comment by mpacer** [comment]
I'm trying to move that forward there's a chained series of PRs (jupyter/nbformat#103, #643, #645) that should be released & merged. Then I was planning on releasing `nbconvert` 5.3.

I literally only today learned from @suchow that that UTF8 fix wasn't in the last release.

**Comment by mpacer** [comment]
@takluyver this is another reason I'd like to release sooner rather than later.

**Comment by cglong** [comment]
@mpacer Congrats on getting the PRs signed off on! Do you have an ETA for when this release will occur? 🙂

CC @ilovezfs

**Comment by mpacer** [comment]
Hopefully within the next few days. [JupyterCon](https://conferences.oreilly.com/jupyter/jup-ny) is absorbing a lot of time.

**Comment by cglong** [comment]
Oh sorry, didn't know this was going on! Thanks for your help 🙂

**Comment by nehalecky** [comment]
missed JupyterCon, but really excited about this upcoming release!

**Comment by mpacer** [comment]
Yes! Sorry about that — I had intended to release on Saturday during sprints, but there were so many people that there just wasn't any time, and then the dev meeting and then travel, but it should be out by the end of the day.

**Comment by nehalecky** [comment]
@mpacer, thanks for the update (and cutting the new release). Now I'm patiently waiting for the new package to arrive in conda, hopefully soon!

**Comment by cglong** [comment]
Yes, thank you @mpacer for taking care of this! 🙂 Since 5.3.0 has already been released to PyPI, I was able to move to it in Homebrew/homebrew-core#17543!

I'll leave this issue open though until 5.3.0 has made its way to Conda!

**Comment by mpacer** [comment]
I should note, this *is* available on conda-forge already :)

Thank you for moving it into homebrew!

Just curious, how does homebrew handle its site-packages? Should this be ok
for registering 3rd-party exporters through entrypoints via pip?

**Comment by cglong** [comment]
> I should note, this *is* available on conda-forge already :)

Awesome! @nehalecky, can you confirm its availability on Conda when you get a chance?

> Thank you for moving it into homebrew!

Of course 😄 I immediately recognized the value of Jupyter and friends, and wanted to make it as easily accessible as possible 🙂

> how does homebrew handle its site-packages? Should this be ok
for registering 3rd-party exporters through entrypoints via pip?

Ultimately, that depends on the formula, but for Jupyter, `PYTHONPATH` is automatically set to the union of site-packages needed for the application and the global site-packages directory.

Therefore, you should be able to use any third-party exporter installed via `pip`. You might also be able to create a formula for the exporter and expose it globally using a `.pth` file 🙂
