### ISSUE TITLE
Why does the html exported output not use codemirror cells?

### ISSUE THREAD

**Issue by lucainnocenti** [jupyter/nbconvert#649]
Possibly a stupid question, but nonetheless: what is the reason for not using codemirror also in the exported html output, which causes difficulties like #447, and makes more difficult to export some codemirror-enabled features like code folding (which can be enabled in the notebook via [nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/wiki/Codefolding))?

**Comment by takluyver** [comment]
Static HTML is simpler, smaller and more flexible than producing Javascript to correctly render the page. You could make an exporter which produces HTML plus Codemirror Javascript, but I think we'll always support the more 'plain' HTML with highlighting done when it's generated.
