### ISSUE TITLE
Document use of the CellExecutionError exception

### ISSUE THREAD

**Issue by wstomv** [jupyter/nbconvert#652]
It took me too long to figure out how to use the `CellExecutionError` exception in my own code; in particular, how to import it.

Suggestion: Add the following line to the example code:
```python
from nbconvert.preprocessors.execute import CellExecutionError
```

in the _Handling errors_ section on https://nbconvert.readthedocs.io/en/stable/execute_api.html

Also, note that in case an exception is raised by `ep.preprocess()`, the variable `out` will be undefined.

Another suggestion: It might be more appropriate to add `CellExecutionError` to https://github.com/jupyter/nbconvert/blob/master/nbconvert/preprocessors/__init__.py
```python
from .execute import CellExecutionError
```

Then you can write:
```python
from nbconvert.preprocessors import ExecutePreprocessor, CellExecutionError
```

**Comment by takluyver** [comment]
Makes sense, do you want to make a pull request?

**Comment by takluyver** [comment]
@mpacer There are sprints at Jupytercon, right? This would be an easy one for someone to tackle.

**Comment by pxhanus** [comment]
@mpacer @willingc I'll try to work on this one.
