### ISSUE TITLE
pypi source tarball missing license file

### ISSUE THREAD

**Issue by nonamedotc** [jupyter/nbconvert#665]
Previous versions of nbconvert tarballs from pypi used to contain the license file under the filename COPYING.md. This file is not called LICENSE in the git repo but is no longer included in the pypi tarball.

I package nbconvert for Fedora and would appreciate the inclusion of license file in the tarball so that downstream packagers would not need to provide license file separately.

Thank you!

**Comment by Carreau** [comment]
Apologies, COPYING.md has been renamed to LICENCE and Manifest.in was not updated accordingly. Do you need a patch release quickly, or is it ok for you to wait until next minor revision ?

**Comment by nonamedotc** [comment]
If it's not too much trouble, a patch release would be great. I am guessing other distros would also be looking for the same file.

Thanks a lot for the quick response. Much appreciated.

**Comment by Carreau** [comment]
Doing our best, and thanks for the quick bug report, the renaming from Copying to License was also done on other repositories that didn't update manifest in either. Hopefully they haven't been released yet :-)

**Comment by Carreau** [comment]
see #666

**Comment by nonamedotc** [comment]
Thank you! :+1:
