### ISSUE TITLE
Manifest.in and misc files not included

### ISSUE THREAD

**Issue by Carreau** [jupyter/nbconvert#667]
The [jupyter-nbconvert](https://github.com/jupyter/nbconvert/blob/d884adaa350d3dbcb4e35a82afbec223e00280c1/scripts/jupyter-nbconvert) file seem to not be included neither in sdist nor in wheel (to check), it is autogenerated by setuptools ?

More generally, I think we should check our repositories with [check-manifest](https://pypi.python.org/pypi/check-manifest) to avoid this kind of issues and decide what should (and should not) be in sdist.

Current output:

```bash
$ check-manifest
lists of files in version control and sdist do not match!
missing from VCS:
  nbconvert/resources/style.min.css
missing from sdist:
  .mailmap
  MANIFEST.in
  codecov.yml
  nbconvert/templates/skeleton/Makefile
  nbconvert/tests/README.md
  readthedocs.yml
  scripts
  scripts/jupyter-nbconvert
suggested MANIFEST.in rules:
  include *.in
  include *.yml
  recursive-include nbconvert *.md
  recursive-include nbconvert Makefile
```

**Comment by mpacer** [comment]
should the Manifest itself be included? Should the scripts not be included or are they built automatically because of some kind of setuptools magic?

**Comment by mpacer** [comment]
@takluyver do you have any thoughts on this? Should I be adding anything to Manifest.in other than the LICENSE file added in #666?

**Comment by takluyver** [comment]
setuptools will generate the script if you install with setuptools. Pip uses setuptools, and that's the recommended way to install, but we include the `jupyter-nbconvert` script for installation not using setuptools. On several projects, though, we're now moving to require setuptools and explicitly disable egg building (which seems to cause most of the unpleasantness with setuptools). We should either do that (and thus get rid of the script), or include the script in setuptools.

I've never included MANIFEST.in itself - I thought it did that automatically, but I haven't checked.

Generally I'd say that the sdist should contain everything you might need to install or develop the package - but not generated files. My idea of an sdist is similar to a git tag, but more stable.

**Comment by mpacer** [comment]
Ok… so for the 5.3.1 patch release I should add the scripts & scripts/jupyter-nbconvert but then I should open an issue about deprecating its support?

**Comment by mpacer** [comment]
Marking this as closed in order to keep the discussion about any particular files (e.g., `Makefile`, `tests/README`, or the `MANIFEST.in` itself) in their own issues.
