### ISSUE TITLE
Deprecate & remove scripts/ directory & jupyter-nbconvert script; require setuptools

### ISSUE THREAD

**Issue by mpacer** [jupyter/nbconvert#668]
Related to discussions around #667 it was suggested that we should remove the `scripts/` directory and the `jupyter-nbconvert` script from the repo. It has never been distributed in sdists until 5.3.1 and seems to not be something that has bothered anyone for its absence. 

This will require changing setup.py to use setuptools to successfully build the `jupyter-nbconvert` when installing.

**Comment by t-makaro** [comment]
Closing as the ```scripts/``` directory no longer exists in master.
