### ISSUE TITLE
Reveal ships a mathjax plugin... let's take the nice things of it

### ISSUE THREAD

**Issue by damianavila** [jupyter/nbconvert#67]
Since we also have to use mathjax in the html output (not only slides) it makes sense to use our custom mathjax macro as we do right now, but we can probably improve it to make it more compatible with the slides using ideas from the reveal mathjax plugin implementation.

**Comment by michaelpacer** [comment]
@damianavila did you have specific suggestions on which ideas to use from the reveal mathjax plugin implementation?

I'm going to add a discussion tag and put this into the no action milestone, since right now this isn't well defined enough to be addressed.

**Comment by damianavila** [comment]
That's ok, in fact we need to revisit the health of that reveal plugin in the latest version.

The implementation should be pretty easy, just activate the plugin, but we have to be sure the plugin behaves accordingly with our MathJax use and config.

For more info, the plugin config lives here: https://github.com/hakimel/reveal.js/#mathjax

**Comment by damianavila** [comment]
Rethinking about this, I don't think there is a need to use the mathjax module from reveal.js since our macro is behaving correctly and we keep in sync both the html and slides exports. Closing now.
