### ISSUE TITLE
html_embed cannot handle 'width' attribute in <img> tag

### ISSUE THREAD

**Issue by sdsawtelle** [jupyter/nbconvert#677]
Using 'jupyter nbconvert --to html_embed mynotebook.ipynb' I ran into two issues with the <img> tag when the width attribute is specified.

First issue is that if 'src' attribute follows 'width' attribute the image is not embedded in the output, it remains like <img width=700 src="relativepath/mypic.png"/> in the output html. 

Second issue is that if 'src' attribute is listed first, the image is embedded, but without maintaining the width specification in the tag (i.e. in the output html the 'width' attribute is missing).

I am using nbconvert 5.1.1

**Comment by juhasch** [comment]
The `html_embed` export is part of jupyter_contrib_nbextensions. There is a PR https://github.com/ipython-contrib/jupyter_contrib_nbextensions/pull/1052 to get rid of the problems you encountered.

**Comment by sdsawtelle** [comment]
Ahh, thank you very much @juhasch.
