### ISSUE TITLE
Allow errors on a cell-by-cell basis

### ISSUE THREAD

**Issue by adrn** [jupyter/nbconvert#680]
In some tutorial notebooks we have in [astropy/astropy-tutorials](https://github.com/astropy/astropy-tutorials), we intentionally raise an exception to demonstrate a feature or concept to the user. But we also want to be able to test the notebooks by running them during the nbconvert phase (using nbsphinx). Right now, we can allow errors on a per-notebook basis using `--allow-errors`, but it would be useful if we could specify (via the cell-level metadata) that certain cells are allowed to fail. 

Is this a feature that you would support in nbconvert?

cc @eteq

(spatialaudio/nbsphinx#125 and astropy/astropy-tutorials#150 are related)

**Comment by takluyver** [comment]
[nbval](https://github.com/computationalmodelling/nbval) and the notebook user interface support a `raises-exception` [cell tag](http://jupyter-notebook.readthedocs.io/en/stable/changelog.html#cell-tags) to indicate that a cell is expected to raise an exception. I'd like nbconvert to respect the same thing.

**Comment by mpacer** [comment]
since it's supported in the notebook, I think that's a reasonable piece of functionality.
