### ISSUE TITLE
How to debug with VS Code?

### ISSUE THREAD

**Issue by gabyx** [jupyter/nbconvert#683]
I am working on an exporter in jupyter_contrib_nbextensions
and I am wondering how I can debug for example `embedhtml.py` installed in `https://github.com/ipython-contrib/jupyter_contrib_nbextensions` 

How can I bring VS Code to start up the converter like the command which works from my terminal
`jupyter nbconvert --to=html_embed Test.ipynb`

In my `launch.json` when I opend the nbconvert repository in VS Code I have:
```json
{
    "version": "0.2.0",
    "configurations": [
    
        {
            "name": "StartNbConvertApp",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "module": "nbconvert",
            "cwd": "${workspaceRoot}",
            "env": {},
            "args" : ["--to=html_embed","Untitled.ipynb"],
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
```
Anybody has some help! Thanks a lot!

**Comment by mpacer** [comment]
did you raise this issue in the `jupyter_contrib_nbextensions` repo?

I don't know about VS Code so I can't help you directly with that. 

Do you mean that you want to have an interactive python API to play with the exporter? If so, then importing the exporter and then running it on your example notebook would give you access to the output that it is creating as an in-memory object. Is that along the lines of what you're thinking of?

**Comment by gabyx** [comment]
exactly, thats the way I have done it  =)

**Comment by mpacer** [comment]
then I would just import your exporter in your python interpreter, and capture the object with 

```python out, resources = yourexporter(your_in_mem_nb)
```

could you explain why that wouldn't work?

**Comment by t-makaro** [comment]
Closing as answered / stale. Please comment asking to reopen if the issue is not resolved.
