### ISSUE TITLE
Inline math preventing conversion to pdf

### ISSUE THREAD

**Issue by albi3ro** [jupyter/nbconvert#686]
I'm running `jupyter nbconvert --to pdf QAHE.ipynb`

I have pandoc and nbconvert installed, and can convert simple documents to pdf.  I can also convert this document to html.  

I have inline math in my markdown, and somehow nbconvert is not recognizing that it needs to be LaTeX math.  

```
l.454 it has a singularity at \$\vec{R}
                                        = ( 0 ,0, R) \$.
?
! Emergency stop.
 ...

l.454 it has a singularity at \$\vec{R}
                                        = ( 0 ,0, R) \$.
!  ==> Fatal error occurred, no output PDF file produced!
```

The line it's trying to run is $\vec{r} = (0,0,R)$, but it's sticking backslashes in.

**Comment by takluyver** [comment]
Can you show the markdown that it's hitting problems with?

**Comment by albi3ro** [comment]
`## Eigenvectors

To find the eigenvectors, we find the nullspace of the following matrix,
\begin{equation}
\begin{vmatrix}
R_0 +R_3 - R_0 \mp R & R_1 - i R_2 \\
R_1 + i R_2 & R_0 - R_3 -R_0 \mp R \\
\end{vmatrix}
\end{equation}

Take the bottom row. Second column value multiples first column and first column value multiples second column.
\begin{equation}
\begin{pmatrix}
\pm R + R_3 \\
R_1 + i R_2  
\end{pmatrix}
\end{equation}

And now we need to normalize the state
\begin{equation}
\frac{1}{\sqrt{2 R \left( R \pm R_3 \right) }}
\begin{pmatrix}
\pm R + R_3\\
R_1 + i R_2
\end{pmatrix}
\end{equation}
In low energy, just the minus state will be occupied (lower energy), but it has a singularity at $\vec{R} = ( 0 ,0, R) $. 

We have two complex numbers in this vector, and thus four things to plot $r_1, \theta_1, r_2, \theta_2$,
\begin{equation}
|\psi \rangle =
\begin{pmatrix}
r_1 e^{i \theta_1} \\
r_2 e^{i \theta_2} 
\end{pmatrix}
\end{equation}

If we chose to create our vector from the top row instead,
\begin{equation}
\begin{pmatrix}
R_1 -i R_2 \\
- R_3 \mp R
\end{pmatrix}
\end{equation} 
and normalized
\begin{equation}
\frac{1}{\sqrt{2 R \left( R \mp R_3 \right) }} 
\begin{pmatrix}
R_1 - i R_2 \\
\pm R - R_3
\end{pmatrix}
\end{equation}
But the minus state for this one has a singularity at $\vec{R} = (0,0, -R )$.  

We can move where the singularity is, but we can't get rid of it.  The problem-point doesn't show up in the physics, only in the wavefunction representation of it.  We cannot well represent the state across the entire Brillouin Zone at the same time.  This problem occurs because we have a topologically non-trivial state and a non-zero Chern number.`

**Comment by takluyver** [comment]
I just played around with it, and I think there needs to be no spaces between the `$` signs and the maths inside them. So change this:

```
... a singularity at $\vec{R} = ( 0 ,0, R) $. 
```

To this:

```
... a singularity at $\vec{R} = ( 0 ,0, R)$. 
```

**Comment by mpacer** [comment]
This is a documented requirement: 

http://pandoc.org/MANUAL.html#extension-tex_math_dollars

> Anything between two $ characters will be treated as TeX math. The opening $ must have a non-space character immediately to its right, while the closing $ must have a non-space character immediately to its left, and must not be followed immediately by a digit.

Closing as a known, documented pandoc issue.
