### ISSUE TITLE
Jupyter notebook CSS 5.x in nbconvert still renders dataframes old style

### ISSUE THREAD

**Issue by oscar6echo** [jupyter/nbconvert#689]
Cf. #679 #682.  
The main purpose of these issues was to have nbconvert use the notebook pandas dataframes new style - like on [this image](https://github.com/oscar6echo/nbconvert-custom). Unfortunately, for some surprising reason, the dataframe old style is style used.  

You can check it with any notebook on nbviewer now that it has updated - Cf. [nbviewer issue #721](https://github.com/jupyter/nbviewer/issues/721)

That's quite surprising to me. When I manually inject the CSS 5.1.x I get the expected rendering. As I do in this [notebook](http://nbviewer.jupyter.org/github/oscar6echo/nbconvert-custom/blob/master/nbconvert_notebook.ipynb) when I inject `notebook_css` in code cell 4.

So the variable [notebook_css_version](https://github.com/jupyter/nbconvert/blob/0a262a3a00a1680c0b30c95b0b9837ed4f8ff063/setup.py#L69) in nbconvert setup does not seem to have an impact !..

I have no idea why. But it should be outlined.

Should have mentioned it earlier but was very busy...

**Comment by oscar6echo** [comment]
The problem is still there I added more details in the original issue #679 .

**Comment by t-makaro** [comment]
Closing as resolved. See [comment](https://github.com/jupyter/nbconvert/issues/679#issuecomment-343910497).
