### ISSUE TITLE
server error when downloading PDF via LaTeX

### ISSUE THREAD

**Issue by MustiDarsh** [jupyter/nbconvert#697]
I have installed a clear version of Python 3.6 and ran the following `$ pip install notebook` to install jupyter on my Windows machine.

When I try to download my notebook as PDF via LaTeX I receive the following error:

![errorjupyter](https://user-images.githubusercontent.com/15389273/31916086-646b2e0a-b851-11e7-92f3-bfe16200b47e.png)

nbconvert was installed as a dependency with jupyter. Furthermore, I have MikTex installed for LaTeX.

Worth mentioning, I have tried this with different python versions and on my Mac as well. 

Hopefully someone could shed some light on this error.

**Comment by mpacer** [comment]
Does the Mac have the same error?

what version of notebook and nbconvert do you have?

**Comment by MustiDarsh** [comment]
@mpacer 

Yes, I receive the same error on my Mac.

The version of my notebook is: 5.2.0 and nbconvert: 5.3.1

Furthermore, these are all the packages installed in my python environment:

```
appdirs (1.4.3)
beautifulsoup4 (4.6.0)
bleach (2.1.1)
bs4 (0.0.1)
certifi (2017.4.17)
chardet (3.0.4)
colorama (0.3.9)
cssselect (1.0.1)
decorator (4.1.2)
entrypoints (0.2.3)
html5lib (1.0b10)
idna (2.5)
ipykernel (4.6.1)
ipython (6.2.1)
ipython-genutils (0.2.0)
ipywidgets (7.0.3)
jedi (0.11.0)
Jinja2 (2.9.6)
jsonschema (2.6.0)
jupyter-client (5.1.0)
jupyter-console (5.2.0)
jupyter-core (4.3.0)
livestreamer (1.12.2)
lxml (3.8.0)
MarkupSafe (1.0)
mfcauto (0.1.2)
mistune (0.7.4)
nbconvert (5.3.1)
nbformat (4.4.0)
notebook (5.2.0)
packaging (16.8)
pandocfilters (1.4.2)
parso (0.1.0)
pickleshare (0.7.4)
pip (9.0.1)
prompt-toolkit (1.0.15)
Pygments (2.2.0)
pyparsing (2.2.0)
python-dateutil (2.6.1)
pyzmq (16.0.2)
qtconsole (4.3.1)
requests (2.17.3)
setuptools (28.8.0)
simplegeneric (0.8.1)
six (1.10.0)
testpath (0.3.1)
tornado (4.5.2)
traitlets (4.3.2)
urllib3 (1.21.1)
wcwidth (0.1.7)
webencodings (0.5.1)
wheel (0.29.0)
widgetsnbextension (3.0.6)
```

The error is the same in python 2.7.13, 2.7.14, 3.5.4 and 3.6.

**Comment by MustiDarsh** [comment]
@mpacer 

Yes, I receive the same error on my Mac.

The version of my notebook is: 5.2.0 and nbconvert: 5.3.1

Furthermore, these are all the packages installed in my python environment:

```
appdirs (1.4.3)
beautifulsoup4 (4.6.0)
bleach (2.1.1)
bs4 (0.0.1)
certifi (2017.4.17)
chardet (3.0.4)
colorama (0.3.9)
cssselect (1.0.1)
decorator (4.1.2)
entrypoints (0.2.3)
html5lib (1.0b10)
idna (2.5)
ipykernel (4.6.1)
ipython (6.2.1)
ipython-genutils (0.2.0)
ipywidgets (7.0.3)
jedi (0.11.0)
Jinja2 (2.9.6)
jsonschema (2.6.0)
jupyter-client (5.1.0)
jupyter-console (5.2.0)
jupyter-core (4.3.0)
lxml (3.8.0)
MarkupSafe (1.0)
mistune (0.7.4)
nbconvert (5.3.1)
nbformat (4.4.0)
notebook (5.2.0)
packaging (16.8)
pandocfilters (1.4.2)
parso (0.1.0)
pickleshare (0.7.4)
pip (9.0.1)
prompt-toolkit (1.0.15)
Pygments (2.2.0)
pyparsing (2.2.0)
python-dateutil (2.6.1)
pyzmq (16.0.2)
qtconsole (4.3.1)
requests (2.17.3)
setuptools (28.8.0)
simplegeneric (0.8.1)
six (1.10.0)
testpath (0.3.1)
tornado (4.5.2)
traitlets (4.3.2)
urllib3 (1.21.1)
wcwidth (0.1.7)
webencodings (0.5.1)
wheel (0.29.0)
widgetsnbextension (3.0.6)
```

The error is the same in python 2.7.13, 2.7.14, 3.5.4 and 3.6.

**Comment by mpacer** [comment]
That is… really really strange. I have no idea why that would be, does it have issues for any of the other exporters?

**Comment by mpacer** [comment]
ok I think this relates to some changes that were made in notebook version 5.2… not anything having to do with nbconvert. 

For now I'd recommend running `jupyter nbconvert Untitled.ipynb --to pdf` from the command line.

**Comment by MustiDarsh** [comment]
@mpacer so if I install an earlier version of notebook, for instance 5.1 or 5.0 will the problem be resolved? 
And should I downgrade any of the dependencies as well?

**Comment by mpacer** [comment]
@meeseeksdev migrate to jupyter/notebook

**Comment by mpacer** [comment]
If you downgrade to 5.1 it should work again.

**Comment by mpacer** [comment]
If you want to follow further development on this bug, please follow jupyter/notebook#2974

**Comment by MustiDarsh** [comment]
@mpacer Downgrading to 5.1 worked like a charm. Thank you!
