### ISSUE TITLE
Setting nbconvert up with meseeksdev

### ISSUE THREAD

**Issue by mpacer** [jupyter/nbconvert#698]
@Carreau how do I get @meseeksdev set up for nbconvert? #697 should be migrated to the notebook repo, so now is as good of a time to fix this as any other.

**Comment by mpacer** [comment]
@meeseeksdev migrate to jupyter/notebook

**Comment by Carreau** [comment]
Instructions are [in the readme](https://github.com/MeeseeksBox/MeeseeksDev#activate-on-your-repo).

**Comment by Carreau** [comment]
Weird, it should be activated. It' just not letting you.

**Comment by Carreau** [comment]
@meeseeksdev migrate to jupyter/notebook

**Comment by Carreau** [comment]
Permissions might be a bit too restrictive for migrate. I'll check.

**Comment by Carreau** [comment]
Can you retry in a few minutes, I've lowered the migrate permission from being admin, to having commit rights. When mr meeseeks is re-deployed it should again listen to you.

**Comment by Carreau** [comment]
Happy to also show you how to debug this.
