### ISSUE TITLE
Possible XML Injection based attack at TemplateExporter

### ISSUE THREAD

**Issue by Danorcohen** [jupyter/nbconvert#706]
One of TemplateExporter Filters is " html2text " which is defined at "filters/strings.py".

strings.py [Line 61] 

```
def html2text(element)
      element = ElementTree.fromstring(element)
```

At line 68 the filter function parses user input using "ElementTree.fromstring".
Using xml.etree.ElementTree.fromstring to parse untrusted XML data is known to be vulnerable to XML attacks such as [Billion_laughs_attack](https://en.wikipedia.org/wiki/Billion_laughs_attack). Replace xml.etree.ElementTree.fromstring with its defusedxml equivalent function or make sure defusedxml.defuse_stdlib() is called.

**Comment by takluyver** [comment]
Thanks; can you have a quick look at #708 ?
