### ISSUE TITLE
Support for html-style colors from markdown to pdf?

### ISSUE THREAD

**Issue by TMorville** [jupyter/nbconvert#707]
If I write this in a markdown cell of a jupyter notebook

`<span style="color:#3297A5">This is a test</span>`

it formats fine in the notebook, but when converting to .pdf using `jupyter nbconvert --to pdf test.ipynb` it comes out as black and white. Is there currently support for this, and if not, are there any alternatives?

nbconvert version 5.3.1.

**Comment by takluyver** [comment]
The conversion to PDF uses pandoc to convert markdown to latex, and then runs latex on it. So for something like this, it's up to what pandoc supports.

**Comment by TMorville** [comment]
Ah. Great, thanks.
