### ISSUE TITLE
Save widget models with Execute preprocessor?

### ISSUE THREAD

**Issue by ricklupton** [jupyter/nbconvert#718]
I'm using a notebook & nbsphinx to document my custom widget. This works fine if I run the notebook by hand and explicitly "save widget state". But it doesn't work if I use nbsphinx to execute the notebook, because the execute preprocessor doesn't save widget states (comm messages are discarded [here](https://github.com/jupyter/nbconvert/blob/master/nbconvert/preprocessors/execute.py#L411)).

From a quick look it doesn't look like it would be too hard to dump these comm messages and save the `data` of the message into the `widgets` part of the notebook document. Is that a good idea?

**Comment by mpacer** [comment]
That seems reasonable but I'd need to see the implementation. I'd happily review a PR if you have a working model.

**Comment by ricklupton** [comment]
Thanks. I haven't finished testing with nbsphinx but this works with the unit test I wrote:
https://github.com/ricklupton/nbconvert/commit/12cff0657e41adf607962bd365b29f66b5748894

It doesn't remove default values like the proper notebook does. Do you know if there's some existing logic for doing that somewhere that can be reused? Or maybe it doesn't matter.

**Comment by ricklupton** [comment]
@mpacer I've finished testing this and it's working in practice for building my documentation using nbsphinx -- I've made a PR if you have a chance to look.

**Comment by scottdraves** [comment]
dup? https://github.com/jupyter/nbconvert/issues/751

**Comment by t-makaro** [comment]
Most of the discussion is in #751, so I am closing this issue as the duplicate.
