### ISSUE TITLE
Why is nbconvert removing empty code cells?

### ISSUE THREAD

**Issue by mgeier** [jupyter/nbconvert#720]
At first I thought this is a bug, but this seems to be the intended behavior.

I just don't get it.
If the notebook contains an empty cell, I think it would be appropriate that the file created by `nbconvert` also contains that empty cell.

This behavior was introduced in #616.

I can of course disable this for my own use if I have to, but I'm wondering why removing stuff that's visible in the Jupyter Notebook should be the default.

**Comment by mgeier** [comment]
Ping?

**Comment by takluyver** [comment]
cc @mpacer @tillahoffmann ?

**Comment by mgeier** [comment]
I've created #784 to fix this.

**Comment by mgeier** [comment]
This is still very much broken, but since nobody seems to want to fix this, I've created a work-around for my problem: https://github.com/spatialaudio/nbsphinx/pull/200.
