### ISSUE TITLE
Adding code folding to nbconverted html

### ISSUE THREAD

**Issue by pjsulin** [jupyter/nbconvert#722]
I am looking to add the same type(exact reproduction is not necessary) of code folding that exists within the notebook, via the code folding extension, to the html outputted via nbconvert. Adding this at the cell level is easily done by adding a few lines of code in a template to insert some additional html and including some additional css. To actually add folding inside of the cell, I initially tried to just modify the code folding preprocessor. This is also easily done, but the html is just escaped by the pygments library so you just end up with html in your code.  

The fundamental problem is that a code cell converted to html is handed off to the language appropriate lexer in the pygments library to convert. This is obviously exactly as planned and what allows so many languages to work in the notebook. There are only two ways that I can think of handling this (outside of writing my own code highlighter/formatter)

1. Modify the data returned from the pygment lexer, essentially unescaping the parts I added.
2. Splitting the cell contents and only feeding the code into the lexer and concat'ing the results with the html I don't want escaped.

Any insights into the best way to solve this would be greatly appreciated!

**Comment by mpacer** [comment]
Can you link to the resources you mentioned? It seems like this should be solved in the templates & filters, not the preprocessors (and _could_ occur after the highlighting). But I might be missing something.

**Comment by pjsulin** [comment]
I'm not sure exactly what resources you are referring to, but what I wrote is based on reading the nbconvert documentation and experimenting with the templates, preprocessors and exporters.

The approach I have taken is to add tokens to the source code at the start and end of the line for the start of the fold and after the fold is complete. After it gets highlighted I replace those tokens with html. I've done it this way because it seemed much easier to use the raw source to determine code lines and indentations, as it is done now in the pre_codefolding preprocessor.

For now have modified the pre_codefolding preprocessor and the html exporter. This is not a very modular approach, but it should be fairly easy to port this so into filters and add to a template.

**Comment by takluyver** [comment]
If you have a JS library that can find the appropriate places to fold code, can it also do its own syntax highlighting? If so, a custom template could skip highlighting the code with pygments, and wrap it in the appropriate tags for the JS library to pick it up and do the highlighting.

**Comment by pjsulin** [comment]
I think I'm going to keep this in python as I am generating for a static site and prefer working in python.  I did take a look at the highlighting built into Code Mirror and if that was easily portable this would be a really good option to reduce diffs between the live notebook and the generated html, but at a quick glance it looks like it would still need at least a wrapper.

I don't have a library, but wrote code that will find the folds. The fold data from Code Mirror that is in the metadata is incomplete as it only provides a list of starting line number for folded sections. So I first generate a more complete data structure that includes the start, end, indentation and also whether it is folded.

I have it basically working and I'm thinking of converting the existing code into filters so that everything could be done in templates. For example, from the existing basic.tpl:

```jinja
{{ cell.source | highlight_code(metadata=cell.metadata) }}

to

{{ cell.source | add_folding_tokens(metadata=cell.metadata)  | highlight_code(metadata=cell.metadata) | replace_tokens()}}
```

**Comment by pjsulin** [comment]
Have not yet converted this and not pressing for me right now. Thanks, closing.
