### ISSUE TITLE
How to write Jinja2 templates that show markdown and suppress graphic descriptions

### ISSUE THREAD

**Issue by seanysull** [jupyter/nbconvert#727]
I am trying to write a Jinja2 template to convert a notebook into LaTex and pdf, however I am struggling. I cannot get the markdown cells to appear in the pdf document, I also wish to suppress the numbering of output and the description that appears above matplotlib graphics, eg:

`Out[1]: <matplotlib.axes._subplots.AxesSubplot at 0x2e62e885cc0>`

Any help or suggestions for learning material would be greatly appreciated. My goal is to produce reports with text and graphics automatically. My current template is an attempt at modifying a template I found in this repositroy:

```
% Default to the notebook output style
((* if not cell_style is defined *))
    ((* set cell_style = 'style_ipython.tplx' *))
((* endif *))

% Inherit from the specified cell style.
((* extends cell_style *))


%===============================================================================
% Latex Book
%===============================================================================

((* block docclass *))
\documentclass{report}
((* endblock docclass *))

% Author and Title from metadata
((* block maketitle *))
((*- if nb.metadata["latex_metadata"]: -*))
((*- if nb.metadata["latex_metadata"]["title"]: -*))
    \title{((( nb.metadata["latex_metadata"]["title"] )))}
((*- endif *))
((*- else -*))
    \title{((( resources.metadata.name )))}
((*- endif *))

\date{\today}
\maketitle
((* endblock maketitle *))

((* block markdowncell scoped *))
((( cell.source | citation2latex | strip_files_prefix | convert_pandoc('markdown+tex_math_double_backslash', 'json',extra_args=[]) | resolve_references | convert_pandoc('json','latex', extra_args=["--chapters"]) )))
((* endblock markdowncell *))


% Disable input cells
((* block input_group *))
((* endblock input_group *))
```

**Comment by mpacer** [comment]
There is a bug right now for code cells if you enable `—no-prompts` on the command line for pdf rendering, but once that’s fixed that’ll take care of the prompt numbers.

If you use plt.show() that should remove the Matlab return statement. 

The key is you shouldn’t need to modify the template to get this functionality.

**Comment by seanysull** [comment]
Ok thanks for your assistance, using plt.show() has suppressed the unwanted output, however, we are still unable to get the markdown cells to appear in the final document

**Comment by mpacer** [comment]
I don't understand why you wouldn't be able to get markdown cells to appear in the final document…  that should work natively. could you say more about your setup?

**Comment by seanysull** [comment]
I have solved the issues from this ticket now, they were related to the template I was using.
