### ISSUE TITLE
Converting IJulia plot to latex fails

### ISSUE THREAD

**Issue by massemanet** [jupyter/nbconvert#740]
I have a notebook created with jupyter 5.2.2
```
Server Information:
You are using Jupyter notebook.
The version of the notebook server is: 5.2.2
The server is running on this version of Python:
Python 2.7.14 |Anaconda, Inc.| (default, Dec  7 2017, 17:05:42) 
[GCC 7.2.0]
```

Jupyter has decided to store plots like this;

```
"text/html": [ "<img src=\"data:image/png;base64,iVBORw0KGgoAAAANh...EUgAA\" />" ]
```

Alas, nbconvert can not convert this to latex. Converting to html works.

```
julia$ jupyter nbconvert --to html foo.ipynb
[NbConvertApp] Converting notebook foo.ipynb to html
[NbConvertApp] Writing 249708 bytes to foo.html
julia$ jupyter nbconvert --to latex foo.ipynb
[NbConvertApp] Converting notebook foo.ipynb to latex
/root/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/nbconvert/filters/datatypefilter.py:41:
UserWarning: Your element with mimetype(s) [u'text/html'] is not able to be represented.
  mimetypes=output.keys())
[NbConvertApp] Writing 15455 bytes to foo.tex
```

Notebook example attached.
[foo.ipynb.txt](https://github.com/jupyter/nbconvert/files/1642624/foo.ipynb.txt)

**Comment by takluyver** [comment]
How did you generate the plot? If you use e.g. `%matplotlib inline`, then it should store it as png data, which does work when converting to Latex.

**Comment by massemanet** [comment]
I'm using the Julia kernel, 0.6.2.

better example notebook attached.

[bla.ipynb.txt](https://github.com/jupyter/nbconvert/files/1642959/bla.ipynb.txt)

**Comment by takluyver** [comment]
If Julia is producing a png plot, I think it would be best if it displayed that as `image/png`, rather than wrapping it in HTML. If we really have to, we can probably make nbconvert recognise png-in-html and extract it as if it was an `image/png` output, but that feels a bit messy.

**Comment by massemanet** [comment]
So I should file a bug with the IJulia people then?
  (I am a total jupyter noob, apologies for possibly stupid questions).

**Comment by takluyver** [comment]
That's OK :-)

I think you should open a bug with either IJulia or the plotting package (I'm not exactly sure how the responsibilities are divided up), but I think there's a good chance that they'll say that there's a good reason they do it like that. They might be better able to suggest a workaround, though.

**Comment by t-makaro** [comment]
Closing as the upstream issue appears resolved. Comment if this is not solved and you'd like it re-opened.

**Comment by masse-wg2** [comment]
this is indeed fixed upstream. apologies for not closing the issue.
