### ISSUE TITLE
Error: IJulia LaTeX output blocks using align environments do not compile

### ISSUE THREAD

**Issue by liamim** [jupyter/nbconvert#746]
I'm currently using IJulia, exporting my notebooks to pdf via nbconvert and xelatex. A library I use, JuMP, pretty-prints its models as LaTeX output, like so:

![](https://i.imgur.com/RoVH3mX.png)

However, when I run `nbconvert`, I get this error:
```
! Package amsmath Error: Erroneous nesting of equation structures;
(amsmath)                trying to recover with `aligned'.
```

This is due to the following snippet of generated LaTeX code:
```latex
\texttt{\color{outcolor}Out[{\color{outcolor}2}]:}
    
    $$ \begin{alignat*}{1}\max\quad & 5 x_{1} - x_{2} + 11 x_{3}\\
\text{Subject to} \quad & 2 x_{1} - x_{2} - x_{3} \geq 0\\
 & 0 \leq x_{i} \leq 3 \quad\forall i \in \{1,2,3\}\\
\end{alignat*}
 $$
```

The output block appears to be automatically wrapped in displaymath `$$`s, but `alignat*` environments cannot function inside a displaymath block -- they must sit outside any math environment.

~~Is there a workaround for this, or is it a bug in nbconvert?~~

This appears to be, jointly, IJulia's fault, since the cell itself looks like
```json
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/latex": [
       "$$ \\begin{alignat*}{1}\\max\\quad & 5 x_{1} - x_{2} + 11 x_{3}\\\\\n",
       "\\text{Subject to} \\quad & 2 x_{1} - x_{2} - x_{3} \\geq 0\\\\\n",
       " & 0 \\leq x_{i} \\leq 3 \\quad\\forall i \\in \\{1,2,3\\}\\\\\n",
       "\\end{alignat*}\n",
       " $$"
      ],
      "text/plain": [
       "Maximization problem with:\n",
       " * 1 linear constraint\n",
       " * 3 variables\n",
       "Solver is default solver"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "m = Model()\n",
    "\n",
    "@variable(m, 0 <= x[1:3] <= 3)\n",
    "@constraint(m, 2x[1] >= x[2] + x[3])\n",
    "@objective(m, Max, 5x[1] - x[2] + 11x[3])\n",
    "\n",
    "m # can print out the model as LaTeX-typeset math"
   ]
  },
```

**Comment by t-makaro** [comment]
This is due to a difference between mathjax, and LaTeX. Given that the output renders correctly (both in notebook and nbconvert to pdf) if I manually remove the ```$$``` from the start and end of the output, this is an ijulia issue. Closing as not nbconvert. Please comment asking to reopen if the corresponding ijulia package seems to think differently.
