### ISSUE TITLE
How to config template in NbConvertApp()

### ISSUE THREAD

**Issue by yshkk** [jupyter/nbconvert#753]
In terminal we can use args `--template=simplepython.tpl` to config template,and how to do this in code when using NbConvertApp() 
```
from nbconvert.nbconvertapp import NbConvertApp
converter = NbConvertApp()
converter.export_format = 'html'
converter.initialize()
converter.notebooks = [os_path]
converter.convert_notebooks()
# how to config template in converter?
# converter.template = simplepython.tpl      
```

Thanks for your help

**Comment by takluyver** [comment]
To run nbconvert from Python code, it's best to create and use an exporter object, see here:
http://nbconvert.readthedocs.io/en/latest/nbconvert_library.html

That document also shows how to specify a different template.

The NbConvertApp is there to define the command line tool, so while it's possible to call it from Python code, it's usually just extra complexity.

**Comment by yshkk** [comment]
Thanks
