### ISSUE TITLE
Cleaning up `notebook.tex` file after creating pdf

### ISSUE THREAD

**Issue by saulshanabrook** [jupyter/nbconvert#767]
Is it possible to remove the `notebook.tex` file after converting a notebook to a PDF? I am trying to see if I can get this to work on JupyterLab(https://github.com/jupyterlab/jupyterlab/issues/4018). The `temp_file_exts` config looks promising, but I am not having much luck with it. I have tried adding `.tex` and `'/../notebook.tex'` to it to no avail.

When I was looking into debugging that, I also couldn't find where the [`clean_temp_files` function](https://github.com/jupyter/nbconvert/blob/53f3c86183abd3fc3a5c007c7146aca09d0785f6/nbconvert/exporters/pdf.py#L159) is called. Is it dead code? Or does it have to be enabled in some way?

**Comment by takluyver** [comment]
At present, the `notebook.tex` file should be generated in a temporary folder, and the whole folder cleaned up when it finishes. That's this context manager:

https://github.com/jupyter/nbconvert/blob/53f3c86183abd3fc3a5c007c7146aca09d0785f6/nbconvert/exporters/pdf.py#L180

I think when we switched to that approach `clean_temp_files` became dead code.
