### ISSUE TITLE
Review the scroll functionality in the slideshow

### ISSUE THREAD

**Issue by damianavila** [jupyter/nbconvert#78]
@bollwyvl has raised a lot of concern about this and I agree with most of them, I think we should revisit our previous decision to have scrolling slides or make something like a `long slide` for people interested in that option.

Check @bollwyvl 's points below:

I think the phrase I used before was that they "break the medium"... slides "unintentionally" bigger (i.e. not infinite like prezi, etc.) than the screen...
- are not supported on any other slide platform
- magnify the "i'm going to read you this slide" presentation style... most people can read well north of 300 words per minute in their mother tongue, and showing someone a dense slide, they'll likely tune you out until they've read it
- break URLs: no way to link to a particular scrolled location. not that the reveal ones are great to begin with
- are not liked by reveal, hence all our troubles
  - will likely never printable or exportable, one of the use cases i value a lot but haven't been able to handle succinctly... even without scrolling slides... but at least it is theoretically doable!
- which require a scroll wheel/bar during a talk is distracting to the speaker and the listeners, and content will be in a half-revealed state, which again breaks focus for both parties
  - if the content really is big, like a big diagram or visualization, then temporary full screen/scroll/zoom on that content is a better fit... with text and margins so big, it's hard to even get 80 character code on a screen
- break touch gestures (unless you've fixed that!)

perhaps an explicit longslide slidetype that, if found, would enable the scrolling, while slide would conform to the reveal model would be less surprising.

**Comment by akhmerov** [comment]
For a reference, this is previous discussion of the same topic: ipython/ipython/issues/3589

Personally I completely agree with all @bollwyvl's arguments, and I found the scrolls in presentations to be a huge pain which required a lot of manual tweaking.

**Comment by yadongli** [comment]
I run into the scrollbar problem when migrating my old IPython notebook slides to the new jupyter version, and suddenly my formulas on the slides are surrounded by scrollbars in both x and y directions, I've tried to put the following text into my custom.css, and regenerate the slides.html using nbconvert, but the scroll bars still show up. Any suggestions on how can I remove the scrollbars from the html/reveal slides generated from nbconvert?

.reveal {
  overflow-y: hidden;
}

**Comment by akhmerov** [comment]
@yadongli this issue is about different scrollbars. Your problem is rather related to #38, but different. Do you mind opening a new issue with an example notebook that reproduces the problem? (as far as I can tell, this issue wasn't reported yet)

**Comment by yadongli** [comment]
Thank you for your prompt reply. I have submitted a new issue #152, thanks!

**Comment by damianavila** [comment]
I am working on this in PR #600

Essentially I default now to disable the scrolling functionality, but still the user have the option to activate the scrolling (which is now **per slide**, not the **whole** slide) just adding the option

```
--SlidesExporter.reveal_scroll=True
```

at the command line.

**Comment by damianavila** [comment]
PR #600 was merged. Now scrolling is False by default and you can turn it on with the option I showed in the previous comment. Closing this one now.

**Comment by mingxiang1006** [comment]
Hi, I have managed to scroll my slides, but my picture can't fit nicely, when I scroll to last row of my subplot, I could not fully view its content. Guidance are appreciated. Thank you. 

Please let me know if you need me to attach example

**Comment by gaksaray** [comment]
Sorry to raise an ancient thread here but I couldn't find any answers. I use `--SlidesExporter.reveal_scroll=True` option to have Reveal.js slides vertically scrollable when their contents overflow:
```
jupyter nbconvert lecture1.ipynb --to slides --SlidesExporter.reveal_scroll=True
```
But, this doesn't seem to work in full screen mode (by pressing »F« on keyboard or by making the browser window full screen). Any ideas why this might be and how to make overflown slides scrollable in full screen mode?

Versions:
jupyterlab 4.1.2
nbconvert-core 7.16.1
