### ISSUE TITLE
HTML export of markdown cells does not render markdown within <cite> tags

### ISSUE THREAD

**Issue by pauleve** [jupyter/nbconvert#788]
In Jupyter markdown cells, when using \<cite> combined with Markdown as follows:
```
<cite data-cite="key">([Foo et al](http://doi.org/xxx/yyy))</cite>
```
the cell is rendered correctly within Jupyter web interface, *i.e.*,  the markdown with \<cite> tag is correctly rendered as 
<cite data-cite="key">([Foo et al](http://doi.org/xxx/yyy))</cite>

However, the HTML export does not process the markdown content of the tag and is displayed as
*(\[Foo et al\](http://doi.org/xxx/yyy))*

Is it an nbconvert or a pandoc bug?

**Comment by takluyver** [comment]
We don't use pandoc when converting to HTML - there's a Python library called mistune that deals with converting Markdown to HTML. I don't know what the standards say about markdown syntax inside HTML tags - it might be that mistune is correct and the notebook interface is wrong in processing the markdown.

**Comment by pauleve** [comment]
Ok, it seems a duplicate of issue #45 ; with mistune, it works correcly when using parse_inline_html, so I guess it is not the setting nbconvert (nor nbviewer) is using..
