### ISSUE TITLE
Converting jupyter to pdf only converts 10 pages instead of full conversion.

### ISSUE THREAD

**Issue by cerushdope** [jupyter/nbconvert#797]
I have used `jupyter nbconvert --to PDF name.ipynb` before and it worked fine but now when I do it, it only converts 10 pages of pdf instead of whole notebook.

**Comment by t-makaro** [comment]
Apparently, compiling to pdf will fail at the first image if there is a space in the name of the notebook. Can you try converting ```--to latex```, and compiling the ```.tex``` document with pdflatex or XeLaTeX?

```
Jupyter nbconvert --to latex name.ipynb
pdflatex name.tex
```

**Comment by lzyang2000** [comment]
yeah the workaround works, but normally still getting 10 pages with no space in name of file...

**Comment by t-makaro** [comment]
A space in the file name is not the only thing that will cause the conversion to fail. A conversion will halt partway if there is an issue, but it will currently not display the error if a pdf is produced. Manually compiling the latex file with ```pdflatex``` or ```XeLaTeX``` will display the issue. See #896 and the commands in my previous comment.

**Comment by t-makaro** [comment]
Closing as stale / partially fixed with #896. The conversion to pdf should now produce the proper error instead of a partial conversion which should let you understand why the conversion is failing. Please fell free to ask to re-open or open a new issue if you have more information and need help.
