### ISSUE TITLE
Execute Notebook in Script: "No such kernel named R"

### ISSUE THREAD

**Issue by gwaygenomics** [jupyter/nbconvert#810]
I am trying to execute a notebook with an R kernel using the command:

```bash
jupyter nbconvert --to=html \
                  --FilesWriter.build_directory=html \
                  --ExecutePreprocessor.kernel_name=R \
                  --execute my_notebook.ipynb
```

I also tried not specifying the `kernel_name`.

In each case I receive an error, but the specific error for the command above is:

```
jupyter_client.kernelspec.NoSuchKernel: No such kernel named R
```

I am using `jupyter 4.4.0` and `conda 4.5.1`.

Any insight as to a solution? @dhimmel

**Comment by gwaygenomics** [comment]
I suppose I could convert to a script first and then run with `Rscript`, but it would be nice to run directly from the notebook

**Comment by dhimmel** [comment]
@gwaygenomics have you looked at the raw notebook for this info:

```json
  "kernelspec": {
   "display_name": "R [conda env:scihub]",
   "language": "R",
   "name": "conda-env-scihub-r"
  },
```

Perhaps you could try the `name` from there. Also try lowercase `r`, if you haven't.

I don't actually know a solution but am interested in seeing the answer.

**Comment by gwaygenomics** [comment]
yeah

```bash
  "kernelspec": {
   "display_name": "R [conda env:multiple-myeloma-classifier]",
   "language": "R",
   "name": "conda-env-multiple-myeloma-classifier-r"
  }
```

the name is used by default (if I don't specify a `kernel_name`). I didn't try a lowercase `r` until just now, but it didn't work either.

```bash
jupyter_client.kernelspec.NoSuchKernel: No such kernel named r
```

:man_shrugging:

**Comment by tallamjr** [comment]
@gwaygenomics , did you manage to resolve this? I have found that changing 
`--ExecutePreprocessor.kernel_name=R` to `--ExecutePreprocessor.kernel_name=ir` fixed things for me. i.e. the full command I am able to run successfully is:

```
jupyter nbconvert --ExecutePreprocessor.kernel_name=ir --ExecutePreprocessor.timeout=600 --to html --execute notebooks/R-example-notebook.ipynb
```

**Comment by gwaygenomics** [comment]
awesome, thanks @tallamjr

**Comment by cvargas-geo** [comment]
--ExecutePreprocessor.kernel_name=ir work form me in sagemaker

**Comment by cvargas-geo** [comment]
> @gwaygenomics , did you manage to resolve this? I have found that changing `--ExecutePreprocessor.kernel_name=R` to `--ExecutePreprocessor.kernel_name=ir` fixed things for me. i.e. the full command I am able to run successfully is:
> 
> ```
> jupyter nbconvert --ExecutePreprocessor.kernel_name=ir \
>                   --ExecutePreprocessor.timeout=600 \
>                   --to html \
>                   --execute notebooks/R-example-notebook.ipynb
> ```

What is the difference?

**Comment by gwaygenomics** [comment]
Yes! `ir` works. Thanks!

**Comment by cvargas-geo** [comment]
> Yes! `ir` works. Thanks!

But its loads a custom libraries by example dplyr ?

**Comment by gwaygenomics** [comment]
In my use case, I'm converting a .ipynb kernel to a .r script. No loading is happening.
