### ISSUE TITLE
Consider factoring out the "execute" module into its own package

### ISSUE THREAD

**Issue by choldgraf** [jupyter/nbconvert#821]
Curious what folks think about this:

I've had a lot of confusion from people who want to run jupyter notebooks from the command line (e.g. as a part of batch jobs). They usually think they can do something like `python notebook.ipynb` or `jupyter notebook.ipynb`.

I usually correct them with the `nbconvert` solution (e.g. `jupyter nbconvert --to notebook --execute --inplace`) though I've found that this seems really unintuitive for most people (e.g., "why do I have to use a notebook conversion tool just to execute it?"). Moreover if you want to make other modifications (like define the kernel to be used), you need to start adding code like `----ExecutePreprocessor.kernel_name=python3` which feels a bit clunky.

In short, IMO the `execute` module is orthogonal enough and useful enough that it could be separated from `nbconvert` into its own repository. Then you could design an API around it that would be more intuitive for folks (e.g. `jupyter nbexecute mynotebook.ipynb --kernel_name=python3`) and design more complexity around this specific task (e.g. find ways to interface with projects such as [nbparameterize](https://github.com/takluyver/nbparameterise) or [papermill](https://github.com/nteract/papermill)). `nbconvert` could then use this API under the hood in conjunction with the `--execute` flag.

So I guess my questions are:

1. Do other folks agree that the "execute" part of nbconvert is useful enough to be its own separate repo?
2. How entangled is the execute preprocessor with `nbconvert`? Would it be extremely difficult to spin it off into its own thing?

**Comment by choldgraf** [comment]
cc @rgbkrk and @takluyver since they've both built on top of the "execute" functionality here. curious what you two think!

**Comment by takluyver** [comment]
Yeah, it probably makes sense, and I don't think it's particularly entangled with nbconvert.

Maybe the hardest decision is picking what to call the new package and the new command. One option is that it could go into `jupyter_client` (or its replacement, `jupyter_kernel_mgmt`) as part of the `jupyter run` command.

**Comment by rgbkrk** [comment]
I do think there's a core of nbconvert that should be extracted out, especially when it's replacing the notebook itself, rather than converting to another format.

**Comment by choldgraf** [comment]
> especially when it's replacing the notebook itself, rather than converting to another format

Totally. I opened this issue because I thought to myself "I'm not converting anything if I want to just run it. I'm just converting it into...itself..."

Something like `jupyter run XXX` makes sense to me...

**Comment by rgbkrk** [comment]
Totally. It's also a pretty strong pre-cursor to us being able to expose functionality we should be sharing for a server side model of the notebook document as its executing.

**Comment by takluyver** [comment]
We kicked that idea around ages ago under the name 'nbmanipulate', IIRC. It definitely makes a kind of sense, but I get package fatigue...

**Comment by MSeal** [comment]
There's not an [nbclient](https://github.com/jupyter/nbclient) repo. I'll be making a push this week to get the logic ported over and prepping for an initial release.

**Comment by choldgraf** [comment]
yessss, I think this is awesome :-)

**Comment by choldgraf** [comment]
![](https://media.giphy.com/media/lMameLIF8voLu8HxWV/giphy.gif)

**Comment by MSeal** [comment]
Hahah -- yeah I forgot to close this issue a bit ago :confetti_ball:
