### ISSUE TITLE
Spaces and markdown to html conversion 

### ISSUE THREAD

**Issue by bbadzioch** [jupyter/nbconvert#829]
The following code entered into a markdown cell gets converted by nbconvert (5.3.1) as expected:

`<p style="color: red;">test</p>`

However, if a space is added either before or after the equality sign like this:

`<p style ="color: red;">test</p>`

then nbconvert produces

`<p>&lt;p style ="color: red;"&gt;test&lt;/p&gt;</p>`

**Comment by takluyver** [comment]
Markdown to HTML conversion is done by [mistune](https://github.com/lepture/mistune); can you see if you can reproduce the results using that directly?

**Comment by bbadzioch** [comment]
I can reproduce it with mistune, I submitted this issue to the mistune repo. I noticed that running mistune with the `parse_block_html=True` option eliminates this problem. In the same way issue #550 can be fixed.

**Comment by takluyver** [comment]
Linking the mistune issue: https://github.com/lepture/mistune/issues/161

**Comment by t-makaro** [comment]
Closing as the upstream issue appears resolved. Please comment asking to reopen if this is still an issue.
