### ISSUE TITLE
Config option `exclude_input` not working for pdf directly but is working for latex

### ISSUE THREAD

**Issue by vbreukels** [jupyter/nbconvert#840]
When exporting a notebook to pdf, the TemplateExporter.exclude_code_cell=True or exclude_input=True option is not recognised. Strangely enough, it does work when exporting to latex first and 'manually' convert the tex file to pdf. 

Is this normal behavior?

More details, I am using nbconvert 5.3.1, from conda repository on a mac os 10.13.2.

**Comment by t-makaro** [comment]
I believe this was fixed in 5.4.0 by #734. Closing as I cannot reproduce this on master. Please comment asking to reopen if this is still an issue.
