### ISSUE TITLE
Converting some NotebookNodes to HTML throws errors

### ISSUE THREAD

**Issue by nicktimko** [jupyter/nbconvert#85]
When attempting to convert a (seemingly valid) `NotebookNode` created a couple different ways, some throw errors at me.

```
import json
import nbconvert
import nbformat

mydict = json.loads('{"cells":[{"cell_type":"code","execution_count":null,"metadata":{"collapsed":true},"outputs":[],"source":[]}],"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.4.2"}},"nbformat":4,"nbformat_minor":0}')

nnode1 = nbformat.NotebookNode(mydict) # exporting causes AttributeError
nnode2 = nbformat.from_dict(mydict) # exporting causes TypeError
nnode3 = nbformat.reads(json.dumps(mydict), as_version=4)

exporter = nbconvert.html.HTMLExporter()
exporter.from_notebook_node(nnode3)
```

Attempting to convert `nnode1` gives AttributeError: 'dict' object has no attribute 'cell_type', while no. 2 results in TypeError: expected string or buffer, both in and around nbconvert/preprocessors/highlightmagics.py:preprocess_cell(...).

Am I doing it wrong or is the package?

**Comment by Carreau** [comment]
Indented for readability. 
```
{'cells': [{'cell_type': 'code',
   'execution_count': None,
   'metadata': {'collapsed': True},
   'outputs': [],
   'source': []}],
 'metadata': {'kernelspec': {'display_name': 'Python 3',
   'language': 'python',
   'name': 'python3'},
  'language_info': {'codemirror_mode': {'name': 'ipython', 'version': 3},
   'file_extension': '.py',
   'mimetype': 'text/x-python',
   'name': 'python',
   'nbconvert_exporter': 'python',
   'pygments_lexer': 'ipython3',
   'version': '3.4.2'}},
 'nbformat': 4,
 'nbformat_minor': 0}
```

So one of the issues (at least for nnode2) is that in-memory source is supposed to be a string, and not a list of string. Which get through the validation process as we have only 1 schema for disk and in-memory (for historical reasons)

We should probably make these distinction and methods more accurate/documented/robust.

**Comment by minrk** [comment]
If you have the raw JSON in-memory, you need to convert it to the in-memory format:

```python
from nbformat.v4 import to_notebook
nb = to_notebook(nb_dict)
```

If you got the JSON *string* somehow (it presumably came from somewhere), you can get a notebook with `nbformat.reads(json_string)` instead of `json.loads(json_string)`
