### ISSUE TITLE
Hide In[] tags (not content) and extra newline in nbconvert script export

### ISSUE THREAD

**Issue by citizenrich** [jupyter/nbconvert#851]
It would be helpful to export cleaner executable scripts to Python from notebooks. The current export seems to include extra newlines and the "In[ ]:" tags. Here's an example exported from a JupyterLab-originated notebook:

```py
# coding: utf-8

# In[ ]:


import pandas as pd


# In[ ]:
```
There are two newlines between each cell and the "# In[ ]:" tag. I'm happy to address this a different way and sorry if this is the wrong repo to bring it up!

**Comment by matanster** [comment]
+1 for this. I don't think these `In [ ]:` lines add an informative value, other in the most bizarre scenario. They do however, introduce overarching noise when diffing notebooks after converting them to python (script). In the least I'm sure it can be made an optional thing to include them, if anyone relied on them before...

**Comment by matanster** [comment]
Wait, isn't `--no-prompt` supposed to remove them? I don't see that happening when I use it so a little confused. Anyway thanks for maintaining nbconvert it's really really helpful!

**Comment by akhmerov** [comment]
`--no-prompt` does remove the prompts. This is what I see:
```bash
jupyter nbconvert --to python Untitled.ipynb --stdout --no-prompt                                                                                                 (main) 
[NbConvertApp] Converting notebook Untitled.ipynb to python
#!/usr/bin/env python
# coding: utf-8

from time import sleep
sleep(3600)
```

**Comment by citizenrich** [comment]
I can still replicate the problem. I add a print statement in another cell. Run it. Then clear outputs. Export from the interface as executable script and the unnecessary bits are there. This happens in both a notebooks and a lab. It does not happen from the command line export.

Also, still two newlines between cells in command line export as well.


```py
# coding: utf-8

# In[ ]:


#!/usr/bin/env python
# coding: utf-8

from time import sleep
sleep(1)


# In[ ]:


print('hello, world!')
```

**Comment by akhmerov** [comment]
What command do you use to output the script?

**Comment by citizenrich** [comment]
The above example uses the webpage menu to do the export. When from the command line, which works:
```
jupyter nbconvert  --no-prompt --to python Untitled.ipynb --stdout
```

**Comment by citizenrich** [comment]
I think what I'm confusing is that the export from the webpage does not include 'no prompts'. I can close this and put in another ticket to add that feature if preferred.

**Comment by akhmerov** [comment]
I see. Perhaps it makes sense then to update the issue description to make it clear that it is about the default values.

**Comment by citizenrich** [comment]
Thanks @akhmerov.  Just to be clear for others coming to this issue, this was my error: nbconvert is behaving as expected. I'll close this. I'll visit with the jupyter notebook/lab repos to ask that the default be to add "--no-prompt" for Python as executable scripts from the interface.

I'm still curious if there is interest in changing from two newlines to one newline for translating between split cells and scripts.
