### ISSUE TITLE
pytest appears to be a runtime dependency

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/nbconvert#853]
Running `nbconvert` from source, it seems that `nbconvert/utils/io.py` imports `pytest` since PR https://github.com/jupyter/nbconvert/pull/758

**Comment by SylvainCorlay** [comment]
cc @mpacer

**Comment by Carreau** [comment]
Yeah, we can either load pytest into the decorator,  or move the decorator into a test-specific utils.
