### ISSUE TITLE
Tornado 6 compatibility

### ISSUE THREAD

**Issue by mrocklin** [jupyter/nbconvert#894]
Note that as of Tornado 6 (still in development) the `web.asynchronous` decorator has left.  This seems to break nbconvert

```
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/nbconvert/postprocessors/serve.py", line 21, in ProxyHandler
    @web.asynchronous
AttributeError: module 'tornado.web' has no attribute 'asynchronous'
```

**Comment by jakirkham** [comment]
Also seeing this with Tornado 6.0.1, which was recently released.

**Comment by stefanseefeld** [comment]
I just installed the whole software stack via `pip3`, now with Tornado 6.0.1 (no longer beta !), and still got the same error. FWIW.

**Comment by minrk** [comment]
This is fixed by #937 and released in nbconvert 5.4.1. Can you `pip install --upgrade nbconvert`?

**Comment by aglavers** [comment]
Confirming that  `conda install nbconvert=5.4.1` resolved this error

      File "/opt/conda/lib/python3.6/site-packages/nbconvert/postprocessors/serve.py", line 21, in ProxyHandler
        @web.asynchronous
    AttributeError: module 'tornado.web' has no attribute 'asynchronous'

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/kernel-does-not-start-in-jupyter-notebook-when-using-other-anaconda-environment-then-base/1952/10
