### ISSUE TITLE
help needed on nbconvert errors (converting ipython notebook to pdf)

### ISSUE THREAD

**Issue by sanittawan** [jupyter/nbconvert#897]
I'm a new Jupyter notebook user. I have looked through similar issues posted here but can't find a fix for Mac users. I tried running this command: 

   ` ipython nbconvert --to pdf filename.ipynb`

And I got the following errors: 

>/usr/local/lib/python3.7/site-packages/nbconvert/utils/pandoc.py:52:
> RuntimeWarning: You are using an unsupported version of pandoc
> (2.3.1).
>     Your version must be at least (1.12.1) but less than (2.0.0).

And 

> OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.

When I tried converting my ipython notebook to pdf using the web interface through file>download as>PDF via LaTex, I also got a similar error: 

>500 : Internal Server Error
The error was:
>nbconvert failed: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.

I use Mac High Sierra 10.13.6. I have both MacTex 2018 and BasicTex installed according to the link in the error message. So, I should have XeLaTex. Via Homebrew, I installed pandoc 2.3.1, my Jupyter version 4.4.0, and ipython 7.0.1. How should I fix both errors? If I have to add XeLaTex to PATH, how do I do it in the terminal? 

Thank you in advance!

**Comment by mgeier** [comment]
The first output you are mentioning is only a warning (see #928), you can most likely ignore it.

The other thing, about locating `xelatex` is unrelated to this.

Sadly, I don't know what's the problem there, but I can tell you what I normally do, which might also help you:

I'm normally just converting `--to latex` and do the generation of the PDF file in a separate step.

I highly recommend the tool `latexmk` for that, I've written a little tutorial there: https://mg.readthedocs.io/latexmk.html

**Comment by moondra2017** [comment]
Having the same problem as parent/OP, though Im on Windows 7.
I guess I will try the "latex" solution if that's currently the best way.

**Comment by t-makaro** [comment]
Closing as a duplicate of #799

**Comment by cafdcarvalho** [comment]
> Sou um novo usuário do notebook Jupyter. Eu examinei problemas semelhantes postados aqui, mas não consigo encontrar uma solução para usuários de Mac. Tentei executar este comando:
> 
> ` ipython nbconvert --to pdf filename.ipynb`
> 
> E recebo os seguintes erros:
> 
> > /usr/local/lib/python3.7/site-packages/nbconvert/utils/pandoc.py:52: 
> > Aviso de tempo de execução: você está usando uma versão não compatível do pandoc 
> > (2.3.1). 
> > Sua versão deve ser pelo menos (1.12.1), mas menor que (2.0.0).
> 
> E
> 
> > OSError: xelatex não encontrado no PATH, se você não instalou o xelatex, pode ser necessário fazer isso. Encontre mais instruções em [https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex ](https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex).
> 
> Quando tentei converter meu notebook ipython em pdf usando a interface da web por meio de arquivo> baixar como> PDF via LaTex, também recebi um erro semelhante:
> 
> > 500: Erro interno do servidor 
> > O erro foi: nbconvert falhou: xelatex não encontrado em PATH, se você não instalou o xelatex, pode ser necessário fazer isso. Encontre mais instruções em [https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex ](https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex).
> 
> Eu uso o Mac High Sierra 10.13.6. Tenho o MacTex 2018 e o BasicTex instalados de acordo com o link na mensagem de erro. Então, eu deveria ter o XeLaTex. Via Homebrew, instalei o pandoc 2.3.1, meu Jupyter versão 4.4.0 e o ipython 7.0.1. Como devo corrigir os dois erros? Se eu tiver que adicionar XeLaTex ao PATH, como faço no terminal?
> 
> Agradeço antecipadamente!

solucionei com a instalação pip install nbconvert
