### ISSUE TITLE
ipython nbconvert --to latex ignores <a name=...> targets, again

### ISSUE THREAD

**Issue by Marek77** [jupyter/nbconvert#899]
Hello,

this is a repeat/regression of issue #578 

pandoc version 1.19.1
jupyter nbconvert version 5.3.1
(on Fedora 27)

Attached minimal test case:

`a.html` and the resulting `a.tex` (command: `pandoc a.html -s -o a.tex`) showing that pandoc is handling the conversion of `<a name="something"></a>` correctly.

`Untitled.ipynb` and the resulting `Untitled.tex` (command: `jupyter nbconvert --to latex Untitled.ipynb`) showing that nbconvert doesn't. The result does not change if the `<a name...>` is in the same cell as the referring link, or in separate cells.

[nbconvert.zip](https://github.com/jupyter/nbconvert/files/2482923/nbconvert.zip)

**Comment by mgeier** [comment]
To be fair, you should use `pandoc` with Markdown input in your comparison. Then you'll see that `pandoc` swallows the `<a ...>`, too.

```
$ pandoc --from html --to latex
text <a name="test"></a> text
^D
text \protect\hypertarget{test}{}{} text
$ pandoc --from markdown --to latex
text <a name="test"></a> text
^D
text text
```

I agree that this would be a useful feature, though.

**Comment by Marek77** [comment]
My issue is not with `pandoc`. In my workflow I have a list of Jupyter notebooks -> `nbconvert` to LaTeX (which uses `pandoc` I believe) -> stitch several .tex files together -> `latexmk` -> a single PDF document.

This has worked until relatively recently (not sure when exactly it got broken though..); I suspect a Jupyter update.

I posted the `pandoc` example as the previous bug was closed with "this is a `pandoc` issue", to show that this is a `nbconvert` regression and NOT a `pandoc` regression.

**Comment by mgeier** [comment]
> This has worked until relatively recently

You mean the `<a name=...>` has been converted to `...\hypertarget...`?
If yes, this must have been a change in the behavior of `pandoc`. It would be helpful if you could find out at which version of `pandoc` this behavior changed.

I don't believe that it is a `nbconvert` regression, but if it is, you should be able to pinpoint a certain `nbconvert` version that shows the desired behavior. Once we have such a version, it should be relatively easy to find the commit that changed the behavior with `git bisect`.

> stitch several .tex files together

This doesn't have anything to do with the current issue, but have you tried using Sphinx and my [nbsphinx](https://nbsphinx.readthedocs.io/en/latest/) extension?
This allows you to combine multiple Jupyter notebooks and create a single LaTeX file from them. For an example PDF see https://readthedocs.org/projects/nbsphinx/downloads/pdf/latest/.
Your `<a name...>` anchor won't work there either, though ...

**Comment by Marek77** [comment]
This took a while, but I have found the version that works. I remembered my docs were correctly generated on Fedora 25 so I installed a VM and indeed the results are good (for me at least). 

Here are the package versions:
```
# rpm -qa \*ipython\* \*pandoc\* | sort
ghc-pandoc-1.17.0.3-2.fc25.x86_64
ghc-pandoc-types-1.16.1-2.fc25.x86_64
pandoc-1.17.0.3-2.fc25.x86_64
pandoc-common-1.17.0.3-2.fc25.x86_64
python-ipython-3.2.1-8.fc25.noarch
python-ipython-console-3.2.1-8.fc25.noarch
python-ipython-gui-3.2.1-8.fc25.noarch
python-ipython-notebook-3.2.1-8.fc25.noarch
python-ipython-sphinx-3.2.1-8.fc25.noarch
```

I updated the attached zip with the files generated on F25.
F25 `pandoc` seems to do a worse job by generating

F25: `\href{}{}\\`
vs
F27: `\protect\hypertarget{test}{}{}\\`

(this is not surprising), but looking at `nbconvert`:

F25: `    \protect\hyperlink{test}{link to}`  (good! :-) )

F27: `    Section \ref{test}` (bad :-( )

[nbconvert.zip](https://github.com/jupyter/nbconvert/files/2620002/nbconvert.zip)

**Comment by mgeier** [comment]
Thanks for the update. I still think that the problem is a change in behavior of `pandoc`, but it is still not 100% clear from your data.

Could you please test only `pandoc` without `nbconvert` involvement on your two systems with something like what I showed in https://github.com/jupyter/nbconvert/issues/899#issuecomment-436215717.

But if it turns out to be a regression in `pandoc`, you should probably create an issue on their issue tracker: https://github.com/jgm/pandoc/issues.

There might also be an option for `pandoc` to switch to your desired behavior?

**Comment by Marek77** [comment]
old (F25) behaviour:

```
$ pandoc --from html --to latex
text <a name="test"></a> text
^D
text \href{}{} text
```

new (F27):

```
$ pandoc --from html --to latex
text <a name="test"></a> text
^D
text \protect\hypertarget{test}{}{} text
```

**Comment by mgeier** [comment]
Thanks, now the same for `pandoc --from markdown --to latex` please, because that's what `nbconvert` actually uses.

**Comment by Marek77** [comment]
F25:

```
$ pandoc --from markdown --to latex
[NAME](#NAME)
^D
\protect\hyperlink{NAME}{NAME}
```

F27:

```
$ pandoc --from markdown --to latex
[NAME](#NAME)
^D
\protect\hyperlink{NAME}{NAME}
```

**Comment by mgeier** [comment]
Thanks again, but the thing that's relevant is this:

```
$ pandoc --from markdown --to latex
text <a name="test"></a> text
^D
???
```

**Comment by mgeier** [comment]
OK, thanks. So there is no difference.

It never actually worked.

You made it sound like a regression in `nbconvert` or `pandoc`, but it's not.

The current (and past) behavior of `nbconvert` (and `pandoc`) is (and always was) to strip this (when converting from Markdown to LaTeX):

    <a name="something"></a>

You were suggesting that there was some version of `nbconvert` or `pandoc` that didn't do that, but it turns out that's not true.

**Comment by Marek77** [comment]
I'm not sure I'm following the conclusion here. Are you saying NOTABUG / WORKSFORME?

Because for me it doesn't, except when I'm generating my PDF in Fedora 25. In F25 I have internal PDF links that work, in F27 they're broken.  

My documentation output is a PDF generated from sources in .pod and .ipynb format. I confirm that the inputs (.ipynb files generated from .pod) are identical (except of metadata `nbformat_minor` values...) between F25 and F27. 

Example:
```
$ diff -Naurb f25/query_mgr.conf.pod.ipynb f27/query_mgr.conf.pod.ipynb
--- f25/query_mgr.conf.pod.ipynb        2018-12-10 13:58:53.125649844 +0100
+++ f27/query_mgr.conf.pod.ipynb        2018-12-10 13:56:42.051659474 +0100
@@ -91,5 +91,5 @@
  ],
  "metadata": {},
  "nbformat": 4,
- "nbformat_minor": 0
+ "nbformat_minor": 2
 }
```

The only other variable is `latexmk` (between `latexmk-4.60-1.fc27.noarch` and `latexmk-4.53a-1.fc25.noarch` to be precise).

So I generated all the inputs for `latexmk` in the F25 VM and fed them into F27 `latexmk`. The PDF is correctly generated and there is no difference between F25 and F27 PDFs from the "internal links inside PDF" point of view.

The whole chain from source to .ipynb is identical between the two systems. Once we go from .ipynb to .tex, things break on F27. With correct .tex inputs, latexmk generates a correct PDF on either system.

For me the only variables left are `pandoc` and `nbconvert`. The result is that to generate my doc I have to keep my old F25 VM.

I don't seem to be able to upload the screenshots, but it's quite frustrating to see links in the PDF as
``` 
 Section ??
 Section ??
 Section ??
 Section ??
 Section ??
 Section ??
 Section ??
```

instead of 
```
 NAME
 DESCRIPTION
 COMMON OPTIONS
 ADVANCED OPTIONS
 FILES
 SEE ALSO
 COPYRIGHT AND LICENSE
```

**Comment by mgeier** [comment]
> I'm not sure I'm following the conclusion here. Are you saying NOTABUG / WORKSFORME?

Not exactly.

I'm saying that based on the files you provided, the only conclusion that can be reached is that the regression you are describing does not exist (in the form that you are describing it).

That doesn't mean there is no regression.

To get to the bottom of this, I would suggest that you do a few steps:

* Create a new Github repository (or a Gist, if you prefer)
* Create a single notebook with a single instance of the problem. Make sure there is nothing else in the notebook that could distract from the actual problem.
* Push the notebook to your repo
* Clone the repo from your F25 VM. Create a `.tex` file *and* a `.pdf` file (for example in an aptly named sub-directory) and push them to the repo.
* Clone the repo from your F27 machine. Create a `.tex` file *and* a `.pdf` file, making sure not to overwrite the previous ones, and push them to the repo.
* Share a link to the repo here.

**Comment by Marek77** [comment]
I created a minimal test case and indeed there is no regression: nbconvert + pandoc don't preserve the anchor when exporting .ipynb to .tex. To get "internal links" of type `<a name='something' />`  I'm using my own post-processing before turning .tex into .pdf.

Closing.

**Comment by m2rik** [comment]
I am having a similar issue with the internal links in the notebook
`Section ?
Section ?
Section ?`
Does anybody seem to have found a fix?
