### ISSUE TITLE
Serve without opening a browser

### ISSUE THREAD

**Issue by teodorlu** [jupyter/nbconvert#906]
Hello!

I would like to run the `serve` postprocessor without having it open a new browser tab each time the process is run. This will let me automatically run nbconvert each time a file changes (with a tool like [entr][1]) without ending up with lots of open tabs.

Possible fix:

- Make `--post serve` just serve the files
- ... and `--post serve --post browse` open files.

But you might be concerned with backwards compatibility, and changing the meaning of --post serve may confuse those who already use the tool. In such a case, perhaps it would be better to make a new `--post just-serve`?

What do you think?

[1]: http://entrproject.org

**Comment by t-makaro** [comment]
This is possible with the [open_in_browser]() configuration option. Just do

```
jupyter nbconvert --to slides notebook.ipynb --post serve --ServePostProcessor.open_in_browser=False
```

**Comment by teodorlu** [comment]
Thanks! That resolves my use case.
