### ISSUE TITLE
What are the plans regarding usage of pandoc?

### ISSUE THREAD

**Issue by mgeier** [jupyter/nbconvert#928]
Currently, we get a warning if we are using `pandoc` >= 2.0:

https://github.com/jupyter/nbconvert/blob/02c5cd1424b65da018f244e0f033a3dde55f76ca/nbconvert/utils/pandoc.py#L18

The warnings look like this:

    RuntimeWarning: You are using an unsupported version of pandoc (2.2.1).
    Your version must be at least (1.12.1) but less than (2.0.0).

Do you really want users to keep using old `pandoc` versions?
Right now that's probably still quite easy, but at some point, older versions will be harder and harder to get (or will have to be compiled from source, but that might also get harder with newer versions of Haskell compilers).

Currently, we are at `pandoc` release 2.5, and it is evolving quite rapidly: https://pandoc.org/releases.html

The warning is not only annoying for me, it's also confusing for others, e.g. #897.

There's actually an open issue: #815, but it doesn't look very active ...

I'm not sure what's the actual problem (#815 doesn't mention it), but for my use cases (using `nbsphinx`) I didn't see any problems, I'm just getting those annoying warnings (and many of them!).

Could this warning probably be limited to the use cases where there are actually problems?

**Comment by paultopia** [comment]
Related to this issue, the warning that is issued comes out very spammy.  When using nbconvert as a library to convert a single notebook to pdf, I get the pandoc warning after calling the `.from_notebook_node()` method at REPL no less than... actually, I stopped counting at 40.  Seriously, it just filled multiple terminal screens with the same damn warning over and over again, apparenting calling `check_pandoc_version()` dozens and dozens of times.  

What would it take to get this down to 1?  If it requires a check for the pandoc version lots of times, can there be some kind of state flag in the conversion process that gets set once the warning has been delivered once, so it doesn't spam people to death?

**Comment by minrk** [comment]
#964 supports pandoc 2 and fixes the warning being shown more than once when an unrecognized pandoc is found.
