### ISSUE TITLE
5.4.1 Release

### ISSUE THREAD

**Issue by MSeal** [jupyter/nbconvert#929]
What PR's should we get in before a patch release would be reasonable to ship? We've had requests for a few changes to get out that already merged.

I would like to get https://github.com/jupyter/nbconvert/pull/905 merged, but it's not mandatory if people would rather that be a 5.5 change.

Thoughts / Requests?

**Comment by mgeier** [comment]
What about making a quick release before the end of the year without any additional changes (since there don't seem to be urgent requests)?

The `nbconvert` project seems to quite inactive right now, probably there is some more progress next year?

**Comment by mgeier** [comment]
I don't mean to appear impatient, but what about this release?

**Comment by MSeal** [comment]
Sorry, you're right to be impatient. My apologies for being late with other tasks. We have a summit we're running this week but I'll get the process going at the end of the week. It sounds like there wasn't any push for other changes and some of the pending changes look to not being moved forward for a bit so I won't block on them.

**Comment by MSeal** [comment]
5.4.1 is live -- apologies for the delay again.

**Comment by Juanlu001** [comment]
Thanks @MSeal!

**Comment by Juanlu001** [comment]
...Although the release that has been uploaded to PyPI is 5.4.1.dev0, I believe? https://pypi.org/project/nbconvert/#history

**Comment by MSeal** [comment]
Oops. Fixing

**Comment by mgeier** [comment]
Thanks a lot @MSeal!
