### ISSUE TITLE
Not removing raw cells when I run `nbconvert --to notebook --TemplateExporter.exclude_raw=True`

### ISSUE THREAD

**Issue by NickleDave** [jupyter/nbconvert#934]
I'm trying to export notebooks from a `./doc/notebooks` folder to a `./notebooks` folder in the root of my project, but remove all the raw cells from the `./doc` versions of the notebooks, where I have rst (such as: `.. _section_name:`).

I tried the following:

    jupyter nbconvert --to notebook $< --output=$@ --TemplateExporter.exclude_raw=True

I'm doing this in a Makefile (so the $< is the name of the `./doc` versions of the notebooks and $@ is the names of the notebook once it is moved to the top-level `./notebook dir`, respectively). 

It runs, but the raw cells are still there in the copies of the notebooks.

Running `make -n name-of-my-rule` tells me that the commands look as intended, so it's not some bug with that.

Not sure if this is a bug, or intended behavior I don't understand, or if there's something I'm missing (in which case I can close this issue, and if some kind soul wants to help me out I asked on S.O. too https://stackoverflow.com/questions/53974582/jupyter-nbconvert-to-notebook-not-excluding-raw-cells)

**Comment by datamove** [comment]
Looks to me the same root cause as

**Comment by NickleDave** [comment]
I saw. Thank you! I'll close this issue and use that workaround for now.
