### ISSUE TITLE
ModuleNotFoundError if running jupyter nbconvert --execute

### ISSUE THREAD

**Issue by leslie-wang** [jupyter/nbconvert#953]
I have one jupyter notebook, and I can run it successfully by `jupyter notebook`, then navigate and select the notebook, but when I run it in shell directly via `https://nbconvert.readthedocs.io/en/latest/execute_api.html` with the same command as the one listed in the web page, I got failure as below. Should I add some environment variable here?
```
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

# Pandas options
pd.set_option('display.max_colwidth', 1000, 'display.max_rows', None, 'display.max_columns', None)

# Plotting options
%matplotlib inline
mpl.style.use('ggplot')
sns.set(style='whitegrid')
------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-fd0c65dc871a> in <module>
----> 1 import numpy as np
      2 import scipy as sp
      3 import pandas as pd
      4 import matplotlib as mpl
      5 import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'numpy'
```

**Comment by leslie-wang** [comment]
seems like numpy was installed on python2, but not in python3. But no idea why browser version works.

**Comment by MSeal** [comment]
Likely you were using each run pattern was using a different python kernel on your system. Were you running with `jupyter nbconvert ...` or by importing? If one was using your python 2 jupyter instead of python 3 that might affect the available kernels to use when executing.
