### ISSUE TITLE
Add CLI option to list available export names

### ISSUE THREAD

**Issue by flying-sheep** [jupyter/nbconvert#960]
I can do

```bash
python -c 'import nbconvert; print(*nbconvert.exporters.get_export_names(), sep=" ")'
```

but that’s not very discoverable

**Comment by MSeal** [comment]
I agree. That would be a nice, quick addition.

**Comment by rahulpshah** [comment]
Is this still an issue? https://github.com/jupyter/nbconvert/blob/8b47cf1ebfde7465e21927db5a699a54e4fc1c1a/nbconvert/nbconvertapp.py#L184

**Comment by flying-sheep** [comment]
Oh! well, I didn’t find that there. Should be inline in the `--to` param docs, too.

**Comment by MSeal** [comment]
I too missed with a quick look since the examples are far away from the `--to` option. @flying-sheep you could make a PR to update that commands description fairly easily.
