### ISSUE TITLE
Great! You will need to add handling of [input requests](http://jupyter-client.readthedocs.org/en/latest/messaging.html#messages-on-the-stdin-router-dealer-sockets) on the input channel of the KernelClient. you will also want to add `allow_stdin=True` to the execute requests, to enable these messages.

### ISSUE THREAD

**Issue by janki9395** [jupyter/nbconvert#966]
Great! You will need to add handling of [input requests](http://jupyter-client.readthedocs.org/en/latest/messaging.html#messages-on-the-stdin-router-dealer-sockets) on the input channel of the KernelClient. you will also want to add `allow_stdin=True` to the execute requests, to enable these messages.

_Originally posted by @minrk in https://github.com/jupyter/nbconvert/issues/288#issuecomment-208331975_

**Comment by t-makaro** [comment]
Closing as this just quotes a comment from another issue.
