### ISSUE TITLE
Feature request: custom output filename

### ISSUE THREAD

**Issue by answerquest** [jupyter/nbconvert#967]
Current command:
```
jupyter nbconvert --to script "10.3.19 some complicated filename I use for explaining to my clients.ipynb"

# output : creates "10.3.19 some complicated filename I use for explaining to my clients.py"
```

Desired command:
```
jupyter nbconvert --to script --o "run1.py" "10.3.19 some complicated filename I use for explaining to my clients.ipynb"
# output : creates "run1.py"
```
Possible?

**Comment by MSeal** [comment]
Yes.

`jupyter nbconvert --to script --output "run1.py" "10.3.19 some complicated filename I use for explaining to my clients.ipynb"`

**Comment by answerquest** [comment]
Ah, thanks! Is this mentioned somewhere in the docs?

https://nbconvert.readthedocs.io/en/latest/search.html?q=--output&check_keywords=yes&area=default

Where would be a good place to put it? From end user perspective it would be great to have a "manpage" or list of all all possible parameters to include in command line

**Comment by mgeier** [comment]
@answerquest You can list all possible command line options with

    python3 -m nbconvert --help

or

    jupyter nbconvert --help
