### ISSUE TITLE
output saved partially to the notebook when executing with timeout=-1

### ISSUE THREAD

**Issue by shamimtowhid** [jupyter/nbconvert#968]
I executed a notebook with nbconvert command and the notebook takes a long time to be fully executed. It finishes successfully executing. However the output is partially written in the new notebook. Is there any way to write the output to the files during execution?

Note: I was trying to save the output in the same file with --inplace=True.

**Comment by MSeal** [comment]
Currently no. The processor builds the whole notebook and then persists it into the desired format. https://papermill.readthedocs.io/en/latest/ wraps nbconvert and it will save notebook execution after each cell completes (and optionally log to stdout/err during cell execution). After I finish https://github.com/jupyter/nbconvert/pull/905 it should be more feasible to potentially allow similar behavior directly in nbconvert.

**Comment by shamimtowhid** [comment]
Thanks for the reply. I think [#905](https://github.com/jupyter/nbconvert/pull/905) will be helpful for me. For now I should use log files as a solution.
