### ISSUE TITLE
Cells with %%time magic seem not to execute in nbconvert?

### ISSUE THREAD

**Issue by kmader** [jupyter/nbconvert#975]
I have been using `nbconvert` along with a few other scripts for my presentations and exercises to ensure all of the cells run correctly. Recently I have noticed that a lot of my builds were failing and it appears that the cells with `%%time` magic were not being executed by nbconvert (https://circleci.com/gh/kmader/Quantitative-Big-Imaging-2019/79?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) and thus the appropriate variables were not being defined, simply deleting the `%%time` statements fixed the issue, but this didn't used to be an issue at all.

**Comment by MSeal** [comment]
Is it related to https://github.com/ipython/ipython/issues/11659 perhaps? This came up today in a few channels

**Comment by cdeil** [comment]
@kmader - could you try to update to IPython 7.5.0 and see if that fixes your issue?
Should be resolved.
See https://ipython.readthedocs.io/en/stable/whatsnew/version7.html#ipython-7-5-0
