### ISSUE TITLE
Latex error with strikethrough

### ISSUE THREAD

**Issue by kennysong** [jupyter/nbconvert#99]
Exporting as PDF gives an error when there's strikethroughs in the markdown text. The webpage displays the error "nbconvert failed: PDF creating failed", and the server displays the error,

```
(/usr/local/texlive/2014/texmf-dist/tex/latex/ucs/data/uni-0.def)
    ! Undefined control sequence.
    l.240 by \sout
                  {Matlab's} Python's \texttt{exp} function. For which of the
    ?
    ! Emergency stop.
    l.240 by \sout
                  {Matlab's} Python's \texttt{exp} function. For which of the
    !  ==> Fatal error occurred, no output PDF file produced!
    Transcript written on notebook.log.
```

**Comment by michaelpacer** [comment]
So I think it's related to a problem with how `\sout` is defined in the `ulem` package for LaTeX (source: http://jansoehlke.com/2010/06/strikethrough-in-latex/), but not in the standard library. 

I don't see anything including `\sout` when I grep nbconvert. 

I wanted to test whether this was just a `pandoc` bug, and so made a minimal test case.

    $ echo "~~anything~~" > test.md
    $ pandoc -s -f markdown -t latex test.md > test.tex

and then noticed that `pandoc` includes the `ulem` package by default, as well as a bunch of other packages that are not included when one runs `jupyter nbconvert strikeoutIssue.ipynb  --to LaTeX` which makes me think that a list of packages are being passed to `pandoc` to be explicitly included. 

Going to try to find that list now…

**Comment by d-diaz** [comment]
I am getting another similar error when using strikethrough in latex and trying to export to PDF. It appears to be the \require{cancel} that is triggering it... 

```
! Undefined control sequence.
<argument>  \require 
                     {cancel} \ \frac {\partial \ell (\mu ,\sigma ^2)}{\part...
l.406 \end{align}
                 
? 
! Emergency stop.
<argument>  \require 
                     {cancel} \ \frac {\partial \ell (\mu ,\sigma ^2)}{\part...
l.406 \end{align}
                 
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on notebook.log.
```

**Comment by michaelpacer** [comment]
Are you directly writing cancel as part of your TeX? Because I found this set of macros in mathjax that might make it work in the browser but not on export if we aren't transforming from mathjax macros to proper TeX.

**Comment by michaelpacer** [comment]
Aha, are you using this package in a custom template? http://ctan.mackichan.com/macros/latex/contrib/cancel/cancel.pdf

**Comment by sthoooon** [comment]
I had same problem with using that "cancel" package for writing math equations. Creating PDF fails when I put `\require{cancel}` code. 

After I put following code in IPython's mathjax.tpl file, PDF was successfully created.
```
TeX: { 
    extensions: ["cancel.js"]
}
```
But new problem came up that created PDF does not contain the page with `\require{cancel}` code on it. Whole page is missing (PDF contains only 1 page instead of 2 pages). Whenever I delete that `\require{cancel}` code, created PDF then contains full 2 pages though there is no more strikeouts on equations. Can't figure out the solution yet.
