### ISSUE TITLE
html dedent for markdown export

### ISSUE THREAD

**Issue by amniskin** [jupyter/nbconvert#996]
nbconvert doesn't dedent 'text/html' outputs, which leads to errors down the line (specifically when converting notebooks that use plotly to Markdown).

To exemplify this issue, convert any notebook that uses plotly to markdown and you'll see the plotly js code (that came from a text/html output cell output -- but was indented) is displayed as verbatim rather than executed.
Given that HTML is dedent invariant (that was awkward to write) it seems like the reader should dedent by default?

I started digging into the code, but wasn't sure where would be the best place to add this. Is this something you all would be into? I can write a pull request, I just need to know where would be a sane place for it?

**Comment by MSeal** [comment]
Would you mind posting images and/or an example notebook with the command used to make sure problem is clear for everyone?

The code which performs the translation is (here)[https://github.com/jupyter/nbconvert/blob/master/nbconvert/exporters/markdown.py] and the template it uses is (here)[https://github.com/jupyter/nbconvert/blob/master/nbconvert/templates/markdown.tpl]. The pandoc library is used for the actual template implementation, which flows through (here)[https://github.com/jupyter/nbconvert/blob/master/nbconvert/utils/pandoc.py#L21]. How these modules interact is unfortunately not super simple, but this is a starting point to explore. The template appears to naively print the text/html without any other processing, so likely an improvement to use a filter or function that improves this behavior would be welcome.

**Comment by amniskin** [comment]
As for a minimal example:

![2019-05-12-154235_958x1031_scrot](https://user-images.githubusercontent.com/10365753/57588709-25a1f700-74cd-11e9-8e55-cc0ed2040311.png)
And the associated markdown output:
![2019-05-12-154408_958x529_scrot](https://user-images.githubusercontent.com/10365753/57588710-276bba80-74cd-11e9-9701-85d8fd77edb5.png)

It seems like this is a problem with the text/html cell parser itself though, no? By that I mean, since HTML is white-space invariant, any leading whitespace can be removed without changing the interpretation of the HTML block. That way if later some other format is sensitive to whitespace, we won't have to remember this there too. It would also make it easier to export a relatively human readable HTML file (with proper indentation).

P.S. Sorry it took so long to respond, I broke the python install on my personal computer and hadn't spent the time to fix it until now.

**Comment by MSeal** [comment]
Seems like a reasonable request. Thanks for gathering the info and adding images. I haven't read through the code-paths involved in a while but your reasoning on where to implement seems right.

**Comment by amniskin** [comment]
I noticed you tagged this with "enhancement" but it's really a bug. The Markdown generated isn't equivalent to the HTML generated, which it should be. The preserved indentation causes some HTML to be displayed as verbatim text rather than HTML to be processed and added to the DOM.

This is particularly annoying if you use plotly because plotly inserts indented code into the HTML cells, and then your plotly javascript initialization call gets inserted as verbatim and never gets called. So that none of your plots show up properly.
